/**
 * ClinicalDecisionPrompt Entity (Section 16)
 * 
 * Represents a decision support prompt/warning generated by the CDO layer.
 * These are passive alerts that appear in patient charts and clinician dashboards.
 * 
 * Based on Section 5: Clinical Deterioration & Rescue
 * - "Early deterioration detected - reassessment overdue"
 * - "Escalation delayed beyond policy threshold"
 */
export interface ClinicalDecisionPrompt {
  id: string; // UUID

  // Patient & Visit Context
  patientId?: string; // Future: link to patient record
  erVisitId?: string; // ER visit identifier (from er_registrations)
  registrationId?: string; // ER registration ID

  // Prompt Details
  domain: 
    | 'CLINICAL_DETERIORATION' // Section 5
    | 'SEPSIS_INFECTION' // Section 6
    | 'MEDICATION_EFFECTIVENESS' // Section 7
    | 'PROCEDURE_SURGICAL' // Section 8
    | 'ICU_HIGH_ACUITY' // Section 9
    | 'TRANSITIONS_CARE' // Section 10
    | 'MATERNAL_NEONATAL' // Section 11
    | 'READMISSION_PATTERNS'; // Section 12

  promptType: string; // e.g., "EARLY_DETERIORATION_DETECTED", "ESCALATION_DELAYED"
  title: string; // Display title
  message: string; // Detailed message/description
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'; // Section 14: Severity-based prioritization
  
  // Context Data (read-only snapshot at time of generation)
  contextData?: {
    triageData?: any; // Snapshot of relevant triage data
    vitalSigns?: any; // Snapshot of vital signs
    timestamp?: Date; // When the condition was detected
    [key: string]: any; // Additional context
  };

  // Acknowledgment (Section 14: Required for high-risk prompts)
  acknowledgedAt?: Date;
  acknowledgedBy?: string; // User ID
  acknowledgmentNotes?: string;
  requiresAcknowledgment: boolean; // true for HIGH/CRITICAL severity

  // Status
  status: 'ACTIVE' | 'ACKNOWLEDGED' | 'RESOLVED' | 'DISMISSED';
  resolvedAt?: Date;
  resolvedBy?: string;

  // Audit
  createdAt: Date;
  updatedAt: Date;
  createdBy?: string; // System/CDO service
  updatedBy?: string;
}

