/**
 * Diet Catalog Definitions — Bilingual constants, types, and seed data
 * for the hospital nutrition / menu management module.
 */

// ─── Bilingual Label Type ───────────────────────────────────────────────────────

export interface BilingualLabel {
  key: string;
  labelAr: string;
  labelEn: string;
}

// ─── Meal Categories ────────────────────────────────────────────────────────────

export const MEAL_CATEGORIES: BilingualLabel[] = [
  { key: 'BREAKFAST',   labelAr: 'فطور',          labelEn: 'Breakfast' },
  { key: 'LUNCH',       labelAr: 'غداء',          labelEn: 'Lunch' },
  { key: 'DINNER',      labelAr: 'عشاء',          labelEn: 'Dinner' },
  { key: 'SNACK',       labelAr: 'وجبة خفيفة',    labelEn: 'Snack' },
  { key: 'BEVERAGE',    labelAr: 'مشروب',         labelEn: 'Beverage' },
  { key: 'SUPPLEMENT',  labelAr: 'مكمل غذائي',    labelEn: 'Supplement' },
];

export const MEAL_CATEGORY_MAP: Record<string, { labelAr: string; labelEn: string }> = Object.fromEntries(
  MEAL_CATEGORIES.map(c => [c.key, { labelAr: c.labelAr, labelEn: c.labelEn }])
);

// ─── Diet Types ─────────────────────────────────────────────────────────────────

export const DIET_TYPES: BilingualLabel[] = [
  { key: 'REGULAR',       labelAr: 'عادي',               labelEn: 'Regular' },
  { key: 'SOFT',          labelAr: 'لين',                labelEn: 'Soft' },
  { key: 'LIQUID',        labelAr: 'سائل',               labelEn: 'Liquid' },
  { key: 'CLEAR_LIQUID',  labelAr: 'سائل صافي',          labelEn: 'Clear Liquid' },
  { key: 'DIABETIC',      labelAr: 'سكري',               labelEn: 'Diabetic' },
  { key: 'RENAL',         labelAr: 'كلوي',               labelEn: 'Renal' },
  { key: 'CARDIAC',       labelAr: 'قلبي',               labelEn: 'Cardiac' },
  { key: 'LOW_SODIUM',    labelAr: 'قليل الملح',         labelEn: 'Low Sodium' },
  { key: 'HIGH_PROTEIN',  labelAr: 'عالي البروتين',      labelEn: 'High Protein' },
  { key: 'GLUTEN_FREE',   labelAr: 'خالي من الغلوتين',   labelEn: 'Gluten Free' },
];

export const DIET_TYPE_MAP: Record<string, { labelAr: string; labelEn: string }> = Object.fromEntries(
  DIET_TYPES.map(d => [d.key, { labelAr: d.labelAr, labelEn: d.labelEn }])
);

// ─── Allergens ──────────────────────────────────────────────────────────────────

export const ALLERGENS: BilingualLabel[] = [
  { key: 'GLUTEN',    labelAr: 'غلوتين',         labelEn: 'Gluten' },
  { key: 'DAIRY',     labelAr: 'ألبان',          labelEn: 'Dairy' },
  { key: 'EGGS',      labelAr: 'بيض',            labelEn: 'Eggs' },
  { key: 'NUTS',      labelAr: 'مكسرات',         labelEn: 'Nuts' },
  { key: 'SOY',       labelAr: 'صويا',           labelEn: 'Soy' },
  { key: 'FISH',      labelAr: 'سمك',            labelEn: 'Fish' },
  { key: 'SHELLFISH', labelAr: 'محار',           labelEn: 'Shellfish' },
];

export const ALLERGEN_MAP: Record<string, { labelAr: string; labelEn: string }> = Object.fromEntries(
  ALLERGENS.map(a => [a.key, { labelAr: a.labelAr, labelEn: a.labelEn }])
);

// ─── Textures ───────────────────────────────────────────────────────────────────

export const TEXTURES: BilingualLabel[] = [
  { key: 'REGULAR',  labelAr: 'عادي',    labelEn: 'Regular' },
  { key: 'MINCED',   labelAr: 'مفروم',   labelEn: 'Minced' },
  { key: 'PUREED',   labelAr: 'مهروس',   labelEn: 'Pureed' },
  { key: 'LIQUID',   labelAr: 'سائل',    labelEn: 'Liquid' },
];

export const TEXTURE_MAP: Record<string, { labelAr: string; labelEn: string }> = Object.fromEntries(
  TEXTURES.map(t => [t.key, { labelAr: t.labelAr, labelEn: t.labelEn }])
);

// ─── Nutrient Daily Reference Values (% DV based on 2000 kcal diet) ─────────

export const NUTRIENT_DAILY_VALUES = {
  calories:      2000,   // kcal
  protein:       50,     // g
  carbohydrates: 275,    // g
  fat:           78,     // g
  fiber:         28,     // g
  sodium:        2300,   // mg
  potassium:     4700,   // mg
  sugar:         50,     // g
} as const;

// ─── Seed Catalog Item Type ─────────────────────────────────────────────────────

export interface SeedCatalogItem {
  name: string;
  nameAr: string;
  category: string;
  dietTypes: string[];
  calories: number;
  protein: number;
  carbohydrates: number;
  fat: number;
  fiber: number;
  sodium: number;
  servingSize: string;
  allergens: string[];
  texture: string;
  isVegetarian: boolean;
  isVegan: boolean;
  isHalal: boolean;
}

// ─── Seed Catalog (~30 hospital menu items) ─────────────────────────────────────

export const SEED_CATALOG: SeedCatalogItem[] = [
  // ── BREAKFAST ──
  {
    name: 'Plain Rice Porridge',
    nameAr: 'عصيدة أرز سادة',
    category: 'BREAKFAST',
    dietTypes: ['REGULAR', 'SOFT', 'DIABETIC', 'RENAL', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 130,
    protein: 2.5,
    carbohydrates: 28,
    fat: 0.8,
    fiber: 0.4,
    sodium: 5,
    servingSize: '250g',
    allergens: [],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Scrambled Eggs',
    nameAr: 'بيض مخفوق',
    category: 'BREAKFAST',
    dietTypes: ['REGULAR', 'SOFT', 'HIGH_PROTEIN', 'GLUTEN_FREE'],
    calories: 182,
    protein: 12,
    carbohydrates: 1.6,
    fat: 14,
    fiber: 0,
    sodium: 280,
    servingSize: '150g',
    allergens: ['EGGS', 'DAIRY'],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Whole Wheat Toast',
    nameAr: 'خبز قمح كامل محمص',
    category: 'BREAKFAST',
    dietTypes: ['REGULAR', 'DIABETIC', 'CARDIAC'],
    calories: 128,
    protein: 5,
    carbohydrates: 24,
    fat: 1.5,
    fiber: 3.6,
    sodium: 200,
    servingSize: '2 slices (60g)',
    allergens: ['GLUTEN'],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Fruit Yogurt',
    nameAr: 'زبادي بالفواكه',
    category: 'BREAKFAST',
    dietTypes: ['REGULAR', 'SOFT'],
    calories: 150,
    protein: 5,
    carbohydrates: 28,
    fat: 2.5,
    fiber: 0.5,
    sodium: 75,
    servingSize: '175g',
    allergens: ['DAIRY'],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Orange Juice',
    nameAr: 'عصير برتقال',
    category: 'BREAKFAST',
    dietTypes: ['REGULAR', 'LIQUID', 'CLEAR_LIQUID', 'GLUTEN_FREE'],
    calories: 112,
    protein: 1.7,
    carbohydrates: 26,
    fat: 0.5,
    fiber: 0.5,
    sodium: 2,
    servingSize: '250ml',
    allergens: [],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  // ── LUNCH ──
  {
    name: 'Grilled Chicken Breast',
    nameAr: 'صدر دجاج مشوي',
    category: 'LUNCH',
    dietTypes: ['REGULAR', 'DIABETIC', 'HIGH_PROTEIN', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 165,
    protein: 31,
    carbohydrates: 0,
    fat: 3.6,
    fiber: 0,
    sodium: 74,
    servingSize: '150g',
    allergens: [],
    texture: 'REGULAR',
    isVegetarian: false,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Steamed Rice',
    nameAr: 'أرز مطهو على البخار',
    category: 'LUNCH',
    dietTypes: ['REGULAR', 'SOFT', 'DIABETIC', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 206,
    protein: 4.3,
    carbohydrates: 45,
    fat: 0.4,
    fiber: 0.6,
    sodium: 1,
    servingSize: '180g',
    allergens: [],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Vegetable Soup',
    nameAr: 'شوربة خضار',
    category: 'LUNCH',
    dietTypes: ['REGULAR', 'SOFT', 'LIQUID', 'DIABETIC', 'RENAL', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 85,
    protein: 3,
    carbohydrates: 14,
    fat: 2,
    fiber: 3,
    sodium: 320,
    servingSize: '250ml',
    allergens: [],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Mixed Salad',
    nameAr: 'سلطة مشكلة',
    category: 'LUNCH',
    dietTypes: ['REGULAR', 'DIABETIC', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 45,
    protein: 2,
    carbohydrates: 8,
    fat: 0.5,
    fiber: 3,
    sodium: 25,
    servingSize: '150g',
    allergens: [],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Lentil Stew',
    nameAr: 'يخنة عدس',
    category: 'LUNCH',
    dietTypes: ['REGULAR', 'SOFT', 'DIABETIC', 'HIGH_PROTEIN', 'CARDIAC'],
    calories: 230,
    protein: 18,
    carbohydrates: 39,
    fat: 1,
    fiber: 15,
    sodium: 380,
    servingSize: '250g',
    allergens: [],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Grilled Fish Fillet',
    nameAr: 'فيليه سمك مشوي',
    category: 'LUNCH',
    dietTypes: ['REGULAR', 'HIGH_PROTEIN', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 140,
    protein: 26,
    carbohydrates: 0,
    fat: 3.5,
    fiber: 0,
    sodium: 60,
    servingSize: '150g',
    allergens: ['FISH'],
    texture: 'REGULAR',
    isVegetarian: false,
    isVegan: false,
    isHalal: true,
  },
  // ── DINNER ──
  {
    name: 'Chicken Soup',
    nameAr: 'شوربة دجاج',
    category: 'DINNER',
    dietTypes: ['REGULAR', 'SOFT', 'LIQUID', 'HIGH_PROTEIN', 'GLUTEN_FREE'],
    calories: 110,
    protein: 8,
    carbohydrates: 10,
    fat: 4,
    fiber: 1,
    sodium: 420,
    servingSize: '300ml',
    allergens: [],
    texture: 'LIQUID',
    isVegetarian: false,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Mashed Potatoes',
    nameAr: 'بطاطس مهروسة',
    category: 'DINNER',
    dietTypes: ['REGULAR', 'SOFT', 'CARDIAC', 'GLUTEN_FREE'],
    calories: 175,
    protein: 3,
    carbohydrates: 33,
    fat: 4,
    fiber: 2.5,
    sodium: 350,
    servingSize: '200g',
    allergens: ['DAIRY'],
    texture: 'PUREED',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Steamed Vegetables',
    nameAr: 'خضار مطهوة على البخار',
    category: 'DINNER',
    dietTypes: ['REGULAR', 'SOFT', 'DIABETIC', 'RENAL', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 55,
    protein: 3,
    carbohydrates: 10,
    fat: 0.5,
    fiber: 4,
    sodium: 30,
    servingSize: '150g',
    allergens: [],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Pasta with Tomato Sauce',
    nameAr: 'معكرونة بصلصة الطماطم',
    category: 'DINNER',
    dietTypes: ['REGULAR', 'SOFT'],
    calories: 280,
    protein: 8,
    carbohydrates: 52,
    fat: 4,
    fiber: 3,
    sodium: 400,
    servingSize: '250g',
    allergens: ['GLUTEN'],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Grilled Fish with Herbs',
    nameAr: 'سمك مشوي بالأعشاب',
    category: 'DINNER',
    dietTypes: ['REGULAR', 'HIGH_PROTEIN', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 155,
    protein: 28,
    carbohydrates: 1,
    fat: 4,
    fiber: 0,
    sodium: 55,
    servingSize: '170g',
    allergens: ['FISH'],
    texture: 'REGULAR',
    isVegetarian: false,
    isVegan: false,
    isHalal: true,
  },
  // ── SNACK ──
  {
    name: 'Fruit Plate',
    nameAr: 'طبق فواكه',
    category: 'SNACK',
    dietTypes: ['REGULAR', 'SOFT', 'DIABETIC', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 95,
    protein: 1,
    carbohydrates: 24,
    fat: 0.3,
    fiber: 3,
    sodium: 2,
    servingSize: '150g',
    allergens: [],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Crackers',
    nameAr: 'بسكويت مملح',
    category: 'SNACK',
    dietTypes: ['REGULAR'],
    calories: 120,
    protein: 2.5,
    carbohydrates: 20,
    fat: 3.5,
    fiber: 0.8,
    sodium: 290,
    servingSize: '30g (6 pieces)',
    allergens: ['GLUTEN'],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Protein Shake',
    nameAr: 'مخفوق بروتين',
    category: 'SNACK',
    dietTypes: ['REGULAR', 'LIQUID', 'HIGH_PROTEIN', 'GLUTEN_FREE'],
    calories: 200,
    protein: 25,
    carbohydrates: 15,
    fat: 5,
    fiber: 1,
    sodium: 180,
    servingSize: '300ml',
    allergens: ['DAIRY', 'SOY'],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Jello',
    nameAr: 'جيلي',
    category: 'SNACK',
    dietTypes: ['REGULAR', 'SOFT', 'LIQUID', 'CLEAR_LIQUID', 'GLUTEN_FREE'],
    calories: 70,
    protein: 1.5,
    carbohydrates: 17,
    fat: 0,
    fiber: 0,
    sodium: 45,
    servingSize: '120g',
    allergens: [],
    texture: 'PUREED',
    isVegetarian: false,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Custard',
    nameAr: 'كاسترد',
    category: 'SNACK',
    dietTypes: ['REGULAR', 'SOFT'],
    calories: 150,
    protein: 4,
    carbohydrates: 22,
    fat: 5,
    fiber: 0,
    sodium: 100,
    servingSize: '150g',
    allergens: ['DAIRY', 'EGGS'],
    texture: 'PUREED',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  // ── BEVERAGE ──
  {
    name: 'Tea',
    nameAr: 'شاي',
    category: 'BEVERAGE',
    dietTypes: ['REGULAR', 'LIQUID', 'CLEAR_LIQUID', 'DIABETIC', 'RENAL', 'CARDIAC', 'LOW_SODIUM', 'GLUTEN_FREE'],
    calories: 2,
    protein: 0,
    carbohydrates: 0.5,
    fat: 0,
    fiber: 0,
    sodium: 5,
    servingSize: '200ml',
    allergens: [],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Coffee',
    nameAr: 'قهوة',
    category: 'BEVERAGE',
    dietTypes: ['REGULAR', 'LIQUID', 'GLUTEN_FREE'],
    calories: 5,
    protein: 0.3,
    carbohydrates: 0,
    fat: 0,
    fiber: 0,
    sodium: 5,
    servingSize: '200ml',
    allergens: [],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  {
    name: 'Milk',
    nameAr: 'حليب',
    category: 'BEVERAGE',
    dietTypes: ['REGULAR', 'LIQUID', 'HIGH_PROTEIN', 'GLUTEN_FREE'],
    calories: 120,
    protein: 8,
    carbohydrates: 12,
    fat: 5,
    fiber: 0,
    sodium: 100,
    servingSize: '250ml',
    allergens: ['DAIRY'],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Apple Juice',
    nameAr: 'عصير تفاح',
    category: 'BEVERAGE',
    dietTypes: ['REGULAR', 'LIQUID', 'CLEAR_LIQUID', 'GLUTEN_FREE'],
    calories: 117,
    protein: 0.3,
    carbohydrates: 29,
    fat: 0.3,
    fiber: 0.5,
    sodium: 10,
    servingSize: '250ml',
    allergens: [],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: true,
    isHalal: true,
  },
  // ── SUPPLEMENT ──
  {
    name: 'Ensure (Vanilla)',
    nameAr: 'إنشور (فانيلا)',
    category: 'SUPPLEMENT',
    dietTypes: ['REGULAR', 'LIQUID', 'HIGH_PROTEIN', 'GLUTEN_FREE'],
    calories: 250,
    protein: 9,
    carbohydrates: 40,
    fat: 6,
    fiber: 1,
    sodium: 200,
    servingSize: '237ml',
    allergens: ['DAIRY', 'SOY'],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Protein Powder Supplement',
    nameAr: 'مكمل مسحوق بروتين',
    category: 'SUPPLEMENT',
    dietTypes: ['REGULAR', 'HIGH_PROTEIN', 'GLUTEN_FREE'],
    calories: 120,
    protein: 24,
    carbohydrates: 3,
    fat: 1,
    fiber: 0,
    sodium: 70,
    servingSize: '30g (1 scoop)',
    allergens: ['DAIRY'],
    texture: 'REGULAR',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Ensure Plus (Chocolate)',
    nameAr: 'إنشور بلس (شوكولاتة)',
    category: 'SUPPLEMENT',
    dietTypes: ['REGULAR', 'LIQUID', 'HIGH_PROTEIN'],
    calories: 350,
    protein: 13,
    carbohydrates: 50,
    fat: 11,
    fiber: 1,
    sodium: 250,
    servingSize: '237ml',
    allergens: ['DAIRY', 'SOY'],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Glucerna (Diabetic Formula)',
    nameAr: 'غلوسيرنا (تركيبة السكري)',
    category: 'SUPPLEMENT',
    dietTypes: ['REGULAR', 'LIQUID', 'DIABETIC', 'GLUTEN_FREE'],
    calories: 200,
    protein: 10,
    carbohydrates: 27,
    fat: 7,
    fiber: 3,
    sodium: 210,
    servingSize: '237ml',
    allergens: ['DAIRY', 'SOY'],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
  {
    name: 'Nepro (Renal Formula)',
    nameAr: 'نيبرو (تركيبة الكلى)',
    category: 'SUPPLEMENT',
    dietTypes: ['REGULAR', 'LIQUID', 'RENAL'],
    calories: 425,
    protein: 19,
    carbohydrates: 40,
    fat: 23,
    fiber: 4,
    sodium: 170,
    servingSize: '237ml',
    allergens: ['DAIRY', 'SOY'],
    texture: 'LIQUID',
    isVegetarian: true,
    isVegan: false,
    isHalal: true,
  },
];
