/**
 * Thea EHR — Server-Side PDF Generation Engine
 *
 * Core engine using pdfkit to produce professional A4 clinical documents with:
 *   - Hospital header (facility name bilingual, date, document title)
 *   - Bilingual support (Arabic secondary text alongside English primary)
 *   - Section headers with accent bars
 *   - Key-value field rows
 *   - Styled tables with zebra striping and auto-pagination
 *   - Medication/prescription rows with numbered circles
 *   - QR codes (via `qrcode` library -> PNG buffer)
 *   - Page-number footers with "Generated by Thea EHR" stamp
 *   - Signature lines
 *   - Confidentiality notices (bilingual)
 *   - Patient and doctor info blocks (reusable across templates)
 *
 * Usage:
 *   const doc = await createPdfDocument({ title: 'Prescription', ... });
 *   addPatientInfoBlock(doc, patient);
 *   addMedicationRow(doc, med, 1);
 *   const buffer = await pdfToBuffer(doc);
 */

import QRCode from 'qrcode';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** A4 dimensions in points */
const A4_WIDTH = 595.28;
const A4_HEIGHT = 841.89;
const MARGIN = 50;
const CONTENT_WIDTH = A4_WIDTH - MARGIN * 2;

// Colors
const COLOR_PRIMARY = '#1a5276';
const COLOR_ACCENT = '#2980b9';
const COLOR_MUTED = '#7f8c8d';
const COLOR_BORDER = '#bdc3c7';
const COLOR_ROW_ALT = '#f8f9fa';
const COLOR_DANGER = '#c0392b';
const COLOR_WARNING = '#e67e22';
const COLOR_BLACK = '#2c3e50';

// Font sizes
const FONT_TITLE = 18;
const FONT_SUBTITLE = 14;
const FONT_SECTION = 13;
const FONT_BODY = 10;
const FONT_SMALL = 8;
const FONT_TINY = 7;

// Line gap
const LINE_GAP = 2;

// ---------------------------------------------------------------------------
// Exported Types
// ---------------------------------------------------------------------------

export interface PdfDocumentOptions {
  /** Document title (English) */
  title: string;
  /** Document title (Arabic) - displayed below English title */
  titleAr?: string;
  /** Facility / hospital name (English) */
  facilityName?: string;
  /** Facility / hospital name (Arabic) */
  facilityNameAr?: string;
  /** Primary language - controls which text appears first */
  language?: 'ar' | 'en';
  /** Date string shown in the header. Defaults to today */
  headerDate?: string;
  /** If true, suppress the standard footer (useful for single-page slips) */
  noFooter?: boolean;
}

export interface TableOptions {
  /** Explicit column widths in points. Must match headers.length */
  columnWidths?: number[];
  /** Background color for the header row */
  headerColor?: string;
  /** Font size for table content */
  fontSize?: number;
  /** Draw alternating row backgrounds (default: true) */
  zebra?: boolean;
}

export interface MedicationItem {
  name: string;
  nameAr?: string;
  dose: string;
  frequency: string;
  route: string;
  duration: string;
  instructions?: string;
}

// ---------------------------------------------------------------------------
// Internal: lazy-import pdfkit (avoids build-time bundling issues in Next.js)
// ---------------------------------------------------------------------------

let _PDFDocumentCtor: any = null;

async function getPDFDocumentCtor(): Promise<any> {
  if (_PDFDocumentCtor) return _PDFDocumentCtor;
  const mod = await import('pdfkit');
  _PDFDocumentCtor = (mod as Record<string, unknown>).default || mod;
  return _PDFDocumentCtor;
}

// ---------------------------------------------------------------------------
// Core: create a PDF document with hospital header
// ---------------------------------------------------------------------------

/**
 * Create a new A4 PDFKit document with a professional hospital header.
 *
 * The document uses `bufferPages: true` so footers (page numbers) can be
 * written across all pages before finalization.
 */
export async function createPdfDocument(
  options: PdfDocumentOptions,
): Promise<PDFKit.PDFDocument> {
  const PDFDocument = await getPDFDocumentCtor();

  const doc = new PDFDocument({
    size: 'A4',
    margin: MARGIN,
    bufferPages: true,
    info: {
      Title: options.title,
      Author: options.facilityName || 'Thea Healthcare',
      Creator: 'Thea EHR PDF Engine',
      Producer: 'pdfkit',
    },
  });

  drawHeader(doc, options);
  return doc;
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

function drawHeader(doc: PDFKit.PDFDocument, options: PdfDocumentOptions): void {
  const {
    title,
    titleAr,
    facilityName = 'Thea Healthcare',
    facilityNameAr,
    headerDate,
  } = options;

  const dateStr =
    headerDate ||
    new Date().toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    });

  // Top accent line
  doc
    .save()
    .moveTo(MARGIN, MARGIN - 10)
    .lineTo(A4_WIDTH - MARGIN, MARGIN - 10)
    .lineWidth(3)
    .strokeColor(COLOR_PRIMARY)
    .stroke()
    .restore();

  // Facility name (left)
  const headerY = MARGIN;
  doc
    .font('Helvetica-Bold')
    .fontSize(FONT_SUBTITLE)
    .fillColor(COLOR_PRIMARY)
    .text(facilityName, MARGIN, headerY, {
      width: CONTENT_WIDTH * 0.6,
      lineBreak: false,
    });

  // Date (right, same line)
  doc
    .font('Helvetica')
    .fontSize(FONT_SMALL)
    .fillColor(COLOR_MUTED)
    .text(dateStr, MARGIN, headerY + 2, {
      width: CONTENT_WIDTH,
      align: 'right',
      lineBreak: false,
    });

  let currentY = headerY + 20;

  // Arabic facility name
  if (facilityNameAr) {
    doc
      .font('Helvetica')
      .fontSize(FONT_BODY)
      .fillColor(COLOR_MUTED)
      .text(facilityNameAr, MARGIN, currentY, {
        width: CONTENT_WIDTH * 0.6,
        lineBreak: false,
      });
    currentY += 16;
  }

  // Divider below facility name
  currentY += 4;
  doc
    .save()
    .moveTo(MARGIN, currentY)
    .lineTo(A4_WIDTH - MARGIN, currentY)
    .lineWidth(0.5)
    .strokeColor(COLOR_BORDER)
    .stroke()
    .restore();
  currentY += 12;

  // Document title (centered)
  doc
    .font('Helvetica-Bold')
    .fontSize(FONT_TITLE)
    .fillColor(COLOR_PRIMARY)
    .text(title, MARGIN, currentY, {
      width: CONTENT_WIDTH,
      align: 'center',
    });
  currentY += FONT_TITLE + 6;

  // Arabic title
  if (titleAr) {
    doc
      .font('Helvetica')
      .fontSize(FONT_SUBTITLE)
      .fillColor(COLOR_MUTED)
      .text(titleAr, MARGIN, currentY, {
        width: CONTENT_WIDTH,
        align: 'center',
      });
    currentY += FONT_SUBTITLE + 6;
  }

  // Divider below title
  currentY += 4;
  doc
    .save()
    .moveTo(MARGIN, currentY)
    .lineTo(A4_WIDTH - MARGIN, currentY)
    .lineWidth(0.5)
    .strokeColor(COLOR_BORDER)
    .stroke()
    .restore();

  currentY += 12;
  doc.y = currentY;
  doc.x = MARGIN;

  // Reset text style for body content
  doc.font('Helvetica').fontSize(FONT_BODY).fillColor(COLOR_BLACK);
}

// ---------------------------------------------------------------------------
// Section header
// ---------------------------------------------------------------------------

/**
 * Add a styled section header with a colored left accent bar.
 */
export function addSectionHeader(
  doc: PDFKit.PDFDocument,
  title: string,
  titleAr?: string,
): void {
  ensureSpace(doc, 32);
  const y = doc.y;
  const barHeight = titleAr ? 30 : 18;

  // Left accent bar
  doc.save().rect(MARGIN, y, 4, barHeight).fill(COLOR_ACCENT).restore();

  doc
    .font('Helvetica-Bold')
    .fontSize(FONT_SECTION)
    .fillColor(COLOR_PRIMARY)
    .text(title, MARGIN + 12, y);

  if (titleAr) {
    doc
      .font('Helvetica')
      .fontSize(FONT_BODY)
      .fillColor(COLOR_MUTED)
      .text(titleAr, MARGIN + 12, doc.y);
  }

  doc.moveDown(0.4);
  doc.font('Helvetica').fontSize(FONT_BODY).fillColor(COLOR_BLACK);
}

// ---------------------------------------------------------------------------
// Key-value field row
// ---------------------------------------------------------------------------

/**
 * Add a label: value row. The label is bold; the value is regular weight.
 * If `labelAr` is provided it is shown in parentheses after the English label.
 */
export function addFieldRow(
  doc: PDFKit.PDFDocument,
  label: string,
  value: string,
  labelAr?: string,
): void {
  ensureSpace(doc, 16);
  const y = doc.y;
  const labelWidth = 180;

  const displayLabel = labelAr ? `${label} (${labelAr})` : label;

  doc
    .font('Helvetica-Bold')
    .fontSize(FONT_BODY)
    .fillColor(COLOR_BLACK)
    .text(`${displayLabel}:`, MARGIN, y, {
      width: labelWidth,
      continued: false,
    });

  doc
    .font('Helvetica')
    .fontSize(FONT_BODY)
    .fillColor(COLOR_BLACK)
    .text(value || '\u2014', MARGIN + labelWidth, y, {
      width: CONTENT_WIDTH - labelWidth,
    });

  // Advance Y to whichever column was taller
  const newY = Math.max(doc.y, y + 14);
  doc.y = newY;
  doc.x = MARGIN;
}

// ---------------------------------------------------------------------------
// Table
// ---------------------------------------------------------------------------

/**
 * Draw a simple table with a header row and data rows.
 *
 * - Header row gets a dark background with white text.
 * - Rows alternate background when `zebra` is true (default).
 * - Automatically adds a new page if a row would overflow the page.
 */
export function addTable(
  doc: PDFKit.PDFDocument,
  headers: string[],
  rows: string[][],
  options: TableOptions = {},
): void {
  const {
    headerColor = COLOR_PRIMARY,
    fontSize = FONT_SMALL,
    zebra = true,
  } = options;

  const colCount = headers.length;
  const colWidths =
    options.columnWidths || distributeColumns(colCount, CONTENT_WIDTH);
  const rowHeight = fontSize + 10;
  const cellPadding = 4;

  ensureSpace(doc, rowHeight * 2);

  // -- Header row --
  let x = MARGIN;
  let y = doc.y;

  doc
    .save()
    .rect(MARGIN, y, CONTENT_WIDTH, rowHeight)
    .fill(headerColor)
    .restore();

  doc.font('Helvetica-Bold').fontSize(fontSize).fillColor('#ffffff');
  headers.forEach((h, i) => {
    doc.text(h, x + cellPadding, y + cellPadding, {
      width: colWidths[i] - cellPadding * 2,
      height: rowHeight,
      ellipsis: true,
      lineBreak: false,
    });
    x += colWidths[i];
  });

  y += rowHeight;

  // -- Data rows --
  doc.font('Helvetica').fontSize(fontSize).fillColor(COLOR_BLACK);

  rows.forEach((row, rowIndex) => {
    // Page overflow check
    if (y + rowHeight > A4_HEIGHT - MARGIN - 30) {
      doc.addPage();
      doc.y = MARGIN;
      y = MARGIN;
    }

    // Zebra stripe
    if (zebra && rowIndex % 2 === 1) {
      doc
        .save()
        .rect(MARGIN, y, CONTENT_WIDTH, rowHeight)
        .fill(COLOR_ROW_ALT)
        .restore();
      doc.fillColor(COLOR_BLACK);
    }

    // Bottom border
    doc
      .save()
      .moveTo(MARGIN, y + rowHeight)
      .lineTo(A4_WIDTH - MARGIN, y + rowHeight)
      .lineWidth(0.3)
      .strokeColor(COLOR_BORDER)
      .stroke()
      .restore();

    x = MARGIN;
    row.forEach((cell, i) => {
      doc.text(cell ?? '', x + cellPadding, y + cellPadding, {
        width: colWidths[i] - cellPadding * 2,
        height: rowHeight,
        ellipsis: true,
        lineBreak: false,
      });
      x += colWidths[i];
    });

    y += rowHeight;
  });

  doc.y = y + 4;
  doc.x = MARGIN;
}

// ---------------------------------------------------------------------------
// Medication row
// ---------------------------------------------------------------------------

/**
 * Add a single medication/prescription entry with a numbered circle,
 * medication name (bilingual), structured detail line, and instructions.
 */
export function addMedicationRow(
  doc: PDFKit.PDFDocument,
  med: MedicationItem,
  index: number,
): void {
  ensureSpace(doc, 50);

  const y = doc.y;

  // Numbered circle
  doc
    .save()
    .circle(MARGIN + 8, y + 8, 8)
    .fill(COLOR_ACCENT)
    .restore();
  doc
    .font('Helvetica-Bold')
    .fontSize(FONT_SMALL)
    .fillColor('#ffffff')
    .text(String(index), MARGIN + 2, y + 4, { width: 14, align: 'center' });

  // Medication name
  const nameX = MARGIN + 24;
  const nameText = med.nameAr
    ? `${med.name} (${med.nameAr})`
    : med.name;
  doc
    .font('Helvetica-Bold')
    .fontSize(FONT_BODY)
    .fillColor(COLOR_BLACK)
    .text(nameText, nameX, y);

  // Detail line: dose | frequency | route | duration
  const parts = [
    med.dose,
    med.frequency,
    med.route,
    med.duration ? `for ${med.duration}` : '',
  ].filter(Boolean);

  doc
    .font('Helvetica')
    .fontSize(FONT_SMALL)
    .fillColor(COLOR_MUTED)
    .text(parts.join('  |  '), nameX, doc.y);

  // Instructions (italic)
  if (med.instructions) {
    doc
      .font('Helvetica-Oblique')
      .fontSize(FONT_SMALL)
      .fillColor(COLOR_BLACK)
      .text(`Instructions: ${med.instructions}`, nameX, doc.y);
  }

  // Separator line
  doc.moveDown(0.3);
  doc
    .save()
    .moveTo(MARGIN + 24, doc.y)
    .lineTo(A4_WIDTH - MARGIN, doc.y)
    .lineWidth(0.3)
    .strokeColor(COLOR_BORDER)
    .stroke()
    .restore();

  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(FONT_BODY).fillColor(COLOR_BLACK);
}

// ---------------------------------------------------------------------------
// QR Code
// ---------------------------------------------------------------------------

/**
 * Render a QR code at the specified position.
 * The `data` string is encoded to a PNG buffer and embedded as an image.
 */
export async function addQrCode(
  doc: PDFKit.PDFDocument,
  data: string,
  x: number,
  y: number,
  size: number = 80,
): Promise<void> {
  const pngBuffer = await QRCode.toBuffer(data, {
    type: 'png',
    width: size * 2, // 2x for sharper rendering
    margin: 1,
    errorCorrectionLevel: 'M',
  });
  doc.image(pngBuffer, x, y, { width: size, height: size });
}

// ---------------------------------------------------------------------------
// Signature line
// ---------------------------------------------------------------------------

/**
 * Add a signature line with label text beneath it.
 */
export function addSignatureLine(
  doc: PDFKit.PDFDocument,
  label: string,
  labelAr?: string,
): void {
  ensureSpace(doc, 50);
  doc.moveDown(1.5);

  const lineY = doc.y;

  doc
    .save()
    .moveTo(MARGIN, lineY)
    .lineTo(MARGIN + 200, lineY)
    .lineWidth(0.5)
    .strokeColor(COLOR_BLACK)
    .stroke()
    .restore();

  const displayLabel = labelAr ? `${label} / ${labelAr}` : label;
  doc
    .font('Helvetica')
    .fontSize(FONT_SMALL)
    .fillColor(COLOR_MUTED)
    .text(displayLabel, MARGIN, lineY + 4);

  doc.moveDown(0.5);
  doc.font('Helvetica').fontSize(FONT_BODY).fillColor(COLOR_BLACK);
}

// ---------------------------------------------------------------------------
// Confidentiality notice
// ---------------------------------------------------------------------------

/**
 * Add a bilingual confidentiality notice near the bottom of the current page.
 */
export function addConfidentialityNotice(
  doc: PDFKit.PDFDocument,
  language: 'ar' | 'en' = 'en',
): void {
  const noticeEn =
    'CONFIDENTIAL: This document contains protected health information (PHI). ' +
    'Unauthorized disclosure is prohibited and may be subject to legal action.';
  const noticeAr =
    '\u0633\u0631\u064a: \u064a\u062d\u062a\u0648\u064a \u0647\u0630\u0627 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u0639\u0644\u0649 \u0645\u0639\u0644\u0648\u0645\u0627\u062a \u0635\u062d\u064a\u0629 \u0645\u062d\u0645\u064a\u0629. ' +
    '\u0627\u0644\u0625\u0641\u0635\u0627\u062d \u063a\u064a\u0631 \u0627\u0644\u0645\u0635\u0631\u062d \u0628\u0647 \u0645\u062d\u0638\u0648\u0631 \u0648\u0642\u062f \u064a\u0639\u0631\u0651\u0636 \u0635\u0627\u062d\u0628\u0647 \u0644\u0644\u0645\u0633\u0627\u0621\u0644\u0629 \u0627\u0644\u0642\u0627\u0646\u0648\u0646\u064a\u0629.';

  doc.moveDown(1);

  // Divider
  doc
    .save()
    .moveTo(MARGIN, doc.y)
    .lineTo(A4_WIDTH - MARGIN, doc.y)
    .lineWidth(0.3)
    .strokeColor(COLOR_BORDER)
    .stroke()
    .restore();

  doc.moveDown(0.3);

  // Primary language notice
  doc
    .font('Helvetica-Oblique')
    .fontSize(FONT_TINY)
    .fillColor(COLOR_MUTED)
    .text(language === 'ar' ? noticeAr : noticeEn, MARGIN, doc.y, {
      width: CONTENT_WIDTH,
      align: 'center',
    });

  // Secondary language notice
  doc.text(language === 'ar' ? noticeEn : noticeAr, MARGIN, doc.y, {
    width: CONTENT_WIDTH,
    align: 'center',
  });

  doc.font('Helvetica').fontSize(FONT_BODY).fillColor(COLOR_BLACK);
}

// ---------------------------------------------------------------------------
// Finalize: add footers and convert to Buffer
// ---------------------------------------------------------------------------

/**
 * Finalize the PDF document:
 *   1. Write page-number footers on every page (unless `noFooter`).
 *   2. End the stream.
 *   3. Return the full PDF as a Uint8Array (compatible with Response).
 *
 * The PDFDocument is ended after this call and cannot be written to again.
 */
export function pdfToBuffer(
  doc: PDFKit.PDFDocument,
  options?: { noFooter?: boolean },
): Promise<Uint8Array> {
  return new Promise<Uint8Array>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(new Uint8Array(Buffer.concat(chunks))));
    doc.on('error', reject);

    // Write footers before ending
    if (!options?.noFooter) {
      writeFooters(doc);
    }

    doc.end();
  });
}

// ---------------------------------------------------------------------------
// Reusable content blocks
// ---------------------------------------------------------------------------

/**
 * Add a patient demographic information block (name, MRN, DOB, gender).
 */
export function addPatientInfoBlock(
  doc: PDFKit.PDFDocument,
  patient: {
    name: string;
    nameAr?: string;
    mrn: string;
    dob?: string;
    gender?: string;
  },
): void {
  addSectionHeader(doc, 'Patient Information', '\u0645\u0639\u0644\u0648\u0645\u0627\u062a \u0627\u0644\u0645\u0631\u064a\u0636');

  const displayName = patient.nameAr
    ? `${patient.name} / ${patient.nameAr}`
    : patient.name;

  addFieldRow(doc, 'Name', displayName, '\u0627\u0644\u0627\u0633\u0645');
  addFieldRow(doc, 'MRN', patient.mrn, '\u0631\u0642\u0645 \u0627\u0644\u0645\u0644\u0641');

  if (patient.dob) {
    addFieldRow(doc, 'Date of Birth', patient.dob, '\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0645\u064a\u0644\u0627\u062f');
  }
  if (patient.gender) {
    addFieldRow(doc, 'Gender', patient.gender, '\u0627\u0644\u062c\u0646\u0633');
  }

  doc.moveDown(0.5);
}

/**
 * Add a doctor / provider information block (name, specialty, license).
 */
export function addDoctorInfoBlock(
  doc: PDFKit.PDFDocument,
  doctor: {
    name: string;
    nameAr?: string;
    licenseNo?: string;
    specialty?: string;
  },
): void {
  addSectionHeader(doc, 'Physician', '\u0627\u0644\u0637\u0628\u064a\u0628 \u0627\u0644\u0645\u0639\u0627\u0644\u062c');

  const displayName = doctor.nameAr
    ? `${doctor.name} / ${doctor.nameAr}`
    : doctor.name;

  addFieldRow(doc, 'Physician', displayName, '\u0627\u0644\u0637\u0628\u064a\u0628');

  if (doctor.specialty) {
    addFieldRow(doc, 'Specialty', doctor.specialty, '\u0627\u0644\u062a\u062e\u0635\u0635');
  }
  if (doctor.licenseNo) {
    addFieldRow(doc, 'License No', doctor.licenseNo, '\u0631\u0642\u0645 \u0627\u0644\u062a\u0631\u062e\u064a\u0635');
  }

  doc.moveDown(0.5);
}

/**
 * Add a horizontal divider line.
 */
export function addDivider(doc: PDFKit.PDFDocument): void {
  doc
    .save()
    .moveTo(MARGIN, doc.y)
    .lineTo(A4_WIDTH - MARGIN, doc.y)
    .lineWidth(0.5)
    .strokeColor(COLOR_BORDER)
    .stroke()
    .restore();
  doc.moveDown(0.5);
}

/**
 * Add a free-text paragraph with optional styling.
 */
export function addParagraph(
  doc: PDFKit.PDFDocument,
  text: string,
  options?: { bold?: boolean; fontSize?: number; color?: string; italic?: boolean },
): void {
  const {
    bold = false,
    italic = false,
    fontSize = FONT_BODY,
    color = COLOR_BLACK,
  } = options || {};

  ensureSpace(doc, fontSize + 10);

  const fontName = bold
    ? 'Helvetica-Bold'
    : italic
      ? 'Helvetica-Oblique'
      : 'Helvetica';

  doc
    .font(fontName)
    .fontSize(fontSize)
    .fillColor(color)
    .text(text, MARGIN, doc.y, { width: CONTENT_WIDTH, lineGap: LINE_GAP });

  doc.font('Helvetica').fontSize(FONT_BODY).fillColor(COLOR_BLACK);
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Write "Page X of N" and timestamps on every buffered page. */
function writeFooters(doc: PDFKit.PDFDocument): void {
  const range = doc.bufferedPageRange();
  const totalPages = range.count;

  for (let i = 0; i < totalPages; i++) {
    doc.switchToPage(i);

    const footerY = A4_HEIGHT - MARGIN + 10;

    // Thin line
    doc
      .save()
      .moveTo(MARGIN, footerY - 4)
      .lineTo(A4_WIDTH - MARGIN, footerY - 4)
      .lineWidth(0.3)
      .strokeColor(COLOR_BORDER)
      .stroke()
      .restore();

    // Left: branding
    doc
      .font('Helvetica')
      .fontSize(FONT_TINY)
      .fillColor(COLOR_MUTED)
      .text('Generated by Thea EHR', MARGIN, footerY, {
        width: CONTENT_WIDTH * 0.4,
        lineBreak: false,
      });

    // Center: page number
    doc.text(`Page ${i + 1} of ${totalPages}`, MARGIN, footerY, {
      width: CONTENT_WIDTH,
      align: 'center',
      lineBreak: false,
    });

    // Right: timestamp
    const ts = new Date().toISOString().replace('T', ' ').slice(0, 19);
    doc.text(ts, MARGIN, footerY, {
      width: CONTENT_WIDTH,
      align: 'right',
      lineBreak: false,
    });
  }
}

/** Ensure at least `requiredPt` of vertical space remains. If not, add a page. */
function ensureSpace(doc: PDFKit.PDFDocument, requiredPt: number): void {
  if (doc.y + requiredPt > A4_HEIGHT - MARGIN - 30) {
    doc.addPage();
    doc.y = MARGIN;
    doc.x = MARGIN;
  }
}

/** Distribute `n` columns evenly across `totalWidth`. */
function distributeColumns(n: number, totalWidth: number): number[] {
  const w = Math.floor(totalWidth / n);
  const widths = Array(n).fill(w) as number[];
  widths[0] += totalWidth - w * n;
  return widths;
}

// ---------------------------------------------------------------------------
// Re-export constants for templates
// ---------------------------------------------------------------------------
export {
  MARGIN,
  CONTENT_WIDTH,
  A4_WIDTH,
  A4_HEIGHT,
  COLOR_PRIMARY,
  COLOR_ACCENT,
  COLOR_MUTED,
  COLOR_DANGER,
  COLOR_WARNING,
  COLOR_BORDER,
  COLOR_BLACK,
  FONT_BODY,
  FONT_SMALL,
  FONT_TINY,
  FONT_SUBTITLE,
  FONT_SECTION,
};
