/**
 * CVision Smart Scheduling - Type Definitions
 *
 * Types for shift management, scheduling, overtime, and AI suggestions.
 */

// ─── Shift Types ────────────────────────────────────────────────

export type ShiftType = 'DAY' | 'NIGHT' | 'EVENING' | 'OFF' | 'LEAVE' | 'OVERTIME' | 'SPLIT';

// ─── Shift ──────────────────────────────────────────────────────

export interface Shift {
  id: string;
  tenantId: string;
  name: string;           // "Day", "Night", "Evening"
  nameEn: string;         // "Day", "Night", "Evening"
  code: ShiftType;
  startTime: string;      // "07:00"
  endTime: string;        // "15:00"
  durationHours: number;  // 8
  color: string;          // "#22C55E" for display
  icon: string;           // "sun", "moon", "sunset" (lucide icon name)
  isOvernight: boolean;   // true for night shifts
  allowance?: number;     // Shift allowance (e.g. night allowance)
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// ─── Schedule ───────────────────────────────────────────────────

export interface Schedule {
  id: string;
  tenantId: string;
  name: string;                    // Schedule name
  departmentId?: string;           // Specific department or null for all
  startDate: Date;                 // Period start
  endDate: Date;                   // Period end
  type: 'WEEKLY' | 'MONTHLY';
  status: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
}

// ─── Schedule Entry (per employee/day) ──────────────────────────

export interface ScheduleEntry {
  id: string;
  tenantId: string;
  scheduleId: string;
  employeeId: string;
  date: Date;                      // The date
  shiftId?: string;                // Assigned shift
  shiftType: ShiftType;            // Shift type
  startTime?: string;              // Custom time (optional)
  endTime?: string;                // Custom time (optional)
  overtimeHours?: number;          // Overtime hours
  leaveRequestId?: string;         // Link to leave request
  notes?: string;                  // Notes
  isAutoGenerated: boolean;        // Auto-generated by AI
  splitGroupId?: string;           // Groups multiple entries that form one split shift day
  splitSegmentIndex?: number;      // 0 = first segment, 1 = second segment, etc.
  createdAt: Date;
  updatedAt: Date;
}

// ─── Overtime Request ───────────────────────────────────────────

export interface OvertimeRequest {
  id: string;
  tenantId: string;
  employeeId: string;
  scheduleEntryId?: string;
  date: Date;
  hours: number;
  rate: number;                    // 1.5 or 2.0
  reason: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  amount?: number;                 // Calculated amount
  approvedBy?: string;
  approvedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

// ─── Scheduling Settings ────────────────────────────────────────

export interface SchedulingSettings {
  id: string;
  tenantId: string;
  departmentId?: string;
  minStaffPerShift: Record<ShiftType, number>;  // Minimum per shift
  maxConsecutiveNights: number;                  // Max consecutive nights
  maxOvertimeHoursPerMonth: number;              // Max overtime hours/month
  restHoursBetweenShifts: number;                // Rest hours between shifts
  weekendDays: number[];                         // Weekend days [5, 6]
  createdAt: Date;
  updatedAt: Date;
}

// ─── AI Schedule Suggestion ─────────────────────────────────────

export interface ScheduleSuggestion {
  type: 'SHORTAGE' | 'CONFLICT' | 'OVERTIME_NEEDED' | 'SWAP_RECOMMENDED';
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
  message: string;
  date?: Date;
  shiftType?: ShiftType;
  affectedEmployees?: string[];
  suggestedAction?: {
    type: 'ADD_EMPLOYEE' | 'SWAP_SHIFT' | 'REQUEST_OVERTIME' | 'REDUCE_SHIFT';
    employeeId?: string;
    fromShift?: ShiftType;
    toShift?: ShiftType;
  };
}

// ─── Schedule Summary ───────────────────────────────────────────

export interface ScheduleSummary {
  totalEmployees: number;
  shiftsCount: Record<ShiftType, number>;
  overtimeHours: number;
  leaveCount: number;
  conflicts: number;
  suggestions: ScheduleSuggestion[];
}

// ─── Unit (under Department) ───────────────────────────────────

export interface Unit {
  id: string;
  tenantId: string;
  departmentId: string;       // Parent department
  name: string;               // "ICU", "ER", "Ward A"
  code: string;               // "ICU", "ER", "WA"
  headNurseId?: string;       // Unit head nurse
  nursingManagerId?: string;  // Nursing manager for unit
  minStaffDay?: number;       // Minimum staff for day shift
  minStaffNight?: number;     // Minimum staff for night shift
  minStaffEvening?: number;   // Minimum staff for evening shift
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// ─── Schedule Status (with Approval Flow) ──────────────────────

export type ScheduleStatus =
  | 'DRAFT'              // Draft - Head Nurse editing
  | 'PENDING_APPROVAL'   // Pending nursing manager approval
  | 'APPROVED'           // Approved
  | 'PUBLISHED'          // Published and active
  | 'REJECTED'           // Rejected
  | 'ARCHIVED';          // Archived

// ─── Leave Approval Status ─────────────────────────────────────

export type LeaveApprovalStatus =
  | 'PENDING_EMPLOYEE'   // Pending employee confirmation
  | 'EMPLOYEE_REJECTED'  // Employee rejected
  | 'PENDING_MANAGER'    // Pending manager approval
  | 'APPROVED'           // Approved
  | 'REJECTED';          // Rejected by manager

// ─── Schedule Leave Request ────────────────────────────────────

export interface ScheduleLeaveRequest {
  id: string;
  tenantId: string;
  employeeId: string;
  unitId?: string;
  scheduleId?: string;

  // Dates
  startDate: Date;
  endDate: Date;
  totalDays: number;

  // Type and reason
  leaveType: 'ANNUAL' | 'SICK' | 'EMERGENCY' | 'UNPAID' | 'MATERNITY' | 'PATERNITY' | 'HAJJ' | 'MARRIAGE' | 'BEREAVEMENT';
  reason?: string;

  // Approval Flow
  status: LeaveApprovalStatus;
  requestedBy: string;              // Head Nurse who requested
  requestedByRole: 'HEAD_NURSE' | 'EMPLOYEE' | 'HR';
  requestedAt: Date;

  // Employee confirmation
  employeeConfirmed?: boolean;
  employeeConfirmedAt?: Date;
  employeeRejectionReason?: string;

  // Manager approval
  managerApprovedBy?: string;
  managerApprovedAt?: Date;
  managerRejectionReason?: string;

  // Schedule linkage
  scheduleEntryIds?: string[];      // Specific days in the schedule

  createdAt: Date;
  updatedAt: Date;
}

// ─── Schedule Approval ─────────────────────────────────────────

export interface ScheduleApproval {
  scheduleId: string;
  status: ScheduleStatus;

  // Creator
  createdBy: string;
  createdByRole: string;
  createdAt: Date;

  // Submission for approval
  submittedBy?: string;
  submittedAt?: Date;

  // Approval
  approvedBy?: string;
  approvedAt?: Date;

  // Rejection
  rejectedBy?: string;
  rejectedAt?: Date;
  rejectionReason?: string;

  // Publishing
  publishedBy?: string;
  publishedAt?: Date;
}

// ─── Assignment Types ────────────────────────────────────────

/** Employee assignment type */
export type AssignmentType =
  | 'REGULAR'      // Regular unit employee
  | 'LOAN'         // Temporary loan
  | 'TRAINING'     // Cross-training
  | 'FLOAT'        // From Float Pool
  | 'PULL_OUT';    // Pulled out from unit

// ─── Pull Out Types ─────────────────────────────────────────

/** Pull-out reason type */
export type PullOutType =
  | 'TRANSFER'        // Transfer to another unit
  | 'TRAINING'        // Training course
  | 'EXTENDED_LEAVE'  // Extended leave
  | 'SUSPENSION'      // Temporary suspension
  | 'OTHER';          // Other

/** Record of employee pull-out from unit */
export interface PullOutRecord {
  id: string;
  tenantId: string;
  employeeId: string;

  // Source unit
  originalUnitId: string;

  // Destination unit (null if no destination)
  destinationUnitId?: string | null;

  // Pull-out type
  pullOutType: PullOutType;

  // Dates
  startDate: Date;
  expectedReturnDate?: Date | null;
  actualReturnDate?: Date | null;

  // Details
  reason?: string;
  notes?: string;

  // Status
  status: 'ACTIVE' | 'RETURNED' | 'CANCELLED';

  // Created by
  createdBy: string;
  createdAt: Date;
  returnedBy?: string;
  returnedAt?: Date;

  updatedAt: Date;
}

/** Display labels */
export const PULL_OUT_TYPE_LABELS: Record<PullOutType, { label: string; icon: string }> = {
  TRANSFER:       { label: 'Transfer to another unit', icon: 'refresh-cw' },
  TRAINING:       { label: 'Training/Course',          icon: 'book-open' },
  EXTENDED_LEAVE: { label: 'Extended Leave',            icon: 'palmtree' },
  SUSPENSION:     { label: 'Temporary Suspension',      icon: 'pause' },
  OTHER:          { label: 'Other',                     icon: 'clipboard-list' },
};

// ─── Employee Assignment ────────────────────────────────────

/** Temporary employee assignment */
export interface EmployeeAssignment {
  id: string;
  tenantId: string;
  employeeId: string;

  // Original and assigned unit
  originalUnitId: string;
  assignedUnitId: string;

  // Assignment type
  assignmentType: AssignmentType;

  // Period
  startDate: Date;
  endDate: Date;

  // Details
  reason?: string;
  hoursPerWeek?: number;

  // Status
  status: 'ACTIVE' | 'COMPLETED' | 'CANCELLED';

  // Approvals
  requestedBy: string;
  requestedAt: Date;
  approvedBy?: string;
  approvedAt?: Date;

  createdAt: Date;
  updatedAt: Date;
}

// ─── Employee Scheduling Info ────────────────────────────────

/** Employee scheduling information */
export interface EmployeeSchedulingInfo {
  primaryUnitId?: string;
  secondaryUnitIds?: string[];
  isFloatPool?: boolean;
  floatPoolDepartments?: string[];
}

// ─── Enhanced Schedule Entry ─────────────────────────────────

/** Enhanced schedule entry with assignment info */
export interface EnhancedScheduleEntry extends ScheduleEntry {
  assignmentType?: AssignmentType;
  originalUnitId?: string;
  assignmentId?: string;
}

// ─── Schedule Employee Info ──────────────────────────────────

/** Employee summary in schedule */
export interface ScheduleEmployeeInfo {
  id: string;
  name: string;
  employeeNo: string;
  primaryUnitId?: string;
  primaryUnitName?: string;
  assignmentType: AssignmentType;
  isFromAnotherUnit: boolean;
  originalUnitName?: string;
}
