/**
 * Saudi MOH Drug Formulary — Part 17: Sedatives, Antidotes, Ophthalmic, Dermatologic, Miscellaneous
 * IDs: FRM-0940 through FRM-0969
 */
import type { FormularyDrug } from './formularyTypes';

export const SEDATIVES_ANXIOLYTICS: FormularyDrug[] = [
  {
    id: 'FRM-0940', genericName: 'Midazolam', genericNameAr: 'ميدازولام',
    brandNames: ['Dormicum', 'Versed'], sfda_registration: 'SFDA-2024-SED-940',
    atcCode: 'N05CD08', atcCategory: 'N05C', therapeuticClass: 'Sedatives & Anxiolytics',
    therapeuticClassAr: 'المهدئات ومضادات القلق', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular', 'intranasal'], forms: [{ form: 'injection', strength: '5mg/ml', unitPrice: 5, inStock: true }, { form: 'oral solution', strength: '2mg/ml', unitPrice: 25, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: true, controlSchedule: 'Schedule IV',
    lookAlikeSoundAlike: ['Midodrine'],
    interactions: [{ interactsWith: 'Ketoconazole', severity: 'major', mechanism: 'CYP3A4 inhibition', clinicalEffect: 'Prolonged sedation and respiratory depression', clinicalEffectAr: 'تخدير مطول وتثبيط تنفسي', management: 'Reduce midazolam dose by 50%', managementAr: 'تقليل جرعة الميدازولام بنسبة 50%' }],
    contraindications: ['Acute narrow-angle glaucoma', 'Severe respiratory insufficiency', 'Sleep apnea'],
    contraindicationsAr: ['الجلوكوما ضيقة الزاوية الحادة', 'قصور تنفسي شديد', 'انقطاع النفس أثناء النوم'],
    monitoringRequired: ['Respiratory rate', 'Oxygen saturation', 'Level of sedation', 'Paradoxical reactions'], storageConditions: 'Store below 30°C, protect from light'
  },
  {
    id: 'FRM-0941', genericName: 'Lorazepam', genericNameAr: 'لورازيبام',
    brandNames: ['Ativan'], sfda_registration: 'SFDA-2024-SED-941',
    atcCode: 'N05BA06', atcCategory: 'N05B', therapeuticClass: 'Sedatives & Anxiolytics',
    therapeuticClassAr: 'المهدئات ومضادات القلق', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [{ form: 'tablet', strength: '1mg', unitPrice: 2, inStock: true }, { form: 'injection', strength: '2mg/ml', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: true, controlSchedule: 'Schedule IV',
    lookAlikeSoundAlike: ['Alprazolam', 'Clonazepam'],
    interactions: [{ interactsWith: 'Opioids', severity: 'major', mechanism: 'Additive CNS/respiratory depression', clinicalEffect: 'Profound sedation, coma, death', clinicalEffectAr: 'تخدير عميق وغيبوبة ووفاة', management: 'Limit dose and duration of concurrent use', managementAr: 'تقليل الجرعة ومدة الاستخدام المتزامن' }],
    contraindications: ['Acute narrow-angle glaucoma', 'Severe respiratory failure', 'Sleep apnea syndrome'],
    contraindicationsAr: ['الجلوكوما ضيقة الزاوية الحادة', 'فشل تنفسي شديد', 'متلازمة انقطاع النفس أثناء النوم'],
    monitoringRequired: ['Respiratory function', 'Sedation level', 'Dependence signs'], storageConditions: 'Refrigerate 2-8°C'
  },
  {
    id: 'FRM-0942', genericName: 'Diazepam', genericNameAr: 'ديازيبام',
    brandNames: ['Valium'], sfda_registration: 'SFDA-2024-SED-942',
    atcCode: 'N05BA01', atcCategory: 'N05B', therapeuticClass: 'Sedatives & Anxiolytics',
    therapeuticClassAr: 'المهدئات ومضادات القلق', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'rectal'], forms: [{ form: 'tablet', strength: '5mg', unitPrice: 1, inStock: true }, { form: 'injection', strength: '5mg/ml', unitPrice: 5, inStock: true }, { form: 'rectal gel', strength: '10mg', unitPrice: 35, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: true, controlSchedule: 'Schedule IV',
    lookAlikeSoundAlike: ['Ditropan', 'Dilantin'],
    interactions: [{ interactsWith: 'Opioids', severity: 'major', mechanism: 'Additive CNS/respiratory depression', clinicalEffect: 'Fatal respiratory depression', clinicalEffectAr: 'تثبيط تنفسي مميت', management: 'Use lowest effective doses', managementAr: 'استخدام أقل جرعات فعالة' }],
    contraindications: ['Myasthenia gravis', 'Severe hepatic insufficiency', 'Acute narrow-angle glaucoma'],
    contraindicationsAr: ['الوهن العضلي الوبيل', 'قصور كبدي شديد', 'الجلوكوما ضيقة الزاوية الحادة'],
    monitoringRequired: ['Respiratory function', 'Sedation level', 'Dependence with prolonged use'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0943', genericName: 'Zolpidem', genericNameAr: 'زولبيديم',
    brandNames: ['Ambien', 'Stilnox'], sfda_registration: 'SFDA-2024-SED-943',
    atcCode: 'N05CF02', atcCategory: 'N05C', therapeuticClass: 'Sedatives & Anxiolytics',
    therapeuticClassAr: 'المهدئات ومضادات القلق', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '10mg', unitPrice: 3, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: true, controlSchedule: 'Schedule IV',
    lookAlikeSoundAlike: ['Zaleplon'],
    interactions: [{ interactsWith: 'CNS depressants', severity: 'major', mechanism: 'Additive CNS depression', clinicalEffect: 'Excessive sedation, complex sleep behaviors', clinicalEffectAr: 'تخدير مفرط وسلوكيات نوم معقدة', management: 'Avoid combination', managementAr: 'تجنب الجمع' }],
    contraindications: ['Severe hepatic impairment', 'Sleep apnea', 'Myasthenia gravis'],
    contraindicationsAr: ['قصور كبدي شديد', 'انقطاع النفس أثناء النوم', 'الوهن العضلي الوبيل'],
    monitoringRequired: ['Sleep quality', 'Complex sleep behaviors', 'Dependence'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0944', genericName: 'Melatonin', genericNameAr: 'ميلاتونين',
    brandNames: ['Circadin'], sfda_registration: 'SFDA-2024-SED-944',
    atcCode: 'N05CH01', atcCategory: 'N05C', therapeuticClass: 'Sedatives & Anxiolytics',
    therapeuticClassAr: 'المهدئات ومضادات القلق', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '2mg', unitPrice: 2, inStock: true }, { form: 'tablet', strength: '3mg', unitPrice: 3, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Fluvoxamine', severity: 'moderate', mechanism: 'CYP1A2 inhibition', clinicalEffect: 'Markedly increased melatonin levels', clinicalEffectAr: 'زيادة ملحوظة في مستويات الميلاتونين', management: 'Avoid combination', managementAr: 'تجنب الجمع' }],
    contraindications: ['Autoimmune diseases (theoretical)', 'Severe hepatic impairment'],
    contraindicationsAr: ['أمراض المناعة الذاتية (نظرياً)', 'قصور كبدي شديد'],
    monitoringRequired: ['Sleep quality', 'Daytime drowsiness'], storageConditions: 'Store below 25°C, protect from light'
  },
];

export const ANTIDOTES_EMERGENCY: FormularyDrug[] = [
  {
    id: 'FRM-0945', genericName: 'N-Acetylcysteine', genericNameAr: 'ن-أسيتيل سيستئين',
    brandNames: ['Mucomyst', 'Acetadote'], sfda_registration: 'SFDA-2024-ANE-945',
    atcCode: 'V03AB23', atcCategory: 'V03A', therapeuticClass: 'Antidotes & Emergency',
    therapeuticClassAr: 'الترياقات والطوارئ', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'inhalation'], forms: [{ form: 'injection', strength: '200mg/ml', unitPrice: 25, inStock: true }, { form: 'effervescent tablet', strength: '600mg', unitPrice: 3, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Activated charcoal', severity: 'moderate', mechanism: 'Charcoal adsorbs NAC', clinicalEffect: 'Reduced NAC efficacy', clinicalEffectAr: 'انخفاض فعالية NAC', management: 'If charcoal given, use IV NAC', managementAr: 'إذا أعطي الفحم، استخدم NAC الوريدي' }],
    contraindications: ['Hypersensitivity (relative — benefit may outweigh risk in poisoning)'],
    contraindicationsAr: ['فرط الحساسية (نسبي — الفائدة قد تفوق المخاطر في التسمم)'],
    monitoringRequired: ['Acetaminophen levels', 'Liver function tests', 'INR', 'Anaphylactoid reactions'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0946', genericName: 'Flumazenil', genericNameAr: 'فلومازينيل',
    brandNames: ['Anexate', 'Romazicon'], sfda_registration: 'SFDA-2024-ANE-946',
    atcCode: 'V03AB25', atcCategory: 'V03A', therapeuticClass: 'Antidotes & Emergency',
    therapeuticClassAr: 'الترياقات والطوارئ', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '0.1mg/ml', unitPrice: 35, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Chronic benzodiazepine dependence (seizure risk)', 'Concurrent tricyclic antidepressant overdose', 'Epilepsy patients on benzodiazepines'],
    contraindicationsAr: ['الاعتماد المزمن على البنزوديازيبين (خطر نوبات)', 'تسمم متزامن بمضادات الاكتئاب ثلاثية الحلقات', 'مرضى الصرع على البنزوديازيبين'],
    monitoringRequired: ['Level of consciousness', 'Seizure activity', 'Resedation (short half-life)'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0947', genericName: 'Naloxone', genericNameAr: 'نالوكسون',
    brandNames: ['Narcan'], sfda_registration: 'SFDA-2024-ANE-947',
    atcCode: 'V03AB15', atcCategory: 'V03A', therapeuticClass: 'Antidotes & Emergency',
    therapeuticClassAr: 'الترياقات والطوارئ', formularyStatus: 'formulary',
    route: ['intravenous', 'intramuscular', 'intranasal', 'subcutaneous'], forms: [{ form: 'injection', strength: '0.4mg/ml', unitPrice: 8, inStock: true }, { form: 'nasal spray', strength: '4mg/0.1ml', unitPrice: 65, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Naltrexone'],
    interactions: [],
    contraindications: ['Hypersensitivity to naloxone'],
    contraindicationsAr: ['فرط الحساسية للنالوكسون'],
    monitoringRequired: ['Respiratory rate', 'Level of consciousness', 'Withdrawal symptoms', 'Repeat dosing (shorter half-life than many opioids)'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0948', genericName: 'Atropine Sulfate', genericNameAr: 'أتروبين سلفات',
    brandNames: ['Atropine'], sfda_registration: 'SFDA-2024-ANE-948',
    atcCode: 'A03BA01', atcCategory: 'A03B', therapeuticClass: 'Antidotes & Emergency',
    therapeuticClassAr: 'الترياقات والطوارئ', formularyStatus: 'formulary',
    route: ['intravenous', 'intramuscular', 'ophthalmic'], forms: [{ form: 'injection', strength: '0.5mg/ml', unitPrice: 3, inStock: true }, { form: 'injection', strength: '1mg/ml', unitPrice: 4, inStock: true }, { form: 'eye drops', strength: '1%', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Anticholinergics', severity: 'moderate', mechanism: 'Additive anticholinergic effects', clinicalEffect: 'Ileus, urinary retention, delirium', clinicalEffectAr: 'علوص واحتباس بولي وهذيان', management: 'Avoid unnecessary combinations', managementAr: 'تجنب التركيبات غير الضرورية' }],
    contraindications: ['Narrow-angle glaucoma (systemic)', 'Obstructive GI disease', 'Myasthenia gravis'],
    contraindicationsAr: ['الجلوكوما ضيقة الزاوية (جهازي)', 'مرض معدي معوي انسدادي', 'الوهن العضلي الوبيل'],
    monitoringRequired: ['Heart rate', 'Pupil response', 'Urinary retention', 'Temperature'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0949', genericName: 'Calcium Gluconate', genericNameAr: 'غلوكونات الكالسيوم',
    brandNames: ['Calcium Gluconate Injection'], sfda_registration: 'SFDA-2024-ANE-949',
    atcCode: 'A12AA03', atcCategory: 'A12A', therapeuticClass: 'Antidotes & Emergency',
    therapeuticClassAr: 'الترياقات والطوارئ', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '10%', unitPrice: 4, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Calcium chloride'],
    interactions: [{ interactsWith: 'Digoxin', severity: 'major', mechanism: 'Synergistic cardiac toxicity', clinicalEffect: 'Fatal arrhythmias', clinicalEffectAr: 'اضطرابات نظم قاتلة', management: 'Avoid rapid IV calcium in digitalized patients', managementAr: 'تجنب الكالسيوم الوريدي السريع في المرضى على الديجوكسين' }],
    contraindications: ['Hypercalcemia', 'Digitalis toxicity', 'Concurrent ceftriaxone in neonates'],
    contraindicationsAr: ['فرط كالسيوم الدم', 'سمية الديجيتال', 'سيفترياكسون المتزامن في حديثي الولادة'],
    monitoringRequired: ['Serum calcium', 'ECG during infusion', 'IV site for extravasation'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0950', genericName: 'Sodium Bicarbonate', genericNameAr: 'بيكربونات الصوديوم',
    brandNames: ['Sodium Bicarbonate Injection'], sfda_registration: 'SFDA-2024-ANE-950',
    atcCode: 'B05CB04', atcCategory: 'B05C', therapeuticClass: 'Antidotes & Emergency',
    therapeuticClassAr: 'الترياقات والطوارئ', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '8.4%', unitPrice: 4, inStock: true }, { form: 'injection', strength: '4.2%', unitPrice: 3, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Sodium chloride'],
    interactions: [],
    contraindications: ['Metabolic alkalosis', 'Hypocalcemia', 'Hypokalemia'],
    contraindicationsAr: ['القلاء الاستقلابي', 'نقص كالسيوم الدم', 'نقص بوتاسيوم الدم'],
    monitoringRequired: ['Arterial blood gas', 'Serum electrolytes', 'Ionized calcium'], storageConditions: 'Store below 30°C'
  },
];

export const OPHTHALMIC_DERMATOLOGIC: FormularyDrug[] = [
  {
    id: 'FRM-0951', genericName: 'Timolol (ophthalmic)', genericNameAr: 'تيمولول (عيني)',
    brandNames: ['Timoptic'], sfda_registration: 'SFDA-2024-OPH-951',
    atcCode: 'S01ED01', atcCategory: 'S01E', therapeuticClass: 'Ophthalmic & Dermatologic',
    therapeuticClassAr: 'أدوية العيون والجلدية', formularyStatus: 'formulary',
    route: ['ophthalmic'], forms: [{ form: 'eye drops', strength: '0.5%', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Atenolol'],
    interactions: [{ interactsWith: 'Verapamil', severity: 'major', mechanism: 'Systemic absorption + additive cardiac effects', clinicalEffect: 'Bradycardia and heart block', clinicalEffectAr: 'بطء القلب وإحصار القلب', management: 'Monitor heart rate', managementAr: 'مراقبة معدل القلب' }],
    contraindications: ['Asthma', 'COPD', 'Sinus bradycardia', 'Heart block >1st degree'],
    contraindicationsAr: ['الربو', 'مرض الانسداد الرئوي المزمن', 'بطء القلب الجيبي', 'إحصار القلب أعلى من الدرجة الأولى'],
    monitoringRequired: ['Intraocular pressure', 'Heart rate', 'Respiratory status'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0952', genericName: 'Latanoprost', genericNameAr: 'لاتانوبروست',
    brandNames: ['Xalatan'], sfda_registration: 'SFDA-2024-OPH-952',
    atcCode: 'S01EE01', atcCategory: 'S01E', therapeuticClass: 'Ophthalmic & Dermatologic',
    therapeuticClassAr: 'أدوية العيون والجلدية', formularyStatus: 'formulary',
    route: ['ophthalmic'], forms: [{ form: 'eye drops', strength: '0.005%', unitPrice: 45, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Travoprost'],
    interactions: [],
    contraindications: ['Hypersensitivity to latanoprost or benzalkonium chloride'],
    contraindicationsAr: ['فرط الحساسية للاتانوبروست أو كلوريد البنزالكونيوم'],
    monitoringRequired: ['Intraocular pressure', 'Iris pigmentation changes', 'Eyelash changes'], storageConditions: 'Refrigerate 2-8°C before opening; room temp 6 weeks after opening'
  },
  {
    id: 'FRM-0953', genericName: 'Artificial Tears (Sodium Hyaluronate)', genericNameAr: 'دموع اصطناعية (هيالورونات الصوديوم)',
    brandNames: ['Hylo-Comod', 'Systane Ultra'], sfda_registration: 'SFDA-2024-OPH-953',
    atcCode: 'S01XA20', atcCategory: 'S01X', therapeuticClass: 'Ophthalmic & Dermatologic',
    therapeuticClassAr: 'أدوية العيون والجلدية', formularyStatus: 'formulary',
    route: ['ophthalmic'], forms: [{ form: 'eye drops', strength: '0.1%', unitPrice: 18, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Hypersensitivity to components'],
    contraindicationsAr: ['فرط الحساسية للمكونات'],
    monitoringRequired: ['Symptom improvement'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0954', genericName: 'Mupirocin', genericNameAr: 'موبيروسين',
    brandNames: ['Bactroban'], sfda_registration: 'SFDA-2024-DER-954',
    atcCode: 'D06AX09', atcCategory: 'D06A', therapeuticClass: 'Ophthalmic & Dermatologic',
    therapeuticClassAr: 'أدوية العيون والجلدية', formularyStatus: 'formulary',
    route: ['topical', 'nasal'], forms: [{ form: 'ointment', strength: '2%', unitPrice: 15, inStock: true }, { form: 'nasal ointment', strength: '2%', unitPrice: 22, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Hypersensitivity to mupirocin', 'Do not use on burns or large open wounds (renal risk from PEG base)'],
    contraindicationsAr: ['فرط الحساسية للموبيروسين', 'لا تستخدم على الحروق أو الجروح المفتوحة الكبيرة'],
    monitoringRequired: ['Clinical response', 'Superinfection signs'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0955', genericName: 'Clobetasol Propionate', genericNameAr: 'كلوبيتازول بروبيونات',
    brandNames: ['Dermovate', 'Temovate'], sfda_registration: 'SFDA-2024-DER-955',
    atcCode: 'D07AD01', atcCategory: 'D07A', therapeuticClass: 'Ophthalmic & Dermatologic',
    therapeuticClassAr: 'أدوية العيون والجلدية', formularyStatus: 'formulary',
    route: ['topical'], forms: [{ form: 'cream', strength: '0.05%', unitPrice: 12, inStock: true }, { form: 'ointment', strength: '0.05%', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Clobetasone'],
    interactions: [],
    contraindications: ['Rosacea', 'Acne', 'Perioral dermatitis', 'Untreated skin infections', 'Children under 12'],
    contraindicationsAr: ['الوردية', 'حب الشباب', 'التهاب الجلد حول الفم', 'عدوى جلدية غير معالجة', 'الأطفال أقل من 12 سنة'],
    monitoringRequired: ['Skin atrophy signs', 'HPA axis suppression with large areas', 'Limit to 2 weeks'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0956', genericName: 'Silver Sulfadiazine', genericNameAr: 'سلفاديازين الفضة',
    brandNames: ['Silvadene', 'Flamazine'], sfda_registration: 'SFDA-2024-DER-956',
    atcCode: 'D06BA01', atcCategory: 'D06B', therapeuticClass: 'Ophthalmic & Dermatologic',
    therapeuticClassAr: 'أدوية العيون والجلدية', formularyStatus: 'formulary',
    route: ['topical'], forms: [{ form: 'cream', strength: '1%', unitPrice: 18, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Sulfasalazine'],
    interactions: [],
    contraindications: ['Sulfonamide allergy', 'Pregnancy at term', 'Premature infants', 'G6PD deficiency'],
    contraindicationsAr: ['حساسية السلفوناميد', 'الحمل في نهاية المدة', 'الخدج', 'نقص G6PD'],
    monitoringRequired: ['CBC for large burns', 'Renal function', 'Wound healing progress'], storageConditions: 'Store below 25°C'
  },
];

export const MISCELLANEOUS_ESSENTIAL: FormularyDrug[] = [
  {
    id: 'FRM-0957', genericName: 'Desmopressin', genericNameAr: 'ديسموبريسين',
    brandNames: ['DDAVP', 'Minirin'], sfda_registration: 'SFDA-2024-MIS-957',
    atcCode: 'H01BA02', atcCategory: 'H01B', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['oral', 'intranasal', 'intravenous', 'subcutaneous'], forms: [{ form: 'tablet', strength: '0.2mg', unitPrice: 8, inStock: true }, { form: 'nasal spray', strength: '10mcg/spray', unitPrice: 95, inStock: true }, { form: 'injection', strength: '4mcg/ml', unitPrice: 35, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Vasopressin'],
    interactions: [{ interactsWith: 'NSAIDs', severity: 'moderate', mechanism: 'Enhanced water retention', clinicalEffect: 'Severe hyponatremia', clinicalEffectAr: 'نقص صوديوم شديد', management: 'Monitor sodium closely', managementAr: 'مراقبة الصوديوم بدقة' }],
    contraindications: ['Habitual polydipsia', 'Moderate to severe renal insufficiency', 'Hyponatremia'],
    contraindicationsAr: ['العطش المفرط المعتاد', 'قصور كلوي متوسط إلى شديد', 'نقص صوديوم الدم'],
    monitoringRequired: ['Serum sodium', 'Fluid intake/output', 'Urine osmolality'], storageConditions: 'Refrigerate 2-8°C'
  },
  {
    id: 'FRM-0958', genericName: 'Octreotide', genericNameAr: 'أوكتريوتيد',
    brandNames: ['Sandostatin'], sfda_registration: 'SFDA-2024-MIS-958',
    atcCode: 'H01CB02', atcCategory: 'H01C', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'restricted',
    restrictionCriteria: 'Acromegaly, carcinoid, variceal bleeding', restrictionCriteriaAr: 'تضخم الأطراف أو الورم السرطاوي أو نزيف الدوالي', approverRole: 'consultant_specialist',
    route: ['subcutaneous', 'intravenous'], forms: [{ form: 'injection', strength: '100mcg/ml', unitPrice: 35, inStock: true }, { form: 'injection', strength: '500mcg/ml', unitPrice: 65, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Cyclosporine', severity: 'moderate', mechanism: 'Reduced cyclosporine absorption', clinicalEffect: 'Transplant rejection risk', clinicalEffectAr: 'خطر رفض الزراعة', management: 'Monitor cyclosporine levels', managementAr: 'مراقبة مستويات السيكلوسبورين' }],
    contraindications: ['Hypersensitivity to octreotide'],
    contraindicationsAr: ['فرط الحساسية للأوكتريوتيد'],
    monitoringRequired: ['Blood glucose', 'Thyroid function', 'Gallbladder ultrasound', 'Vitamin B12 levels'], storageConditions: 'Refrigerate 2-8°C'
  },
  {
    id: 'FRM-0959', genericName: 'Vasopressin', genericNameAr: 'فاسوبريسين',
    brandNames: ['Pitressin', 'Vasostrict'], sfda_registration: 'SFDA-2024-MIS-959',
    atcCode: 'H01BA01', atcCategory: 'H01B', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '20units/ml', unitPrice: 18, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Desmopressin'],
    interactions: [],
    contraindications: ['Vascular disease especially coronary', 'Chronic nephritis'],
    contraindicationsAr: ['أمراض الأوعية الدموية خاصة الشريان التاجي', 'التهاب الكلية المزمن'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'Fluid intake/output', 'Serum sodium', 'Signs of water intoxication'], storageConditions: 'Refrigerate 2-8°C'
  },
  {
    id: 'FRM-0960', genericName: 'Bosentan', genericNameAr: 'بوسنتان',
    brandNames: ['Tracleer'], sfda_registration: 'SFDA-2024-MIS-960',
    atcCode: 'C02KX01', atcCategory: 'C02K', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'restricted',
    restrictionCriteria: 'Pulmonary arterial hypertension (PAH)', restrictionCriteriaAr: 'ارتفاع ضغط الدم الشرياني الرئوي', approverRole: 'cardiologist',
    route: ['oral'], forms: [{ form: 'tablet', strength: '62.5mg', unitPrice: 85, inStock: true }, { form: 'tablet', strength: '125mg', unitPrice: 120, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Hepatotoxicity and teratogenicity. Pregnancy must be excluded before initiation and prevented during treatment.',
    blackBoxWarningAr: 'سمية كبدية وتشوه جنيني. يجب استبعاد الحمل قبل البدء ومنعه أثناء العلاج.',
    interactions: [{ interactsWith: 'Cyclosporine', severity: 'major', mechanism: 'Markedly increased bosentan levels via CYP3A4 inhibition', clinicalEffect: 'Liver toxicity and hypotension', clinicalEffectAr: 'سمية كبدية وانخفاض ضغط الدم', management: 'Contraindicated combination', managementAr: 'تركيبة ممنوعة' }],
    contraindications: ['Pregnancy', 'Concurrent cyclosporine or glyburide', 'Elevated aminotransferases >3x ULN'],
    contraindicationsAr: ['الحمل', 'السيكلوسبورين أو الغليبوريد المتزامن', 'ارتفاع ناقلات الأمين أكثر من 3 أضعاف'],
    monitoringRequired: ['Liver function tests monthly', 'Pregnancy test monthly', 'Hemoglobin at 1 and 3 months'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0961', genericName: 'Tranexamic Acid', genericNameAr: 'حمض الترانيكساميك',
    brandNames: ['Cyklokapron', 'Lysteda'], sfda_registration: 'SFDA-2024-MIS-961',
    atcCode: 'B02AA02', atcCategory: 'B02A', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '500mg', unitPrice: 3, inStock: true }, { form: 'injection', strength: '100mg/ml', unitPrice: 8, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Combined oral contraceptives', severity: 'moderate', mechanism: 'Additive thrombotic risk', clinicalEffect: 'Increased VTE risk', clinicalEffectAr: 'زيادة خطر الجلطات الوريدية', management: 'Use with caution', managementAr: 'الاستخدام بحذر' }],
    contraindications: ['Active thromboembolic disease', 'History of convulsions', 'Subarachnoid hemorrhage'],
    contraindicationsAr: ['مرض الانسداد التجلطي النشط', 'تاريخ نوبات', 'نزيف تحت العنكبوتية'],
    monitoringRequired: ['Signs of thrombosis', 'Renal function', 'Visual changes (rare retinal toxicity)'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0962', genericName: 'Mannitol', genericNameAr: 'مانيتول',
    brandNames: ['Osmitrol'], sfda_registration: 'SFDA-2024-MIS-962',
    atcCode: 'B05BC01', atcCategory: 'B05B', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '20%', unitPrice: 8, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Sorbitol'],
    interactions: [],
    contraindications: ['Severe renal failure with anuria', 'Pulmonary edema', 'Active intracranial bleeding', 'Severe dehydration'],
    contraindicationsAr: ['فشل كلوي شديد مع انقطاع البول', 'وذمة رئوية', 'نزيف داخل القحف النشط', 'جفاف شديد'],
    monitoringRequired: ['Serum osmolality (keep <320)', 'Serum electrolytes', 'Fluid balance', 'Renal function'], storageConditions: 'Store below 30°C, do not freeze'
  },
  {
    id: 'FRM-0963', genericName: 'Aminophylline', genericNameAr: 'أمينوفيلين',
    brandNames: ['Aminophylline Injection'], sfda_registration: 'SFDA-2024-MIS-963',
    atcCode: 'R03DA05', atcCategory: 'R03D', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['intravenous', 'oral'], forms: [{ form: 'injection', strength: '25mg/ml', unitPrice: 4, inStock: true }, { form: 'tablet', strength: '100mg', unitPrice: 1, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Theophylline'],
    interactions: [{ interactsWith: 'Ciprofloxacin', severity: 'major', mechanism: 'CYP1A2 inhibition', clinicalEffect: 'Theophylline toxicity (seizures, arrhythmias)', clinicalEffectAr: 'سمية الثيوفيلين (نوبات واضطرابات نظم)', management: 'Reduce theophylline dose by 30-50%', managementAr: 'تقليل جرعة الثيوفيلين بنسبة 30-50%' }],
    contraindications: ['Uncontrolled arrhythmias', 'Active peptic ulcer', 'Seizure disorder'],
    contraindicationsAr: ['اضطرابات النظم غير المنضبطة', 'قرحة هضمية نشطة', 'اضطراب نوبات'],
    monitoringRequired: ['Serum theophylline levels (10-20mcg/ml)', 'Heart rate', 'Signs of toxicity'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0964', genericName: 'Oxytocin', genericNameAr: 'أوكسيتوسين',
    brandNames: ['Pitocin', 'Syntocinon'], sfda_registration: 'SFDA-2024-MIS-964',
    atcCode: 'H01BB02', atcCategory: 'H01B', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['intravenous', 'intramuscular'], forms: [{ form: 'injection', strength: '10IU/ml', unitPrice: 4, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'X', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: false, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Oxycodone'],
    blackBoxWarning: 'Not for elective labor induction. Uterine hyperstimulation can cause fetal distress, death, or uterine rupture.',
    blackBoxWarningAr: 'ليس للتحريض الاختياري للولادة. فرط تنبيه الرحم قد يسبب ضائقة جنينية أو وفاة أو تمزق الرحم.',
    interactions: [{ interactsWith: 'Misoprostol', severity: 'major', mechanism: 'Synergistic uterotonic effect', clinicalEffect: 'Uterine rupture', clinicalEffectAr: 'تمزق الرحم', management: 'Allow adequate interval between agents', managementAr: 'السماح بفترة كافية بين الأدوية' }],
    contraindications: ['Cephalopelvic disproportion', 'Unfavorable fetal positions', 'Previous uterine surgery (relative)', 'Cord prolapse'],
    contraindicationsAr: ['عدم التناسب الرأسي الحوضي', 'أوضاع جنينية غير ملائمة', 'جراحة رحم سابقة (نسبي)', 'تدلي الحبل'],
    monitoringRequired: ['Continuous fetal monitoring', 'Uterine contractions', 'Maternal vital signs', 'Fluid balance (water intoxication)'], storageConditions: 'Refrigerate 2-8°C'
  },
  {
    id: 'FRM-0965', genericName: 'Dopamine', genericNameAr: 'دوبامين',
    brandNames: ['Intropin'], sfda_registration: 'SFDA-2024-MIS-965',
    atcCode: 'C01CA04', atcCategory: 'C01C', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '200mg/5ml', unitPrice: 6, inStock: true }, { form: 'injection', strength: '400mg/250ml premixed', unitPrice: 18, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Dobutamine'],
    interactions: [{ interactsWith: 'Phenytoin', severity: 'major', mechanism: 'Hypotension and bradycardia', clinicalEffect: 'Cardiovascular collapse', clinicalEffectAr: 'انهيار قلبي وعائي', management: 'Avoid concurrent IV phenytoin', managementAr: 'تجنب الفينيتوين الوريدي المتزامن' }],
    contraindications: ['Pheochromocytoma', 'Uncorrected tachyarrhythmias', 'Ventricular fibrillation'],
    contraindicationsAr: ['ورم القواتم', 'تسرع النظم غير المصحح', 'رجفان بطيني'],
    monitoringRequired: ['Continuous ECG', 'Blood pressure', 'Urine output', 'IV site for extravasation'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0966', genericName: 'Norepinephrine', genericNameAr: 'نورإبينفرين',
    brandNames: ['Levophed'], sfda_registration: 'SFDA-2024-MIS-966',
    atcCode: 'C01CA03', atcCategory: 'C01C', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '4mg/4ml', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Epinephrine'],
    interactions: [{ interactsWith: 'Tricyclic antidepressants', severity: 'major', mechanism: 'Potentiated pressor response', clinicalEffect: 'Severe hypertension', clinicalEffectAr: 'ارتفاع شديد في ضغط الدم', management: 'Start with lower dose', managementAr: 'ابدأ بجرعة أقل' }],
    contraindications: ['Mesenteric or peripheral vascular thrombosis', 'Hypotension from blood volume deficit (without fluid replacement)'],
    contraindicationsAr: ['تجلط الأوعية المساريقية أو المحيطية', 'انخفاض ضغط الدم من نقص حجم الدم (بدون تعويض السوائل)'],
    monitoringRequired: ['Continuous blood pressure', 'ECG', 'Central venous access preferred', 'Tissue perfusion', 'IV site (severe necrosis if extravasation)'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0967', genericName: 'Epinephrine (Adrenaline)', genericNameAr: 'إبينفرين (أدرينالين)',
    brandNames: ['EpiPen', 'Adrenaline'], sfda_registration: 'SFDA-2024-MIS-967',
    atcCode: 'C01CA24', atcCategory: 'C01C', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['intravenous', 'intramuscular', 'subcutaneous', 'inhalation'], forms: [{ form: 'injection', strength: '1mg/ml (1:1000)', unitPrice: 4, inStock: true }, { form: 'auto-injector', strength: '0.3mg', unitPrice: 120, inStock: true }, { form: 'injection', strength: '0.1mg/ml (1:10000)', unitPrice: 5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Norepinephrine', 'Ephedrine'],
    interactions: [{ interactsWith: 'Beta-blockers', severity: 'major', mechanism: 'Unopposed alpha stimulation', clinicalEffect: 'Severe hypertension and reflex bradycardia', clinicalEffectAr: 'ارتفاع شديد في ضغط الدم وبطء القلب الانعكاسي', management: 'Consider glucagon for anaphylaxis in beta-blocked patients', managementAr: 'النظر في الجلوكاجون لصدمة الحساسية في المرضى على حاصرات بيتا' }],
    contraindications: ['No absolute contraindications in life-threatening anaphylaxis'],
    contraindicationsAr: ['لا موانع مطلقة في صدمة الحساسية المهددة للحياة'],
    monitoringRequired: ['Heart rate and rhythm', 'Blood pressure', 'Oxygen saturation', 'Serum potassium'], storageConditions: 'Store below 25°C, protect from light, do not freeze'
  },
  {
    id: 'FRM-0968', genericName: 'Phenylephrine', genericNameAr: 'فينيليفرين',
    brandNames: ['Neo-Synephrine'], sfda_registration: 'SFDA-2024-MIS-968',
    atcCode: 'C01CA06', atcCategory: 'C01C', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['intravenous', 'nasal', 'ophthalmic'], forms: [{ form: 'injection', strength: '10mg/ml', unitPrice: 6, inStock: true }, { form: 'nasal spray', strength: '0.25%', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Phenytoin'],
    interactions: [{ interactsWith: 'MAO inhibitors', severity: 'major', mechanism: 'Potentiated pressor effect', clinicalEffect: 'Hypertensive crisis', clinicalEffectAr: 'أزمة ارتفاع ضغط الدم', management: 'Reduce phenylephrine dose significantly', managementAr: 'تقليل جرعة الفينيليفرين بشكل كبير' }],
    contraindications: ['Severe hypertension', 'Ventricular tachycardia'],
    contraindicationsAr: ['ارتفاع ضغط الدم الشديد', 'تسرع القلب البطيني'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'Tissue perfusion'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0969', genericName: 'Dobutamine', genericNameAr: 'دوبوتامين',
    brandNames: ['Dobutrex'], sfda_registration: 'SFDA-2024-MIS-969',
    atcCode: 'C01CA07', atcCategory: 'C01C', therapeuticClass: 'Miscellaneous Essential',
    therapeuticClassAr: 'أدوية أساسية متنوعة', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '250mg/20ml', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Dopamine'],
    interactions: [{ interactsWith: 'Beta-blockers', severity: 'moderate', mechanism: 'Antagonism of inotropic effect', clinicalEffect: 'Reduced cardiac output improvement', clinicalEffectAr: 'انخفاض تحسن النتاج القلبي', management: 'May need higher dobutamine dose', managementAr: 'قد يحتاج جرعة دوبوتامين أعلى' }],
    contraindications: ['IHSS (Idiopathic Hypertrophic Subaortic Stenosis)', 'Hypersensitivity to dobutamine'],
    contraindicationsAr: ['تضيق تحت الأبهري الضخامي مجهول السبب', 'فرط الحساسية للدوبوتامين'],
    monitoringRequired: ['Continuous ECG', 'Blood pressure', 'Heart rate', 'Urine output', 'Serum potassium'], storageConditions: 'Store below 30°C'
  },
];

