/**
 * Saudi MOH Drug Formulary — Part 6: Anti-infectives Extended
 * Antifungals, Antivirals, Anti-TB, Antiparasitics
 * IDs: FRM-0252 through FRM-0301
 */
import type { FormularyDrug } from './formularyTypes';

export const ANTIFUNGALS: FormularyDrug[] = [
  {
    id: 'FRM-0252', genericName: 'Fluconazole', genericNameAr: 'فلوكونازول',
    brandNames: ['Diflucan', 'Flucoral'], sfda_registration: 'SFDA-2024-ANT-252',
    atcCode: 'J02AC01', atcCategory: 'J02A', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'formulary',
    route: ['oral', 'intravenous'], forms: [{ form: 'capsule', strength: '150mg', unitPrice: 8, inStock: true }, { form: 'injection', strength: '200mg/100ml', unitPrice: 35, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Fluoxetine'],
    interactions: [{ interactsWith: 'Warfarin', severity: 'major', mechanism: 'CYP2C9 inhibition', clinicalEffect: 'Increased bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف', management: 'Monitor INR closely, reduce warfarin dose', managementAr: 'مراقبة INR وتقليل جرعة الوارفارين' }],
    contraindications: ['Hypersensitivity to azole antifungals', 'Concurrent terfenadine use'],
    contraindicationsAr: ['فرط الحساسية لمضادات الفطريات الآزولية', 'الاستخدام المتزامن مع تيرفينادين'],
    monitoringRequired: ['Liver function tests', 'Renal function'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0253', genericName: 'Voriconazole', genericNameAr: 'فوريكونازول',
    brandNames: ['Vfend'], sfda_registration: 'SFDA-2024-ANT-253',
    atcCode: 'J02AC03', atcCategory: 'J02A', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'restricted',
    restrictionCriteria: 'Invasive aspergillosis or resistant Candida', restrictionCriteriaAr: 'داء الرشاشيات الغازية أو المبيضات المقاومة', approverRole: 'infectious_disease_specialist',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '200mg', unitPrice: 85, inStock: true }, { form: 'injection', strength: '200mg', unitPrice: 250, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Fluconazole'],
    interactions: [{ interactsWith: 'Sirolimus', severity: 'major', mechanism: 'CYP3A4 inhibition', clinicalEffect: 'Sirolimus toxicity', clinicalEffectAr: 'سمية سيروليمس', management: 'Contraindicated combination', managementAr: 'تركيبة ممنوعة' }],
    contraindications: ['Concurrent sirolimus', 'Concurrent rifampicin', 'Severe hepatic impairment'],
    contraindicationsAr: ['الاستخدام المتزامن مع سيروليمس', 'الاستخدام المتزامن مع ريفامبيسين', 'قصور كبدي شديد'],
    monitoringRequired: ['Visual function', 'Liver function tests', 'Trough drug levels'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0254', genericName: 'Amphotericin B Liposomal', genericNameAr: 'أمفوتيريسين ب ليبوزومي',
    brandNames: ['AmBisome'], sfda_registration: 'SFDA-2024-ANT-254',
    atcCode: 'J02AA01', atcCategory: 'J02A', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'restricted',
    restrictionCriteria: 'Severe systemic fungal infections', restrictionCriteriaAr: 'العدوى الفطرية الجهازية الشديدة', approverRole: 'infectious_disease_specialist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '50mg', unitPrice: 450, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Amphotericin B conventional'],
    interactions: [{ interactsWith: 'Gentamicin', severity: 'major', mechanism: 'Additive nephrotoxicity', clinicalEffect: 'Increased kidney damage risk', clinicalEffectAr: 'زيادة خطر تلف الكلى', management: 'Avoid combination if possible', managementAr: 'تجنب الجمع إن أمكن' }],
    contraindications: ['Hypersensitivity to amphotericin B'],
    contraindicationsAr: ['فرط الحساسية للأمفوتيريسين ب'],
    monitoringRequired: ['Renal function daily', 'Serum potassium', 'Magnesium levels', 'Infusion reactions'], storageConditions: 'Refrigerate 2-8°C'
  },
  {
    id: 'FRM-0255', genericName: 'Caspofungin', genericNameAr: 'كاسبوفنجين',
    brandNames: ['Cancidas'], sfda_registration: 'SFDA-2024-ANT-255',
    atcCode: 'J02AX04', atcCategory: 'J02A', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'restricted',
    restrictionCriteria: 'Invasive candidiasis or aspergillosis', restrictionCriteriaAr: 'داء المبيضات أو الرشاشيات الغازية', approverRole: 'infectious_disease_specialist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '70mg', unitPrice: 380, inStock: true }, { form: 'injection', strength: '50mg', unitPrice: 320, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Micafungin'],
    interactions: [{ interactsWith: 'Cyclosporine', severity: 'moderate', mechanism: 'Hepatic enzyme interaction', clinicalEffect: 'Elevated liver enzymes', clinicalEffectAr: 'ارتفاع إنزيمات الكبد', management: 'Monitor LFTs', managementAr: 'مراقبة وظائف الكبد' }],
    contraindications: ['Hypersensitivity to echinocandins'],
    contraindicationsAr: ['فرط الحساسية للإكينوكاندين'],
    monitoringRequired: ['Liver function tests', 'CBC'], storageConditions: 'Refrigerate 2-8°C'
  },
  {
    id: 'FRM-0256', genericName: 'Micafungin', genericNameAr: 'ميكافنجين',
    brandNames: ['Mycamine'], sfda_registration: 'SFDA-2024-ANT-256',
    atcCode: 'J02AX05', atcCategory: 'J02A', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'restricted',
    restrictionCriteria: 'Esophageal candidiasis or invasive candidiasis', restrictionCriteriaAr: 'داء المبيضات المريئي أو الغازي', approverRole: 'infectious_disease_specialist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '100mg', unitPrice: 290, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Caspofungin'],
    interactions: [{ interactsWith: 'Sirolimus', severity: 'moderate', mechanism: 'Increased sirolimus levels', clinicalEffect: 'Sirolimus toxicity risk', clinicalEffectAr: 'خطر سمية سيروليمس', management: 'Monitor sirolimus levels', managementAr: 'مراقبة مستويات سيروليمس' }],
    contraindications: ['Hypersensitivity to micafungin or echinocandins'],
    contraindicationsAr: ['فرط الحساسية للميكافنجين أو الإكينوكاندين'],
    monitoringRequired: ['Liver function tests', 'Renal function'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0257', genericName: 'Itraconazole', genericNameAr: 'إيتراكونازول',
    brandNames: ['Sporanox'], sfda_registration: 'SFDA-2024-ANT-257',
    atcCode: 'J02AC02', atcCategory: 'J02A', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'capsule', strength: '100mg', unitPrice: 12, inStock: true }, { form: 'oral solution', strength: '10mg/ml', unitPrice: 65, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Fluconazole'],
    interactions: [{ interactsWith: 'Simvastatin', severity: 'major', mechanism: 'CYP3A4 inhibition', clinicalEffect: 'Rhabdomyolysis risk', clinicalEffectAr: 'خطر انحلال الربيدات', management: 'Contraindicated combination', managementAr: 'تركيبة ممنوعة' }],
    contraindications: ['Heart failure', 'Concurrent HMG-CoA reductase inhibitors'],
    contraindicationsAr: ['فشل القلب', 'الاستخدام المتزامن مع مثبطات HMG-CoA'],
    monitoringRequired: ['Liver function tests', 'Heart function in prolonged use'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0258', genericName: 'Terbinafine', genericNameAr: 'تيربينافين',
    brandNames: ['Lamisil'], sfda_registration: 'SFDA-2024-ANT-258',
    atcCode: 'D01BA02', atcCategory: 'D01B', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'formulary',
    route: ['oral', 'topical'], forms: [{ form: 'tablet', strength: '250mg', unitPrice: 6, inStock: true }, { form: 'cream', strength: '1%', unitPrice: 15, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Terbutaline'],
    interactions: [{ interactsWith: 'Rifampicin', severity: 'moderate', mechanism: 'CYP induction', clinicalEffect: 'Reduced terbinafine levels', clinicalEffectAr: 'انخفاض مستويات تيربينافين', management: 'May need dose adjustment', managementAr: 'قد يحتاج تعديل الجرعة' }],
    contraindications: ['Chronic or active liver disease', 'Hypersensitivity'],
    contraindicationsAr: ['مرض كبدي مزمن أو نشط', 'فرط الحساسية'],
    monitoringRequired: ['Liver function tests before and during treatment', 'CBC'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0259', genericName: 'Nystatin', genericNameAr: 'نيستاتين',
    brandNames: ['Mycostatin'], sfda_registration: 'SFDA-2024-ANT-259',
    atcCode: 'A07AA02', atcCategory: 'A07A', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'formulary',
    route: ['oral', 'topical'], forms: [{ form: 'oral suspension', strength: '100000IU/ml', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Nitrostat'],
    interactions: [],
    contraindications: ['Hypersensitivity to nystatin'],
    contraindicationsAr: ['فرط الحساسية للنيستاتين'],
    monitoringRequired: ['Clinical response'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0260', genericName: 'Posaconazole', genericNameAr: 'بوساكونازول',
    brandNames: ['Noxafil'], sfda_registration: 'SFDA-2024-ANT-260',
    atcCode: 'J02AC04', atcCategory: 'J02A', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'restricted',
    restrictionCriteria: 'Prophylaxis in immunocompromised or refractory fungal infections', restrictionCriteriaAr: 'الوقاية في المرضى منقوصي المناعة أو العدوى الفطرية المقاومة', approverRole: 'infectious_disease_specialist',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '100mg', unitPrice: 120, inStock: true }, { form: 'injection', strength: '300mg/16.7ml', unitPrice: 350, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Voriconazole'],
    interactions: [{ interactsWith: 'Cyclosporine', severity: 'major', mechanism: 'CYP3A4 inhibition', clinicalEffect: 'Increased cyclosporine levels', clinicalEffectAr: 'زيادة مستويات السيكلوسبورين', management: 'Reduce cyclosporine dose by 25%', managementAr: 'تقليل جرعة السيكلوسبورين بنسبة 25%' }],
    contraindications: ['Concurrent ergot alkaloids', 'Concurrent sirolimus'],
    contraindicationsAr: ['الاستخدام المتزامن مع قلويدات الإرغوت', 'الاستخدام المتزامن مع سيروليمس'],
    monitoringRequired: ['Liver function tests', 'Trough drug levels', 'ECG for QTc'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0261', genericName: 'Anidulafungin', genericNameAr: 'أنيدولافنجين',
    brandNames: ['Eraxis'], sfda_registration: 'SFDA-2024-ANT-261',
    atcCode: 'J02AX06', atcCategory: 'J02A', therapeuticClass: 'Antifungals',
    therapeuticClassAr: 'مضادات الفطريات', formularyStatus: 'restricted',
    restrictionCriteria: 'Invasive candidiasis in ICU patients', restrictionCriteriaAr: 'داء المبيضات الغازي في مرضى العناية المركزة', approverRole: 'infectious_disease_specialist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '100mg', unitPrice: 340, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Caspofungin', 'Micafungin'],
    interactions: [{ interactsWith: 'Cyclosporine', severity: 'minor', mechanism: 'Slight increase in anidulafungin exposure', clinicalEffect: 'No significant clinical effect', clinicalEffectAr: 'لا تأثير سريري مهم', management: 'No dose adjustment needed', managementAr: 'لا حاجة لتعديل الجرعة' }],
    contraindications: ['Hypersensitivity to echinocandins'],
    contraindicationsAr: ['فرط الحساسية للإكينوكاندين'],
    monitoringRequired: ['Liver function tests', 'Signs of histamine-mediated reactions'], storageConditions: 'Refrigerate 2-8°C'
  },
];

export const ANTIVIRALS: FormularyDrug[] = [
  {
    id: 'FRM-0262', genericName: 'Acyclovir', genericNameAr: 'أسيكلوفير',
    brandNames: ['Zovirax'], sfda_registration: 'SFDA-2024-ANT-262',
    atcCode: 'J05AB01', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'topical'], forms: [{ form: 'tablet', strength: '400mg', unitPrice: 3, inStock: true }, { form: 'injection', strength: '250mg', unitPrice: 25, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Valacyclovir'],
    interactions: [{ interactsWith: 'Probenecid', severity: 'moderate', mechanism: 'Reduced renal clearance', clinicalEffect: 'Increased acyclovir levels', clinicalEffectAr: 'زيادة مستويات الأسيكلوفير', management: 'Dose adjustment may be needed', managementAr: 'قد يحتاج تعديل الجرعة' }],
    contraindications: ['Hypersensitivity to acyclovir or valacyclovir'],
    contraindicationsAr: ['فرط الحساسية للأسيكلوفير أو فالاسيكلوفير'],
    monitoringRequired: ['Renal function', 'Hydration status'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0263', genericName: 'Valacyclovir', genericNameAr: 'فالاسيكلوفير',
    brandNames: ['Valtrex'], sfda_registration: 'SFDA-2024-ANT-263',
    atcCode: 'J05AB11', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '500mg', unitPrice: 8, inStock: true }, { form: 'tablet', strength: '1000mg', unitPrice: 14, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Acyclovir', 'Valganciclovir'],
    interactions: [{ interactsWith: 'Mycophenolate', severity: 'moderate', mechanism: 'Competition for renal tubular secretion', clinicalEffect: 'Increased levels of both drugs', clinicalEffectAr: 'زيادة مستويات كلا الدوائين', management: 'Monitor renal function', managementAr: 'مراقبة وظائف الكلى' }],
    contraindications: ['Hypersensitivity to valacyclovir or acyclovir'],
    contraindicationsAr: ['فرط الحساسية لفالاسيكلوفير أو الأسيكلوفير'],
    monitoringRequired: ['Renal function', 'CBC in immunocompromised'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0264', genericName: 'Oseltamivir', genericNameAr: 'أوسيلتاميفير',
    brandNames: ['Tamiflu'], sfda_registration: 'SFDA-2024-ANT-264',
    atcCode: 'J05AH02', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'capsule', strength: '75mg', unitPrice: 18, inStock: true }, { form: 'oral suspension', strength: '6mg/ml', unitPrice: 45, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Hypersensitivity to oseltamivir'],
    contraindicationsAr: ['فرط الحساسية للأوسيلتاميفير'],
    monitoringRequired: ['Clinical response', 'Neuropsychiatric events in children'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0265', genericName: 'Tenofovir Disoproxil', genericNameAr: 'تينوفوفير ديسوبروكسيل',
    brandNames: ['Viread'], sfda_registration: 'SFDA-2024-ANT-265',
    atcCode: 'J05AF07', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '300mg', unitPrice: 22, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Tenofovir Alafenamide'],
    interactions: [{ interactsWith: 'Didanosine', severity: 'major', mechanism: 'Increased didanosine levels', clinicalEffect: 'Pancreatitis and neuropathy risk', clinicalEffectAr: 'خطر التهاب البنكرياس والاعتلال العصبي', management: 'Avoid combination or reduce didanosine dose', managementAr: 'تجنب الجمع أو تقليل جرعة ديدانوزين' }],
    contraindications: ['Severe renal impairment (CrCl <30ml/min) without dose adjustment'],
    contraindicationsAr: ['قصور كلوي شديد بدون تعديل الجرعة'],
    monitoringRequired: ['Renal function every 3 months', 'Bone mineral density', 'Serum phosphorus'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0266', genericName: 'Entecavir', genericNameAr: 'إنتيكافير',
    brandNames: ['Baraclude'], sfda_registration: 'SFDA-2024-ANT-266',
    atcCode: 'J05AF10', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '0.5mg', unitPrice: 28, inStock: true }, { form: 'tablet', strength: '1mg', unitPrice: 42, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Severe acute exacerbations of hepatitis B reported upon discontinuation',
    blackBoxWarningAr: 'تم الإبلاغ عن تفاقم حاد شديد لالتهاب الكبد ب عند التوقف',
    interactions: [],
    contraindications: ['Hypersensitivity to entecavir'],
    contraindicationsAr: ['فرط الحساسية للإنتيكافير'],
    monitoringRequired: ['HBV DNA levels', 'Liver function tests', 'Lactic acidosis signs'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0267', genericName: 'Sofosbuvir', genericNameAr: 'سوفوسبوفير',
    brandNames: ['Sovaldi'], sfda_registration: 'SFDA-2024-ANT-267',
    atcCode: 'J05AP08', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'restricted',
    restrictionCriteria: 'Chronic hepatitis C, specialist prescribing only', restrictionCriteriaAr: 'التهاب الكبد سي المزمن، وصف الأخصائي فقط', approverRole: 'hepatologist',
    route: ['oral'], forms: [{ form: 'tablet', strength: '400mg', unitPrice: 180, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Amiodarone', severity: 'major', mechanism: 'Symptomatic bradycardia', clinicalEffect: 'Life-threatening bradycardia', clinicalEffectAr: 'بطء القلب المهدد للحياة', management: 'Contraindicated with amiodarone', managementAr: 'ممنوع مع الأميودارون' }],
    contraindications: ['Concurrent amiodarone', 'Strong P-gp inducers'],
    contraindicationsAr: ['الاستخدام المتزامن مع الأميودارون', 'محفزات P-gp القوية'],
    monitoringRequired: ['HCV RNA at baseline and post-treatment', 'Heart rate if used with beta-blockers'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0268', genericName: 'Sofosbuvir/Ledipasvir', genericNameAr: 'سوفوسبوفير/ليديباسفير',
    brandNames: ['Harvoni'], sfda_registration: 'SFDA-2024-ANT-268',
    atcCode: 'J05AP51', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'restricted',
    restrictionCriteria: 'HCV genotype 1, 4, 5, or 6', restrictionCriteriaAr: 'التهاب الكبد سي النمط الجيني 1 أو 4 أو 5 أو 6', approverRole: 'hepatologist',
    route: ['oral'], forms: [{ form: 'tablet', strength: '400mg/90mg', unitPrice: 220, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Rosuvastatin', severity: 'major', mechanism: 'Increased statin levels via OATP inhibition', clinicalEffect: 'Myopathy/rhabdomyolysis', clinicalEffectAr: 'اعتلال عضلي/انحلال ربيدات', management: 'Do not exceed rosuvastatin 10mg', managementAr: 'لا تتجاوز روسوفاستاتين 10ملغ' }],
    contraindications: ['Concurrent rifampicin', 'Concurrent St. Johns Wort'],
    contraindicationsAr: ['الاستخدام المتزامن مع ريفامبيسين', 'الاستخدام المتزامن مع نبتة سانت جون'],
    monitoringRequired: ['HCV RNA levels', 'Liver function tests'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0269', genericName: 'Ganciclovir', genericNameAr: 'غانسيكلوفير',
    brandNames: ['Cymevene'], sfda_registration: 'SFDA-2024-ANT-269',
    atcCode: 'J05AB06', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'restricted',
    restrictionCriteria: 'CMV infection in immunocompromised', restrictionCriteriaAr: 'عدوى الفيروس المضخم للخلايا في منقوصي المناعة', approverRole: 'infectious_disease_specialist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '500mg', unitPrice: 95, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Acyclovir', 'Valganciclovir'],
    blackBoxWarning: 'Granulocytopenia, anemia, thrombocytopenia. Teratogenic and carcinogenic in animals.',
    blackBoxWarningAr: 'نقص المحببات وفقر الدم ونقص الصفيحات. ماسخ ومسرطن في الحيوانات.',
    interactions: [{ interactsWith: 'Imipenem', severity: 'major', mechanism: 'Increased seizure risk', clinicalEffect: 'Generalized seizures', clinicalEffectAr: 'نوبات صرعية معممة', management: 'Avoid combination', managementAr: 'تجنب الجمع' }],
    contraindications: ['Absolute neutrophil count <500', 'Platelet count <25000', 'Pregnancy'],
    contraindicationsAr: ['عدد العدلات المطلق أقل من 500', 'عدد الصفيحات أقل من 25000', 'الحمل'],
    monitoringRequired: ['CBC twice weekly', 'Renal function', 'Serum creatinine'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0270', genericName: 'Remdesivir', genericNameAr: 'ريمديسيفير',
    brandNames: ['Veklury'], sfda_registration: 'SFDA-2024-ANT-270',
    atcCode: 'J05AB16', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'restricted',
    restrictionCriteria: 'Hospitalized COVID-19 or severe viral pneumonia', restrictionCriteriaAr: 'كوفيد-19 في المرضى المنومين أو الالتهاب الرئوي الفيروسي الشديد', approverRole: 'infectious_disease_specialist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '100mg', unitPrice: 280, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Chloroquine', severity: 'moderate', mechanism: 'Antagonistic antiviral effect', clinicalEffect: 'Reduced remdesivir efficacy', clinicalEffectAr: 'انخفاض فعالية ريمديسيفير', management: 'Avoid combination', managementAr: 'تجنب الجمع' }],
    contraindications: ['eGFR <30ml/min (IV formulation contains SBECD)', 'Hypersensitivity'],
    contraindicationsAr: ['معدل الترشيح الكبيبي أقل من 30 (التركيبة الوريدية تحتوي SBECD)', 'فرط الحساسية'],
    monitoringRequired: ['Liver function tests', 'Renal function', 'Infusion reactions'], storageConditions: 'Store below 30°C, use within 24h of reconstitution'
  },
  {
    id: 'FRM-0271', genericName: 'Ribavirin', genericNameAr: 'ريبافيرين',
    brandNames: ['Copegus', 'Rebetol'], sfda_registration: 'SFDA-2024-ANT-271',
    atcCode: 'J05AB04', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'restricted',
    restrictionCriteria: 'Hepatitis C combination therapy', restrictionCriteriaAr: 'العلاج المركب لالتهاب الكبد سي', approverRole: 'hepatologist',
    route: ['oral'], forms: [{ form: 'capsule', strength: '200mg', unitPrice: 8, inStock: true }, { form: 'tablet', strength: '400mg', unitPrice: 14, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Hemolytic anemia. Teratogenic — contraindicated in pregnancy and partners of pregnant women.',
    blackBoxWarningAr: 'فقر الدم الانحلالي. ماسخ — ممنوع في الحمل وشركاء الحوامل.',
    interactions: [{ interactsWith: 'Didanosine', severity: 'major', mechanism: 'Mitochondrial toxicity', clinicalEffect: 'Fatal hepatic failure and pancreatitis', clinicalEffectAr: 'فشل كبدي مميت والتهاب بنكرياس', management: 'Contraindicated', managementAr: 'ممنوع' }],
    contraindications: ['Pregnancy', 'Male partners of pregnant women', 'Hemoglobinopathies', 'Severe cardiac disease'],
    contraindicationsAr: ['الحمل', 'الشركاء الذكور للحوامل', 'اعتلالات الهيموغلوبين', 'أمراض قلبية شديدة'],
    monitoringRequired: ['CBC every 2 weeks initially', 'Pregnancy test monthly', 'Cardiac assessment'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0272', genericName: 'Lamivudine', genericNameAr: 'لاميفودين',
    brandNames: ['Epivir', 'Zeffix'], sfda_registration: 'SFDA-2024-ANT-272',
    atcCode: 'J05AF05', atcCategory: 'J05A', therapeuticClass: 'Antivirals',
    therapeuticClassAr: 'مضادات الفيروسات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '150mg', unitPrice: 6, inStock: true }, { form: 'tablet', strength: '100mg', unitPrice: 12, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Lamotrigine'],
    interactions: [{ interactsWith: 'Trimethoprim', severity: 'moderate', mechanism: 'Reduced renal clearance of lamivudine', clinicalEffect: 'Increased lamivudine levels', clinicalEffectAr: 'زيادة مستويات لاميفودين', management: 'No adjustment unless renal impairment', managementAr: 'لا تعديل إلا في القصور الكلوي' }],
    contraindications: ['Hypersensitivity to lamivudine'],
    contraindicationsAr: ['فرط الحساسية للاميفودين'],
    monitoringRequired: ['HBV DNA or HIV RNA', 'Liver function tests', 'CBC'], storageConditions: 'Store below 30°C'
  },
];

export const ANTI_TB: FormularyDrug[] = [
  {
    id: 'FRM-0273', genericName: 'Isoniazid', genericNameAr: 'أيزونيازيد',
    brandNames: ['INH'], sfda_registration: 'SFDA-2024-ANT-273',
    atcCode: 'J04AC01', atcCategory: 'J04A', therapeuticClass: 'Anti-tuberculosis',
    therapeuticClassAr: 'مضادات السل', formularyStatus: 'formulary',
    route: ['oral', 'intramuscular'], forms: [{ form: 'tablet', strength: '300mg', unitPrice: 1.5, inStock: true }, { form: 'tablet', strength: '100mg', unitPrice: 1, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Severe and sometimes fatal hepatitis may occur.',
    blackBoxWarningAr: 'قد يحدث التهاب كبد شديد ومميت أحياناً.',
    interactions: [{ interactsWith: 'Carbamazepine', severity: 'major', mechanism: 'Inhibition of carbamazepine metabolism', clinicalEffect: 'Carbamazepine toxicity', clinicalEffectAr: 'سمية كاربامازيبين', management: 'Monitor carbamazepine levels', managementAr: 'مراقبة مستويات كاربامازيبين' }],
    contraindications: ['Acute liver disease', 'Previous isoniazid hepatotoxicity'],
    contraindicationsAr: ['مرض كبدي حاد', 'سمية كبدية سابقة من أيزونيازيد'],
    monitoringRequired: ['Liver function tests monthly', 'Peripheral neuropathy signs', 'Give pyridoxine supplementation'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0274', genericName: 'Rifampicin', genericNameAr: 'ريفامبيسين',
    brandNames: ['Rifadin', 'Rimactane'], sfda_registration: 'SFDA-2024-ANT-274',
    atcCode: 'J04AB02', atcCategory: 'J04A', therapeuticClass: 'Anti-tuberculosis',
    therapeuticClassAr: 'مضادات السل', formularyStatus: 'formulary',
    route: ['oral', 'intravenous'], forms: [{ form: 'capsule', strength: '300mg', unitPrice: 3, inStock: true }, { form: 'capsule', strength: '150mg', unitPrice: 2, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Rifabutin', 'Rifapentine'],
    interactions: [{ interactsWith: 'Warfarin', severity: 'major', mechanism: 'CYP3A4/2C9 induction', clinicalEffect: 'Dramatically reduced warfarin effect', clinicalEffectAr: 'انخفاض كبير في تأثير الوارفارين', management: 'Increase warfarin dose, monitor INR frequently', managementAr: 'زيادة جرعة الوارفارين ومراقبة INR بشكل متكرر' }],
    contraindications: ['Concurrent protease inhibitors', 'Jaundice', 'Hypersensitivity'],
    contraindicationsAr: ['الاستخدام المتزامن مع مثبطات البروتياز', 'اليرقان', 'فرط الحساسية'],
    monitoringRequired: ['Liver function tests', 'CBC', 'Renal function', 'Warn patient of orange body fluids'], storageConditions: 'Store below 25°C, protect from moisture'
  },
  {
    id: 'FRM-0275', genericName: 'Pyrazinamide', genericNameAr: 'بيرازيناميد',
    brandNames: ['Pyrazinamide'], sfda_registration: 'SFDA-2024-ANT-275',
    atcCode: 'J04AK01', atcCategory: 'J04A', therapeuticClass: 'Anti-tuberculosis',
    therapeuticClassAr: 'مضادات السل', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '500mg', unitPrice: 1.5, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Allopurinol', severity: 'moderate', mechanism: 'Pyrazinamide inhibits uric acid excretion', clinicalEffect: 'Hyperuricemia and gout flares', clinicalEffectAr: 'فرط حمض اليوريك ونوبات النقرس', management: 'Monitor uric acid levels', managementAr: 'مراقبة مستويات حمض اليوريك' }],
    contraindications: ['Severe hepatic impairment', 'Acute gout'],
    contraindicationsAr: ['قصور كبدي شديد', 'نقرس حاد'],
    monitoringRequired: ['Liver function tests', 'Serum uric acid', 'Joint symptoms'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0276', genericName: 'Ethambutol', genericNameAr: 'إيثامبوتول',
    brandNames: ['Myambutol'], sfda_registration: 'SFDA-2024-ANT-276',
    atcCode: 'J04AK02', atcCategory: 'J04A', therapeuticClass: 'Anti-tuberculosis',
    therapeuticClassAr: 'مضادات السل', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '400mg', unitPrice: 2, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Optic neuritis', 'Unable to report visual changes (young children)'],
    contraindicationsAr: ['التهاب العصب البصري', 'عدم القدرة على الإبلاغ عن تغيرات الرؤية'],
    monitoringRequired: ['Visual acuity and color vision monthly', 'Renal function'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0277', genericName: 'Streptomycin', genericNameAr: 'ستربتومايسين',
    brandNames: ['Streptomycin Sulfate'], sfda_registration: 'SFDA-2024-ANT-277',
    atcCode: 'J04AM01', atcCategory: 'J04A', therapeuticClass: 'Anti-tuberculosis',
    therapeuticClassAr: 'مضادات السل', formularyStatus: 'formulary',
    route: ['intramuscular'], forms: [{ form: 'injection', strength: '1g', unitPrice: 8, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Gentamicin'],
    interactions: [{ interactsWith: 'Furosemide', severity: 'major', mechanism: 'Additive ototoxicity', clinicalEffect: 'Irreversible hearing loss', clinicalEffectAr: 'فقدان سمع لا رجعي', management: 'Avoid combination if possible', managementAr: 'تجنب الجمع إن أمكن' }],
    contraindications: ['Myasthenia gravis', 'Pregnancy'],
    contraindicationsAr: ['الوهن العضلي الوبيل', 'الحمل'],
    monitoringRequired: ['Audiometry', 'Renal function', 'Vestibular function'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0278', genericName: 'Bedaquiline', genericNameAr: 'بيداكيلين',
    brandNames: ['Sirturo'], sfda_registration: 'SFDA-2024-ANT-278',
    atcCode: 'J04AK05', atcCategory: 'J04A', therapeuticClass: 'Anti-tuberculosis',
    therapeuticClassAr: 'مضادات السل', formularyStatus: 'restricted',
    restrictionCriteria: 'MDR-TB only, specialist approval required', restrictionCriteriaAr: 'السل المقاوم للأدوية المتعددة فقط، يتطلب موافقة أخصائي', approverRole: 'pulmonologist',
    route: ['oral'], forms: [{ form: 'tablet', strength: '100mg', unitPrice: 180, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Increased mortality observed in clinical trials. QT prolongation risk.',
    blackBoxWarningAr: 'لوحظ زيادة في الوفيات في التجارب السريرية. خطر إطالة QT.',
    interactions: [{ interactsWith: 'Lopinavir/Ritonavir', severity: 'major', mechanism: 'CYP3A4 inhibition increases bedaquiline levels', clinicalEffect: 'Increased QT prolongation risk', clinicalEffectAr: 'زيادة خطر إطالة QT', management: 'Avoid combination if possible', managementAr: 'تجنب الجمع إن أمكن' }],
    contraindications: ['QTcF >500ms', 'Concurrent QT-prolonging drugs'],
    contraindicationsAr: ['إطالة QTcF أكثر من 500 مللي ثانية', 'الأدوية المطيلة لـ QT المتزامنة'],
    monitoringRequired: ['ECG monthly', 'Liver function tests', 'Sputum cultures'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0279', genericName: 'Linezolid', genericNameAr: 'لينيزوليد',
    brandNames: ['Zyvox'], sfda_registration: 'SFDA-2024-ANT-279',
    atcCode: 'J01XX08', atcCategory: 'J01X', therapeuticClass: 'Anti-tuberculosis',
    therapeuticClassAr: 'مضادات السل', formularyStatus: 'restricted',
    restrictionCriteria: 'MDR/XDR-TB or resistant gram-positive infections', restrictionCriteriaAr: 'السل المقاوم أو العدوى إيجابية الغرام المقاومة', approverRole: 'infectious_disease_specialist',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '600mg', unitPrice: 85, inStock: true }, { form: 'injection', strength: '600mg/300ml', unitPrice: 120, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Serotonergic drugs', severity: 'major', mechanism: 'MAO inhibition causing serotonin syndrome', clinicalEffect: 'Serotonin syndrome', clinicalEffectAr: 'متلازمة السيروتونين', management: 'Avoid SSRIs/SNRIs during treatment', managementAr: 'تجنب مثبطات استرداد السيروتونين أثناء العلاج' }],
    contraindications: ['Concurrent MAOIs', 'Uncontrolled hypertension', 'Pheochromocytoma'],
    contraindicationsAr: ['مثبطات MAO المتزامنة', 'ارتفاع ضغط الدم غير المنضبط', 'ورم القواتم'],
    monitoringRequired: ['CBC weekly', 'Visual function', 'Peripheral neuropathy', 'Lactic acidosis'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0280', genericName: 'Delamanid', genericNameAr: 'ديلامانيد',
    brandNames: ['Deltyba'], sfda_registration: 'SFDA-2024-ANT-280',
    atcCode: 'J04AK06', atcCategory: 'J04A', therapeuticClass: 'Anti-tuberculosis',
    therapeuticClassAr: 'مضادات السل', formularyStatus: 'restricted',
    restrictionCriteria: 'MDR-TB when other regimens cannot be composed', restrictionCriteriaAr: 'السل المقاوم للأدوية المتعددة عند تعذر تكوين نظم أخرى', approverRole: 'pulmonologist',
    route: ['oral'], forms: [{ form: 'tablet', strength: '50mg', unitPrice: 160, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Bedaquiline', severity: 'major', mechanism: 'Additive QT prolongation', clinicalEffect: 'Risk of torsades de pointes', clinicalEffectAr: 'خطر تسارع القلب البطيني', management: 'Use with extreme caution, frequent ECG', managementAr: 'استخدام بحذر شديد مع تخطيط قلب متكرر' }],
    contraindications: ['Serum albumin <2.8g/dL', 'QTcF >500ms'],
    contraindicationsAr: ['ألبومين المصل أقل من 2.8غ/دل', 'إطالة QTcF أكثر من 500'],
    monitoringRequired: ['ECG monthly', 'Serum albumin', 'Liver function tests'], storageConditions: 'Store below 30°C'
  },
];

export const ANTIPARASITICS: FormularyDrug[] = [
  {
    id: 'FRM-0281', genericName: 'Albendazole', genericNameAr: 'ألبيندازول',
    brandNames: ['Zentel', 'Alzental'], sfda_registration: 'SFDA-2024-ANT-281',
    atcCode: 'P02CA03', atcCategory: 'P02C', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '400mg', unitPrice: 4, inStock: true }, { form: 'oral suspension', strength: '200mg/5ml', unitPrice: 10, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Mebendazole'],
    interactions: [{ interactsWith: 'Dexamethasone', severity: 'moderate', mechanism: 'Increased albendazole metabolite levels', clinicalEffect: 'Enhanced efficacy but also toxicity', clinicalEffectAr: 'زيادة الفعالية ولكن أيضاً السمية', management: 'Monitor for side effects', managementAr: 'مراقبة الآثار الجانبية' }],
    contraindications: ['Pregnancy first trimester', 'Hypersensitivity to benzimidazoles'],
    contraindicationsAr: ['الثلث الأول من الحمل', 'فرط الحساسية للبنزيميدازولات'],
    monitoringRequired: ['CBC every 2 weeks for prolonged courses', 'Liver function tests'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0282', genericName: 'Mebendazole', genericNameAr: 'ميبيندازول',
    brandNames: ['Vermox'], sfda_registration: 'SFDA-2024-ANT-282',
    atcCode: 'P02CA01', atcCategory: 'P02C', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '100mg', unitPrice: 3, inStock: true }, { form: 'oral suspension', strength: '100mg/5ml', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Albendazole'],
    interactions: [],
    contraindications: ['Hypersensitivity to mebendazole'],
    contraindicationsAr: ['فرط الحساسية للميبيندازول'],
    monitoringRequired: ['Stool examination post-treatment', 'CBC for prolonged courses'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0283', genericName: 'Ivermectin', genericNameAr: 'إيفرمكتين',
    brandNames: ['Stromectol', 'Iverzine'], sfda_registration: 'SFDA-2024-ANT-283',
    atcCode: 'P02CF01', atcCategory: 'P02C', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '6mg', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Possible INR increase', clinicalEffect: 'Increased bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف', management: 'Monitor INR closely', managementAr: 'مراقبة INR بدقة' }],
    contraindications: ['Children <15kg', 'Loa loa co-infection (risk of encephalopathy)'],
    contraindicationsAr: ['الأطفال أقل من 15 كغ', 'عدوى لوا لوا المصاحبة (خطر اعتلال دماغي)'],
    monitoringRequired: ['Clinical response', 'Mazzotti reaction in onchocerciasis'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0284', genericName: 'Praziquantel', genericNameAr: 'برازيكوانتيل',
    brandNames: ['Biltricide'], sfda_registration: 'SFDA-2024-ANT-284',
    atcCode: 'P02BA01', atcCategory: 'P02B', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '600mg', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Rifampicin', severity: 'major', mechanism: 'CYP450 induction reduces praziquantel levels', clinicalEffect: 'Treatment failure', clinicalEffectAr: 'فشل العلاج', management: 'Avoid combination or increase dose', managementAr: 'تجنب الجمع أو زيادة الجرعة' }],
    contraindications: ['Ocular cysticercosis', 'Concurrent rifampicin'],
    contraindicationsAr: ['داء الكيسات المذنبة العيني', 'الاستخدام المتزامن مع ريفامبيسين'],
    monitoringRequired: ['Clinical response', 'Stool examination'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0285', genericName: 'Hydroxychloroquine', genericNameAr: 'هيدروكسي كلوروكين',
    brandNames: ['Plaquenil'], sfda_registration: 'SFDA-2024-ANT-285',
    atcCode: 'P01BA02', atcCategory: 'P01B', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '200mg', unitPrice: 3, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Chloroquine'],
    interactions: [{ interactsWith: 'Digoxin', severity: 'moderate', mechanism: 'Increased digoxin levels', clinicalEffect: 'Digoxin toxicity', clinicalEffectAr: 'سمية الديجوكسين', management: 'Monitor digoxin levels', managementAr: 'مراقبة مستويات الديجوكسين' }],
    contraindications: ['Retinal disease', 'Hypersensitivity to 4-aminoquinolines', 'G6PD deficiency with risk of hemolysis'],
    contraindicationsAr: ['مرض الشبكية', 'فرط الحساسية لمركبات 4-أمينوكينولين', 'نقص G6PD مع خطر انحلال الدم'],
    monitoringRequired: ['Ophthalmologic exam annually after 5 years', 'CBC', 'Retinal screening'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0286', genericName: 'Artesunate', genericNameAr: 'أرتيسونات',
    brandNames: ['Artesunate IV'], sfda_registration: 'SFDA-2024-ANT-286',
    atcCode: 'P01BE03', atcCategory: 'P01B', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['intravenous', 'intramuscular'], forms: [{ form: 'injection', strength: '60mg', unitPrice: 18, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Artemether'],
    interactions: [],
    contraindications: ['Hypersensitivity to artemisinins', 'First trimester pregnancy (unless life-threatening malaria)'],
    contraindicationsAr: ['فرط الحساسية للأرتيميسينين', 'الثلث الأول من الحمل (إلا في الملاريا المهددة للحياة)'],
    monitoringRequired: ['Parasitemia levels daily', 'Hemoglobin (delayed hemolysis days 7-28)', 'G6PD status'], storageConditions: 'Store below 30°C, protect from light'
  },
  {
    id: 'FRM-0287', genericName: 'Quinine Sulfate', genericNameAr: 'كينين سلفات',
    brandNames: ['Qualaquin'], sfda_registration: 'SFDA-2024-ANT-287',
    atcCode: 'P01BC01', atcCategory: 'P01B', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '300mg', unitPrice: 5, inStock: true }, { form: 'injection', strength: '300mg/ml', unitPrice: 12, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Quinidine'],
    interactions: [{ interactsWith: 'Digoxin', severity: 'major', mechanism: 'Increased digoxin levels', clinicalEffect: 'Digoxin toxicity', clinicalEffectAr: 'سمية الديجوكسين', management: 'Reduce digoxin dose by 50%', managementAr: 'تقليل جرعة الديجوكسين بنسبة 50%' }],
    contraindications: ['Myasthenia gravis', 'Optic neuritis', 'G6PD deficiency', 'Blackwater fever history'],
    contraindicationsAr: ['الوهن العضلي الوبيل', 'التهاب العصب البصري', 'نقص G6PD', 'تاريخ حمى الماء الأسود'],
    monitoringRequired: ['Blood glucose (hypoglycemia risk)', 'ECG monitoring', 'Hearing assessment'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0288', genericName: 'Nitazoxanide', genericNameAr: 'نيتازوكسانيد',
    brandNames: ['Alinia', 'Nanazoxid'], sfda_registration: 'SFDA-2024-ANT-288',
    atcCode: 'P01AX11', atcCategory: 'P01A', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '500mg', unitPrice: 6, inStock: true }, { form: 'oral suspension', strength: '100mg/5ml', unitPrice: 22, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'High protein binding displacement', clinicalEffect: 'Potential INR increase', clinicalEffectAr: 'احتمال زيادة INR', management: 'Monitor INR', managementAr: 'مراقبة INR' }],
    contraindications: ['Hypersensitivity to nitazoxanide'],
    contraindicationsAr: ['فرط الحساسية للنيتازوكسانيد'],
    monitoringRequired: ['Stool examination', 'Clinical response'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0289', genericName: 'Atovaquone/Proguanil', genericNameAr: 'أتوفاكون/بروغوانيل',
    brandNames: ['Malarone'], sfda_registration: 'SFDA-2024-ANT-289',
    atcCode: 'P01BB51', atcCategory: 'P01B', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '250mg/100mg', unitPrice: 15, inStock: true }, { form: 'tablet', strength: '62.5mg/25mg', unitPrice: 10, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Metoclopramide', severity: 'moderate', mechanism: 'Reduced atovaquone absorption', clinicalEffect: 'Decreased efficacy', clinicalEffectAr: 'انخفاض الفعالية', management: 'Use alternative antiemetic', managementAr: 'استخدام مضاد غثيان بديل' }],
    contraindications: ['Severe renal impairment (CrCl <30ml/min)', 'Hypersensitivity'],
    contraindicationsAr: ['قصور كلوي شديد', 'فرط الحساسية'],
    monitoringRequired: ['Parasitemia in treatment', 'Liver function tests'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0290', genericName: 'Primaquine', genericNameAr: 'بريماكين',
    brandNames: ['Primaquine Phosphate'], sfda_registration: 'SFDA-2024-ANT-290',
    atcCode: 'P01BA03', atcCategory: 'P01B', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'conditional',
    restrictionCriteria: 'Requires G6PD testing before use', restrictionCriteriaAr: 'يتطلب فحص G6PD قبل الاستخدام', approverRole: 'infectious_disease_specialist',
    route: ['oral'], forms: [{ form: 'tablet', strength: '15mg', unitPrice: 4, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Quinacrine', severity: 'major', mechanism: 'Increased primaquine toxicity', clinicalEffect: 'Severe hemolytic anemia', clinicalEffectAr: 'فقر دم انحلالي شديد', management: 'Do not use concurrently', managementAr: 'لا تستخدم بالتزامن' }],
    contraindications: ['G6PD deficiency', 'Pregnancy', 'Concurrent bone marrow suppressants'],
    contraindicationsAr: ['نقص G6PD', 'الحمل', 'مثبطات نخاع العظم المتزامنة'],
    monitoringRequired: ['G6PD status before treatment', 'CBC weekly', 'Hemoglobin', 'Methemoglobin if symptomatic'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0291', genericName: 'Mefloquine', genericNameAr: 'ميفلوكين',
    brandNames: ['Lariam'], sfda_registration: 'SFDA-2024-ANT-291',
    atcCode: 'P01BC02', atcCategory: 'P01B', therapeuticClass: 'Antiparasitics',
    therapeuticClassAr: 'مضادات الطفيليات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '250mg', unitPrice: 14, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Neuropsychiatric adverse reactions (anxiety, depression, psychosis) may persist after discontinuation.',
    blackBoxWarningAr: 'قد تستمر التفاعلات العصبية النفسية (القلق والاكتئاب والذهان) بعد التوقف.',
    interactions: [{ interactsWith: 'Halofantrine', severity: 'major', mechanism: 'QT prolongation', clinicalEffect: 'Fatal cardiac arrhythmias', clinicalEffectAr: 'اضطرابات قلبية مميتة', management: 'Contraindicated within 15 weeks', managementAr: 'ممنوع خلال 15 أسبوعاً' }],
    contraindications: ['Active depression', 'Anxiety disorder', 'Psychosis', 'Seizure disorder', 'Cardiac conduction abnormalities'],
    contraindicationsAr: ['اكتئاب نشط', 'اضطراب القلق', 'الذهان', 'اضطراب النوبات', 'اضطرابات التوصيل القلبي'],
    monitoringRequired: ['Neuropsychiatric symptoms', 'Liver function tests', 'Eye exam for prolonged use'], storageConditions: 'Store below 30°C'
  },
];

