/**
 * Saudi MOH Drug Formulary — Part 16: Corticosteroids, Antihistamines, Vitamins, Muscle Relaxants, Laxatives
 * IDs: FRM-0900 through FRM-0939
 */
import type { FormularyDrug } from './formularyTypes';

export const CORTICOSTEROIDS: FormularyDrug[] = [
  {
    id: 'FRM-0900', genericName: 'Prednisolone', genericNameAr: 'بريدنيزولون',
    brandNames: ['Predone', 'Prelone'], sfda_registration: 'SFDA-2024-COR-900',
    atcCode: 'H02AB06', atcCategory: 'H02A', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '5mg', unitPrice: 0.5, inStock: true }, { form: 'oral solution', strength: '15mg/5ml', unitPrice: 18, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Prednisone'],
    interactions: [{ interactsWith: 'NSAIDs', severity: 'moderate', mechanism: 'Additive GI toxicity', clinicalEffect: 'Increased GI bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف المعدي المعوي', management: 'Add GI protection', managementAr: 'إضافة حماية للمعدة' }],
    contraindications: ['Systemic fungal infections', 'Live vaccines during high-dose therapy'],
    contraindicationsAr: ['العدوى الفطرية الجهازية', 'اللقاحات الحية أثناء الجرعات العالية'],
    monitoringRequired: ['Blood glucose', 'Blood pressure', 'Bone density for prolonged use'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0901', genericName: 'Dexamethasone', genericNameAr: 'ديكساميثازون',
    brandNames: ['Decadron', 'Dexacort'], sfda_registration: 'SFDA-2024-COR-901',
    atcCode: 'H02AB02', atcCategory: 'H02A', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [{ form: 'tablet', strength: '4mg', unitPrice: 2, inStock: true }, { form: 'injection', strength: '4mg/ml', unitPrice: 5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Desoximetasone'],
    interactions: [{ interactsWith: 'Phenytoin', severity: 'moderate', mechanism: 'CYP3A4 induction reduces dexamethasone', clinicalEffect: 'Reduced corticosteroid effect', clinicalEffectAr: 'انخفاض تأثير الكورتيكوستيرويد', management: 'May need dose increase', managementAr: 'قد يحتاج زيادة الجرعة' }],
    contraindications: ['Cerebral malaria', 'Systemic fungal infections'],
    contraindicationsAr: ['الملاريا الدماغية', 'العدوى الفطرية الجهازية'],
    monitoringRequired: ['Blood glucose', 'Adrenal suppression signs', 'Electrolytes'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0902', genericName: 'Hydrocortisone', genericNameAr: 'هيدروكورتيزون',
    brandNames: ['Solu-Cortef', 'Cortef'], sfda_registration: 'SFDA-2024-COR-902',
    atcCode: 'H02AB09', atcCategory: 'H02A', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'topical'], forms: [{ form: 'tablet', strength: '10mg', unitPrice: 1.5, inStock: true }, { form: 'injection', strength: '100mg', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Hydroxychloroquine'],
    interactions: [{ interactsWith: 'Ketoconazole', severity: 'moderate', mechanism: 'CYP3A4 inhibition increases hydrocortisone', clinicalEffect: 'Increased steroid effects', clinicalEffectAr: 'زيادة تأثيرات الستيرويد', management: 'Reduce hydrocortisone dose', managementAr: 'تقليل جرعة الهيدروكورتيزون' }],
    contraindications: ['Systemic fungal infections'],
    contraindicationsAr: ['العدوى الفطرية الجهازية'],
    monitoringRequired: ['Blood glucose', 'Cortisol levels in replacement therapy', 'Blood pressure'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0903', genericName: 'Methylprednisolone', genericNameAr: 'ميثيل بريدنيزولون',
    brandNames: ['Solu-Medrol', 'Medrol'], sfda_registration: 'SFDA-2024-COR-903',
    atcCode: 'H02AB04', atcCategory: 'H02A', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [{ form: 'tablet', strength: '4mg', unitPrice: 2, inStock: true }, { form: 'injection', strength: '500mg', unitPrice: 45, inStock: true }, { form: 'injection', strength: '1000mg', unitPrice: 80, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Medroxyprogesterone'],
    interactions: [{ interactsWith: 'Cyclosporine', severity: 'moderate', mechanism: 'Mutual metabolism inhibition', clinicalEffect: 'Increased levels of both drugs', clinicalEffectAr: 'زيادة مستويات كلا الدوائين', management: 'Monitor drug levels', managementAr: 'مراقبة مستويات الأدوية' }],
    contraindications: ['Idiopathic thrombocytopenic purpura (IM route)', 'Systemic fungal infections'],
    contraindicationsAr: ['فرفرية نقص الصفيحات (الحقن العضلي)', 'العدوى الفطرية الجهازية'],
    monitoringRequired: ['Blood glucose', 'Electrolytes', 'Blood pressure', 'Infection signs'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0904', genericName: 'Budesonide', genericNameAr: 'بوديسونايد',
    brandNames: ['Pulmicort', 'Entocort'], sfda_registration: 'SFDA-2024-COR-904',
    atcCode: 'R03BA02', atcCategory: 'R03B', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['inhalation', 'oral'], forms: [{ form: 'nebulizer suspension', strength: '0.5mg/2ml', unitPrice: 8, inStock: true }, { form: 'capsule', strength: '3mg', unitPrice: 15, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Beclomethasone'],
    interactions: [{ interactsWith: 'Ketoconazole', severity: 'moderate', mechanism: 'CYP3A4 inhibition', clinicalEffect: 'Increased budesonide exposure', clinicalEffectAr: 'زيادة التعرض للبوديسونايد', management: 'Avoid CYP3A4 inhibitors', managementAr: 'تجنب مثبطات CYP3A4' }],
    contraindications: ['Status asthmaticus (not for acute relief)', 'Active pulmonary TB'],
    contraindicationsAr: ['حالة الربو (ليس للإغاثة الحادة)', 'السل الرئوي النشط'],
    monitoringRequired: ['Oral candidiasis signs', 'Growth in children', 'Adrenal function'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0905', genericName: 'Betamethasone', genericNameAr: 'بيتاميثازون',
    brandNames: ['Celestene', 'Celestone'], sfda_registration: 'SFDA-2024-COR-905',
    atcCode: 'H02AB01', atcCategory: 'H02A', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['oral', 'intramuscular', 'topical'], forms: [{ form: 'injection', strength: '4mg/ml', unitPrice: 12, inStock: true }, { form: 'cream', strength: '0.1%', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Beclomethasone'],
    interactions: [{ interactsWith: 'Aminoglutethimide', severity: 'moderate', mechanism: 'Accelerated dexamethasone metabolism', clinicalEffect: 'Reduced corticosteroid effect', clinicalEffectAr: 'انخفاض تأثير الكورتيكوستيرويد', management: 'Increase dose if needed', managementAr: 'زيادة الجرعة إذا لزم الأمر' }],
    contraindications: ['Systemic fungal infections'],
    contraindicationsAr: ['العدوى الفطرية الجهازية'],
    monitoringRequired: ['Blood glucose', 'Adrenal function'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0906', genericName: 'Fludrocortisone', genericNameAr: 'فلودروكورتيزون',
    brandNames: ['Florinef'], sfda_registration: 'SFDA-2024-COR-906',
    atcCode: 'H02AA02', atcCategory: 'H02A', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '0.1mg', unitPrice: 5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Fluticasone'],
    interactions: [{ interactsWith: 'Potassium-depleting diuretics', severity: 'moderate', mechanism: 'Additive hypokalemia', clinicalEffect: 'Severe hypokalemia', clinicalEffectAr: 'نقص بوتاسيوم شديد', management: 'Monitor potassium', managementAr: 'مراقبة البوتاسيوم' }],
    contraindications: ['Systemic fungal infections', 'Hypertension'],
    contraindicationsAr: ['العدوى الفطرية الجهازية', 'ارتفاع ضغط الدم'],
    monitoringRequired: ['Blood pressure', 'Serum potassium', 'Weight', 'Edema signs'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0907', genericName: 'Prednisone', genericNameAr: 'بريدنيزون',
    brandNames: ['Deltasone'], sfda_registration: 'SFDA-2024-COR-907',
    atcCode: 'H02AB07', atcCategory: 'H02A', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '5mg', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '20mg', unitPrice: 1.5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Prednisolone', 'Prilosec'],
    interactions: [{ interactsWith: 'Rifampicin', severity: 'moderate', mechanism: 'CYP3A4 induction', clinicalEffect: 'Reduced prednisone efficacy', clinicalEffectAr: 'انخفاض فعالية بريدنيزون', management: 'May need to double dose', managementAr: 'قد يحتاج مضاعفة الجرعة' }],
    contraindications: ['Systemic fungal infections', 'Live vaccines with immunosuppressive doses'],
    contraindicationsAr: ['العدوى الفطرية الجهازية', 'اللقاحات الحية مع الجرعات المثبطة للمناعة'],
    monitoringRequired: ['Blood glucose', 'Blood pressure', 'Bone density', 'Ophthalmologic exam'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0908', genericName: 'Beclomethasone', genericNameAr: 'بيكلوميثازون',
    brandNames: ['Beclovent', 'QVAR'], sfda_registration: 'SFDA-2024-COR-908',
    atcCode: 'R03BA01', atcCategory: 'R03B', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['inhalation', 'nasal'], forms: [{ form: 'inhaler', strength: '250mcg/puff', unitPrice: 35, inStock: true }, { form: 'nasal spray', strength: '50mcg/spray', unitPrice: 22, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Betamethasone', 'Budesonide'],
    interactions: [],
    contraindications: ['Status asthmaticus', 'Active pulmonary TB'],
    contraindicationsAr: ['حالة الربو الحادة', 'السل الرئوي النشط'],
    monitoringRequired: ['Oral candidiasis', 'Growth in children', 'Adrenal function with high doses'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0909', genericName: 'Triamcinolone', genericNameAr: 'تريامسينولون',
    brandNames: ['Kenalog', 'Kenacort'], sfda_registration: 'SFDA-2024-COR-909',
    atcCode: 'H02AB08', atcCategory: 'H02A', therapeuticClass: 'Corticosteroids',
    therapeuticClassAr: 'الكورتيكوستيرويدات', formularyStatus: 'formulary',
    route: ['intramuscular', 'intra-articular', 'topical'], forms: [{ form: 'injection', strength: '40mg/ml', unitPrice: 18, inStock: true }, { form: 'cream', strength: '0.1%', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Local or systemic infection at injection site', 'Systemic fungal infections'],
    contraindicationsAr: ['عدوى موضعية أو جهازية في موقع الحقن', 'العدوى الفطرية الجهازية'],
    monitoringRequired: ['Joint symptoms post-injection', 'Blood glucose', 'Adrenal function'], storageConditions: 'Store below 25°C, do not freeze'
  },
];

export const ANTIHISTAMINES: FormularyDrug[] = [
  {
    id: 'FRM-0910', genericName: 'Cetirizine', genericNameAr: 'سيتيريزين',
    brandNames: ['Zyrtec', 'Alerid'], sfda_registration: 'SFDA-2024-AHI-910',
    atcCode: 'R06AE07', atcCategory: 'R06A', therapeuticClass: 'Antihistamines',
    therapeuticClassAr: 'مضادات الهيستامين', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '10mg', unitPrice: 1.5, inStock: true }, { form: 'syrup', strength: '5mg/5ml', unitPrice: 10, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Sertraline'],
    interactions: [],
    contraindications: ['Hypersensitivity to cetirizine or hydroxyzine', 'Severe renal impairment without dose adjustment'],
    contraindicationsAr: ['فرط الحساسية للسيتيريزين أو الهيدروكسيزين', 'قصور كلوي شديد بدون تعديل الجرعة'],
    monitoringRequired: ['Sedation level', 'Renal function in elderly'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0911', genericName: 'Loratadine', genericNameAr: 'لوراتادين',
    brandNames: ['Claritin', 'Lorfast'], sfda_registration: 'SFDA-2024-AHI-911',
    atcCode: 'R06AX13', atcCategory: 'R06A', therapeuticClass: 'Antihistamines',
    therapeuticClassAr: 'مضادات الهيستامين', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '10mg', unitPrice: 1.5, inStock: true }, { form: 'syrup', strength: '5mg/5ml', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Lovastatin'],
    interactions: [],
    contraindications: ['Hypersensitivity to loratadine'],
    contraindicationsAr: ['فرط الحساسية للوراتادين'],
    monitoringRequired: ['Clinical response'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0912', genericName: 'Fexofenadine', genericNameAr: 'فيكسوفينادين',
    brandNames: ['Telfast', 'Allegra'], sfda_registration: 'SFDA-2024-AHI-912',
    atcCode: 'R06AX26', atcCategory: 'R06A', therapeuticClass: 'Antihistamines',
    therapeuticClassAr: 'مضادات الهيستامين', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '120mg', unitPrice: 2, inStock: true }, { form: 'tablet', strength: '180mg', unitPrice: 3, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Hypersensitivity to fexofenadine'],
    contraindicationsAr: ['فرط الحساسية لفيكسوفينادين'],
    monitoringRequired: ['Clinical response'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0913', genericName: 'Diphenhydramine', genericNameAr: 'ديفينهيدرامين',
    brandNames: ['Benadryl'], sfda_registration: 'SFDA-2024-AHI-913',
    atcCode: 'R06AA02', atcCategory: 'R06A', therapeuticClass: 'Antihistamines',
    therapeuticClassAr: 'مضادات الهيستامين', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [{ form: 'capsule', strength: '25mg', unitPrice: 1, inStock: true }, { form: 'injection', strength: '50mg/ml', unitPrice: 5, inStock: true }, { form: 'syrup', strength: '12.5mg/5ml', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Dimenhydrinate'],
    interactions: [{ interactsWith: 'MAO inhibitors', severity: 'major', mechanism: 'Anticholinergic potentiation', clinicalEffect: 'Hypotension and CNS depression', clinicalEffectAr: 'انخفاض ضغط الدم واكتئاب الجهاز العصبي', management: 'Avoid combination', managementAr: 'تجنب الجمع' }],
    contraindications: ['Neonates', 'Nursing mothers', 'Concurrent MAO inhibitors'],
    contraindicationsAr: ['حديثي الولادة', 'الأمهات المرضعات', 'مثبطات MAO المتزامنة'],
    monitoringRequired: ['Sedation level', 'Anticholinergic effects'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0914', genericName: 'Chlorphenamine', genericNameAr: 'كلورفينامين',
    brandNames: ['Chlor-Trimeton', 'Allerfin'], sfda_registration: 'SFDA-2024-AHI-914',
    atcCode: 'R06AB04', atcCategory: 'R06A', therapeuticClass: 'Antihistamines',
    therapeuticClassAr: 'مضادات الهيستامين', formularyStatus: 'formulary',
    route: ['oral', 'intramuscular', 'intravenous'], forms: [{ form: 'tablet', strength: '4mg', unitPrice: 0.5, inStock: true }, { form: 'injection', strength: '10mg/ml', unitPrice: 3, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Chlorpromazine'],
    interactions: [],
    contraindications: ['Premature and newborn infants', 'Concurrent MAO inhibitors'],
    contraindicationsAr: ['الخدج وحديثي الولادة', 'مثبطات MAO المتزامنة'],
    monitoringRequired: ['Sedation', 'Anticholinergic effects in elderly'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0915', genericName: 'Desloratadine', genericNameAr: 'ديسلوراتادين',
    brandNames: ['Aerius', 'Clarinex'], sfda_registration: 'SFDA-2024-AHI-915',
    atcCode: 'R06AX27', atcCategory: 'R06A', therapeuticClass: 'Antihistamines',
    therapeuticClassAr: 'مضادات الهيستامين', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '5mg', unitPrice: 2, inStock: true }, { form: 'syrup', strength: '0.5mg/ml', unitPrice: 15, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Loratadine'],
    interactions: [],
    contraindications: ['Hypersensitivity to desloratadine or loratadine'],
    contraindicationsAr: ['فرط الحساسية للديسلوراتادين أو اللوراتادين'],
    monitoringRequired: ['Clinical response'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0916', genericName: 'Levocetirizine', genericNameAr: 'ليفوسيتيريزين',
    brandNames: ['Xyzal'], sfda_registration: 'SFDA-2024-AHI-916',
    atcCode: 'R06AE09', atcCategory: 'R06A', therapeuticClass: 'Antihistamines',
    therapeuticClassAr: 'مضادات الهيستامين', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '5mg', unitPrice: 2, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Cetirizine'],
    interactions: [],
    contraindications: ['End-stage renal disease', 'Hypersensitivity to cetirizine'],
    contraindicationsAr: ['مرض كلوي بالمرحلة النهائية', 'فرط الحساسية للسيتيريزين'],
    monitoringRequired: ['Renal function', 'Sedation level'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0917', genericName: 'Promethazine', genericNameAr: 'بروميثازين',
    brandNames: ['Phenergan'], sfda_registration: 'SFDA-2024-AHI-917',
    atcCode: 'R06AD02', atcCategory: 'R06A', therapeuticClass: 'Antihistamines',
    therapeuticClassAr: 'مضادات الهيستامين', formularyStatus: 'formulary',
    route: ['oral', 'intramuscular', 'rectal'], forms: [{ form: 'tablet', strength: '25mg', unitPrice: 1.5, inStock: true }, { form: 'injection', strength: '25mg/ml', unitPrice: 5, inStock: true }, { form: 'syrup', strength: '5mg/5ml', unitPrice: 10, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Chlorpromazine'],
    blackBoxWarning: 'Contraindicated in children <2 years due to fatal respiratory depression risk. IV use may cause tissue necrosis.',
    blackBoxWarningAr: 'ممنوع في الأطفال أقل من سنتين بسبب خطر تثبيط الجهاز التنفسي المميت. الاستخدام الوريدي قد يسبب نخر الأنسجة.',
    interactions: [{ interactsWith: 'Opioids', severity: 'major', mechanism: 'Additive CNS/respiratory depression', clinicalEffect: 'Excessive sedation and respiratory failure', clinicalEffectAr: 'تخدير مفرط وفشل تنفسي', management: 'Reduce opioid dose', managementAr: 'تقليل جرعة الأفيونات' }],
    contraindications: ['Children under 2 years', 'Comatose patients', 'Intra-arterial injection'],
    contraindicationsAr: ['الأطفال أقل من سنتين', 'المرضى في غيبوبة', 'الحقن داخل الشرايين'],
    monitoringRequired: ['Respiratory rate', 'Sedation level', 'IV site for tissue injury'], storageConditions: 'Store below 25°C, protect from light'
  },
];

export const VITAMINS_MINERALS: FormularyDrug[] = [
  {
    id: 'FRM-0918', genericName: 'Cholecalciferol (Vitamin D3)', genericNameAr: 'كوليكالسيفيرول (فيتامين د3)',
    brandNames: ['Vi-De-3', 'Biodal'], sfda_registration: 'SFDA-2024-VIT-918',
    atcCode: 'A11CC05', atcCategory: 'A11C', therapeuticClass: 'Vitamins & Minerals',
    therapeuticClassAr: 'الفيتامينات والمعادن', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '1000IU', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '50000IU', unitPrice: 5, inStock: true }, { form: 'drops', strength: '400IU/drop', unitPrice: 15, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Calcitriol'],
    interactions: [{ interactsWith: 'Thiazide diuretics', severity: 'moderate', mechanism: 'Reduced calcium excretion', clinicalEffect: 'Hypercalcemia risk', clinicalEffectAr: 'خطر فرط كالسيوم الدم', management: 'Monitor calcium levels', managementAr: 'مراقبة مستويات الكالسيوم' }],
    contraindications: ['Hypercalcemia', 'Hypervitaminosis D'],
    contraindicationsAr: ['فرط كالسيوم الدم', 'فرط فيتامين د'],
    monitoringRequired: ['25-OH Vitamin D levels', 'Serum calcium'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0919', genericName: 'Cyanocobalamin (Vitamin B12)', genericNameAr: 'سيانوكوبالامين (فيتامين ب12)',
    brandNames: ['Neurobion'], sfda_registration: 'SFDA-2024-VIT-919',
    atcCode: 'B03BA01', atcCategory: 'B03B', therapeuticClass: 'Vitamins & Minerals',
    therapeuticClassAr: 'الفيتامينات والمعادن', formularyStatus: 'formulary',
    route: ['oral', 'intramuscular'], forms: [{ form: 'tablet', strength: '1000mcg', unitPrice: 1, inStock: true }, { form: 'injection', strength: '1000mcg/ml', unitPrice: 5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Hypersensitivity to cobalt or cobalamins'],
    contraindicationsAr: ['فرط الحساسية للكوبالت أو الكوبالامين'],
    monitoringRequired: ['Vitamin B12 levels', 'CBC', 'Reticulocyte count'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0920', genericName: 'Folic Acid', genericNameAr: 'حمض الفوليك',
    brandNames: ['Folvite'], sfda_registration: 'SFDA-2024-VIT-920',
    atcCode: 'B03BB01', atcCategory: 'B03B', therapeuticClass: 'Vitamins & Minerals',
    therapeuticClassAr: 'الفيتامينات والمعادن', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '5mg', unitPrice: 0.3, inStock: true }, { form: 'tablet', strength: '1mg', unitPrice: 0.2, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Folinic acid'],
    interactions: [{ interactsWith: 'Methotrexate', severity: 'moderate', mechanism: 'Antagonism of methotrexate antifolate effect', clinicalEffect: 'Reduced methotrexate efficacy in cancer', clinicalEffectAr: 'انخفاض فعالية الميثوتريكسات في السرطان', management: 'Consult oncologist before combining', managementAr: 'استشارة طبيب الأورام قبل الجمع' }],
    contraindications: ['Untreated B12 deficiency (can mask symptoms)'],
    contraindicationsAr: ['نقص ب12 غير المعالج (يمكن أن يخفي الأعراض)'],
    monitoringRequired: ['Folate levels', 'Vitamin B12 to rule out deficiency'], storageConditions: 'Store below 30°C, protect from light'
  },
  {
    id: 'FRM-0921', genericName: 'Iron Sucrose', genericNameAr: 'حديد سكروز',
    brandNames: ['Venofer'], sfda_registration: 'SFDA-2024-VIT-921',
    atcCode: 'B03AC02', atcCategory: 'B03A', therapeuticClass: 'Vitamins & Minerals',
    therapeuticClassAr: 'الفيتامينات والمعادن', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '100mg/5ml', unitPrice: 35, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Iron dextran', 'Ferric carboxymaltose'],
    interactions: [],
    contraindications: ['Iron overload', 'Anemia not due to iron deficiency', 'Known hypersensitivity'],
    contraindicationsAr: ['فرط الحديد', 'فقر الدم غير الناجم عن نقص الحديد', 'فرط الحساسية المعروف'],
    monitoringRequired: ['Iron studies (ferritin, TSAT)', 'Hemoglobin', 'Signs of hypersensitivity during infusion'], storageConditions: 'Store below 25°C, do not freeze'
  },
  {
    id: 'FRM-0922', genericName: 'Ferrous Sulfate', genericNameAr: 'كبريتات الحديدوز',
    brandNames: ['Ferograd', 'Feosol'], sfda_registration: 'SFDA-2024-VIT-922',
    atcCode: 'B03AA07', atcCategory: 'B03A', therapeuticClass: 'Vitamins & Minerals',
    therapeuticClassAr: 'الفيتامينات والمعادن', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '325mg', unitPrice: 0.5, inStock: true }, { form: 'syrup', strength: '75mg/5ml', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Ferrous gluconate', 'Ferrous fumarate'],
    interactions: [{ interactsWith: 'Levothyroxine', severity: 'moderate', mechanism: 'Reduced absorption of levothyroxine', clinicalEffect: 'Hypothyroidism symptoms', clinicalEffectAr: 'أعراض قصور الغدة الدرقية', management: 'Separate by at least 4 hours', managementAr: 'فصل بفارق 4 ساعات على الأقل' }],
    contraindications: ['Iron overload', 'Hemochromatosis', 'Repeated blood transfusions'],
    contraindicationsAr: ['فرط الحديد', 'داء ترسب الأصبغة الدموية', 'نقل الدم المتكرر'],
    monitoringRequired: ['Iron studies', 'Hemoglobin', 'GI tolerance'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0923', genericName: 'Calcium Carbonate', genericNameAr: 'كربونات الكالسيوم',
    brandNames: ['Caltrate', 'OsCal'], sfda_registration: 'SFDA-2024-VIT-923',
    atcCode: 'A12AA04', atcCategory: 'A12A', therapeuticClass: 'Vitamins & Minerals',
    therapeuticClassAr: 'الفيتامينات والمعادن', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '500mg', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '1250mg', unitPrice: 1, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Calcium chloride', 'Calcium gluconate'],
    interactions: [{ interactsWith: 'Ciprofloxacin', severity: 'moderate', mechanism: 'Chelation reduces absorption', clinicalEffect: 'Antibiotic treatment failure', clinicalEffectAr: 'فشل علاج المضاد الحيوي', management: 'Separate by 2 hours', managementAr: 'فصل بفارق ساعتين' }],
    contraindications: ['Hypercalcemia', 'Severe renal impairment', 'Calcium kidney stones'],
    contraindicationsAr: ['فرط كالسيوم الدم', 'قصور كلوي شديد', 'حصوات الكلى الكالسيوم'],
    monitoringRequired: ['Serum calcium', 'Renal function'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0924', genericName: 'Phytomenadione (Vitamin K1)', genericNameAr: 'فيتونادايون (فيتامين ك1)',
    brandNames: ['Konakion'], sfda_registration: 'SFDA-2024-VIT-924',
    atcCode: 'B02BA01', atcCategory: 'B02B', therapeuticClass: 'Vitamins & Minerals',
    therapeuticClassAr: 'الفيتامينات والمعادن', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [{ form: 'injection', strength: '10mg/ml', unitPrice: 8, inStock: true }, { form: 'oral drops', strength: '2mg/0.2ml', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Warfarin', severity: 'major', mechanism: 'Direct antagonism', clinicalEffect: 'Reversal of anticoagulant effect', clinicalEffectAr: 'عكس تأثير مضاد التخثر', management: 'Use only for warfarin reversal or deficiency', managementAr: 'يستخدم فقط لعكس الوارفارين أو النقص' }],
    contraindications: ['Hypersensitivity'],
    contraindicationsAr: ['فرط الحساسية'],
    monitoringRequired: ['INR', 'Signs of anaphylaxis with IV administration'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0925', genericName: 'Thiamine (Vitamin B1)', genericNameAr: 'ثيامين (فيتامين ب1)',
    brandNames: ['Benerva'], sfda_registration: 'SFDA-2024-VIT-925',
    atcCode: 'A11DA01', atcCategory: 'A11D', therapeuticClass: 'Vitamins & Minerals',
    therapeuticClassAr: 'الفيتامينات والمعادن', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [{ form: 'tablet', strength: '100mg', unitPrice: 0.5, inStock: true }, { form: 'injection', strength: '100mg/ml', unitPrice: 5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Hypersensitivity to thiamine'],
    contraindicationsAr: ['فرط الحساسية للثيامين'],
    monitoringRequired: ['Thiamine levels in at-risk patients', 'Neurological status in Wernicke encephalopathy'], storageConditions: 'Store below 25°C, protect from light'
  },
];

export const MUSCLE_RELAXANTS_GOUT: FormularyDrug[] = [
  {
    id: 'FRM-0926', genericName: 'Baclofen', genericNameAr: 'باكلوفين',
    brandNames: ['Lioresal'], sfda_registration: 'SFDA-2024-MRG-926',
    atcCode: 'M03BX01', atcCategory: 'M03B', therapeuticClass: 'Muscle Relaxants & Gout',
    therapeuticClassAr: 'مرخيات العضلات وأدوية النقرس', formularyStatus: 'formulary',
    route: ['oral', 'intrathecal'], forms: [{ form: 'tablet', strength: '10mg', unitPrice: 2, inStock: true }, { form: 'tablet', strength: '25mg', unitPrice: 3, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'CNS depressants', severity: 'major', mechanism: 'Additive CNS depression', clinicalEffect: 'Excessive sedation and respiratory depression', clinicalEffectAr: 'تخدير مفرط وتثبيط تنفسي', management: 'Reduce doses of CNS depressants', managementAr: 'تقليل جرعات مثبطات الجهاز العصبي' }],
    contraindications: ['Peptic ulcer disease'],
    contraindicationsAr: ['مرض القرحة الهضمية'],
    monitoringRequired: ['CNS effects', 'Withdrawal symptoms if discontinued abruptly', 'Renal function'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0927', genericName: 'Tizanidine', genericNameAr: 'تيزانيدين',
    brandNames: ['Zanaflex', 'Sirdalud'], sfda_registration: 'SFDA-2024-MRG-927',
    atcCode: 'M03BX02', atcCategory: 'M03B', therapeuticClass: 'Muscle Relaxants & Gout',
    therapeuticClassAr: 'مرخيات العضلات وأدوية النقرس', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '2mg', unitPrice: 2, inStock: true }, { form: 'tablet', strength: '4mg', unitPrice: 3, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Tiagabine'],
    interactions: [{ interactsWith: 'Ciprofloxacin', severity: 'major', mechanism: 'CYP1A2 inhibition', clinicalEffect: 'Severe hypotension and excessive sedation', clinicalEffectAr: 'انخفاض شديد في ضغط الدم وتخدير مفرط', management: 'Contraindicated combination', managementAr: 'تركيبة ممنوعة' }],
    contraindications: ['Concurrent fluvoxamine or ciprofloxacin', 'Severe hepatic impairment'],
    contraindicationsAr: ['الاستخدام المتزامن مع فلوفوكسامين أو سيبروفلوكساسين', 'قصور كبدي شديد'],
    monitoringRequired: ['Blood pressure', 'Liver function tests', 'Sedation level'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0928', genericName: 'Dantrolene', genericNameAr: 'دانترولين',
    brandNames: ['Dantrium'], sfda_registration: 'SFDA-2024-MRG-928',
    atcCode: 'M03CA01', atcCategory: 'M03C', therapeuticClass: 'Muscle Relaxants & Gout',
    therapeuticClassAr: 'مرخيات العضلات وأدوية النقرس', formularyStatus: 'restricted',
    restrictionCriteria: 'Malignant hyperthermia or severe spasticity', restrictionCriteriaAr: 'فرط الحرارة الخبيث أو التشنج الشديد', approverRole: 'anesthesiologist',
    route: ['oral', 'intravenous'], forms: [{ form: 'capsule', strength: '25mg', unitPrice: 8, inStock: true }, { form: 'injection', strength: '20mg', unitPrice: 180, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Risk of hepatotoxicity. Monitor liver function.',
    blackBoxWarningAr: 'خطر السمية الكبدية. مراقبة وظائف الكبد.',
    interactions: [{ interactsWith: 'Calcium channel blockers', severity: 'major', mechanism: 'Cardiovascular collapse risk', clinicalEffect: 'Hyperkalemia and myocardial depression', clinicalEffectAr: 'فرط بوتاسيوم الدم واكتئاب عضلة القلب', management: 'Avoid IV verapamil with IV dantrolene', managementAr: 'تجنب فيراباميل الوريدي مع دانترولين الوريدي' }],
    contraindications: ['Active hepatic disease', 'Where spasticity maintains posture/balance'],
    contraindicationsAr: ['مرض كبدي نشط', 'حيث يحافظ التشنج على الوضعية/التوازن'],
    monitoringRequired: ['Liver function tests at baseline and regularly', 'Muscle strength'], storageConditions: 'Store below 30°C, protect from light'
  },
  {
    id: 'FRM-0929', genericName: 'Methocarbamol', genericNameAr: 'ميثوكاربامول',
    brandNames: ['Robaxin'], sfda_registration: 'SFDA-2024-MRG-929',
    atcCode: 'M03BA03', atcCategory: 'M03B', therapeuticClass: 'Muscle Relaxants & Gout',
    therapeuticClassAr: 'مرخيات العضلات وأدوية النقرس', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [{ form: 'tablet', strength: '500mg', unitPrice: 2, inStock: true }, { form: 'injection', strength: '1000mg/10ml', unitPrice: 12, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'CNS depressants', severity: 'moderate', mechanism: 'Additive CNS depression', clinicalEffect: 'Excessive drowsiness', clinicalEffectAr: 'نعاس مفرط', management: 'Use with caution', managementAr: 'الاستخدام بحذر' }],
    contraindications: ['Renal impairment (IV form contains polyethylene glycol)', 'Myasthenia gravis'],
    contraindicationsAr: ['قصور كلوي (الشكل الوريدي يحتوي بولي إيثيلين غلايكول)', 'الوهن العضلي الوبيل'],
    monitoringRequired: ['CNS effects', 'Urine discoloration (brown/green)'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0930', genericName: 'Colchicine', genericNameAr: 'كولشيسين',
    brandNames: ['Colcrys'], sfda_registration: 'SFDA-2024-MRG-930',
    atcCode: 'M04AC01', atcCategory: 'M04A', therapeuticClass: 'Muscle Relaxants & Gout',
    therapeuticClassAr: 'مرخيات العضلات وأدوية النقرس', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '0.5mg', unitPrice: 3, inStock: true }],
    maxDailyDose: 3, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Clarithromycin', severity: 'major', mechanism: 'P-gp and CYP3A4 inhibition', clinicalEffect: 'Fatal colchicine toxicity', clinicalEffectAr: 'سمية كولشيسين مميتة', management: 'Reduce colchicine dose or avoid', managementAr: 'تقليل جرعة كولشيسين أو تجنب' }],
    contraindications: ['Severe renal and hepatic impairment combined', 'Concurrent strong CYP3A4 inhibitors with renal/hepatic impairment'],
    contraindicationsAr: ['قصور كلوي وكبدي شديد مجتمعين', 'مثبطات CYP3A4 القوية مع قصور كلوي/كبدي'],
    monitoringRequired: ['CBC', 'Renal function', 'Hepatic function', 'GI symptoms'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0931', genericName: 'Allopurinol', genericNameAr: 'ألوبيورينول',
    brandNames: ['Zyloric', 'Zyloprim'], sfda_registration: 'SFDA-2024-MRG-931',
    atcCode: 'M04AA01', atcCategory: 'M04A', therapeuticClass: 'Muscle Relaxants & Gout',
    therapeuticClassAr: 'مرخيات العضلات وأدوية النقرس', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '100mg', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '300mg', unitPrice: 1, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Azathioprine', severity: 'major', mechanism: 'Xanthine oxidase inhibition blocks azathioprine metabolism', clinicalEffect: 'Severe bone marrow suppression', clinicalEffectAr: 'تثبيط شديد لنخاع العظم', management: 'Reduce azathioprine dose by 75%', managementAr: 'تقليل جرعة الآزاثيوبرين بنسبة 75%' }],
    contraindications: ['Acute gout attack (do not initiate)', 'HLA-B*5801 positive patients (high risk of SJS/TEN)'],
    contraindicationsAr: ['نوبة نقرس حادة (لا تبدأ العلاج)', 'المرضى إيجابيو HLA-B*5801 (خطر عالي لمتلازمة ستيفنز جونسون)'],
    monitoringRequired: ['Serum uric acid', 'Renal function', 'Liver function tests', 'CBC', 'HLA-B*5801 screening'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0932', genericName: 'Febuxostat', genericNameAr: 'فيبوكسوستات',
    brandNames: ['Uloric', 'Adenuric'], sfda_registration: 'SFDA-2024-MRG-932',
    atcCode: 'M04AA03', atcCategory: 'M04A', therapeuticClass: 'Muscle Relaxants & Gout',
    therapeuticClassAr: 'مرخيات العضلات وأدوية النقرس', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '40mg', unitPrice: 5, inStock: true }, { form: 'tablet', strength: '80mg', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Cardiovascular death risk higher than allopurinol in clinical trials.',
    blackBoxWarningAr: 'خطر الوفاة القلبية الوعائية أعلى من الألوبيورينول في التجارب السريرية.',
    interactions: [{ interactsWith: 'Azathioprine', severity: 'major', mechanism: 'Inhibits xanthine oxidase', clinicalEffect: 'Increased azathioprine toxicity', clinicalEffectAr: 'زيادة سمية الآزاثيوبرين', management: 'Contraindicated combination', managementAr: 'تركيبة ممنوعة' }],
    contraindications: ['Concurrent azathioprine or mercaptopurine', 'Severe hepatic impairment'],
    contraindicationsAr: ['الاستخدام المتزامن مع الآزاثيوبرين أو الميركابتوبورين', 'قصور كبدي شديد'],
    monitoringRequired: ['Serum uric acid', 'Liver function tests', 'Cardiovascular events'], storageConditions: 'Store below 25°C'
  },
];

export const LAXATIVES_GI: FormularyDrug[] = [
  {
    id: 'FRM-0933', genericName: 'Lactulose', genericNameAr: 'لاكتيلوز',
    brandNames: ['Duphalac'], sfda_registration: 'SFDA-2024-LAX-933',
    atcCode: 'A06AD11', atcCategory: 'A06A', therapeuticClass: 'Laxatives',
    therapeuticClassAr: 'الملينات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'oral solution', strength: '10g/15ml', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Lactose'],
    interactions: [],
    contraindications: ['Galactosemia', 'Intestinal obstruction'],
    contraindicationsAr: ['الجالاكتوزيميا', 'انسداد معوي'],
    monitoringRequired: ['Electrolytes for prolonged use', 'Ammonia levels in hepatic encephalopathy'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0934', genericName: 'Bisacodyl', genericNameAr: 'بيساكوديل',
    brandNames: ['Dulcolax'], sfda_registration: 'SFDA-2024-LAX-934',
    atcCode: 'A06AB02', atcCategory: 'A06A', therapeuticClass: 'Laxatives',
    therapeuticClassAr: 'الملينات', formularyStatus: 'formulary',
    route: ['oral', 'rectal'], forms: [{ form: 'tablet', strength: '5mg', unitPrice: 0.5, inStock: true }, { form: 'suppository', strength: '10mg', unitPrice: 2, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Intestinal obstruction', 'Acute abdominal conditions', 'Severe dehydration'],
    contraindicationsAr: ['انسداد معوي', 'حالات بطنية حادة', 'جفاف شديد'],
    monitoringRequired: ['Electrolytes with prolonged use', 'Bowel habits'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0935', genericName: 'Macrogol (PEG 3350)', genericNameAr: 'ماكروغول',
    brandNames: ['Movicol', 'MiraLax'], sfda_registration: 'SFDA-2024-LAX-935',
    atcCode: 'A06AD65', atcCategory: 'A06A', therapeuticClass: 'Laxatives',
    therapeuticClassAr: 'الملينات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'powder for solution', strength: '13.125g/sachet', unitPrice: 3, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Intestinal obstruction', 'Ileus', 'Bowel perforation'],
    contraindicationsAr: ['انسداد معوي', 'العلوص', 'ثقب الأمعاء'],
    monitoringRequired: ['Electrolytes for prolonged use', 'Hydration status'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0936', genericName: 'Senna', genericNameAr: 'سنا',
    brandNames: ['Senokot'], sfda_registration: 'SFDA-2024-LAX-936',
    atcCode: 'A06AB06', atcCategory: 'A06A', therapeuticClass: 'Laxatives',
    therapeuticClassAr: 'الملينات', formularyStatus: 'formulary',
    route: ['oral'], forms: [{ form: 'tablet', strength: '8.6mg', unitPrice: 0.5, inStock: true }, { form: 'syrup', strength: '8.8mg/5ml', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Intestinal obstruction', 'Acute inflammatory bowel disease', 'Abdominal pain of unknown cause'],
    contraindicationsAr: ['انسداد معوي', 'مرض التهاب الأمعاء الحاد', 'ألم بطني مجهول السبب'],
    monitoringRequired: ['Electrolytes with chronic use', 'Melanosis coli with prolonged use'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0937', genericName: 'Docusate Sodium', genericNameAr: 'دوكوسات الصوديوم',
    brandNames: ['Colace'], sfda_registration: 'SFDA-2024-LAX-937',
    atcCode: 'A06AA02', atcCategory: 'A06A', therapeuticClass: 'Laxatives',
    therapeuticClassAr: 'الملينات', formularyStatus: 'formulary',
    route: ['oral', 'rectal'], forms: [{ form: 'capsule', strength: '100mg', unitPrice: 0.5, inStock: true }, { form: 'enema', strength: '283mg', unitPrice: 5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Mineral oil', severity: 'moderate', mechanism: 'Increased mineral oil absorption', clinicalEffect: 'Lipoid pneumonia risk if aspirated', clinicalEffectAr: 'خطر الالتهاب الرئوي الدهني', management: 'Avoid combination', managementAr: 'تجنب الجمع' }],
    contraindications: ['Intestinal obstruction', 'Concurrent mineral oil'],
    contraindicationsAr: ['انسداد معوي', 'الزيت المعدني المتزامن'],
    monitoringRequired: ['Bowel habits', 'Electrolytes if prolonged use'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0938', genericName: 'Glycerin', genericNameAr: 'غليسيرين',
    brandNames: ['Glycerin Suppository'], sfda_registration: 'SFDA-2024-LAX-938',
    atcCode: 'A06AX01', atcCategory: 'A06A', therapeuticClass: 'Laxatives',
    therapeuticClassAr: 'الملينات', formularyStatus: 'formulary',
    route: ['rectal'], forms: [{ form: 'suppository', strength: '2g', unitPrice: 1, inStock: true }, { form: 'suppository', strength: '1g', unitPrice: 0.8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Intestinal obstruction', 'Undiagnosed rectal bleeding'],
    contraindicationsAr: ['انسداد معوي', 'نزيف مستقيمي غير مشخص'],
    monitoringRequired: ['Clinical response'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0939', genericName: 'Succinylcholine', genericNameAr: 'سكسينيل كولين',
    brandNames: ['Anectine'], sfda_registration: 'SFDA-2024-MRG-939',
    atcCode: 'M03AB01', atcCategory: 'M03A', therapeuticClass: 'Muscle Relaxants & Gout',
    therapeuticClassAr: 'مرخيات العضلات وأدوية النقرس', formularyStatus: 'restricted',
    restrictionCriteria: 'Operating room and emergency intubation only', restrictionCriteriaAr: 'غرفة العمليات والتنبيب الطارئ فقط', approverRole: 'anesthesiologist',
    route: ['intravenous', 'intramuscular'], forms: [{ form: 'injection', strength: '20mg/ml', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Sucralfate'],
    blackBoxWarning: 'Risk of malignant hyperthermia, hyperkalemia, and cardiac arrest especially in children with undiagnosed myopathy.',
    blackBoxWarningAr: 'خطر فرط الحرارة الخبيث وفرط بوتاسيوم الدم وتوقف القلب خاصة في الأطفال مع اعتلال عضلي غير مشخص.',
    interactions: [{ interactsWith: 'Anticholinesterases', severity: 'major', mechanism: 'Prolonged neuromuscular blockade', clinicalEffect: 'Extended paralysis', clinicalEffectAr: 'شلل ممتد', management: 'Ventilatory support until recovery', managementAr: 'دعم التنفس حتى التعافي' }],
    contraindications: ['Personal/family history of malignant hyperthermia', 'Denervation injuries', 'Burns >48h old', 'Hyperkalemia risk'],
    contraindicationsAr: ['تاريخ شخصي/عائلي لفرط الحرارة الخبيث', 'إصابات إزالة التعصيب', 'حروق أكثر من 48 ساعة', 'خطر فرط البوتاسيوم'],
    monitoringRequired: ['Neuromuscular function', 'ECG and potassium', 'Temperature for MH'], storageConditions: 'Refrigerate 2-8°C'
  },
];

