/**
 * Saudi MOH Drug Formulary — Drug Data Part 11
 * Hormonal & Reproductive Agents
 * IDs: FRM-0640 through FRM-0679
 */
import type { FormularyDrug } from './formularyTypes';

export const HORMONAL_REPRODUCTIVE: FormularyDrug[] = [
  // ── 1. Thyroid Agents ──
  {
    id: 'FRM-0640', genericName: 'Liothyronine', genericNameAr: 'ليوثيرونين',
    brandNames: ['Cytomel', 'Triostat'], sfda_registration: 'SFDA-2024-THY-640',
    atcCode: 'H03AA02', atcCategory: 'Thyroid hormones',
    therapeuticClass: 'Thyroid Hormone', therapeuticClassAr: 'هرمون الغدة الدرقية',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Endocrinologist approval; use when T4 monotherapy insufficient',
    restrictionCriteriaAr: 'موافقة أخصائي الغدد الصماء؛ يستخدم عند عدم كفاية العلاج بـ T4',
    approverRole: 'endocrinologist',
    route: ['oral', 'intravenous'], forms: [
      { form: 'Tablet', strength: '5 mcg', unitPrice: 2.8, inStock: true },
      { form: 'Tablet', strength: '25 mcg', unitPrice: 3.5, inStock: true },
      { form: 'Injection', strength: '10 mcg/mL', unitPrice: 85.0, inStock: false },
    ],
    maxDailyDose: 75, maxDailyDoseUnit: 'mcg',
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Levothyroxine', 'Liotrix'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Increased catabolism of vitamin K-dependent clotting factors', clinicalEffect: 'Enhanced anticoagulant effect', clinicalEffectAr: 'تعزيز تأثير مضاد التخثر', management: 'Monitor INR closely; adjust warfarin dose', managementAr: 'مراقبة INR عن كثب؛ تعديل جرعة الوارفارين' },
      { interactsWith: 'Digoxin', severity: 'moderate', mechanism: 'Thyroid hormones increase digoxin clearance', clinicalEffect: 'Reduced digoxin levels', clinicalEffectAr: 'انخفاض مستويات الديجوكسين', management: 'Monitor digoxin levels when initiating or adjusting thyroid therapy', managementAr: 'مراقبة مستويات الديجوكسين عند بدء أو تعديل علاج الغدة الدرقية' },
    ],
    contraindications: ['Uncorrected adrenal insufficiency', 'Acute myocardial infarction', 'Thyrotoxicosis'],
    contraindicationsAr: ['قصور الغدة الكظرية غير المصحح', 'احتشاء عضلة القلب الحاد', 'التسمم الدرقي'],
    monitoringRequired: ['TSH', 'Free T3', 'Heart rate', 'ECG in elderly'],
    storageConditions: 'Store at 15-30°C, protect from light',
  },
  {
    id: 'FRM-0641', genericName: 'Methimazole', genericNameAr: 'ميثيمازول',
    brandNames: ['Tapazole', 'Thymazole'], sfda_registration: 'SFDA-2024-THY-641',
    atcCode: 'H03BB02', atcCategory: 'Antithyroid preparations',
    therapeuticClass: 'Antithyroid Agent', therapeuticClassAr: 'مضاد الغدة الدرقية',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '5 mg', unitPrice: 1.5, inStock: true },
      { form: 'Tablet', strength: '10 mg', unitPrice: 2.2, inStock: true },
    ],
    maxDailyDose: 60, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Metolazone', 'Methotrexate'],
    blackBoxWarning: 'Risk of agranulocytosis; obtain baseline and periodic CBCs',
    blackBoxWarningAr: 'خطر ندرة المحببات؛ إجراء فحص دم شامل أساسي ودوري',
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Hyperthyroidism increases warfarin metabolism; correction changes requirements', clinicalEffect: 'Altered anticoagulant effect as thyroid status normalizes', clinicalEffectAr: 'تغير تأثير مضاد التخثر مع تطبيع حالة الغدة الدرقية', management: 'Monitor INR frequently during dose adjustments', managementAr: 'مراقبة INR بشكل متكرر أثناء تعديل الجرعة' },
      { interactsWith: 'Beta-blockers', severity: 'minor', mechanism: 'Reduced clearance as thyroid function normalizes', clinicalEffect: 'Potential for enhanced beta-blocker effect', clinicalEffectAr: 'احتمال تعزيز تأثير حاصرات بيتا', management: 'Taper beta-blocker as euthyroidism is achieved', managementAr: 'تقليل حاصرات بيتا تدريجياً مع تحقيق السواء الدرقي' },
    ],
    contraindications: ['Prior agranulocytosis from thionamides', 'Severe hepatic impairment'],
    contraindicationsAr: ['ندرة محببات سابقة من الثيوناميدات', 'قصور كبدي شديد'],
    monitoringRequired: ['CBC with differential', 'Liver function tests', 'TSH every 4-6 weeks', 'Free T4'],
    storageConditions: 'Store at 15-30°C',
  },
  {
    id: 'FRM-0642', genericName: 'Propylthiouracil', genericNameAr: 'بروبيل ثيوراسيل',
    brandNames: ['PTU'], sfda_registration: 'SFDA-2024-THY-642',
    atcCode: 'H03BA02', atcCategory: 'Antithyroid preparations',
    therapeuticClass: 'Antithyroid Agent', therapeuticClassAr: 'مضاد الغدة الدرقية',
    formularyStatus: 'restricted',
    restrictionCriteria: 'First trimester of pregnancy or methimazole intolerance only',
    restrictionCriteriaAr: 'الثلث الأول من الحمل أو عدم تحمل الميثيمازول فقط',
    approverRole: 'endocrinologist',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '50 mg', unitPrice: 1.8, inStock: true },
    ],
    maxDailyDose: 600, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Purinthol'],
    blackBoxWarning: 'Severe hepatotoxicity including fatal hepatic necrosis reported; reserve for patients who cannot tolerate methimazole',
    blackBoxWarningAr: 'تسمم كبدي شديد بما في ذلك نخر كبدي مميت؛ يقتصر على المرضى الذين لا يتحملون الميثيمازول',
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Altered vitamin K-dependent factor metabolism', clinicalEffect: 'Altered anticoagulant response', clinicalEffectAr: 'تغير استجابة مضاد التخثر', management: 'Monitor INR closely during treatment', managementAr: 'مراقبة INR عن كثب أثناء العلاج' },
    ],
    contraindications: ['Severe hepatic disease', 'Prior PTU-induced hepatotoxicity'],
    contraindicationsAr: ['مرض كبدي شديد', 'تسمم كبدي سابق بسبب PTU'],
    monitoringRequired: ['LFTs at baseline and periodically', 'CBC with differential', 'TSH', 'Free T4'],
    storageConditions: 'Store at 15-30°C, protect from light',
  },
  {
    id: 'FRM-0643', genericName: 'Potassium Iodide', genericNameAr: 'يوديد البوتاسيوم',
    brandNames: ['Lugol Solution', 'SSKI', 'ThyroShield'], sfda_registration: 'SFDA-2024-THY-643',
    atcCode: 'H03CA', atcCategory: 'Iodine therapy',
    therapeuticClass: 'Thyroid Agent', therapeuticClassAr: 'عامل الغدة الدرقية',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Pre-thyroidectomy preparation or thyroid storm only',
    restrictionCriteriaAr: 'تحضير ما قبل استئصال الغدة الدرقية أو العاصفة الدرقية فقط',
    approverRole: 'endocrinologist',
    route: ['oral'], forms: [
      { form: 'Oral solution', strength: '65 mg/mL', unitPrice: 12.0, inStock: true },
      { form: 'Tablet', strength: '130 mg', unitPrice: 3.5, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Potassium chloride'],
    interactions: [
      { interactsWith: 'Lithium', severity: 'major', mechanism: 'Additive hypothyroid effect', clinicalEffect: 'Increased risk of hypothyroidism', clinicalEffectAr: 'زيادة خطر قصور الغدة الدرقية', management: 'Monitor thyroid function closely', managementAr: 'مراقبة وظائف الغدة الدرقية عن كثب' },
    ],
    contraindications: ['Dermatitis herpetiformis', 'Hypocomplementemic vasculitis', 'Iodine hypersensitivity'],
    contraindicationsAr: ['التهاب الجلد الحلئي الشكل', 'التهاب الأوعية ناقص المتممة', 'فرط الحساسية لليود'],
    monitoringRequired: ['TSH', 'Free T4', 'Serum potassium'],
    storageConditions: 'Store at 15-30°C, protect from light and moisture',
  },

  // ── 2. Systemic Corticosteroids ──
  {
    id: 'FRM-0644', genericName: 'Dexamethasone', genericNameAr: 'ديكساميثازون',
    brandNames: ['Decadron', 'Dexacort'], sfda_registration: 'SFDA-2024-COR-644',
    atcCode: 'H02AB02', atcCategory: 'Corticosteroids for systemic use',
    therapeuticClass: 'Systemic Corticosteroid', therapeuticClassAr: 'كورتيكوستيرويد جهازي',
    formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [
      { form: 'Tablet', strength: '0.5 mg', unitPrice: 0.8, inStock: true },
      { form: 'Tablet', strength: '4 mg', unitPrice: 2.5, inStock: true },
      { form: 'Injection', strength: '4 mg/mL', unitPrice: 8.0, inStock: true },
      { form: 'Injection', strength: '10 mg/mL', unitPrice: 15.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Desoximetasone', 'Dextroamphetamine'],
    interactions: [
      { interactsWith: 'NSAIDs', severity: 'major', mechanism: 'Additive GI mucosal damage', clinicalEffect: 'Increased risk of GI bleeding and ulceration', clinicalEffectAr: 'زيادة خطر النزف والتقرح المعدي المعوي', management: 'Add gastroprotection with PPI; avoid if possible', managementAr: 'إضافة حماية معدية بمثبطات مضخة البروتون؛ تجنب إن أمكن' },
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Corticosteroids may enhance or reduce anticoagulant effect', clinicalEffect: 'Unpredictable INR changes', clinicalEffectAr: 'تغيرات غير متوقعة في INR', management: 'Monitor INR closely when initiating or discontinuing', managementAr: 'مراقبة INR عن كثب عند البدء أو التوقف' },
    ],
    contraindications: ['Systemic fungal infections', 'Live vaccine administration', 'Cerebral malaria'],
    contraindicationsAr: ['العدوى الفطرية الجهازية', 'إعطاء اللقاحات الحية', 'الملاريا الدماغية'],
    monitoringRequired: ['Blood glucose', 'Blood pressure', 'Serum potassium', 'Bone density with long-term use'],
    storageConditions: 'Store at 20-25°C, protect from light',
  },
  {
    id: 'FRM-0645', genericName: 'Betamethasone', genericNameAr: 'بيتاميثازون',
    brandNames: ['Celestone', 'Betnesol'], sfda_registration: 'SFDA-2024-COR-645',
    atcCode: 'H02AB01', atcCategory: 'Corticosteroids for systemic use',
    therapeuticClass: 'Systemic Corticosteroid', therapeuticClassAr: 'كورتيكوستيرويد جهازي',
    formularyStatus: 'formulary',
    route: ['intramuscular', 'oral'], forms: [
      { form: 'Injection', strength: '6 mg/mL (acetate/phosphate)', unitPrice: 22.0, inStock: true },
      { form: 'Tablet', strength: '0.5 mg', unitPrice: 1.5, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Dexamethasone'],
    interactions: [
      { interactsWith: 'NSAIDs', severity: 'major', mechanism: 'Additive GI mucosal injury', clinicalEffect: 'Increased GI bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف المعدي المعوي', management: 'Co-prescribe PPI for gastroprotection', managementAr: 'وصف مثبط مضخة البروتون للحماية المعدية' },
    ],
    contraindications: ['Systemic fungal infections', 'Idiopathic thrombocytopenic purpura (IM)'],
    contraindicationsAr: ['العدوى الفطرية الجهازية', 'فرفرية قلة الصفيحات مجهولة السبب (عضلي)'],
    monitoringRequired: ['Blood glucose', 'Blood pressure', 'Adrenal function'],
    storageConditions: 'Store at 20-25°C, protect from light',
  },
  {
    id: 'FRM-0646', genericName: 'Fludrocortisone', genericNameAr: 'فلودروكورتيزون',
    brandNames: ['Florinef'], sfda_registration: 'SFDA-2024-COR-646',
    atcCode: 'H02AA02', atcCategory: 'Mineralocorticoids',
    therapeuticClass: 'Mineralocorticoid', therapeuticClassAr: 'كورتيكوستيرويد معدني',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Adrenal insufficiency or salt-losing congenital adrenal hyperplasia',
    restrictionCriteriaAr: 'قصور الغدة الكظرية أو فرط تنسج الكظر الخلقي المفقد للملح',
    approverRole: 'endocrinologist',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '0.1 mg', unitPrice: 6.5, inStock: true },
    ],
    maxDailyDose: 0.2, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Fluticasone'],
    interactions: [
      { interactsWith: 'Diuretics', severity: 'moderate', mechanism: 'Opposing effects on sodium and potassium balance', clinicalEffect: 'Hypokalemia risk', clinicalEffectAr: 'خطر نقص بوتاسيوم الدم', management: 'Monitor electrolytes regularly', managementAr: 'مراقبة الأملاح بانتظام' },
    ],
    contraindications: ['Systemic fungal infections', 'Severe hypertension', 'Heart failure'],
    contraindicationsAr: ['العدوى الفطرية الجهازية', 'ارتفاع ضغط الدم الشديد', 'فشل القلب'],
    monitoringRequired: ['Blood pressure', 'Serum potassium', 'Serum sodium', 'Body weight'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0647', genericName: 'Triamcinolone Acetonide', genericNameAr: 'تريامسينولون أسيتونيد',
    brandNames: ['Kenalog', 'Kenacort'], sfda_registration: 'SFDA-2024-COR-647',
    atcCode: 'H02AB08', atcCategory: 'Corticosteroids for systemic use',
    therapeuticClass: 'Systemic Corticosteroid', therapeuticClassAr: 'كورتيكوستيرويد جهازي',
    formularyStatus: 'formulary',
    route: ['intramuscular', 'intra-articular'], forms: [
      { form: 'Injection', strength: '40 mg/mL', unitPrice: 18.0, inStock: true },
      { form: 'Injection', strength: '10 mg/mL', unitPrice: 12.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Triamterene'],
    interactions: [
      { interactsWith: 'NSAIDs', severity: 'major', mechanism: 'Additive GI toxicity', clinicalEffect: 'Increased GI bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف المعدي المعوي', management: 'Add PPI; minimize concurrent use', managementAr: 'إضافة مثبط مضخة البروتون؛ تقليل الاستخدام المتزامن' },
    ],
    contraindications: ['Systemic fungal infections', 'Intra-articular injection into infected joints'],
    contraindicationsAr: ['العدوى الفطرية الجهازية', 'الحقن داخل المفاصل المصابة بالعدوى'],
    monitoringRequired: ['Blood glucose', 'Injection site for local atrophy', 'Adrenal function'],
    storageConditions: 'Store at 20-25°C, do not freeze',
  },
  {
    id: 'FRM-0648', genericName: 'Budesonide (oral)', genericNameAr: 'بوديسونيد (فموي)',
    brandNames: ['Entocort', 'Budenofalk'], sfda_registration: 'SFDA-2024-COR-648',
    atcCode: 'A07EA06', atcCategory: 'Intestinal anti-inflammatory agents',
    therapeuticClass: 'Locally-acting Corticosteroid', therapeuticClassAr: 'كورتيكوستيرويد موضعي التأثير',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Capsule', strength: '3 mg', unitPrice: 8.5, inStock: true },
      { form: 'Capsule', strength: '9 mg', unitPrice: 22.0, inStock: true },
    ],
    maxDailyDose: 9, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Budesonide inhaler'],
    interactions: [
      { interactsWith: 'Ketoconazole', severity: 'major', mechanism: 'CYP3A4 inhibition increases budesonide exposure', clinicalEffect: 'Increased systemic corticosteroid effects', clinicalEffectAr: 'زيادة التأثيرات الجهازية للكورتيكوستيرويد', management: 'Avoid combination; use alternative antifungal', managementAr: 'تجنب الجمع؛ استخدام مضاد فطري بديل' },
    ],
    contraindications: ['Severe hepatic impairment (cirrhosis)', 'Systemic fungal infections'],
    contraindicationsAr: ['قصور كبدي شديد (تليف)', 'العدوى الفطرية الجهازية'],
    monitoringRequired: ['Adrenal function if prolonged use', 'Liver function tests', 'Blood glucose'],
    storageConditions: 'Store at 25°C, protect from moisture',
  },

  // ── 3. Sex Hormones ──
  {
    id: 'FRM-0649', genericName: 'Estradiol', genericNameAr: 'استراديول',
    brandNames: ['Estrace', 'Progynova', 'Climara'], sfda_registration: 'SFDA-2024-HOR-649',
    atcCode: 'G03CA03', atcCategory: 'Natural and semisynthetic estrogens',
    therapeuticClass: 'Estrogen', therapeuticClassAr: 'إستروجين',
    formularyStatus: 'formulary',
    route: ['oral', 'transdermal', 'vaginal'], forms: [
      { form: 'Tablet', strength: '1 mg', unitPrice: 3.0, inStock: true },
      { form: 'Tablet', strength: '2 mg', unitPrice: 4.0, inStock: true },
      { form: 'Transdermal patch', strength: '50 mcg/day', unitPrice: 18.0, inStock: true },
      { form: 'Vaginal cream', strength: '0.01%', unitPrice: 35.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ethinylestradiol'],
    blackBoxWarning: 'Increased risk of endometrial cancer, stroke, DVT, and PE; use lowest effective dose for shortest duration',
    blackBoxWarningAr: 'زيادة خطر سرطان بطانة الرحم والسكتة والجلطة الوريدية العميقة؛ استخدام أقل جرعة فعالة لأقصر مدة',
    interactions: [
      { interactsWith: 'Aromatase inhibitors', severity: 'major', mechanism: 'Estrogen opposes therapeutic effect of aromatase inhibitors', clinicalEffect: 'Reduced efficacy of aromatase inhibitor therapy', clinicalEffectAr: 'تقليل فعالية مثبطات الأروماتيز', management: 'Contraindicated combination in breast cancer', managementAr: 'تركيبة ممنوعة في سرطان الثدي' },
      { interactsWith: 'Rifampin', severity: 'moderate', mechanism: 'CYP3A4 induction reduces estrogen levels', clinicalEffect: 'Decreased estrogen efficacy', clinicalEffectAr: 'انخفاض فعالية الإستروجين', management: 'Consider dose adjustment or alternative', managementAr: 'النظر في تعديل الجرعة أو البديل' },
    ],
    contraindications: ['Known or suspected breast cancer', 'Undiagnosed vaginal bleeding', 'Active DVT/PE', 'Active liver disease'],
    contraindicationsAr: ['سرطان الثدي المعروف أو المشتبه', 'نزيف مهبلي غير مشخص', 'جلطة وريدية نشطة', 'مرض كبدي نشط'],
    monitoringRequired: ['Mammography', 'Endometrial thickness (ultrasound)', 'Lipid profile', 'Blood pressure'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0650', genericName: 'Conjugated Estrogens', genericNameAr: 'إستروجينات مقترنة',
    brandNames: ['Premarin'], sfda_registration: 'SFDA-2024-HOR-650',
    atcCode: 'G03CA57', atcCategory: 'Natural and semisynthetic estrogens',
    therapeuticClass: 'Estrogen', therapeuticClassAr: 'إستروجين',
    formularyStatus: 'formulary',
    route: ['oral', 'vaginal'], forms: [
      { form: 'Tablet', strength: '0.3 mg', unitPrice: 4.5, inStock: true },
      { form: 'Tablet', strength: '0.625 mg', unitPrice: 5.5, inStock: true },
      { form: 'Vaginal cream', strength: '0.625 mg/g', unitPrice: 42.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Estradiol'],
    blackBoxWarning: 'Increased risk of endometrial cancer, stroke, DVT, PE, and probable dementia in women >65',
    blackBoxWarningAr: 'زيادة خطر سرطان بطانة الرحم والسكتة والجلطة والخرف المحتمل عند النساء فوق 65',
    interactions: [
      { interactsWith: 'Thyroid hormones', severity: 'moderate', mechanism: 'Estrogens increase thyroxine-binding globulin', clinicalEffect: 'May require increased thyroid dose', clinicalEffectAr: 'قد يتطلب زيادة جرعة الغدة الدرقية', management: 'Monitor TSH; adjust thyroid dose as needed', managementAr: 'مراقبة TSH؛ تعديل جرعة الغدة الدرقية حسب الحاجة' },
    ],
    contraindications: ['Breast cancer', 'Estrogen-dependent neoplasia', 'Active thromboembolic disorder', 'Pregnancy'],
    contraindicationsAr: ['سرطان الثدي', 'أورام معتمدة على الإستروجين', 'اضطراب انصمام خثاري نشط', 'الحمل'],
    monitoringRequired: ['Mammography', 'Pelvic exam', 'Blood pressure', 'Lipid profile'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0651', genericName: 'Medroxyprogesterone Acetate', genericNameAr: 'ميدروكسي بروجسترون أسيتات',
    brandNames: ['Provera', 'Depo-Provera'], sfda_registration: 'SFDA-2024-HOR-651',
    atcCode: 'G03DA02', atcCategory: 'Pregnadien derivatives',
    therapeuticClass: 'Progestogen', therapeuticClassAr: 'بروجستوجين',
    formularyStatus: 'formulary',
    route: ['oral', 'intramuscular'], forms: [
      { form: 'Tablet', strength: '2.5 mg', unitPrice: 2.0, inStock: true },
      { form: 'Tablet', strength: '5 mg', unitPrice: 2.5, inStock: true },
      { form: 'Tablet', strength: '10 mg', unitPrice: 3.5, inStock: true },
      { form: 'Injection', strength: '150 mg/mL', unitPrice: 25.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Methylprednisolone', 'Hydroxyprogesterone'],
    blackBoxWarning: 'Depo injection: loss of bone mineral density; limit duration; increased breast cancer risk with estrogen',
    blackBoxWarningAr: 'حقن ديبو: فقدان كثافة العظام؛ الحد من المدة؛ زيادة خطر سرطان الثدي مع الإستروجين',
    interactions: [
      { interactsWith: 'Aminoglutethimide', severity: 'major', mechanism: 'Reduces medroxyprogesterone bioavailability', clinicalEffect: 'Decreased progestogen efficacy', clinicalEffectAr: 'انخفاض فعالية البروجستوجين', management: 'Avoid combination or increase dose', managementAr: 'تجنب الجمع أو زيادة الجرعة' },
    ],
    contraindications: ['Known or suspected pregnancy', 'Breast cancer', 'Active thromboembolic disorders', 'Severe hepatic dysfunction'],
    contraindicationsAr: ['حمل معروف أو مشتبه', 'سرطان الثدي', 'اضطرابات انصمام خثاري نشطة', 'خلل كبدي شديد'],
    monitoringRequired: ['Bone density (Depo long-term)', 'Blood pressure', 'Lipid profile', 'Glucose'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0652', genericName: 'Norethisterone', genericNameAr: 'نوريثيستيرون',
    brandNames: ['Primolut-N', 'Norlutate'], sfda_registration: 'SFDA-2024-HOR-652',
    atcCode: 'G03DC02', atcCategory: 'Estren derivatives',
    therapeuticClass: 'Progestogen', therapeuticClassAr: 'بروجستوجين',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '5 mg', unitPrice: 2.5, inStock: true },
    ],
    maxDailyDose: 15, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Norgestrel'],
    interactions: [
      { interactsWith: 'Rifampin', severity: 'major', mechanism: 'CYP3A4 induction reduces progestogen levels', clinicalEffect: 'Contraceptive failure risk', clinicalEffectAr: 'خطر فشل منع الحمل', management: 'Use alternative non-hormonal method', managementAr: 'استخدام وسيلة بديلة غير هرمونية' },
    ],
    contraindications: ['Pregnancy', 'Active thromboembolic disease', 'Severe hepatic impairment', 'Breast cancer'],
    contraindicationsAr: ['الحمل', 'مرض انصمام خثاري نشط', 'قصور كبدي شديد', 'سرطان الثدي'],
    monitoringRequired: ['Liver function tests', 'Blood pressure'],
    storageConditions: 'Store at 15-25°C',
  },
  {
    id: 'FRM-0653', genericName: 'Testosterone', genericNameAr: 'تستوستيرون',
    brandNames: ['Androgel', 'Nebido', 'Sustanon'], sfda_registration: 'SFDA-2024-HOR-653',
    atcCode: 'G03BA03', atcCategory: '3-oxoandrosten (4) derivatives',
    therapeuticClass: 'Androgen', therapeuticClassAr: 'أندروجين',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Confirmed hypogonadism with two low morning testosterone levels',
    restrictionCriteriaAr: 'قصور الغدد التناسلية المؤكد بمستويين منخفضين للتستوستيرون الصباحي',
    approverRole: 'endocrinologist',
    route: ['intramuscular', 'topical', 'transdermal'], forms: [
      { form: 'Injection', strength: '250 mg/mL (Sustanon)', unitPrice: 35.0, inStock: true },
      { form: 'Injection', strength: '1000 mg/4mL (Nebido)', unitPrice: 280.0, inStock: true },
      { form: 'Gel', strength: '1% (50 mg/sachet)', unitPrice: 15.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: true, controlSchedule: 'Schedule III',
    lookAlikeSoundAlike: ['Testolactone'],
    blackBoxWarning: 'Increased risk of major adverse cardiovascular events; do not use for age-related decline',
    blackBoxWarningAr: 'زيادة خطر الأحداث القلبية الوعائية الرئيسية؛ لا يستخدم لانخفاض مرتبط بالعمر',
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Testosterone enhances anticoagulant effect', clinicalEffect: 'Increased bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف', management: 'Monitor INR closely; reduce warfarin dose', managementAr: 'مراقبة INR عن كثب؛ تقليل جرعة الوارفارين' },
      { interactsWith: 'Insulin', severity: 'moderate', mechanism: 'Testosterone may enhance insulin sensitivity', clinicalEffect: 'Hypoglycemia risk', clinicalEffectAr: 'خطر نقص السكر', management: 'Monitor blood glucose; adjust insulin', managementAr: 'مراقبة سكر الدم؛ تعديل الأنسولين' },
    ],
    contraindications: ['Breast or prostate cancer', 'Polycythemia (Hct >54%)', 'Severe heart failure', 'Pregnancy or women of childbearing potential'],
    contraindicationsAr: ['سرطان الثدي أو البروستات', 'كثرة الحمر (>54%)', 'فشل قلب شديد', 'الحمل أو النساء في سن الإنجاب'],
    monitoringRequired: ['Hematocrit', 'PSA', 'Testosterone levels', 'Lipid profile', 'Liver function'],
    storageConditions: 'Store at 20-25°C, protect from light',
  },

  // ── 4. Contraceptives ──
  {
    id: 'FRM-0654', genericName: 'Levonorgestrel', genericNameAr: 'ليفونورجيستريل',
    brandNames: ['Plan B', 'Mirena', 'Postinor'], sfda_registration: 'SFDA-2024-CON-654',
    atcCode: 'G03AC03', atcCategory: 'Progestogens',
    therapeuticClass: 'Progestogen Contraceptive', therapeuticClassAr: 'موانع حمل بروجستوجينية',
    formularyStatus: 'formulary',
    route: ['oral', 'intrauterine'], forms: [
      { form: 'Tablet', strength: '1.5 mg (emergency)', unitPrice: 12.0, inStock: true },
      { form: 'Tablet', strength: '0.03 mg', unitPrice: 1.5, inStock: true },
      { form: 'Intrauterine system', strength: '52 mg (Mirena)', unitPrice: 450.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Norgestrel'],
    interactions: [
      { interactsWith: 'Carbamazepine', severity: 'major', mechanism: 'CYP3A4 induction reduces progestogen levels', clinicalEffect: 'Contraceptive failure', clinicalEffectAr: 'فشل منع الحمل', management: 'Use non-hormonal contraception or IUD', managementAr: 'استخدام وسيلة غير هرمونية أو لولب' },
    ],
    contraindications: ['Known or suspected pregnancy', 'Unexplained vaginal bleeding', 'Breast cancer', 'Severe hepatic disease'],
    contraindicationsAr: ['حمل معروف أو مشتبه', 'نزيف مهبلي غير مبرر', 'سرطان الثدي', 'مرض كبدي شديد'],
    monitoringRequired: ['Blood pressure', 'Menstrual pattern'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0655', genericName: 'Ethinylestradiol/Levonorgestrel', genericNameAr: 'إيثينيل إستراديول/ليفونورجيستريل',
    brandNames: ['Microgynon', 'Levlen', 'Alesse'], sfda_registration: 'SFDA-2024-CON-655',
    atcCode: 'G03AA07', atcCategory: 'Progestogens and estrogens, fixed combinations',
    therapeuticClass: 'Combined Oral Contraceptive', therapeuticClassAr: 'موانع حمل فموية مركبة',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '30 mcg / 150 mcg', unitPrice: 1.2, inStock: true },
      { form: 'Tablet', strength: '20 mcg / 100 mcg', unitPrice: 1.5, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ethinylestradiol/Desogestrel'],
    blackBoxWarning: 'Cigarette smoking increases risk of serious cardiovascular events; do not use in women >35 who smoke',
    blackBoxWarningAr: 'التدخين يزيد خطر الأحداث القلبية الوعائية الخطيرة؛ لا يستخدم للنساء فوق 35 المدخنات',
    interactions: [
      { interactsWith: 'Rifampin', severity: 'major', mechanism: 'CYP3A4 induction markedly reduces hormone levels', clinicalEffect: 'Contraceptive failure', clinicalEffectAr: 'فشل منع الحمل', management: 'Use alternative non-hormonal contraception', managementAr: 'استخدام وسيلة منع حمل غير هرمونية' },
      { interactsWith: 'Lamotrigine', severity: 'major', mechanism: 'Estrogen induces lamotrigine glucuronidation', clinicalEffect: 'Reduced lamotrigine levels; seizure risk', clinicalEffectAr: 'انخفاض مستويات لاموتريجين؛ خطر نوبات', management: 'Adjust lamotrigine dose; consider progestin-only method', managementAr: 'تعديل جرعة لاموتريجين؛ النظر في وسيلة بروجستين فقط' },
    ],
    contraindications: ['Smokers >35 years', 'History of VTE', 'Migraine with aura', 'Breast cancer', 'Active liver disease'],
    contraindicationsAr: ['مدخنات فوق 35 سنة', 'تاريخ جلطة وريدية عميقة', 'صداع نصفي مع هالة', 'سرطان الثدي', 'مرض كبدي نشط'],
    monitoringRequired: ['Blood pressure', 'Lipid profile', 'Liver function if symptomatic'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0656', genericName: 'Desogestrel', genericNameAr: 'ديسوجيستريل',
    brandNames: ['Cerazette', 'Cerelle'], sfda_registration: 'SFDA-2024-CON-656',
    atcCode: 'G03AC09', atcCategory: 'Progestogens',
    therapeuticClass: 'Progestogen-only Contraceptive', therapeuticClassAr: 'موانع حمل بروجستوجين فقط',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '75 mcg', unitPrice: 2.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Drospirenone'],
    interactions: [
      { interactsWith: 'Phenytoin', severity: 'major', mechanism: 'Enzyme induction reduces progestogen levels', clinicalEffect: 'Contraceptive failure', clinicalEffectAr: 'فشل منع الحمل', management: 'Use non-hormonal contraception', managementAr: 'استخدام وسيلة غير هرمونية' },
    ],
    contraindications: ['Active VTE', 'Severe hepatic disease', 'Breast cancer', 'Unexplained vaginal bleeding'],
    contraindicationsAr: ['جلطة وريدية نشطة', 'مرض كبدي شديد', 'سرطان الثدي', 'نزيف مهبلي غير مبرر'],
    monitoringRequired: ['Blood pressure', 'Menstrual pattern'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0657', genericName: 'Etonogestrel Implant', genericNameAr: 'غرسة إيتونوجيستريل',
    brandNames: ['Implanon NXT', 'Nexplanon'], sfda_registration: 'SFDA-2024-CON-657',
    atcCode: 'G03AC08', atcCategory: 'Progestogens',
    therapeuticClass: 'Long-acting Contraceptive', therapeuticClassAr: 'موانع حمل طويلة المفعول',
    formularyStatus: 'formulary',
    route: ['subdermal'], forms: [
      { form: 'Subdermal implant', strength: '68 mg (3 years)', unitPrice: 650.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'Efavirenz', severity: 'major', mechanism: 'CYP3A4 induction reduces etonogestrel levels', clinicalEffect: 'Reduced contraceptive efficacy', clinicalEffectAr: 'انخفاض فعالية منع الحمل', management: 'Use additional barrier method or IUD', managementAr: 'استخدام وسيلة حاجز إضافية أو لولب' },
    ],
    contraindications: ['Pregnancy', 'Active thromboembolic disease', 'Breast cancer', 'Hepatic tumors'],
    contraindicationsAr: ['الحمل', 'مرض انصمام خثاري نشط', 'سرطان الثدي', 'أورام الكبد'],
    monitoringRequired: ['Insertion site', 'Menstrual pattern', 'Palpability of implant'],
    storageConditions: 'Store at 2-30°C, keep in original packaging',
  },
  {
    id: 'FRM-0658', genericName: 'Copper Intrauterine Device', genericNameAr: 'جهاز رحمي نحاسي',
    brandNames: ['Paragard', 'Multiload Cu375'], sfda_registration: 'SFDA-2024-CON-658',
    atcCode: 'G02BA02', atcCategory: 'Intrauterine contraceptives',
    therapeuticClass: 'Non-hormonal Contraceptive', therapeuticClassAr: 'موانع حمل غير هرمونية',
    formularyStatus: 'formulary',
    route: ['intrauterine'], forms: [
      { form: 'Intrauterine device', strength: '380 mm² copper', unitPrice: 120.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'X', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Pregnancy', 'PID or STI at time of insertion', 'Wilson disease', 'Uterine cavity distortion', 'Copper allergy'],
    contraindicationsAr: ['الحمل', 'التهاب الحوض أو عدوى منقولة جنسياً عند الإدخال', 'مرض ويلسون', 'تشوه تجويف الرحم', 'حساسية النحاس'],
    monitoringRequired: ['String check after menses', 'Ultrasound if strings not visible'],
    storageConditions: 'Store at room temperature in sterile packaging',
  },

  // ── 5. Fertility Agents ──
  {
    id: 'FRM-0659', genericName: 'Clomiphene Citrate', genericNameAr: 'كلوميفين سيترات',
    brandNames: ['Clomid', 'Serophene'], sfda_registration: 'SFDA-2024-FER-659',
    atcCode: 'G03GB02', atcCategory: 'Ovulation stimulants, synthetic',
    therapeuticClass: 'Ovulation Inducer', therapeuticClassAr: 'محفز الإباضة',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '50 mg', unitPrice: 8.0, inStock: true },
    ],
    maxDailyDose: 150, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Clomipramine'],
    interactions: [
      { interactsWith: 'Estrogen', severity: 'moderate', mechanism: 'Estrogens may counteract anti-estrogenic action of clomiphene', clinicalEffect: 'Reduced ovulation induction efficacy', clinicalEffectAr: 'انخفاض فعالية تحفيز الإباضة', management: 'Avoid concurrent estrogen therapy', managementAr: 'تجنب العلاج المتزامن بالإستروجين' },
    ],
    contraindications: ['Pregnancy', 'Ovarian cysts (not PCOS)', 'Uncontrolled thyroid/adrenal dysfunction', 'Hepatic disease'],
    contraindicationsAr: ['الحمل', 'أكياس المبيض (غير المتعدد)', 'خلل الغدة الدرقية/الكظرية غير المسيطر عليه', 'مرض كبدي'],
    monitoringRequired: ['Follicular ultrasound', 'Serum estradiol', 'Endometrial thickness', 'Visual symptoms'],
    storageConditions: 'Store at 15-25°C, protect from light and moisture',
  },
  {
    id: 'FRM-0660', genericName: 'Letrozole (Fertility)', genericNameAr: 'ليتروزول (خصوبة)',
    brandNames: ['Femara'], sfda_registration: 'SFDA-2024-FER-660',
    atcCode: 'L02BG04', atcCategory: 'Aromatase inhibitors',
    therapeuticClass: 'Aromatase Inhibitor (Off-label Fertility)', therapeuticClassAr: 'مثبط أروماتيز (خصوبة)',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Reproductive endocrinologist approval for ovulation induction',
    restrictionCriteriaAr: 'موافقة أخصائي الغدد الصماء التناسلية لتحفيز الإباضة',
    approverRole: 'reproductive_endocrinologist',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '2.5 mg', unitPrice: 6.0, inStock: true },
    ],
    maxDailyDose: 7.5, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Levetiracetam'],
    interactions: [
      { interactsWith: 'Tamoxifen', severity: 'major', mechanism: 'Tamoxifen as CYP inhibitor reduces letrozole metabolism', clinicalEffect: 'Altered drug levels and efficacy', clinicalEffectAr: 'تغير مستويات الدواء والفعالية', management: 'Avoid concurrent use', managementAr: 'تجنب الاستخدام المتزامن' },
    ],
    contraindications: ['Pregnancy', 'Premenopausal (for oncology use)', 'Severe hepatic impairment'],
    contraindicationsAr: ['الحمل', 'ما قبل انقطاع الطمث (للاستخدام الأورامي)', 'قصور كبدي شديد'],
    monitoringRequired: ['Follicular monitoring (ultrasound)', 'Serum estradiol', 'Pregnancy test before each cycle'],
    storageConditions: 'Store at 25°C',
  },
  {
    id: 'FRM-0661', genericName: 'Follitropin alfa (FSH)', genericNameAr: 'فوليتروبين ألفا (FSH)',
    brandNames: ['Gonal-F', 'Bemfola'], sfda_registration: 'SFDA-2024-FER-661',
    atcCode: 'G03GA05', atcCategory: 'Gonadotropins',
    therapeuticClass: 'Gonadotropin', therapeuticClassAr: 'موجهة الغدد التناسلية',
    formularyStatus: 'restricted',
    restrictionCriteria: 'IVF/fertility specialist only; requires ultrasound monitoring capability',
    restrictionCriteriaAr: 'أخصائي أطفال أنابيب/خصوبة فقط؛ يتطلب إمكانية المراقبة بالموجات فوق الصوتية',
    approverRole: 'reproductive_endocrinologist',
    route: ['subcutaneous'], forms: [
      { form: 'Pen injector', strength: '300 IU/0.5mL', unitPrice: 180.0, inStock: true },
      { form: 'Pen injector', strength: '450 IU/0.75mL', unitPrice: 260.0, inStock: true },
      { form: 'Pen injector', strength: '900 IU/1.5mL', unitPrice: 480.0, inStock: false },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Follitropin beta'],
    blackBoxWarning: 'Ovarian hyperstimulation syndrome (OHSS) may be life-threatening; strict monitoring required',
    blackBoxWarningAr: 'متلازمة فرط تحفيز المبيض قد تكون مهددة للحياة؛ مراقبة صارمة مطلوبة',
    interactions: [
      { interactsWith: 'Clomiphene', severity: 'moderate', mechanism: 'Additive ovarian stimulation', clinicalEffect: 'Increased OHSS risk', clinicalEffectAr: 'زيادة خطر فرط تحفيز المبيض', management: 'Use lower FSH doses when combined', managementAr: 'استخدام جرعات FSH أقل عند الجمع' },
    ],
    contraindications: ['Primary ovarian failure', 'Uncontrolled thyroid/adrenal insufficiency', 'Ovarian cysts not due to PCOS', 'Sex hormone-dependent tumors', 'Pregnancy'],
    contraindicationsAr: ['فشل المبيض الأولي', 'قصور الغدة الدرقية/الكظرية غير المسيطر عليه', 'أكياس المبيض غير ناتجة عن المتعدد', 'أورام معتمدة على الهرمونات الجنسية', 'الحمل'],
    monitoringRequired: ['Serial transvaginal ultrasound', 'Serum estradiol levels', 'OHSS symptoms', 'Body weight'],
    storageConditions: 'Store at 2-8°C, do not freeze; may store at ≤25°C for up to 3 months',
  },
  {
    id: 'FRM-0662', genericName: 'Choriogonadotropin alfa (hCG)', genericNameAr: 'كوريوغونادوتروبين ألفا (hCG)',
    brandNames: ['Ovitrelle', 'Pregnyl'], sfda_registration: 'SFDA-2024-FER-662',
    atcCode: 'G03GA08', atcCategory: 'Gonadotropins',
    therapeuticClass: 'Gonadotropin', therapeuticClassAr: 'موجهة الغدد التناسلية',
    formularyStatus: 'restricted',
    restrictionCriteria: 'IVF trigger shot or documented hypogonadism only',
    restrictionCriteriaAr: 'حقنة تحفيز أطفال الأنابيب أو قصور الغدد التناسلية الموثق فقط',
    approverRole: 'reproductive_endocrinologist',
    route: ['subcutaneous', 'intramuscular'], forms: [
      { form: 'Pre-filled syringe', strength: '250 mcg (Ovitrelle)', unitPrice: 120.0, inStock: true },
      { form: 'Injection', strength: '5000 IU (Pregnyl)', unitPrice: 45.0, inStock: true },
      { form: 'Injection', strength: '10000 IU (Pregnyl)', unitPrice: 75.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['FSH', 'LH'],
    interactions: [
      { interactsWith: 'Gonadotropins (FSH)', severity: 'moderate', mechanism: 'Additive ovarian stimulation when used as trigger', clinicalEffect: 'OHSS risk if timed incorrectly', clinicalEffectAr: 'خطر فرط تحفيز المبيض إذا كان التوقيت غير صحيح', management: 'Trigger only when follicles reach appropriate size', managementAr: 'التحفيز فقط عند وصول الجريبات للحجم المناسب' },
    ],
    contraindications: ['Ovarian hyperstimulation syndrome', 'Precocious puberty', 'Androgen-dependent neoplasia', 'Pregnancy (except luteal support)'],
    contraindicationsAr: ['متلازمة فرط تحفيز المبيض', 'البلوغ المبكر', 'أورام معتمدة على الأندروجين', 'الحمل (باستثناء دعم الطور الأصفري)'],
    monitoringRequired: ['Ultrasound follicle size', 'Serum estradiol', 'OHSS symptoms post-trigger'],
    storageConditions: 'Store at 2-8°C, protect from light',
  },

  // ── 6. GnRH Agents ──
  {
    id: 'FRM-0663', genericName: 'Leuprolide Acetate', genericNameAr: 'ليوبروليد أسيتات',
    brandNames: ['Lupron', 'Eligard', 'Lucrin'], sfda_registration: 'SFDA-2024-GNR-663',
    atcCode: 'L02AE02', atcCategory: 'GnRH analogues',
    therapeuticClass: 'GnRH Agonist', therapeuticClassAr: 'ناهض GnRH',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Oncologist, endocrinologist, or reproductive specialist approval',
    restrictionCriteriaAr: 'موافقة أخصائي أورام أو غدد صماء أو تناسلية',
    approverRole: 'specialist',
    route: ['subcutaneous', 'intramuscular'], forms: [
      { form: 'Injection', strength: '3.75 mg (monthly)', unitPrice: 350.0, inStock: true },
      { form: 'Injection', strength: '11.25 mg (3-month)', unitPrice: 950.0, inStock: true },
      { form: 'Injection', strength: '22.5 mg (3-month depot)', unitPrice: 1200.0, inStock: false },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Levalbuterol'],
    blackBoxWarning: 'Initial testosterone flare may worsen symptoms in prostate cancer; use with antiandrogen for first weeks',
    blackBoxWarningAr: 'اشتعال التستوستيرون الأولي قد يفاقم أعراض سرطان البروستات؛ استخدام مع مضاد أندروجين في الأسابيع الأولى',
    interactions: [
      { interactsWith: 'QT-prolonging drugs', severity: 'moderate', mechanism: 'Androgen deprivation therapy may prolong QT interval', clinicalEffect: 'Increased risk of cardiac arrhythmia', clinicalEffectAr: 'زيادة خطر عدم انتظام ضربات القلب', management: 'ECG monitoring; avoid other QT-prolonging agents', managementAr: 'مراقبة ECG؛ تجنب العوامل الأخرى المطيلة لـ QT' },
    ],
    contraindications: ['Pregnancy', 'Undiagnosed vaginal bleeding', 'Hypersensitivity to GnRH analogs'],
    contraindicationsAr: ['الحمل', 'نزيف مهبلي غير مشخص', 'فرط الحساسية لنظائر GnRH'],
    monitoringRequired: ['Testosterone/estradiol levels', 'Bone density (long-term)', 'PSA (prostate cancer)', 'Hot flash diary', 'Glucose/lipids'],
    storageConditions: 'Store at 20-25°C; depot form at 2-8°C',
  },
  {
    id: 'FRM-0664', genericName: 'Goserelin Acetate', genericNameAr: 'غوسيريلين أسيتات',
    brandNames: ['Zoladex'], sfda_registration: 'SFDA-2024-GNR-664',
    atcCode: 'L02AE03', atcCategory: 'GnRH analogues',
    therapeuticClass: 'GnRH Agonist', therapeuticClassAr: 'ناهض GnRH',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Oncologist or reproductive specialist approval required',
    restrictionCriteriaAr: 'موافقة أخصائي أورام أو تناسلية مطلوبة',
    approverRole: 'specialist',
    route: ['subcutaneous'], forms: [
      { form: 'Implant', strength: '3.6 mg (monthly)', unitPrice: 380.0, inStock: true },
      { form: 'Implant', strength: '10.8 mg (3-month)', unitPrice: 1050.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Granisetron'],
    interactions: [
      { interactsWith: 'QT-prolonging drugs', severity: 'moderate', mechanism: 'Additive QT prolongation with androgen deprivation', clinicalEffect: 'Arrhythmia risk', clinicalEffectAr: 'خطر عدم انتظام ضربات القلب', management: 'Baseline and periodic ECG monitoring', managementAr: 'مراقبة ECG أساسية ودورية' },
    ],
    contraindications: ['Pregnancy', 'Breastfeeding', 'Hypersensitivity to GnRH analogs'],
    contraindicationsAr: ['الحمل', 'الرضاعة', 'فرط الحساسية لنظائر GnRH'],
    monitoringRequired: ['Hormone levels', 'Bone density', 'PSA', 'Blood glucose', 'Lipid profile'],
    storageConditions: 'Store below 25°C, do not freeze',
  },
  {
    id: 'FRM-0665', genericName: 'Cetrorelix', genericNameAr: 'سيتروريليكس',
    brandNames: ['Cetrotide'], sfda_registration: 'SFDA-2024-GNR-665',
    atcCode: 'H01CC02', atcCategory: 'Anti-gonadotropin-releasing hormones',
    therapeuticClass: 'GnRH Antagonist', therapeuticClassAr: 'مضاد GnRH',
    formularyStatus: 'restricted',
    restrictionCriteria: 'IVF cycle management only; reproductive specialist',
    restrictionCriteriaAr: 'إدارة دورة أطفال الأنابيب فقط؛ أخصائي تناسلية',
    approverRole: 'reproductive_endocrinologist',
    route: ['subcutaneous'], forms: [
      { form: 'Injection', strength: '0.25 mg', unitPrice: 95.0, inStock: true },
      { form: 'Injection', strength: '3 mg', unitPrice: 280.0, inStock: false },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ganirelix'],
    interactions: [
      { interactsWith: 'Gonadotropins', severity: 'minor', mechanism: 'Intended co-administration in IVF protocols', clinicalEffect: 'Prevents premature LH surge', clinicalEffectAr: 'يمنع ارتفاع LH المبكر', management: 'Use per IVF protocol timing', managementAr: 'الاستخدام وفق توقيت بروتوكول أطفال الأنابيب' },
    ],
    contraindications: ['Pregnancy', 'Severe renal impairment', 'Hypersensitivity to GnRH analogs or mannitol'],
    contraindicationsAr: ['الحمل', 'قصور كلوي شديد', 'فرط الحساسية لنظائر GnRH أو المانيتول'],
    monitoringRequired: ['Follicular ultrasound', 'Estradiol levels', 'LH levels'],
    storageConditions: 'Store at 2-8°C, protect from light',
  },

  // ── 7. Anti-androgens ──
  {
    id: 'FRM-0666', genericName: 'Finasteride', genericNameAr: 'فيناسترايد',
    brandNames: ['Proscar', 'Propecia'], sfda_registration: 'SFDA-2024-AND-666',
    atcCode: 'G04CB01', atcCategory: '5-alpha reductase inhibitors',
    therapeuticClass: '5-alpha Reductase Inhibitor', therapeuticClassAr: 'مثبط 5-ألفا ريدكتيز',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '1 mg', unitPrice: 3.0, inStock: true },
      { form: 'Tablet', strength: '5 mg', unitPrice: 4.0, inStock: true },
    ],
    maxDailyDose: 5, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Furosemide'],
    blackBoxWarning: 'Women of childbearing potential must not handle crushed or broken tablets due to risk of birth defects',
    blackBoxWarningAr: 'يجب على النساء في سن الإنجاب عدم لمس الأقراص المكسورة أو المسحوقة بسبب خطر العيوب الخلقية',
    interactions: [
      { interactsWith: 'Testosterone', severity: 'moderate', mechanism: 'Opposing pharmacologic effects', clinicalEffect: 'May reduce therapeutic benefit of finasteride', clinicalEffectAr: 'قد يقلل الفائدة العلاجية للفيناسترايد', management: 'Assess clinical rationale for combination', managementAr: 'تقييم المبرر السريري للجمع' },
    ],
    contraindications: ['Pregnancy or women of childbearing potential', 'Pediatric patients', 'Hypersensitivity to 5-ARI'],
    contraindicationsAr: ['الحمل أو النساء في سن الإنجاب', 'مرضى الأطفال', 'فرط الحساسية لمثبطات 5-ألفا ريدكتيز'],
    monitoringRequired: ['PSA (note: reduces PSA by ~50%)', 'Digital rectal exam', 'Sexual function assessment'],
    storageConditions: 'Store at 15-30°C, protect from light',
  },
  {
    id: 'FRM-0667', genericName: 'Dutasteride', genericNameAr: 'دوتاستيرايد',
    brandNames: ['Avodart'], sfda_registration: 'SFDA-2024-AND-667',
    atcCode: 'G04CB02', atcCategory: '5-alpha reductase inhibitors',
    therapeuticClass: '5-alpha Reductase Inhibitor', therapeuticClassAr: 'مثبط 5-ألفا ريدكتيز',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Capsule', strength: '0.5 mg', unitPrice: 5.0, inStock: true },
    ],
    maxDailyDose: 0.5, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Finasteride'],
    interactions: [
      { interactsWith: 'CYP3A4 inhibitors (Ritonavir)', severity: 'moderate', mechanism: 'CYP3A4 inhibition increases dutasteride levels', clinicalEffect: 'Increased dutasteride exposure and side effects', clinicalEffectAr: 'زيادة التعرض للدوتاستيرايد وآثاره الجانبية', management: 'Monitor for adverse effects; no dose adjustment usually needed', managementAr: 'مراقبة الآثار الجانبية؛ عادة لا يلزم تعديل الجرعة' },
    ],
    contraindications: ['Pregnancy or women of childbearing potential', 'Severe hepatic impairment', 'Pediatric patients'],
    contraindicationsAr: ['الحمل أو النساء في سن الإنجاب', 'قصور كبدي شديد', 'مرضى الأطفال'],
    monitoringRequired: ['PSA (reduces by ~50%)', 'Hepatic function', 'Sexual function'],
    storageConditions: 'Store at 25°C; capsules may soften if stored above 30°C',
  },
  {
    id: 'FRM-0668', genericName: 'Spironolactone (Hirsutism)', genericNameAr: 'سبيرونولاكتون (الشعرانية)',
    brandNames: ['Aldactone'], sfda_registration: 'SFDA-2024-AND-668',
    atcCode: 'C03DA01', atcCategory: 'Aldosterone antagonists',
    therapeuticClass: 'Anti-androgen / Aldosterone Antagonist', therapeuticClassAr: 'مضاد أندروجين / مضاد الألدوستيرون',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '25 mg', unitPrice: 1.0, inStock: true },
      { form: 'Tablet', strength: '50 mg', unitPrice: 1.5, inStock: true },
      { form: 'Tablet', strength: '100 mg', unitPrice: 2.5, inStock: true },
    ],
    maxDailyDose: 200, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Eplerenone'],
    blackBoxWarning: 'Shown to be tumorigenic in chronic toxicity studies in rats; use only when necessary',
    blackBoxWarningAr: 'ثبت أنه مسبب للأورام في دراسات السمية المزمنة على الفئران؛ يستخدم عند الضرورة فقط',
    interactions: [
      { interactsWith: 'ACE inhibitors', severity: 'major', mechanism: 'Both agents increase potassium retention', clinicalEffect: 'Life-threatening hyperkalemia', clinicalEffectAr: 'ارتفاع بوتاسيوم الدم المهدد للحياة', management: 'Monitor potassium closely; avoid in severe renal impairment', managementAr: 'مراقبة البوتاسيوم عن كثب؛ تجنب في القصور الكلوي الشديد' },
      { interactsWith: 'Potassium supplements', severity: 'major', mechanism: 'Additive potassium retention', clinicalEffect: 'Hyperkalemia', clinicalEffectAr: 'ارتفاع بوتاسيوم الدم', management: 'Avoid concomitant potassium supplementation', managementAr: 'تجنب مكملات البوتاسيوم المتزامنة' },
    ],
    contraindications: ['Hyperkalemia', 'Addison disease', 'Anuria', 'Severe renal impairment (eGFR <30)', 'Pregnancy'],
    contraindicationsAr: ['ارتفاع بوتاسيوم الدم', 'مرض أديسون', 'انقطاع البول', 'قصور كلوي شديد', 'الحمل'],
    monitoringRequired: ['Serum potassium', 'Renal function', 'Blood pressure', 'Menstrual regularity'],
    storageConditions: 'Store at 25°C',
  },

  // ── 8. Bone Metabolism ──
  {
    id: 'FRM-0669', genericName: 'Alendronate Sodium', genericNameAr: 'أليندرونات الصوديوم',
    brandNames: ['Fosamax', 'Fosamax Plus D'], sfda_registration: 'SFDA-2024-BON-669',
    atcCode: 'M05BA04', atcCategory: 'Bisphosphonates',
    therapeuticClass: 'Bisphosphonate', therapeuticClassAr: 'بيسفوسفونات',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '10 mg (daily)', unitPrice: 2.0, inStock: true },
      { form: 'Tablet', strength: '70 mg (weekly)', unitPrice: 8.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Risedronate'],
    blackBoxWarning: 'Risk of osteonecrosis of the jaw (ONJ), particularly with dental procedures; atypical femoral fractures with prolonged use',
    blackBoxWarningAr: 'خطر تنخر عظم الفك خاصة مع إجراءات الأسنان؛ كسور الفخذ اللانمطية مع الاستخدام المطول',
    interactions: [
      { interactsWith: 'Calcium supplements', severity: 'moderate', mechanism: 'Calcium chelates bisphosphonate reducing absorption', clinicalEffect: 'Reduced alendronate efficacy', clinicalEffectAr: 'انخفاض فعالية الأليندرونات', management: 'Separate by at least 30 minutes; take alendronate fasting', managementAr: 'الفصل بـ 30 دقيقة على الأقل؛ تناول الأليندرونات على معدة فارغة' },
      { interactsWith: 'NSAIDs', severity: 'moderate', mechanism: 'Additive GI mucosal irritation', clinicalEffect: 'Increased risk of GI ulceration', clinicalEffectAr: 'زيادة خطر التقرح المعدي المعوي', management: 'Use with caution; monitor for GI symptoms', managementAr: 'استخدام بحذر؛ مراقبة أعراض الجهاز الهضمي' },
    ],
    contraindications: ['Esophageal abnormalities', 'Inability to stand/sit upright for 30 min', 'Hypocalcemia', 'CrCl <35 mL/min'],
    contraindicationsAr: ['تشوهات المريء', 'عدم القدرة على الجلوس منتصباً لمدة 30 دقيقة', 'نقص كالسيوم الدم', 'تصفية الكرياتينين أقل من 35'],
    monitoringRequired: ['Serum calcium', 'Vitamin D level', 'Bone density (DEXA) every 2 years', 'Renal function', 'Dental exam'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0670', genericName: 'Risedronate Sodium', genericNameAr: 'ريزيدرونات الصوديوم',
    brandNames: ['Actonel', 'Atelvia'], sfda_registration: 'SFDA-2024-BON-670',
    atcCode: 'M05BA07', atcCategory: 'Bisphosphonates',
    therapeuticClass: 'Bisphosphonate', therapeuticClassAr: 'بيسفوسفونات',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '5 mg (daily)', unitPrice: 2.5, inStock: true },
      { form: 'Tablet', strength: '35 mg (weekly)', unitPrice: 10.0, inStock: true },
      { form: 'Tablet', strength: '150 mg (monthly)', unitPrice: 35.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Alendronate'],
    interactions: [
      { interactsWith: 'Antacids (calcium, magnesium)', severity: 'moderate', mechanism: 'Polyvalent cations chelate bisphosphonate', clinicalEffect: 'Reduced risedronate absorption', clinicalEffectAr: 'انخفاض امتصاص الريزيدرونات', management: 'Take risedronate fasting; separate antacids by 30+ minutes', managementAr: 'تناول الريزيدرونات على معدة فارغة؛ فصل مضادات الحموضة بـ 30 دقيقة' },
    ],
    contraindications: ['Esophageal abnormalities', 'Inability to stand upright for 30 min', 'Hypocalcemia', 'CrCl <30 mL/min'],
    contraindicationsAr: ['تشوهات المريء', 'عدم القدرة على الوقوف لمدة 30 دقيقة', 'نقص كالسيوم الدم', 'تصفية الكرياتينين أقل من 30'],
    monitoringRequired: ['Serum calcium', 'Vitamin D', 'Bone density', 'Renal function'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0671', genericName: 'Zoledronic Acid', genericNameAr: 'حمض الزوليدرونيك',
    brandNames: ['Zometa', 'Aclasta', 'Reclast'], sfda_registration: 'SFDA-2024-BON-671',
    atcCode: 'M05BA08', atcCategory: 'Bisphosphonates',
    therapeuticClass: 'Bisphosphonate (IV)', therapeuticClassAr: 'بيسفوسفونات (وريدي)',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Specialist approval; adequate renal function (CrCl >35); dental clearance',
    restrictionCriteriaAr: 'موافقة الأخصائي؛ وظائف كلوية كافية؛ تقييم أسنان',
    approverRole: 'specialist',
    route: ['intravenous'], forms: [
      { form: 'Infusion', strength: '4 mg/5mL (oncology)', unitPrice: 180.0, inStock: true },
      { form: 'Infusion', strength: '5 mg/100mL (osteoporosis)', unitPrice: 350.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Zolmitriptan'],
    blackBoxWarning: 'Risk of renal impairment; osteonecrosis of jaw; atypical femoral fractures; infuse over no less than 15 minutes',
    blackBoxWarningAr: 'خطر القصور الكلوي؛ تنخر عظم الفك؛ كسور فخذية لانمطية؛ التسريب لا يقل عن 15 دقيقة',
    interactions: [
      { interactsWith: 'Aminoglycosides', severity: 'major', mechanism: 'Additive hypocalcemic effect', clinicalEffect: 'Prolonged hypocalcemia', clinicalEffectAr: 'نقص كالسيوم مطول', management: 'Monitor calcium closely; supplement as needed', managementAr: 'مراقبة الكالسيوم عن كثب؛ التكميل حسب الحاجة' },
      { interactsWith: 'Nephrotoxic drugs', severity: 'major', mechanism: 'Additive renal toxicity', clinicalEffect: 'Increased risk of acute kidney injury', clinicalEffectAr: 'زيادة خطر الإصابة الكلوية الحادة', management: 'Ensure adequate hydration; check CrCl before each dose', managementAr: 'ضمان الترطيب الكافي؛ فحص تصفية الكرياتينين قبل كل جرعة' },
    ],
    contraindications: ['CrCl <35 mL/min', 'Hypocalcemia', 'Pregnancy', 'Breastfeeding'],
    contraindicationsAr: ['تصفية الكرياتينين أقل من 35', 'نقص كالسيوم الدم', 'الحمل', 'الرضاعة'],
    monitoringRequired: ['Serum creatinine before each dose', 'Serum calcium/magnesium/phosphate', 'Dental exam', 'Bone density'],
    storageConditions: 'Store at 25°C; diluted solution stable for 24 hours at 2-8°C',
  },
  {
    id: 'FRM-0672', genericName: 'Teriparatide', genericNameAr: 'تيريباراتيد',
    brandNames: ['Forteo', 'Teribone'], sfda_registration: 'SFDA-2024-BON-672',
    atcCode: 'H05AA02', atcCategory: 'Parathyroid hormones',
    therapeuticClass: 'Parathyroid Hormone Analog', therapeuticClassAr: 'نظير هرمون الغدة جار الدرقية',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Failed bisphosphonate therapy or very high fracture risk; endocrinologist/rheumatologist',
    restrictionCriteriaAr: 'فشل علاج البيسفوسفونات أو خطر كسور مرتفع جداً؛ أخصائي غدد صماء/روماتيزم',
    approverRole: 'specialist',
    route: ['subcutaneous'], forms: [
      { form: 'Pen injector', strength: '250 mcg/mL (600 mcg/2.4mL)', unitPrice: 850.0, inStock: true },
    ],
    maxDailyDose: 20, maxDailyDoseUnit: 'mcg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: [],
    blackBoxWarning: 'Caused osteosarcoma in rats; do not use >2 years cumulative; avoid in patients at increased osteosarcoma risk (Paget disease, unexplained elevated ALP, prior radiation to bone)',
    blackBoxWarningAr: 'سبب ساركوما عظمية في الفئران؛ لا يستخدم أكثر من سنتين تراكمياً؛ تجنب في المرضى المعرضين لخطر الساركوما العظمية',
    interactions: [
      { interactsWith: 'Digoxin', severity: 'moderate', mechanism: 'Teriparatide transiently raises serum calcium', clinicalEffect: 'Potential digoxin toxicity from hypercalcemia', clinicalEffectAr: 'سمية الديجوكسين المحتملة من فرط كالسيوم الدم', management: 'Monitor calcium and digoxin levels', managementAr: 'مراقبة مستويات الكالسيوم والديجوكسين' },
    ],
    contraindications: ['Paget disease of bone', 'Unexplained elevated ALP', 'Prior bone radiation', 'Open epiphyses (children)', 'Pre-existing hypercalcemia', 'Bone metastases'],
    contraindicationsAr: ['مرض باجيت العظمي', 'ارتفاع غير مبرر في الفوسفاتيز القلوي', 'إشعاع عظمي سابق', 'صفائح نمو مفتوحة', 'فرط كالسيوم موجود', 'نقائل عظمية'],
    monitoringRequired: ['Serum calcium', 'Uric acid', 'Orthostatic blood pressure', 'Bone density', 'Duration of therapy (max 2 years)'],
    storageConditions: 'Store at 2-8°C, do not freeze; in-use pen for up to 28 days at 2-8°C',
  },
  {
    id: 'FRM-0673', genericName: 'Raloxifene', genericNameAr: 'رالوكسيفين',
    brandNames: ['Evista'], sfda_registration: 'SFDA-2024-BON-673',
    atcCode: 'G03XC01', atcCategory: 'Selective estrogen receptor modulators',
    therapeuticClass: 'SERM', therapeuticClassAr: 'معدل مستقبلات الإستروجين الانتقائي',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '60 mg', unitPrice: 7.5, inStock: true },
    ],
    maxDailyDose: 60, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Tamoxifen'],
    blackBoxWarning: 'Increased risk of VTE and fatal stroke in postmenopausal women with coronary heart disease risk',
    blackBoxWarningAr: 'زيادة خطر الجلطة الوريدية والسكتة الدماغية المميتة عند النساء بعد انقطاع الطمث المعرضات لأمراض القلب',
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Raloxifene may decrease warfarin effect', clinicalEffect: 'Reduced anticoagulation', clinicalEffectAr: 'انخفاض تأثير مضاد التخثر', management: 'Monitor PT/INR when starting/stopping', managementAr: 'مراقبة PT/INR عند البدء أو التوقف' },
      { interactsWith: 'Cholestyramine', severity: 'major', mechanism: 'Reduces raloxifene absorption by 60%', clinicalEffect: 'Markedly reduced efficacy', clinicalEffectAr: 'انخفاض ملحوظ في الفعالية', management: 'Avoid concomitant administration', managementAr: 'تجنب الإعطاء المتزامن' },
    ],
    contraindications: ['Active or history of VTE', 'Pregnancy', 'Breastfeeding'],
    contraindicationsAr: ['جلطة وريدية نشطة أو سابقة', 'الحمل', 'الرضاعة'],
    monitoringRequired: ['Bone density', 'Lipid profile', 'VTE symptoms', 'Endometrial monitoring'],
    storageConditions: 'Store at 20-25°C',
  },

  // ── 9. Pituitary / Growth ──
  {
    id: 'FRM-0674', genericName: 'Somatropin', genericNameAr: 'سوماتروبين',
    brandNames: ['Genotropin', 'Norditropin', 'Humatrope'], sfda_registration: 'SFDA-2024-PIT-674',
    atcCode: 'H01AC01', atcCategory: 'Somatropin and agonists',
    therapeuticClass: 'Growth Hormone', therapeuticClassAr: 'هرمون النمو',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Confirmed GH deficiency by stimulation testing; pediatric endocrinologist approval',
    restrictionCriteriaAr: 'نقص هرمون النمو المؤكد باختبار التحفيز؛ موافقة أخصائي غدد صماء أطفال',
    approverRole: 'pediatric_endocrinologist',
    route: ['subcutaneous'], forms: [
      { form: 'Pen injector', strength: '5.3 mg (16 IU)', unitPrice: 450.0, inStock: true },
      { form: 'Pen injector', strength: '12 mg (36 IU)', unitPrice: 980.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Somatostatin', 'Octreotide'],
    interactions: [
      { interactsWith: 'Insulin/Oral hypoglycemics', severity: 'moderate', mechanism: 'GH antagonizes insulin action', clinicalEffect: 'Hyperglycemia; may need insulin dose increase', clinicalEffectAr: 'ارتفاع السكر؛ قد يحتاج لزيادة جرعة الأنسولين', management: 'Monitor glucose closely; adjust diabetes medications', managementAr: 'مراقبة الجلوكوز عن كثب؛ تعديل أدوية السكري' },
      { interactsWith: 'Glucocorticoids', severity: 'moderate', mechanism: 'Glucocorticoids inhibit GH growth-promoting effect', clinicalEffect: 'Reduced growth response', clinicalEffectAr: 'انخفاض استجابة النمو', management: 'Use lowest effective glucocorticoid dose', managementAr: 'استخدام أقل جرعة فعالة من الكورتيكوستيرويد' },
    ],
    contraindications: ['Active malignancy', 'Closed epiphyses (if for height)', 'Acute critical illness', 'Active proliferative diabetic retinopathy', 'Prader-Willi syndrome with severe obesity'],
    contraindicationsAr: ['ورم خبيث نشط', 'صفائح نمو مغلقة (إذا للطول)', 'مرض حرج حاد', 'اعتلال شبكية سكري تكاثري نشط', 'متلازمة برادر-ويلي مع سمنة شديدة'],
    monitoringRequired: ['IGF-1 levels', 'Growth velocity', 'Bone age annually', 'Thyroid function', 'Glucose/HbA1c', 'Scoliosis screening'],
    storageConditions: 'Store at 2-8°C, do not freeze; in-use pen up to 28 days at 2-8°C',
  },
  {
    id: 'FRM-0675', genericName: 'Desmopressin', genericNameAr: 'ديسموبريسين',
    brandNames: ['DDAVP', 'Minirin', 'Stimate'], sfda_registration: 'SFDA-2024-PIT-675',
    atcCode: 'H01BA02', atcCategory: 'Vasopressin analogues',
    therapeuticClass: 'Vasopressin Analog', therapeuticClassAr: 'نظير الفازوبريسين',
    formularyStatus: 'formulary',
    route: ['oral', 'intranasal', 'intravenous', 'subcutaneous'], forms: [
      { form: 'Tablet', strength: '0.1 mg', unitPrice: 5.0, inStock: true },
      { form: 'Tablet', strength: '0.2 mg', unitPrice: 7.0, inStock: true },
      { form: 'Nasal spray', strength: '10 mcg/spray', unitPrice: 65.0, inStock: true },
      { form: 'Injection', strength: '4 mcg/mL', unitPrice: 35.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Vasopressin'],
    interactions: [
      { interactsWith: 'Carbamazepine', severity: 'moderate', mechanism: 'Both can cause hyponatremia via SIADH-like effect', clinicalEffect: 'Severe hyponatremia risk', clinicalEffectAr: 'خطر نقص الصوديوم الشديد', management: 'Monitor serum sodium closely', managementAr: 'مراقبة صوديوم الدم عن كثب' },
    ],
    contraindications: ['Hyponatremia', 'Habitual polydipsia', 'Moderate to severe renal impairment', 'Von Willebrand type IIB'],
    contraindicationsAr: ['نقص صوديوم الدم', 'العطش المفرط المعتاد', 'قصور كلوي متوسط لشديد', 'فون ويلبراند نوع IIB'],
    monitoringRequired: ['Serum sodium', 'Urine osmolality', 'Fluid intake/output', 'Body weight'],
    storageConditions: 'Store at 2-8°C; tablets at 20-25°C',
  },
  {
    id: 'FRM-0676', genericName: 'Octreotide', genericNameAr: 'أوكتريوتيد',
    brandNames: ['Sandostatin', 'Sandostatin LAR'], sfda_registration: 'SFDA-2024-PIT-676',
    atcCode: 'H01CB02', atcCategory: 'Somatostatin analogues',
    therapeuticClass: 'Somatostatin Analog', therapeuticClassAr: 'نظير السوماتوستاتين',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Acromegaly, neuroendocrine tumors, or variceal bleeding; specialist only',
    restrictionCriteriaAr: 'تضخم الأطراف أو أورام الغدد الصم العصبية أو نزيف الدوالي؛ أخصائي فقط',
    approverRole: 'specialist',
    route: ['subcutaneous', 'intramuscular'], forms: [
      { form: 'Injection', strength: '0.1 mg/mL', unitPrice: 35.0, inStock: true },
      { form: 'Injection', strength: '0.5 mg/mL', unitPrice: 120.0, inStock: true },
      { form: 'LAR depot', strength: '20 mg', unitPrice: 2200.0, inStock: true },
      { form: 'LAR depot', strength: '30 mg', unitPrice: 2800.0, inStock: false },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Somatropin'],
    interactions: [
      { interactsWith: 'Insulin/Oral hypoglycemics', severity: 'moderate', mechanism: 'Octreotide suppresses insulin and glucagon; variable glucose effect', clinicalEffect: 'Hypo- or hyperglycemia', clinicalEffectAr: 'نقص أو ارتفاع السكر', management: 'Frequent glucose monitoring; adjust diabetes medications', managementAr: 'مراقبة الجلوكوز المتكررة؛ تعديل أدوية السكري' },
      { interactsWith: 'Cyclosporine', severity: 'moderate', mechanism: 'Reduced cyclosporine absorption', clinicalEffect: 'Decreased cyclosporine levels', clinicalEffectAr: 'انخفاض مستويات السيكلوسبورين', management: 'Monitor cyclosporine levels; adjust dose', managementAr: 'مراقبة مستويات السيكلوسبورين؛ تعديل الجرعة' },
    ],
    contraindications: ['Hypersensitivity to octreotide'],
    contraindicationsAr: ['فرط الحساسية للأوكتريوتيد'],
    monitoringRequired: ['GH/IGF-1 levels', 'Blood glucose', 'Thyroid function', 'Gallbladder ultrasound (q12 months)', 'Vitamin B12 (long-term)'],
    storageConditions: 'Store at 2-8°C, protect from light; LAR must be refrigerated',
  },

  // ── 10. Gout / Uric Acid ──
  {
    id: 'FRM-0677', genericName: 'Allopurinol', genericNameAr: 'ألوبيورينول',
    brandNames: ['Zyloprim', 'Zyloric'], sfda_registration: 'SFDA-2024-GOU-677',
    atcCode: 'M04AA01', atcCategory: 'Preparations inhibiting uric acid production',
    therapeuticClass: 'Xanthine Oxidase Inhibitor', therapeuticClassAr: 'مثبط زانثين أوكسيديز',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '100 mg', unitPrice: 0.5, inStock: true },
      { form: 'Tablet', strength: '300 mg', unitPrice: 1.2, inStock: true },
    ],
    maxDailyDose: 800, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Albuterol'],
    blackBoxWarning: 'Severe hypersensitivity reactions (SJS/TEN/DRESS) reported; HLA-B*5801 testing recommended in at-risk populations (Southeast Asian, African American)',
    blackBoxWarningAr: 'تفاعلات فرط حساسية شديدة (متلازمة ستيفنز-جونسون) مبلغ عنها؛ يوصى بفحص HLA-B*5801 في الفئات المعرضة',
    interactions: [
      { interactsWith: 'Azathioprine', severity: 'major', mechanism: 'Allopurinol inhibits xanthine oxidase, blocking azathioprine metabolism', clinicalEffect: 'Severe myelosuppression and pancytopenia', clinicalEffectAr: 'تثبيط نقي العظم الشديد وقلة الكريات الشاملة', management: 'Reduce azathioprine dose by 75%; monitor CBC frequently', managementAr: 'تقليل جرعة الآزاثيوبرين بنسبة 75%؛ مراقبة CBC بشكل متكرر' },
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Inhibition of warfarin metabolism', clinicalEffect: 'Enhanced anticoagulant effect', clinicalEffectAr: 'تعزيز تأثير مضاد التخثر', management: 'Monitor INR closely', managementAr: 'مراقبة INR عن كثب' },
    ],
    contraindications: ['HLA-B*5801 positive', 'Acute gout attack (do not initiate during flare)'],
    contraindicationsAr: ['إيجابي HLA-B*5801', 'نوبة نقرس حادة (لا تبدأ أثناء النوبة)'],
    monitoringRequired: ['Uric acid levels', 'Renal function', 'CBC', 'Liver function', 'HLA-B*5801 pre-screening'],
    storageConditions: 'Store at 15-25°C, protect from light and moisture',
  },
  {
    id: 'FRM-0678', genericName: 'Febuxostat', genericNameAr: 'فيبوكسوستات',
    brandNames: ['Uloric', 'Adenuric'], sfda_registration: 'SFDA-2024-GOU-678',
    atcCode: 'M04AA03', atcCategory: 'Preparations inhibiting uric acid production',
    therapeuticClass: 'Xanthine Oxidase Inhibitor', therapeuticClassAr: 'مثبط زانثين أوكسيديز',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Failed or intolerant to allopurinol; not first-line in cardiovascular disease',
    restrictionCriteriaAr: 'فشل أو عدم تحمل الألوبيورينول؛ ليس الخط الأول في أمراض القلب',
    approverRole: 'physician',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '40 mg', unitPrice: 6.0, inStock: true },
      { form: 'Tablet', strength: '80 mg', unitPrice: 8.0, inStock: true },
      { form: 'Tablet', strength: '120 mg', unitPrice: 12.0, inStock: true },
    ],
    maxDailyDose: 120, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Allopurinol'],
    blackBoxWarning: 'Higher cardiovascular death rate compared to allopurinol in CARES trial; use only after allopurinol failure',
    blackBoxWarningAr: 'معدل وفاة قلبية أعلى مقارنة بالألوبيورينول في دراسة CARES؛ يستخدم فقط بعد فشل الألوبيورينول',
    interactions: [
      { interactsWith: 'Azathioprine', severity: 'major', mechanism: 'Inhibits xanthine oxidase, blocking azathioprine metabolism', clinicalEffect: 'Severe myelosuppression', clinicalEffectAr: 'تثبيط نقي العظم الشديد', management: 'Contraindicated; do not combine', managementAr: 'موانع استعمال؛ لا تجمع بينهما' },
      { interactsWith: 'Theophylline', severity: 'moderate', mechanism: 'Febuxostat may increase theophylline levels', clinicalEffect: 'Theophylline toxicity risk', clinicalEffectAr: 'خطر سمية الثيوفيلين', management: 'Monitor theophylline levels when starting febuxostat', managementAr: 'مراقبة مستويات الثيوفيلين عند بدء الفيبوكسوستات' },
    ],
    contraindications: ['Concurrent azathioprine/mercaptopurine', 'Severe hepatic impairment'],
    contraindicationsAr: ['الاستخدام المتزامن مع آزاثيوبرين/ميركابتوبيورين', 'قصور كبدي شديد'],
    monitoringRequired: ['Uric acid levels', 'Liver function tests', 'Cardiovascular events monitoring', 'CBC'],
    storageConditions: 'Store at 20-25°C',
  },
  {
    id: 'FRM-0679', genericName: 'Colchicine', genericNameAr: 'كولشيسين',
    brandNames: ['Colcrys', 'Mitigare'], sfda_registration: 'SFDA-2024-GOU-679',
    atcCode: 'M04AC01', atcCategory: 'Preparations with no effect on uric acid metabolism',
    therapeuticClass: 'Anti-gout Agent', therapeuticClassAr: 'مضاد النقرس',
    formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Tablet', strength: '0.5 mg', unitPrice: 2.0, inStock: true },
      { form: 'Tablet', strength: '0.6 mg', unitPrice: 2.5, inStock: true },
    ],
    maxDailyDose: 1.8, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Cortisone'],
    blackBoxWarning: 'Fatal overdose reported; narrow therapeutic index; dose reduction required with CYP3A4/P-gp inhibitors',
    blackBoxWarningAr: 'جرعة زائدة مميتة مبلغ عنها؛ نطاق علاجي ضيق؛ تقليل الجرعة مطلوب مع مثبطات CYP3A4',
    interactions: [
      { interactsWith: 'Clarithromycin', severity: 'major', mechanism: 'CYP3A4 and P-glycoprotein inhibition increases colchicine levels', clinicalEffect: 'Life-threatening colchicine toxicity (multi-organ failure)', clinicalEffectAr: 'سمية كولشيسين مهددة للحياة (فشل متعدد الأعضاء)', management: 'Reduce colchicine dose by 50% or avoid; contraindicated in renal/hepatic impairment', managementAr: 'تقليل جرعة الكولشيسين بنسبة 50% أو التجنب؛ ممنوع في القصور الكلوي/الكبدي' },
      { interactsWith: 'Cyclosporine', severity: 'major', mechanism: 'P-glycoprotein inhibition increases colchicine absorption', clinicalEffect: 'Colchicine toxicity: myopathy, neuropathy', clinicalEffectAr: 'سمية الكولشيسين: اعتلال عضلي، اعتلال عصبي', management: 'Reduce colchicine dose; monitor for muscle weakness', managementAr: 'تقليل جرعة الكولشيسين؛ مراقبة ضعف العضلات' },
    ],
    contraindications: ['Severe renal impairment with concurrent CYP3A4/P-gp inhibitor', 'Severe hepatic impairment with concurrent CYP3A4/P-gp inhibitor', 'Blood dyscrasias'],
    contraindicationsAr: ['قصور كلوي شديد مع مثبط CYP3A4 متزامن', 'قصور كبدي شديد مع مثبط CYP3A4 متزامن', 'اضطرابات الدم'],
    monitoringRequired: ['CBC', 'Renal function', 'Hepatic function', 'Muscle symptoms (CK if symptomatic)', 'GI tolerance'],
    storageConditions: 'Store at 20-25°C, protect from light',
  },
];
