/**
 * Saudi MOH Drug Formulary — Drug Data Part 15
 * Topical Preparations & Local Agents
 * IDs: FRM-0800 through FRM-0839
 */
import type { FormularyDrug } from './formularyTypes';

export const TOPICAL_LOCAL: FormularyDrug[] = [
  // ── Topical Steroids (6) ──────────────────────────────────────────
  {
    id: 'FRM-0800', genericName: 'Hydrocortisone 1% Cream', genericNameAr: 'هيدروكورتيزون 1% كريم',
    brandNames: ['Cortaid', 'Hytone', 'Locoid'], sfda_registration: 'SFDA-TOP-0800', atcCode: 'D07AA02',
    atcCategory: 'Corticosteroids, weak (group I)', therapeuticClass: 'Topical Corticosteroid — Low Potency',
    therapeuticClassAr: 'كورتيكوستيرويد موضعي — منخفض الفعالية', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '1% 30g', unitPrice: 8.50, inStock: true },
      { form: 'Ointment', strength: '1% 30g', unitPrice: 9.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Hydrocortisone injection', 'Hydrochlorothiazide'],
    interactions: [
      { interactsWith: 'Other topical corticosteroids', severity: 'moderate', mechanism: 'Additive steroid effect on skin',
        clinicalEffect: 'Increased risk of skin atrophy', clinicalEffectAr: 'زيادة خطر ضمور الجلد',
        management: 'Avoid concurrent use on same area', managementAr: 'تجنب الاستخدام المتزامن على نفس المنطقة' },
    ],
    contraindications: ['Untreated skin infections', 'Rosacea', 'Perioral dermatitis'],
    contraindicationsAr: ['عدوى جلدية غير معالجة', 'الوردية', 'التهاب الجلد حول الفم'],
    monitoringRequired: ['Skin integrity with prolonged use'], storageConditions: 'Store below 25°C, do not freeze',
  },
  {
    id: 'FRM-0801', genericName: 'Betamethasone Valerate Cream', genericNameAr: 'بيتاميثازون فاليرات كريم',
    brandNames: ['Betnovate', 'Beta-Val', 'Celestoderm'], sfda_registration: 'SFDA-TOP-0801', atcCode: 'D07AC01',
    atcCategory: 'Corticosteroids, potent (group III)', therapeuticClass: 'Topical Corticosteroid — Medium-High Potency',
    therapeuticClassAr: 'كورتيكوستيرويد موضعي — متوسط إلى عالي الفعالية', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '0.1% 30g', unitPrice: 14.00, inStock: true },
      { form: 'Ointment', strength: '0.1% 30g', unitPrice: 15.00, inStock: true },
      { form: 'Scalp lotion', strength: '0.1% 30ml', unitPrice: 18.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Betamethasone dipropionate', 'Beclometasone'],
    interactions: [
      { interactsWith: 'Topical retinoids', severity: 'minor', mechanism: 'Increased skin irritation',
        clinicalEffect: 'Enhanced irritation and dryness', clinicalEffectAr: 'زيادة التهيج والجفاف',
        management: 'Separate application times', managementAr: 'فصل أوقات التطبيق' },
    ],
    contraindications: ['Viral skin infections', 'Tuberculous skin lesions', 'Acne vulgaris'],
    contraindicationsAr: ['عدوى جلدية فيروسية', 'آفات جلدية سُلّية', 'حب الشباب الشائع'],
    monitoringRequired: ['Skin atrophy signs', 'HPA axis suppression with large-area use'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0802', genericName: 'Clobetasol Propionate Cream', genericNameAr: 'كلوبيتازول بروبيونات كريم',
    brandNames: ['Dermovate', 'Temovate', 'Clobex'], sfda_registration: 'SFDA-TOP-0802', atcCode: 'D07AD01',
    atcCategory: 'Corticosteroids, very potent (group IV)', therapeuticClass: 'Topical Corticosteroid — Super-High Potency',
    therapeuticClassAr: 'كورتيكوستيرويد موضعي — فائق الفعالية', formularyStatus: 'restricted',
    restrictionCriteria: 'Max 2 weeks continuous use; dermatology approval for extension beyond 2 weeks',
    restrictionCriteriaAr: 'أقصى مدة استخدام مستمر أسبوعان؛ يتطلب موافقة الجلدية للتمديد',
    approverRole: 'dermatologist', route: ['topical'], forms: [
      { form: 'Cream', strength: '0.05% 30g', unitPrice: 22.00, inStock: true },
      { form: 'Ointment', strength: '0.05% 30g', unitPrice: 24.00, inStock: true },
      { form: 'Scalp solution', strength: '0.05% 30ml', unitPrice: 28.00, inStock: false },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Clobetasone', 'Clobestol'],
    blackBoxWarning: 'Not for use on face, groin, or axillae. Limit to 2 consecutive weeks. Risk of HPA axis suppression.',
    blackBoxWarningAr: 'لا يُستخدم على الوجه أو الفخذ أو الإبط. يُحدد بأسبوعين متتاليين. خطر تثبيط محور HPA.',
    interactions: [
      { interactsWith: 'Other corticosteroids (systemic)', severity: 'major', mechanism: 'Additive HPA axis suppression',
        clinicalEffect: 'Adrenal suppression risk', clinicalEffectAr: 'خطر تثبيط الغدة الكظرية',
        management: 'Monitor cortisol if using concomitantly', managementAr: 'مراقبة الكورتيزول عند الاستخدام المتزامن' },
    ],
    contraindications: ['Facial dermatoses', 'Children under 12', 'Rosacea', 'Perioral dermatitis', 'Infected skin without antimicrobial'],
    contraindicationsAr: ['أمراض جلد الوجه', 'أطفال أقل من 12 سنة', 'الوردية', 'التهاب حول الفم', 'جلد مصاب بدون مضاد ميكروبي'],
    monitoringRequired: ['HPA axis function with prolonged/extensive use', 'Skin atrophy', 'Striae development'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0803', genericName: 'Mometasone Furoate Cream', genericNameAr: 'موميتازون فيوروات كريم',
    brandNames: ['Elocon', 'Elocom'], sfda_registration: 'SFDA-TOP-0803', atcCode: 'D07AC13',
    atcCategory: 'Corticosteroids, potent (group III)', therapeuticClass: 'Topical Corticosteroid — Medium-High Potency',
    therapeuticClassAr: 'كورتيكوستيرويد موضعي — متوسط إلى عالي الفعالية', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '0.1% 15g', unitPrice: 16.00, inStock: true },
      { form: 'Ointment', strength: '0.1% 15g', unitPrice: 17.50, inStock: true },
      { form: 'Lotion', strength: '0.1% 30ml', unitPrice: 20.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Mometasone nasal spray', 'Metronidazole'],
    interactions: [
      { interactsWith: 'Occlusive dressings', severity: 'moderate', mechanism: 'Increased systemic absorption',
        clinicalEffect: 'HPA axis suppression', clinicalEffectAr: 'تثبيط محور HPA',
        management: 'Avoid prolonged occlusion', managementAr: 'تجنب التغطية المطولة' },
    ],
    contraindications: ['Untreated bacterial/fungal/viral skin infections', 'Acne'],
    contraindicationsAr: ['عدوى جلدية بكتيرية/فطرية/فيروسية غير معالجة', 'حب الشباب'],
    monitoringRequired: ['Skin condition response at 2 weeks'], storageConditions: 'Store at 2–25°C',
  },
  {
    id: 'FRM-0804', genericName: 'Triamcinolone Acetonide Cream', genericNameAr: 'ترايامسينولون أسيتونيد كريم',
    brandNames: ['Kenalog', 'Aristocort', 'Triamcort'], sfda_registration: 'SFDA-TOP-0804', atcCode: 'D07AB09',
    atcCategory: 'Corticosteroids, moderately potent (group II)', therapeuticClass: 'Topical Corticosteroid — Medium Potency',
    therapeuticClassAr: 'كورتيكوستيرويد موضعي — متوسط الفعالية', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '0.1% 30g', unitPrice: 12.00, inStock: true },
      { form: 'Ointment', strength: '0.1% 30g', unitPrice: 13.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Triamcinolone injection', 'Triamterene'],
    interactions: [
      { interactsWith: 'Topical antifungals', severity: 'minor', mechanism: 'Masking of fungal infection symptoms',
        clinicalEffect: 'Delayed diagnosis of fungal infection', clinicalEffectAr: 'تأخير تشخيص العدوى الفطرية',
        management: 'Use combination products only when indicated', managementAr: 'استخدام المنتجات المركبة فقط عند الحاجة' },
    ],
    contraindications: ['Fungal skin infections (sole therapy)', 'Viral skin infections'],
    contraindicationsAr: ['عدوى جلدية فطرية (كعلاج وحيد)', 'عدوى جلدية فيروسية'],
    monitoringRequired: ['Treatment response', 'Signs of skin atrophy'], storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0805', genericName: 'Fluocinolone Acetonide Cream', genericNameAr: 'فلوسينولون أسيتونيد كريم',
    brandNames: ['Synalar', 'Derma-Smoothe'], sfda_registration: 'SFDA-TOP-0805', atcCode: 'D07AC04',
    atcCategory: 'Corticosteroids, potent (group III)', therapeuticClass: 'Topical Corticosteroid — Medium Potency',
    therapeuticClassAr: 'كورتيكوستيرويد موضعي — متوسط الفعالية', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '0.025% 30g', unitPrice: 14.50, inStock: true },
      { form: 'Scalp oil', strength: '0.01% 120ml', unitPrice: 35.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Fluocinonide', 'Fluconazole'],
    interactions: [
      { interactsWith: 'Topical retinoids', severity: 'minor', mechanism: 'Irritation potential',
        clinicalEffect: 'Increased skin sensitivity', clinicalEffectAr: 'زيادة حساسية الجلد',
        management: 'Alternate application times', managementAr: 'تناوب أوقات التطبيق' },
    ],
    contraindications: ['Primary skin infections', 'Rosacea'],
    contraindicationsAr: ['عدوى جلدية أولية', 'الوردية'],
    monitoringRequired: ['Skin condition at follow-up'], storageConditions: 'Store below 25°C',
  },

  // ── Topical Antifungals (4) ───────────────────────────────────────
  {
    id: 'FRM-0806', genericName: 'Clotrimazole Cream', genericNameAr: 'كلوتريمازول كريم',
    brandNames: ['Canesten', 'Lotrimin', 'Mycelex'], sfda_registration: 'SFDA-TOP-0806', atcCode: 'D01AC01',
    atcCategory: 'Antifungals for topical use — Imidazole derivatives', therapeuticClass: 'Topical Antifungal',
    therapeuticClassAr: 'مضاد فطريات موضعي', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '1% 20g', unitPrice: 7.00, inStock: true },
      { form: 'Vaginal cream', strength: '2% 20g', unitPrice: 12.00, inStock: true },
      { form: 'Solution', strength: '1% 20ml', unitPrice: 9.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Cotrimazine', 'Clomipramine'],
    interactions: [
      { interactsWith: 'Topical corticosteroids', severity: 'minor', mechanism: 'May mask fungal infection signs',
        clinicalEffect: 'Apparent improvement masking ongoing infection', clinicalEffectAr: 'تحسن ظاهري مع استمرار العدوى',
        management: 'Re-evaluate after steroid discontinuation', managementAr: 'إعادة تقييم بعد إيقاف الستيرويد' },
    ],
    contraindications: ['Hypersensitivity to imidazoles'],
    contraindicationsAr: ['فرط حساسية لمشتقات الإيميدازول'],
    monitoringRequired: ['Clinical response at 2–4 weeks'], storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0807', genericName: 'Miconazole Cream', genericNameAr: 'ميكونازول كريم',
    brandNames: ['Daktarin', 'Micatin', 'Monistat'], sfda_registration: 'SFDA-TOP-0807', atcCode: 'D01AC02',
    atcCategory: 'Antifungals for topical use — Imidazole derivatives', therapeuticClass: 'Topical Antifungal',
    therapeuticClassAr: 'مضاد فطريات موضعي', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '2% 30g', unitPrice: 9.50, inStock: true },
      { form: 'Oral gel', strength: '2% 40g', unitPrice: 14.00, inStock: true },
      { form: 'Powder', strength: '2% 30g', unitPrice: 11.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Metronidazole', 'Minocycline'],
    interactions: [
      { interactsWith: 'Warfarin (oral gel form)', severity: 'major', mechanism: 'CYP2C9 inhibition — oral gel absorbed systemically',
        clinicalEffect: 'Increased INR and bleeding risk', clinicalEffectAr: 'زيادة INR وخطر النزيف',
        management: 'Monitor INR closely with oral gel; topical cream negligible interaction', managementAr: 'مراقبة INR عن كثب مع الجل الفموي؛ تأثير الكريم الموضعي ضئيل' },
    ],
    contraindications: ['Hypersensitivity to imidazoles'],
    contraindicationsAr: ['فرط حساسية لمشتقات الإيميدازول'],
    monitoringRequired: ['INR if oral gel used with anticoagulants'], storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0808', genericName: 'Terbinafine Cream', genericNameAr: 'تيربينافين كريم',
    brandNames: ['Lamisil', 'Terbisil'], sfda_registration: 'SFDA-TOP-0808', atcCode: 'D01AE15',
    atcCategory: 'Antifungals for topical use — Other', therapeuticClass: 'Topical Antifungal — Allylamine',
    therapeuticClassAr: 'مضاد فطريات موضعي — أليل أمين', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '1% 15g', unitPrice: 18.00, inStock: true },
      { form: 'Spray', strength: '1% 30ml', unitPrice: 25.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Terbinafine oral tablets', 'Terbutaline'],
    interactions: [
      { interactsWith: 'None clinically significant for topical form', severity: 'minor', mechanism: 'Negligible systemic absorption',
        clinicalEffect: 'No significant interactions', clinicalEffectAr: 'لا تفاعلات ذات أهمية سريرية',
        management: 'No special precautions', managementAr: 'لا احتياطات خاصة' },
    ],
    contraindications: ['Hypersensitivity to terbinafine'],
    contraindicationsAr: ['فرط حساسية للتيربينافين'],
    monitoringRequired: ['Clinical response at 1–2 weeks for tinea'], storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0809', genericName: 'Nystatin Cream', genericNameAr: 'نيستاتين كريم',
    brandNames: ['Mycostatin', 'Nystop'], sfda_registration: 'SFDA-TOP-0809', atcCode: 'D01AA01',
    atcCategory: 'Antifungals for topical use — Antibiotics', therapeuticClass: 'Topical Antifungal — Polyene',
    therapeuticClassAr: 'مضاد فطريات موضعي — بوليين', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '100,000 IU/g 30g', unitPrice: 10.00, inStock: true },
      { form: 'Ointment', strength: '100,000 IU/g 30g', unitPrice: 11.00, inStock: true },
      { form: 'Powder', strength: '100,000 IU/g 15g', unitPrice: 8.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Nystatin oral suspension', 'Nitazoxanide'],
    interactions: [
      { interactsWith: 'No clinically significant interactions', severity: 'minor', mechanism: 'Not absorbed systemically',
        clinicalEffect: 'None expected', clinicalEffectAr: 'لا يُتوقع تفاعلات',
        management: 'No precautions needed', managementAr: 'لا حاجة لاحتياطات' },
    ],
    contraindications: ['Hypersensitivity to nystatin'],
    contraindicationsAr: ['فرط حساسية للنيستاتين'],
    monitoringRequired: ['Clinical resolution of candidiasis'], storageConditions: 'Store below 25°C',
  },

  // ── Topical Antibiotics (4) ───────────────────────────────────────
  {
    id: 'FRM-0810', genericName: 'Mupirocin Ointment', genericNameAr: 'موبيروسين مرهم',
    brandNames: ['Bactroban', 'Centany'], sfda_registration: 'SFDA-TOP-0810', atcCode: 'D06AX09',
    atcCategory: 'Antibiotics for topical use — Other', therapeuticClass: 'Topical Antibiotic',
    therapeuticClassAr: 'مضاد حيوي موضعي', formularyStatus: 'formulary',
    route: ['topical', 'intranasal'], forms: [
      { form: 'Ointment', strength: '2% 15g', unitPrice: 18.00, inStock: true },
      { form: 'Nasal ointment', strength: '2% 3g', unitPrice: 22.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Mupirocin calcium', 'Bacitracin'],
    interactions: [
      { interactsWith: 'Other topical products on same site', severity: 'minor', mechanism: 'May dilute mupirocin concentration',
        clinicalEffect: 'Reduced antibacterial efficacy', clinicalEffectAr: 'انخفاض فعالية مضاد البكتيريا',
        management: 'Do not apply other topical products on same site', managementAr: 'لا تضع منتجات موضعية أخرى على نفس المنطقة' },
    ],
    contraindications: ['Hypersensitivity to mupirocin or polyethylene glycol'],
    contraindicationsAr: ['فرط حساسية للموبيروسين أو البولي إيثيلين جلايكول'],
    monitoringRequired: ['MRSA decolonization efficacy', 'Culture after 5-day course'], storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0811', genericName: 'Fusidic Acid Cream', genericNameAr: 'حمض الفيوسيديك كريم',
    brandNames: ['Fucidin', 'Fucicort'], sfda_registration: 'SFDA-TOP-0811', atcCode: 'D06AX01',
    atcCategory: 'Antibiotics for topical use — Other', therapeuticClass: 'Topical Antibiotic',
    therapeuticClassAr: 'مضاد حيوي موضعي', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '2% 15g', unitPrice: 15.00, inStock: true },
      { form: 'Ointment', strength: '2% 15g', unitPrice: 16.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Fusidic acid eye drops', 'Flucloxacillin'],
    interactions: [
      { interactsWith: 'Topical corticosteroids (combination products)', severity: 'minor', mechanism: 'Combined immunosuppression',
        clinicalEffect: 'Prolonged infection if steroid masks signs', clinicalEffectAr: 'إطالة العدوى إذا أخفى الستيرويد العلامات',
        management: 'Limit combination use to 2 weeks', managementAr: 'حصر استخدام التركيبة بأسبوعين' },
    ],
    contraindications: ['Hypersensitivity to fusidic acid'],
    contraindicationsAr: ['فرط حساسية لحمض الفيوسيديك'],
    monitoringRequired: ['Resistance development with prolonged use'], storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0812', genericName: 'Silver Sulfadiazine Cream', genericNameAr: 'سلفاديازين الفضة كريم',
    brandNames: ['Silvadene', 'Flamazine', 'Dermazin'], sfda_registration: 'SFDA-TOP-0812', atcCode: 'D06BA01',
    atcCategory: 'Chemotherapeutics for topical use — Sulfonamides', therapeuticClass: 'Topical Antimicrobial — Burns',
    therapeuticClassAr: 'مضاد ميكروبي موضعي — الحروق', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '1% 50g', unitPrice: 20.00, inStock: true },
      { form: 'Cream', strength: '1% 250g', unitPrice: 65.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Sulfadiazine oral', 'Sulfasalazine'],
    blackBoxWarning: 'Contains sulfonamide — do not use in patients with known sulfa allergy. Avoid in neonates (kernicterus risk).',
    blackBoxWarningAr: 'يحتوي على سلفوناميد — لا يُستخدم مع مرضى حساسية السلفا. يُتجنب عند حديثي الولادة (خطر اليرقان النووي).',
    interactions: [
      { interactsWith: 'Enzymatic debridement agents (collagenase)', severity: 'moderate', mechanism: 'Silver ions inactivate enzymatic agents',
        clinicalEffect: 'Reduced debriding efficacy', clinicalEffectAr: 'انخفاض فعالية التنضير الإنزيمي',
        management: 'Do not use concurrently', managementAr: 'لا يُستخدم بالتزامن' },
    ],
    contraindications: ['Sulfonamide allergy', 'Pregnancy at term', 'Neonates < 2 months', 'G6PD deficiency'],
    contraindicationsAr: ['حساسية السلفوناميد', 'الحمل في الأشهر الأخيرة', 'حديثي الولادة أقل من شهرين', 'نقص G6PD'],
    monitoringRequired: ['CBC with prolonged large-area use', 'Renal function', 'Wound healing progress'],
    storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0813', genericName: 'Gentamicin Cream', genericNameAr: 'جنتاميسين كريم',
    brandNames: ['Garamycin', 'Gentak'], sfda_registration: 'SFDA-TOP-0813', atcCode: 'D06AX07',
    atcCategory: 'Antibiotics for topical use — Other', therapeuticClass: 'Topical Antibiotic — Aminoglycoside',
    therapeuticClassAr: 'مضاد حيوي موضعي — أمينوغليكوزيد', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '0.1% 15g', unitPrice: 10.00, inStock: true },
      { form: 'Ointment', strength: '0.1% 15g', unitPrice: 11.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Gentamicin injection', 'Clindamycin'],
    interactions: [
      { interactsWith: 'Systemic aminoglycosides', severity: 'moderate', mechanism: 'Additive nephro/ototoxicity with large wound absorption',
        clinicalEffect: 'Increased toxicity risk on large burns/wounds', clinicalEffectAr: 'زيادة خطر السمية على الحروق/الجروح الكبيرة',
        management: 'Avoid on extensive wounds if receiving systemic aminoglycosides', managementAr: 'تجنب الاستخدام على جروح واسعة مع أمينوغليكوزيدات جهازية' },
    ],
    contraindications: ['Hypersensitivity to aminoglycosides'],
    contraindicationsAr: ['فرط حساسية للأمينوغليكوزيدات'],
    monitoringRequired: ['Wound culture if no improvement in 7 days'], storageConditions: 'Store below 25°C',
  },

  // ── Antiseptics & Wound Care (5) ──────────────────────────────────
  {
    id: 'FRM-0814', genericName: 'Povidone-Iodine Solution', genericNameAr: 'محلول بوفيدون أيودين',
    brandNames: ['Betadine', 'Povisep'], sfda_registration: 'SFDA-TOP-0814', atcCode: 'D08AG02',
    atcCategory: 'Antiseptics and disinfectants — Iodine products', therapeuticClass: 'Antiseptic',
    therapeuticClassAr: 'مطهر', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Solution', strength: '10% 120ml', unitPrice: 12.00, inStock: true },
      { form: 'Scrub', strength: '7.5% 500ml', unitPrice: 28.00, inStock: true },
      { form: 'Ointment', strength: '10% 30g', unitPrice: 10.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Potassium iodide', 'Povidone (PVP)'],
    interactions: [
      { interactsWith: 'Lithium', severity: 'moderate', mechanism: 'Iodine absorption may affect thyroid function',
        clinicalEffect: 'Hypothyroidism risk with large-area/prolonged use', clinicalEffectAr: 'خطر قصور الغدة الدرقية مع الاستخدام الواسع/المطول',
        management: 'Monitor thyroid function with extensive use', managementAr: 'مراقبة وظيفة الغدة الدرقية مع الاستخدام المكثف' },
    ],
    contraindications: ['Iodine allergy', 'Thyroid disorders (large-area use)', 'Neonates'],
    contraindicationsAr: ['حساسية اليود', 'اضطرابات الغدة الدرقية (استخدام واسع)', 'حديثي الولادة'],
    monitoringRequired: ['Thyroid function with extensive/prolonged use'], storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0815', genericName: 'Chlorhexidine Gluconate Solution', genericNameAr: 'محلول كلورهيكسيدين جلوكونات',
    brandNames: ['Hibiscrub', 'Hibiclens', 'ChloraPrep'], sfda_registration: 'SFDA-TOP-0815', atcCode: 'D08AC02',
    atcCategory: 'Antiseptics and disinfectants — Biguanides', therapeuticClass: 'Antiseptic / Surgical Prep',
    therapeuticClassAr: 'مطهر / تحضير جراحي', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Solution', strength: '4% 500ml', unitPrice: 18.00, inStock: true },
      { form: 'Solution', strength: '0.5% in alcohol 200ml', unitPrice: 15.00, inStock: true },
      { form: 'Wipes', strength: '2% pack of 6', unitPrice: 12.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Chlorhexidine mouthwash', 'Chloramphenicol'],
    interactions: [
      { interactsWith: 'Soap/anionic surfactants', severity: 'moderate', mechanism: 'Inactivation of chlorhexidine by anionic compounds',
        clinicalEffect: 'Reduced antiseptic activity', clinicalEffectAr: 'انخفاض الفعالية المطهرة',
        management: 'Rinse soap thoroughly before applying chlorhexidine', managementAr: 'شطف الصابون جيداً قبل تطبيق الكلورهيكسيدين' },
    ],
    contraindications: ['Known chlorhexidine allergy (rare anaphylaxis reported)', 'Do not instill in middle ear'],
    contraindicationsAr: ['حساسية معروفة للكلورهيكسيدين (تفاعل تأقي نادر)', 'لا يُوضع في الأذن الوسطى'],
    monitoringRequired: ['Allergic reactions'], storageConditions: 'Store below 25°C, flammable (alcohol-based)',
  },
  {
    id: 'FRM-0816', genericName: 'Hydrogen Peroxide Solution', genericNameAr: 'محلول بيروكسيد الهيدروجين',
    brandNames: ['Peroxyl', 'Proxacol'], sfda_registration: 'SFDA-TOP-0816', atcCode: 'D08AX01',
    atcCategory: 'Antiseptics and disinfectants — Other', therapeuticClass: 'Antiseptic / Wound Cleanser',
    therapeuticClassAr: 'مطهر / منظف جروح', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Solution', strength: '3% 250ml', unitPrice: 5.00, inStock: true },
      { form: 'Cream', strength: '1% 25g', unitPrice: 8.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Benzoyl peroxide', 'Carbamide peroxide'],
    interactions: [
      { interactsWith: 'Povidone-iodine', severity: 'minor', mechanism: 'Oxidation may reduce iodine efficacy',
        clinicalEffect: 'Reduced antiseptic effect of both', clinicalEffectAr: 'انخفاض التأثير المطهر لكليهما',
        management: 'Use separately, not concurrently', managementAr: 'استخدام كل منهما منفرداً' },
    ],
    contraindications: ['Deep wounds or body cavities (gas embolism risk)', 'Closed wounds'],
    contraindicationsAr: ['جروح عميقة أو تجاويف الجسم (خطر الانسداد الغازي)', 'جروح مغلقة'],
    monitoringRequired: ['Tissue viability — avoid on granulating wounds'], storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0817', genericName: 'Silver Alginate Wound Dressing', genericNameAr: 'ضماد جروح ألجينات الفضة',
    brandNames: ['Aquacel Ag', 'Silvercel', 'Biatain Ag'], sfda_registration: 'SFDA-TOP-0817', atcCode: 'D09AA',
    atcCategory: 'Medicated dressings — Soft paraffin dressings', therapeuticClass: 'Antimicrobial Wound Dressing',
    therapeuticClassAr: 'ضماد جروح مضاد للميكروبات', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Dressing', strength: '10x10cm', unitPrice: 35.00, inStock: true },
      { form: 'Dressing', strength: '15x15cm', unitPrice: 55.00, inStock: true },
      { form: 'Ribbon dressing', strength: '2x45cm', unitPrice: 30.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Silver sulfadiazine cream', 'Calcium alginate'],
    interactions: [
      { interactsWith: 'Topical enzymatic debriding agents', severity: 'moderate', mechanism: 'Silver ions may inactivate enzymes',
        clinicalEffect: 'Reduced debridement efficacy', clinicalEffectAr: 'انخفاض فعالية التنضير',
        management: 'Remove silver dressing before enzymatic debridement', managementAr: 'إزالة ضماد الفضة قبل التنضير الإنزيمي' },
    ],
    contraindications: ['Silver allergy', 'Third-degree burns (inadequate coverage)', 'MRI contraindicated with silver in situ'],
    contraindicationsAr: ['حساسية الفضة', 'حروق الدرجة الثالثة (تغطية غير كافية)', 'التصوير بالرنين المغناطيسي مع وجود الفضة'],
    monitoringRequired: ['Wound assessment at each dressing change', 'Signs of infection'],
    storageConditions: 'Store in original packaging, below 25°C',
  },
  {
    id: 'FRM-0818', genericName: 'Medical-Grade Honey Wound Gel', genericNameAr: 'جل عسل طبي للجروح',
    brandNames: ['Medihoney', 'Manuka Health', 'Activon'], sfda_registration: 'SFDA-TOP-0818', atcCode: 'D03AX',
    atcCategory: 'Other preparations for treatment of wounds and ulcers', therapeuticClass: 'Biological Wound Dressing',
    therapeuticClassAr: 'ضماد جروح بيولوجي', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Gel', strength: '25g tube', unitPrice: 42.00, inStock: true },
      { form: 'Impregnated dressing', strength: '10x10cm', unitPrice: 38.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Manuka honey (food grade — not for wound use)'],
    interactions: [
      { interactsWith: 'No clinically significant interactions', severity: 'minor', mechanism: 'No systemic absorption',
        clinicalEffect: 'None expected', clinicalEffectAr: 'لا يُتوقع تفاعلات',
        management: 'None required', managementAr: 'لا يتطلب إجراء' },
    ],
    contraindications: ['Bee product allergy'],
    contraindicationsAr: ['حساسية منتجات النحل'],
    monitoringRequired: ['Wound bed condition', 'Exudate management'], storageConditions: 'Store below 25°C',
  },

  // ── Ophthalmic (6) ────────────────────────────────────────────────
  {
    id: 'FRM-0819', genericName: 'Timolol Maleate Eye Drops', genericNameAr: 'تيمولول ماليات قطرة عينية',
    brandNames: ['Timoptic', 'Betimol', 'Istalol'], sfda_registration: 'SFDA-TOP-0819', atcCode: 'S01ED01',
    atcCategory: 'Ophthalmologicals — Beta blocking agents', therapeuticClass: 'Anti-Glaucoma — Beta-Blocker',
    therapeuticClassAr: 'مضاد جلوكوما — حاصر بيتا', formularyStatus: 'formulary',
    route: ['ophthalmic'], forms: [
      { form: 'Eye drops', strength: '0.5% 5ml', unitPrice: 14.00, inStock: true },
      { form: 'Eye drops', strength: '0.25% 5ml', unitPrice: 12.00, inStock: true },
      { form: 'Gel-forming eye drops', strength: '0.5% 5ml', unitPrice: 22.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Timolol/dorzolamide', 'Atenolol'],
    interactions: [
      { interactsWith: 'Systemic beta-blockers', severity: 'major', mechanism: 'Additive beta-blockade (systemic absorption from eye drops)',
        clinicalEffect: 'Bradycardia, hypotension, bronchospasm', clinicalEffectAr: 'بطء القلب، انخفاض الضغط، تشنج قصبي',
        management: 'Monitor heart rate and blood pressure', managementAr: 'مراقبة معدل القلب وضغط الدم' },
      { interactsWith: 'Calcium channel blockers (verapamil, diltiazem)', severity: 'major', mechanism: 'Additive cardiac depression',
        clinicalEffect: 'Heart block, severe bradycardia', clinicalEffectAr: 'إحصار قلبي، بطء قلب شديد',
        management: 'Use with caution; monitor ECG', managementAr: 'استخدام بحذر مع مراقبة تخطيط القلب' },
    ],
    contraindications: ['Asthma', 'COPD', 'Sinus bradycardia', 'Heart block (2nd/3rd degree)', 'Decompensated heart failure'],
    contraindicationsAr: ['الربو', 'مرض الانسداد الرئوي المزمن', 'بطء القلب الجيبي', 'إحصار القلب (الدرجة 2/3)', 'قصور قلب غير معوض'],
    monitoringRequired: ['IOP every 3–6 months', 'Heart rate', 'Respiratory status in at-risk patients'],
    storageConditions: 'Store at 15–25°C, protect from light',
  },
  {
    id: 'FRM-0820', genericName: 'Latanoprost Eye Drops', genericNameAr: 'لاتانوبروست قطرة عينية',
    brandNames: ['Xalatan', 'Latoprost'], sfda_registration: 'SFDA-TOP-0820', atcCode: 'S01EE01',
    atcCategory: 'Ophthalmologicals — Prostaglandin analogues', therapeuticClass: 'Anti-Glaucoma — Prostaglandin Analogue',
    therapeuticClassAr: 'مضاد جلوكوما — نظير البروستاجلاندين', formularyStatus: 'formulary',
    route: ['ophthalmic'], forms: [
      { form: 'Eye drops', strength: '0.005% 2.5ml', unitPrice: 45.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Latanoprostene bunod', 'Travoprost'],
    interactions: [
      { interactsWith: 'Other prostaglandin analogues', severity: 'moderate', mechanism: 'Paradoxical IOP elevation',
        clinicalEffect: 'Increased intraocular pressure', clinicalEffectAr: 'زيادة ضغط العين',
        management: 'Do not combine prostaglandin analogues', managementAr: 'لا تُجمع نظائر البروستاجلاندين' },
    ],
    contraindications: ['Hypersensitivity to latanoprost or benzalkonium chloride'],
    contraindicationsAr: ['فرط حساسية للاتانوبروست أو كلوريد البنزالكونيوم'],
    monitoringRequired: ['IOP every 4–6 weeks initially', 'Iris pigmentation change', 'Eyelash growth'],
    storageConditions: 'Unopened: 2–8°C; Opened: below 25°C, use within 4 weeks',
  },
  {
    id: 'FRM-0821', genericName: 'Brimonidine Eye Drops', genericNameAr: 'بريمونيدين قطرة عينية',
    brandNames: ['Alphagan', 'Alphagan P'], sfda_registration: 'SFDA-TOP-0821', atcCode: 'S01EA05',
    atcCategory: 'Ophthalmologicals — Sympathomimetics', therapeuticClass: 'Anti-Glaucoma — Alpha-2 Agonist',
    therapeuticClassAr: 'مضاد جلوكوما — منبه ألفا-2', formularyStatus: 'formulary',
    route: ['ophthalmic'], forms: [
      { form: 'Eye drops', strength: '0.2% 5ml', unitPrice: 28.00, inStock: true },
      { form: 'Eye drops', strength: '0.15% 5ml', unitPrice: 32.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Brimonidine/timolol combination', 'Bromfenac'],
    interactions: [
      { interactsWith: 'MAO inhibitors', severity: 'major', mechanism: 'Potentiation of adrenergic effects',
        clinicalEffect: 'Hypertensive crisis risk', clinicalEffectAr: 'خطر نوبة ارتفاع ضغط الدم',
        management: 'Contraindicated — do not combine', managementAr: 'موانع — لا يُجمع' },
      { interactsWith: 'CNS depressants', severity: 'moderate', mechanism: 'Additive CNS depression from systemic absorption',
        clinicalEffect: 'Drowsiness, fatigue', clinicalEffectAr: 'نعاس، إرهاق',
        management: 'Caution when driving or operating machinery', managementAr: 'حذر عند القيادة أو تشغيل الآلات' },
    ],
    contraindications: ['Children < 2 years (severe CNS depression)', 'MAO inhibitor use', 'Tricyclic antidepressant use'],
    contraindicationsAr: ['أطفال أقل من سنتين (تثبيط شديد للجهاز العصبي)', 'استخدام مثبطات MAO', 'استخدام مضادات الاكتئاب ثلاثية الحلقات'],
    monitoringRequired: ['IOP', 'Allergic conjunctivitis symptoms', 'CNS effects in pediatrics'],
    storageConditions: 'Store at 15–25°C',
  },
  {
    id: 'FRM-0822', genericName: 'Artificial Tears (Sodium Hyaluronate)', genericNameAr: 'دموع اصطناعية (هيالورونات الصوديوم)',
    brandNames: ['Hylo-Comod', 'Blink Intensive', 'Systane Ultra'], sfda_registration: 'SFDA-TOP-0822', atcCode: 'S01XA20',
    atcCategory: 'Ophthalmologicals — Other', therapeuticClass: 'Ocular Lubricant',
    therapeuticClassAr: 'مرطب عيني', formularyStatus: 'formulary',
    route: ['ophthalmic'], forms: [
      { form: 'Eye drops', strength: '0.1% 10ml', unitPrice: 22.00, inStock: true },
      { form: 'Eye drops (preservative-free)', strength: '0.15% 30x0.4ml', unitPrice: 38.00, inStock: true },
      { form: 'Eye gel', strength: '0.2% 10g', unitPrice: 28.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Hyaluronic acid dermal filler'],
    interactions: [
      { interactsWith: 'Contact lenses', severity: 'minor', mechanism: 'Preservative (BAK) may be absorbed by soft lenses',
        clinicalEffect: 'Lens discoloration or discomfort', clinicalEffectAr: 'تلون العدسة أو عدم الراحة',
        management: 'Remove lenses before instillation; wait 15 min before reinserting or use preservative-free', managementAr: 'إزالة العدسات قبل التقطير؛ انتظار 15 دقيقة أو استخدام خالي من المواد الحافظة' },
    ],
    contraindications: ['Hypersensitivity to any component'],
    contraindicationsAr: ['فرط حساسية لأي مكون'],
    monitoringRequired: ['Dry eye symptom improvement'], storageConditions: 'Store below 25°C; discard single-use vials after opening',
  },
  {
    id: 'FRM-0823', genericName: 'Tobramycin Eye Drops', genericNameAr: 'توبراميسين قطرة عينية',
    brandNames: ['Tobrex', 'Tobradex'], sfda_registration: 'SFDA-TOP-0823', atcCode: 'S01AA12',
    atcCategory: 'Ophthalmologicals — Antibiotics', therapeuticClass: 'Ophthalmic Antibiotic — Aminoglycoside',
    therapeuticClassAr: 'مضاد حيوي عيني — أمينوغليكوزيد', formularyStatus: 'formulary',
    route: ['ophthalmic'], forms: [
      { form: 'Eye drops', strength: '0.3% 5ml', unitPrice: 16.00, inStock: true },
      { form: 'Eye ointment', strength: '0.3% 3.5g', unitPrice: 18.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Tobramycin injection', 'Tobramycin/dexamethasone'],
    interactions: [
      { interactsWith: 'Systemic aminoglycosides', severity: 'minor', mechanism: 'Additive but minimal systemic absorption',
        clinicalEffect: 'Negligible additive toxicity from drops', clinicalEffectAr: 'سمية إضافية ضئيلة من القطرات',
        management: 'Safe to combine; monitor if frequent/prolonged dosing', managementAr: 'آمن للجمع؛ مراقبة مع الجرعات المتكررة/المطولة' },
    ],
    contraindications: ['Aminoglycoside hypersensitivity'],
    contraindicationsAr: ['فرط حساسية للأمينوغليكوزيدات'],
    monitoringRequired: ['Clinical response at 48–72 hours', 'Culture if no improvement'],
    storageConditions: 'Store at 8–25°C, do not freeze',
  },
  {
    id: 'FRM-0824', genericName: 'Dexamethasone Eye Drops', genericNameAr: 'ديكساميثازون قطرة عينية',
    brandNames: ['Maxidex', 'Ozurdex'], sfda_registration: 'SFDA-TOP-0824', atcCode: 'S01BA01',
    atcCategory: 'Ophthalmologicals — Corticosteroids', therapeuticClass: 'Ophthalmic Corticosteroid',
    therapeuticClassAr: 'كورتيكوستيرويد عيني', formularyStatus: 'conditional',
    restrictionCriteria: 'Ophthalmologist prescription required; max 2 weeks without re-evaluation',
    restrictionCriteriaAr: 'يتطلب وصفة طبيب عيون؛ أقصى أسبوعان بدون إعادة تقييم',
    approverRole: 'ophthalmologist', route: ['ophthalmic'], forms: [
      { form: 'Eye drops', strength: '0.1% 5ml', unitPrice: 15.00, inStock: true },
      { form: 'Eye suspension', strength: '0.1% 5ml', unitPrice: 14.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Dexamethasone injection', 'Dexamethasone oral'],
    interactions: [
      { interactsWith: 'NSAIDs (ophthalmic)', severity: 'moderate', mechanism: 'Additive effect on corneal healing delay',
        clinicalEffect: 'Increased risk of corneal melting', clinicalEffectAr: 'زيادة خطر ذوبان القرنية',
        management: 'Avoid combination post-corneal surgery without specialist oversight', managementAr: 'تجنب الجمع بعد جراحة القرنية بدون إشراف متخصص' },
    ],
    contraindications: ['Herpes simplex keratitis', 'Fungal eye infections', 'Untreated bacterial conjunctivitis', 'Glaucoma (uncontrolled)'],
    contraindicationsAr: ['التهاب القرنية بالهربس البسيط', 'عدوى فطرية بالعين', 'التهاب ملتحمة بكتيري غير معالج', 'جلوكوما غير متحكم بها'],
    monitoringRequired: ['IOP at 2 weeks (steroid-induced glaucoma)', 'Signs of superinfection', 'Cataract formation with prolonged use'],
    storageConditions: 'Store at 8–25°C, shake suspension before use',
  },

  // ── ENT (4) ───────────────────────────────────────────────────────
  {
    id: 'FRM-0825', genericName: 'Oxymetazoline Nasal Spray', genericNameAr: 'أوكسي ميتازولين بخاخ أنفي',
    brandNames: ['Afrin', 'Otrivin Plus', 'Nasivin'], sfda_registration: 'SFDA-TOP-0825', atcCode: 'R01AA05',
    atcCategory: 'Nasal preparations — Sympathomimetics', therapeuticClass: 'Nasal Decongestant',
    therapeuticClassAr: 'مزيل احتقان أنفي', formularyStatus: 'formulary',
    route: ['intranasal'], forms: [
      { form: 'Nasal spray', strength: '0.05% 15ml', unitPrice: 10.00, inStock: true },
      { form: 'Nasal drops (pediatric)', strength: '0.025% 10ml', unitPrice: 8.00, inStock: true },
    ],
    maxDailyDose: 6, maxDailyDoseUnit: 'sprays per nostril',
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Xylometazoline', 'Oxybutynin'],
    blackBoxWarning: 'Do not use for more than 3 consecutive days — risk of rebound congestion (rhinitis medicamentosa).',
    blackBoxWarningAr: 'لا يُستخدم لأكثر من 3 أيام متتالية — خطر الاحتقان الارتدادي.',
    interactions: [
      { interactsWith: 'MAO inhibitors', severity: 'major', mechanism: 'Potentiation of sympathomimetic effects',
        clinicalEffect: 'Hypertensive crisis', clinicalEffectAr: 'نوبة ارتفاع ضغط الدم',
        management: 'Contraindicated within 14 days of MAO inhibitor use', managementAr: 'موانع خلال 14 يوماً من استخدام مثبطات MAO' },
    ],
    contraindications: ['MAO inhibitor use', 'Severe hypertension', 'Children < 6 years (0.05% strength)'],
    contraindicationsAr: ['استخدام مثبطات MAO', 'ارتفاع ضغط دم شديد', 'أطفال أقل من 6 سنوات (تركيز 0.05%)'],
    monitoringRequired: ['Duration of use (max 3 days)', 'Blood pressure in hypertensive patients'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0826', genericName: 'Fluticasone Propionate Nasal Spray', genericNameAr: 'فلوتيكازون بروبيونات بخاخ أنفي',
    brandNames: ['Flixonase', 'Flonase', 'Avamys'], sfda_registration: 'SFDA-TOP-0826', atcCode: 'R01AD08',
    atcCategory: 'Nasal preparations — Corticosteroids', therapeuticClass: 'Intranasal Corticosteroid',
    therapeuticClassAr: 'كورتيكوستيرويد أنفي', formularyStatus: 'formulary',
    route: ['intranasal'], forms: [
      { form: 'Nasal spray', strength: '50mcg/spray 120 sprays', unitPrice: 32.00, inStock: true },
    ],
    maxDailyDose: 200, maxDailyDoseUnit: 'mcg',
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Fluticasone inhaler', 'Fluconazole'],
    interactions: [
      { interactsWith: 'Ritonavir / strong CYP3A4 inhibitors', severity: 'major', mechanism: 'Reduced fluticasone metabolism — systemic accumulation',
        clinicalEffect: 'Cushing syndrome, adrenal suppression', clinicalEffectAr: 'متلازمة كوشينغ، تثبيط الغدة الكظرية',
        management: 'Avoid combination; use alternative steroid (beclometasone)', managementAr: 'تجنب الجمع؛ استخدام ستيرويد بديل (بيكلوميتازون)' },
    ],
    contraindications: ['Untreated nasal infections', 'Recent nasal surgery (until healed)'],
    contraindicationsAr: ['عدوى أنفية غير معالجة', 'جراحة أنفية حديثة (حتى الشفاء)'],
    monitoringRequired: ['Nasal septum integrity with chronic use', 'Growth velocity in children'],
    storageConditions: 'Store at 4–30°C',
  },
  {
    id: 'FRM-0827', genericName: 'Ciprofloxacin Otic Drops', genericNameAr: 'سيبروفلوكساسين قطرة أذنية',
    brandNames: ['Ciloxan Otic', 'Cetraxal'], sfda_registration: 'SFDA-TOP-0827', atcCode: 'S02AA15',
    atcCategory: 'Otologicals — Antiinfectives', therapeuticClass: 'Otic Antibiotic — Fluoroquinolone',
    therapeuticClassAr: 'مضاد حيوي أذني — فلوروكينولون', formularyStatus: 'formulary',
    route: ['otic'], forms: [
      { form: 'Ear drops', strength: '0.3% 10ml', unitPrice: 18.00, inStock: true },
      { form: 'Ear drops (with dexamethasone)', strength: '0.3%/0.1% 5ml', unitPrice: 25.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ciprofloxacin eye drops', 'Ciprofloxacin oral'],
    interactions: [
      { interactsWith: 'No significant interactions for otic route', severity: 'minor', mechanism: 'Minimal systemic absorption',
        clinicalEffect: 'None expected', clinicalEffectAr: 'لا يُتوقع تفاعلات',
        management: 'None required', managementAr: 'لا يتطلب إجراء' },
    ],
    contraindications: ['Fluoroquinolone hypersensitivity', 'Perforated tympanic membrane (unless ENT-directed)'],
    contraindicationsAr: ['فرط حساسية للفلوروكينولونات', 'ثقب طبلة الأذن (إلا بتوجيه الأنف والأذن والحنجرة)'],
    monitoringRequired: ['Clinical response at 7 days', 'Hearing assessment if chronic otitis'],
    storageConditions: 'Store below 25°C, discard 28 days after opening',
  },
  {
    id: 'FRM-0828', genericName: 'Acetic Acid Otic Solution', genericNameAr: 'محلول حمض الخليك للأذن',
    brandNames: ['VoSol', 'Acetasol'], sfda_registration: 'SFDA-TOP-0828', atcCode: 'S02AA10',
    atcCategory: 'Otologicals — Antiinfectives', therapeuticClass: 'Otic Antiseptic — Acidifying Agent',
    therapeuticClassAr: 'مطهر أذني — عامل تحميض', formularyStatus: 'formulary',
    route: ['otic'], forms: [
      { form: 'Ear drops', strength: '2% 15ml', unitPrice: 8.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Acetic acid (cleaning vinegar)', 'Acetazolamide'],
    interactions: [
      { interactsWith: 'Alkaline ear preparations', severity: 'minor', mechanism: 'pH neutralization reduces efficacy',
        clinicalEffect: 'Reduced antimicrobial effect', clinicalEffectAr: 'انخفاض التأثير المضاد للميكروبات',
        management: 'Do not mix with alkaline products', managementAr: 'لا يُخلط مع المنتجات القلوية' },
    ],
    contraindications: ['Perforated tympanic membrane'],
    contraindicationsAr: ['ثقب طبلة الأذن'],
    monitoringRequired: ['Symptom resolution', 'Ear canal irritation'], storageConditions: 'Store below 25°C',
  },

  // ── Local Anesthetics (4) ─────────────────────────────────────────
  {
    id: 'FRM-0829', genericName: 'Lidocaine 2% Gel', genericNameAr: 'ليدوكايين 2% جل',
    brandNames: ['Xylocaine Gel', 'LMX', 'Instillagel'], sfda_registration: 'SFDA-TOP-0829', atcCode: 'N01BB02',
    atcCategory: 'Anesthetics — Amides', therapeuticClass: 'Topical Local Anesthetic',
    therapeuticClassAr: 'مخدر موضعي', formularyStatus: 'formulary',
    route: ['topical', 'urethral'], forms: [
      { form: 'Gel', strength: '2% 30g', unitPrice: 12.00, inStock: true },
      { form: 'Jelly (urethral)', strength: '2% 11ml syringe', unitPrice: 8.00, inStock: true },
      { form: 'Spray', strength: '10% 50ml', unitPrice: 35.00, inStock: true },
    ],
    maxDailyDose: 4.5, maxDailyDoseUnit: 'mg/kg',
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Lidocaine injection', 'Lidocaine patches'],
    interactions: [
      { interactsWith: 'Other local anesthetics', severity: 'moderate', mechanism: 'Additive toxicity (cumulative dose)',
        clinicalEffect: 'CNS and cardiac toxicity risk', clinicalEffectAr: 'خطر سمية عصبية وقلبية',
        management: 'Calculate total dose from all local anesthetic sources', managementAr: 'حساب الجرعة الإجمالية من جميع مصادر المخدر الموضعي' },
    ],
    contraindications: ['Amide local anesthetic allergy', 'Severe liver disease'],
    contraindicationsAr: ['حساسية لمخدرات الأميد الموضعية', 'مرض كبدي شديد'],
    monitoringRequired: ['Total dose calculation', 'Signs of systemic toxicity (tinnitus, metallic taste, seizures)'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0830', genericName: 'Bupivacaine Hydrochloride Injection', genericNameAr: 'بوبيفاكايين هيدروكلوريد حقن',
    brandNames: ['Marcaine', 'Sensorcaine'], sfda_registration: 'SFDA-TOP-0830', atcCode: 'N01BB01',
    atcCategory: 'Anesthetics — Amides', therapeuticClass: 'Local Anesthetic — Long-Acting',
    therapeuticClassAr: 'مخدر موضعي — طويل المفعول', formularyStatus: 'formulary',
    route: ['injection — local infiltration', 'epidural', 'spinal'], forms: [
      { form: 'Injection', strength: '0.25% 20ml', unitPrice: 12.00, inStock: true },
      { form: 'Injection', strength: '0.5% 20ml', unitPrice: 14.00, inStock: true },
      { form: 'Injection (with epinephrine)', strength: '0.5% + 1:200,000 epi 20ml', unitPrice: 16.00, inStock: true },
      { form: 'Spinal (hyperbaric)', strength: '0.5% 4ml', unitPrice: 10.00, inStock: true },
    ],
    maxDailyDose: 2, maxDailyDoseUnit: 'mg/kg (without epinephrine); 3 mg/kg (with epinephrine)',
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ropivacaine', 'Levobupivacaine'],
    blackBoxWarning: 'Cardiotoxicity risk: bupivacaine has narrow margin between effective dose and cardiotoxic dose. IV bolus is fatal. Must have lipid emulsion (Intralipid) available.',
    blackBoxWarningAr: 'خطر سمية قلبية: البوبيفاكايين له هامش ضيق بين الجرعة الفعالة والسامة للقلب. الحقن الوريدي السريع مميت. يجب توفر المستحلب الدهني.',
    interactions: [
      { interactsWith: 'Other local anesthetics', severity: 'major', mechanism: 'Additive cardiotoxicity',
        clinicalEffect: 'Cardiac arrest, arrhythmia', clinicalEffectAr: 'توقف القلب، اضطراب نظم',
        management: 'Strict total dose calculation; have lipid emulsion ready', managementAr: 'حساب دقيق للجرعة الإجمالية؛ تجهيز المستحلب الدهني' },
      { interactsWith: 'Beta-blockers', severity: 'moderate', mechanism: 'Reduced hepatic metabolism of bupivacaine',
        clinicalEffect: 'Increased plasma levels and toxicity risk', clinicalEffectAr: 'زيادة مستويات البلازما وخطر السمية',
        management: 'Reduce dose; monitor closely', managementAr: 'تقليل الجرعة مع مراقبة وثيقة' },
    ],
    contraindications: ['IV regional anesthesia (Bier block)', 'Obstetric paracervical block (0.75%)', 'Severe heart block'],
    contraindicationsAr: ['التخدير الوريدي الناحي (حصار بيير)', 'الحصار المجاور لعنق الرحم (0.75%)', 'إحصار قلبي شديد'],
    monitoringRequired: ['ECG during large doses', 'Blood pressure', 'CNS toxicity signs', 'Lipid emulsion availability'],
    storageConditions: 'Store at 15–25°C, do not freeze',
  },
  {
    id: 'FRM-0831', genericName: 'Ropivacaine Hydrochloride Injection', genericNameAr: 'روبيفاكايين هيدروكلوريد حقن',
    brandNames: ['Naropin'], sfda_registration: 'SFDA-TOP-0831', atcCode: 'N01BB09',
    atcCategory: 'Anesthetics — Amides', therapeuticClass: 'Local Anesthetic — Long-Acting (Safer Cardiac Profile)',
    therapeuticClassAr: 'مخدر موضعي — طويل المفعول (أقل سمية قلبية)', formularyStatus: 'formulary',
    route: ['injection — local infiltration', 'epidural', 'nerve block'], forms: [
      { form: 'Injection', strength: '0.2% 20ml', unitPrice: 18.00, inStock: true },
      { form: 'Injection', strength: '0.75% 20ml', unitPrice: 22.00, inStock: true },
      { form: 'Infusion', strength: '0.2% 200ml', unitPrice: 45.00, inStock: true },
    ],
    maxDailyDose: 3, maxDailyDoseUnit: 'mg/kg',
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Bupivacaine', 'Levobupivacaine'],
    interactions: [
      { interactsWith: 'Fluvoxamine/CYP1A2 inhibitors', severity: 'moderate', mechanism: 'Reduced ropivacaine metabolism',
        clinicalEffect: 'Increased plasma concentration', clinicalEffectAr: 'زيادة تركيز البلازما',
        management: 'Reduce dose with strong CYP1A2 inhibitors', managementAr: 'تقليل الجرعة مع مثبطات CYP1A2 القوية' },
    ],
    contraindications: ['Amide local anesthetic allergy', 'IV regional anesthesia'],
    contraindicationsAr: ['حساسية لمخدرات الأميد الموضعية', 'التخدير الوريدي الناحي'],
    monitoringRequired: ['Hemodynamic status', 'CNS toxicity signs', 'Motor/sensory block level'],
    storageConditions: 'Store below 30°C, do not freeze',
  },
  {
    id: 'FRM-0832', genericName: 'EMLA Cream (Lidocaine/Prilocaine)', genericNameAr: 'كريم إملا (ليدوكايين/بريلوكايين)',
    brandNames: ['EMLA', 'LMX Plus'], sfda_registration: 'SFDA-TOP-0832', atcCode: 'N01BB20',
    atcCategory: 'Anesthetics — Amides — Combinations', therapeuticClass: 'Topical Anesthetic — Combination',
    therapeuticClassAr: 'مخدر موضعي — تركيبة مزدوجة', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '2.5%/2.5% 5g', unitPrice: 12.00, inStock: true },
      { form: 'Cream', strength: '2.5%/2.5% 30g', unitPrice: 45.00, inStock: true },
      { form: 'Patch', strength: '1g patch', unitPrice: 8.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Lidocaine cream alone', 'Prilocaine injection'],
    blackBoxWarning: 'Methemoglobinemia risk with prilocaine — especially in neonates, G6PD deficiency, and with concurrent methemoglobin-inducing drugs.',
    blackBoxWarningAr: 'خطر ميتهيموغلوبينية الدم مع بريلوكايين — خاصة عند حديثي الولادة ونقص G6PD ومع أدوية أخرى محفزة.',
    interactions: [
      { interactsWith: 'Methemoglobin-inducing drugs (sulfonamides, dapsone, nitrates)', severity: 'major', mechanism: 'Additive methemoglobin formation from prilocaine',
        clinicalEffect: 'Clinical methemoglobinemia (cyanosis, dyspnea)', clinicalEffectAr: 'ميتهيموغلوبينية سريرية (زرقة، ضيق تنفس)',
        management: 'Avoid or minimize application area; monitor SpO2', managementAr: 'تجنب أو تقليل منطقة التطبيق؛ مراقبة SpO2' },
    ],
    contraindications: ['Methemoglobinemia', 'Neonates < 37 weeks gestation', 'Infants < 3 months on methemoglobin inducers'],
    contraindicationsAr: ['ميتهيموغلوبينية الدم', 'حديثي ولادة أقل من 37 أسبوعاً', 'رضع أقل من 3 أشهر مع محفزات الميتهيموغلوبين'],
    monitoringRequired: ['Application time (max 60 min on intact skin)', 'SpO2 in neonates/infants', 'Methemoglobin levels if symptomatic'],
    storageConditions: 'Store below 30°C, do not freeze',
  },

  // ── Dermatological Specialty (4) ──────────────────────────────────
  {
    id: 'FRM-0833', genericName: 'Tretinoin Cream', genericNameAr: 'تريتينوين كريم',
    brandNames: ['Retin-A', 'Stieva-A', 'Acretin'], sfda_registration: 'SFDA-TOP-0833', atcCode: 'D10AD01',
    atcCategory: 'Anti-acne preparations — Retinoids for topical use', therapeuticClass: 'Topical Retinoid',
    therapeuticClassAr: 'ريتينويد موضعي', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '0.025% 20g', unitPrice: 18.00, inStock: true },
      { form: 'Cream', strength: '0.05% 20g', unitPrice: 20.00, inStock: true },
      { form: 'Gel', strength: '0.01% 20g', unitPrice: 16.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'X', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Isotretinoin (oral)', 'Tazarotene'],
    blackBoxWarning: 'Pregnancy Category X — teratogenic. Must ensure negative pregnancy test before prescribing to women of childbearing potential.',
    blackBoxWarningAr: 'فئة الحمل X — مسبب تشوهات. يجب التأكد من سلبية اختبار الحمل قبل الوصف للنساء في سن الإنجاب.',
    interactions: [
      { interactsWith: 'Benzoyl peroxide', severity: 'moderate', mechanism: 'Oxidation and inactivation of tretinoin',
        clinicalEffect: 'Reduced tretinoin efficacy', clinicalEffectAr: 'انخفاض فعالية التريتينوين',
        management: 'Apply at different times (tretinoin PM, benzoyl peroxide AM)', managementAr: 'تطبيق في أوقات مختلفة (تريتينوين مساءً، بنزويل بيروكسيد صباحاً)' },
      { interactsWith: 'Photosensitizing drugs', severity: 'moderate', mechanism: 'Additive photosensitivity',
        clinicalEffect: 'Severe sunburn risk', clinicalEffectAr: 'خطر حروق شمسية شديدة',
        management: 'Strict sun protection; apply SPF 30+ daily', managementAr: 'حماية صارمة من الشمس؛ واقي SPF 30+ يومياً' },
    ],
    contraindications: ['Pregnancy', 'Eczema', 'Sunburn', 'Broken skin'],
    contraindicationsAr: ['الحمل', 'الأكزيما', 'حروق الشمس', 'جلد متهتك'],
    monitoringRequired: ['Pregnancy testing', 'Skin irritation', 'Sun protection compliance'],
    storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0834', genericName: 'Adapalene Gel', genericNameAr: 'أدابالين جل',
    brandNames: ['Differin', 'Adaferin'], sfda_registration: 'SFDA-TOP-0834', atcCode: 'D10AD03',
    atcCategory: 'Anti-acne preparations — Retinoids for topical use', therapeuticClass: 'Topical Retinoid — Third Generation',
    therapeuticClassAr: 'ريتينويد موضعي — الجيل الثالث', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Gel', strength: '0.1% 30g', unitPrice: 22.00, inStock: true },
      { form: 'Cream', strength: '0.1% 30g', unitPrice: 24.00, inStock: true },
      { form: 'Gel (with benzoyl peroxide)', strength: '0.1%/2.5% 30g', unitPrice: 35.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Tretinoin', 'Tazarotene'],
    interactions: [
      { interactsWith: 'Drying/irritating topicals (salicylic acid, sulfur)', severity: 'moderate', mechanism: 'Cumulative irritation',
        clinicalEffect: 'Excessive dryness, peeling, erythema', clinicalEffectAr: 'جفاف مفرط، تقشر، احمرار',
        management: 'Introduce gradually; avoid concurrent irritants initially', managementAr: 'إدخال تدريجي؛ تجنب المهيجات المتزامنة في البداية' },
    ],
    contraindications: ['Pregnancy (precautionary)', 'Sunburned/eczematous skin'],
    contraindicationsAr: ['الحمل (احتياطي)', 'جلد محروق شمسياً أو مصاب بالأكزيما'],
    monitoringRequired: ['Skin tolerability at 2 weeks', 'Sun protection'], storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0835', genericName: 'Calcipotriol Cream', genericNameAr: 'كالسيبوتريول كريم',
    brandNames: ['Dovonex', 'Daivonex', 'Daivobet'], sfda_registration: 'SFDA-TOP-0835', atcCode: 'D05AX02',
    atcCategory: 'Antipsoriatics — Other', therapeuticClass: 'Topical Vitamin D Analogue — Psoriasis',
    therapeuticClassAr: 'نظير فيتامين د موضعي — الصدفية', formularyStatus: 'formulary',
    route: ['topical'], forms: [
      { form: 'Cream', strength: '50mcg/g 30g', unitPrice: 32.00, inStock: true },
      { form: 'Ointment', strength: '50mcg/g 30g', unitPrice: 34.00, inStock: true },
      { form: 'Scalp solution', strength: '50mcg/ml 60ml', unitPrice: 42.00, inStock: true },
    ],
    maxDailyDose: 100, maxDailyDoseUnit: 'g per week',
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Calcitriol', 'Calcitonin'],
    interactions: [
      { interactsWith: 'Calcium supplements / Vitamin D supplements', severity: 'moderate', mechanism: 'Additive hypercalcemia with large-area use',
        clinicalEffect: 'Hypercalcemia (nausea, weakness, confusion)', clinicalEffectAr: 'فرط كالسيوم الدم (غثيان، ضعف، ارتباك)',
        management: 'Limit application to < 100g/week; monitor calcium levels', managementAr: 'حصر التطبيق بأقل من 100غ/أسبوع؛ مراقبة مستويات الكالسيوم' },
    ],
    contraindications: ['Hypercalcemia', 'Severe renal impairment', 'Calcium metabolism disorders'],
    contraindicationsAr: ['فرط كالسيوم الدم', 'قصور كلوي شديد', 'اضطرابات استقلاب الكالسيوم'],
    monitoringRequired: ['Serum calcium (if > 100g/week)', 'Psoriasis severity score'],
    storageConditions: 'Store below 25°C, do not freeze',
  },
  {
    id: 'FRM-0836', genericName: 'Tacrolimus Ointment', genericNameAr: 'تاكروليموس مرهم',
    brandNames: ['Protopic', 'Tacroz'], sfda_registration: 'SFDA-TOP-0836', atcCode: 'D11AH01',
    atcCategory: 'Other dermatological preparations — Agents for dermatitis', therapeuticClass: 'Topical Calcineurin Inhibitor',
    therapeuticClassAr: 'مثبط كالسينيورين موضعي', formularyStatus: 'conditional',
    restrictionCriteria: 'Second-line for atopic dermatitis after topical steroids fail; dermatology specialist initiation',
    restrictionCriteriaAr: 'خط ثانٍ لالتهاب الجلد التأتبي بعد فشل الستيرويدات الموضعية؛ بدء بواسطة أخصائي جلدية',
    approverRole: 'dermatologist', route: ['topical'], forms: [
      { form: 'Ointment', strength: '0.03% 30g', unitPrice: 55.00, inStock: true },
      { form: 'Ointment', strength: '0.1% 30g', unitPrice: 65.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Tacrolimus oral/IV', 'Pimecrolimus'],
    blackBoxWarning: 'FDA black box: potential risk of malignancy (lymphoma, skin cancer). Use minimum amount for shortest duration. Not for children < 2 years.',
    blackBoxWarningAr: 'تحذير FDA: خطر محتمل للأورام الخبيثة (لمفوما، سرطان جلد). استخدام أقل كمية لأقصر مدة. لا يُستخدم للأطفال أقل من سنتين.',
    interactions: [
      { interactsWith: 'CYP3A4 inhibitors (erythromycin, fluconazole)', severity: 'moderate', mechanism: 'Theoretical increased systemic levels with extensive use',
        clinicalEffect: 'Immunosuppression risk on large areas', clinicalEffectAr: 'خطر تثبيط المناعة على مساحات كبيرة',
        management: 'Limit application area; monitor for systemic effects', managementAr: 'تحديد منطقة التطبيق؛ مراقبة التأثيرات الجهازية' },
      { interactsWith: 'Alcohol consumption', severity: 'moderate', mechanism: 'Facial flushing reaction',
        clinicalEffect: 'Facial erythema and warmth after alcohol', clinicalEffectAr: 'احمرار الوجه ودفء بعد الكحول',
        management: 'Counsel patient about this reaction', managementAr: 'توعية المريض بهذا التفاعل' },
    ],
    contraindications: ['Children < 2 years', 'Netherton syndrome', 'Generalized erythroderma', 'Immunocompromised patients'],
    contraindicationsAr: ['أطفال أقل من سنتين', 'متلازمة نيذرتون', 'احمرار الجلد المعمم', 'مرضى نقص المناعة'],
    monitoringRequired: ['Skin cancer surveillance', 'Lymphadenopathy', 'UV exposure minimization'],
    storageConditions: 'Store at 15–25°C',
  },

  // ── Oral/Dental Topical (3) ───────────────────────────────────────
  {
    id: 'FRM-0837', genericName: 'Chlorhexidine Gluconate Mouthwash', genericNameAr: 'غسول فم كلورهيكسيدين جلوكونات',
    brandNames: ['Corsodyl', 'Peridex', 'Paroex'], sfda_registration: 'SFDA-TOP-0837', atcCode: 'A01AB03',
    atcCategory: 'Stomatological preparations — Antiinfectives for local oral treatment', therapeuticClass: 'Oral Antiseptic Mouthwash',
    therapeuticClassAr: 'غسول فم مطهر', formularyStatus: 'formulary',
    route: ['oral rinse'], forms: [
      { form: 'Mouthwash', strength: '0.12% 300ml', unitPrice: 15.00, inStock: true },
      { form: 'Mouthwash', strength: '0.2% 300ml', unitPrice: 18.00, inStock: true },
      { form: 'Oral gel', strength: '1% 50g', unitPrice: 20.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Chlorhexidine surgical scrub (not for oral use)', 'Cetylpyridinium chloride'],
    interactions: [
      { interactsWith: 'Toothpaste (sodium lauryl sulfate)', severity: 'minor', mechanism: 'Anionic surfactant reduces chlorhexidine binding',
        clinicalEffect: 'Reduced antimicrobial efficacy', clinicalEffectAr: 'انخفاض الفعالية المضادة للميكروبات',
        management: 'Wait 30 minutes after brushing before using mouthwash', managementAr: 'الانتظار 30 دقيقة بعد تنظيف الأسنان قبل استخدام الغسول' },
    ],
    contraindications: ['Known chlorhexidine allergy'],
    contraindicationsAr: ['حساسية معروفة للكلورهيكسيدين'],
    monitoringRequired: ['Tooth staining (reversible)', 'Taste alteration', 'Oral mucosa condition'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0838', genericName: 'Benzocaine Oral Gel', genericNameAr: 'بنزوكايين جل فموي',
    brandNames: ['Orajel', 'Anbesol', 'Bonjela'], sfda_registration: 'SFDA-TOP-0838', atcCode: 'A01AD11',
    atcCategory: 'Stomatological preparations — Other agents for local oral treatment', therapeuticClass: 'Oral Topical Anesthetic',
    therapeuticClassAr: 'مخدر موضعي فموي', formularyStatus: 'formulary',
    route: ['oral topical'], forms: [
      { form: 'Oral gel', strength: '20% 10g', unitPrice: 12.00, inStock: true },
      { form: 'Oral gel (pediatric)', strength: '7.5% 10g', unitPrice: 10.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Benzocaine spray', 'Benzonatate (cough)'],
    blackBoxWarning: 'Methemoglobinemia risk, especially in children < 2 years. FDA warns against use in teething infants.',
    blackBoxWarningAr: 'خطر ميتهيموغلوبينية الدم، خاصة عند الأطفال أقل من سنتين. تحذير FDA ضد الاستخدام لتسكين آلام التسنين عند الرضع.',
    interactions: [
      { interactsWith: 'Other methemoglobin inducers (prilocaine, sulfonamides, dapsone)', severity: 'major',
        mechanism: 'Additive methemoglobin formation', clinicalEffect: 'Clinical methemoglobinemia',
        clinicalEffectAr: 'ميتهيموغلوبينية سريرية',
        management: 'Avoid concurrent use; monitor oxygen saturation', managementAr: 'تجنب الاستخدام المتزامن؛ مراقبة تشبع الأكسجين' },
    ],
    contraindications: ['Children < 2 years', 'Methemoglobinemia', 'G6PD deficiency'],
    contraindicationsAr: ['أطفال أقل من سنتين', 'ميتهيموغلوبينية الدم', 'نقص G6PD'],
    monitoringRequired: ['Duration of use', 'SpO2 in young children', 'Methemoglobin level if symptomatic'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0839', genericName: 'Nystatin Oral Suspension', genericNameAr: 'نيستاتين معلق فموي',
    brandNames: ['Mycostatin Oral', 'Nilstat', 'Nystex'], sfda_registration: 'SFDA-TOP-0839', atcCode: 'A07AA02',
    atcCategory: 'Intestinal antiinfectives — Antibiotics', therapeuticClass: 'Oral Antifungal — Topical Action',
    therapeuticClassAr: 'مضاد فطريات فموي — تأثير موضعي', formularyStatus: 'formulary',
    route: ['oral'], forms: [
      { form: 'Oral suspension', strength: '100,000 IU/ml 30ml', unitPrice: 14.00, inStock: true },
      { form: 'Oral suspension', strength: '100,000 IU/ml 60ml', unitPrice: 22.00, inStock: true },
    ],
    maxDailyDose: 400000, maxDailyDoseUnit: 'IU (infants); 2,000,000 IU (adults)',
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Nystatin cream (topical)', 'Natamycin'],
    interactions: [
      { interactsWith: 'No clinically significant interactions', severity: 'minor', mechanism: 'Not systemically absorbed from GI tract',
        clinicalEffect: 'None expected', clinicalEffectAr: 'لا يُتوقع تفاعلات',
        management: 'None required', managementAr: 'لا يتطلب إجراء' },
    ],
    contraindications: ['Hypersensitivity to nystatin'],
    contraindicationsAr: ['فرط حساسية للنيستاتين'],
    monitoringRequired: ['Oral candidiasis resolution (7–14 days)', 'Compliance with swish-and-swallow technique'],
    storageConditions: 'Store at 2–25°C, shake well before use',
  },
];
