/**
 * Saudi MOH Drug Formulary — Drug Data Part 3
 * Anticoagulants, Extended Antihypertensives, Antiplatelets, Lipid-Lowering Agents
 */

import type { FormularyDrug } from './formularyTypes';

// ─── ANTICOAGULANTS (15) ─────────────────────────────────────────────────────

export const ANTICOAGULANTS: FormularyDrug[] = [
  {
    id: 'FRM-0080', genericName: 'Warfarin', genericNameAr: 'وارفارين',
    brandNames: ['Coumadin', 'Marevan'], sfda_registration: 'SFDA-2024-WAR-080',
    atcCode: 'B01AA03', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '1mg', unitPrice: 0.4, inStock: true },
      { form: 'tablet', strength: '2mg', unitPrice: 0.4, inStock: true },
      { form: 'tablet', strength: '5mg', unitPrice: 0.5, inStock: true },
    ],
    maxDailyDose: 15, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Warfarin/Wafarin (spelling)', 'Coumadin/Kemadrin'],
    blackBoxWarning: 'Major or fatal bleeding. Regular INR monitoring required.',
    blackBoxWarningAr: 'نزيف كبير أو مميت. يتطلب مراقبة INR منتظمة.',
    interactions: [
      { interactsWith: 'Amoxicillin', severity: 'moderate', mechanism: 'Altered gut flora affecting vitamin K synthesis',
        clinicalEffect: 'Increased INR and bleeding risk', clinicalEffectAr: 'زيادة INR وخطر النزيف',
        management: 'Monitor INR within 3-5 days of antibiotic start', managementAr: 'مراقبة INR خلال 3-5 أيام من بدء المضاد الحيوي' },
      { interactsWith: 'Aspirin', severity: 'major', mechanism: 'Additive anticoagulant/antiplatelet effect',
        clinicalEffect: 'Significantly increased bleeding risk', clinicalEffectAr: 'زيادة كبيرة في خطر النزيف',
        management: 'Avoid unless specifically indicated; monitor closely', managementAr: 'تجنب إلا إذا كان هناك مبرر محدد؛ مراقبة دقيقة' },
    ],
    contraindications: ['Active bleeding', 'Hemorrhagic stroke', 'Severe hepatic disease', 'Pregnancy'],
    contraindicationsAr: ['نزيف نشط', 'سكتة نزفية', 'مرض كبدي شديد', 'الحمل'],
    monitoringRequired: ['INR (target 2-3 for most indications)', 'Signs of bleeding', 'Hgb/Hct', 'Dietary vitamin K intake'],
    storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0081', genericName: 'Heparin (Unfractionated)', genericNameAr: 'هيبارين (غير مجزأ)',
    brandNames: ['Heparin Leo', 'Heparin Sodium'], sfda_registration: 'SFDA-2024-HEP-081',
    atcCode: 'B01AB01', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['iv', 'sc'],
    forms: [
      { form: 'injection', strength: '5000 IU/ml (5ml vial)', unitPrice: 12.0, inStock: true },
      { form: 'injection', strength: '25000 IU/5ml', unitPrice: 18.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Heparin/Hespan'],
    blackBoxWarning: 'HIT (heparin-induced thrombocytopenia) can be fatal. Monitor platelets.',
    blackBoxWarningAr: 'قلة الصفيحات المحرضة بالهيبارين (HIT) قد تكون مميتة. راقب الصفيحات.',
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Additive anticoagulation',
        clinicalEffect: 'Excessive bleeding', clinicalEffectAr: 'نزيف مفرط',
        management: 'Overlap carefully during transition; monitor aPTT and INR', managementAr: 'تداخل بحذر أثناء الانتقال؛ مراقبة aPTT و INR' },
    ],
    contraindications: ['Active major bleeding', 'History of HIT', 'Severe thrombocytopenia'],
    contraindicationsAr: ['نزيف كبير نشط', 'تاريخ HIT', 'قلة صفيحات شديدة'],
    monitoringRequired: ['aPTT every 6h (target 1.5-2.5x control)', 'Platelets baseline + q2-3 days', 'Anti-Xa if obese', 'Signs of HIT'],
    storageConditions: 'Store below 25°C. Do not freeze.',
  },
  {
    id: 'FRM-0082', genericName: 'Enoxaparin', genericNameAr: 'إينوكسابارين',
    brandNames: ['Clexane', 'Lovenox'], sfda_registration: 'SFDA-2024-ENO-082',
    atcCode: 'B01AB05', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['sc', 'iv'],
    forms: [
      { form: 'injection', strength: '40mg/0.4ml syringe', unitPrice: 22.0, inStock: true },
      { form: 'injection', strength: '60mg/0.6ml syringe', unitPrice: 32.0, inStock: true },
      { form: 'injection', strength: '80mg/0.8ml syringe', unitPrice: 40.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Enoxaparin/Dalteparin'],
    interactions: [
      { interactsWith: 'Aspirin', severity: 'major', mechanism: 'Additive bleeding risk',
        clinicalEffect: 'Increased hemorrhagic events', clinicalEffectAr: 'زيادة الأحداث النزفية',
        management: 'Use with caution; monitor for bleeding', managementAr: 'استخدام بحذر؛ مراقبة النزيف' },
    ],
    contraindications: ['Active major bleeding', 'History of HIT with LMWH', 'Severe renal impairment (CrCl <15)'],
    contraindicationsAr: ['نزيف كبير نشط', 'تاريخ HIT مع هيبارين منخفض الوزن', 'قصور كلوي شديد'],
    monitoringRequired: ['Anti-Xa levels (renal impairment/extremes of weight)', 'Platelets', 'Renal function', 'Signs of bleeding'],
    storageConditions: 'Store below 25°C. Do not freeze.',
  },
  {
    id: 'FRM-0083', genericName: 'Dalteparin', genericNameAr: 'دالتيبارين',
    brandNames: ['Fragmin'], sfda_registration: 'SFDA-2024-DAL-083',
    atcCode: 'B01AB04', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['sc', 'iv'],
    forms: [
      { form: 'injection', strength: '5000 IU/0.2ml syringe', unitPrice: 25.0, inStock: true },
      { form: 'injection', strength: '10000 IU/ml syringe', unitPrice: 45.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Dalteparin/Enoxaparin'],
    interactions: [
      { interactsWith: 'Ketorolac', severity: 'major', mechanism: 'Additive bleeding risk with NSAIDs',
        clinicalEffect: 'Increased hemorrhage risk', clinicalEffectAr: 'زيادة خطر النزيف',
        management: 'Avoid concurrent use if possible', managementAr: 'تجنب الاستخدام المتزامن إذا أمكن' },
    ],
    contraindications: ['Active bleeding', 'History of HIT', 'Unstable angina receiving dalteparin in presence of prosthetic valve'],
    contraindicationsAr: ['نزيف نشط', 'تاريخ HIT', 'ذبحة غير مستقرة مع صمام صناعي'],
    monitoringRequired: ['Anti-Xa levels if renal impairment', 'Platelets', 'Signs of bleeding'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0084', genericName: 'Fondaparinux', genericNameAr: 'فوندابارينوكس',
    brandNames: ['Arixtra'], sfda_registration: 'SFDA-2024-FON-084',
    atcCode: 'B01AX05', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['sc'],
    forms: [
      { form: 'injection', strength: '2.5mg/0.5ml syringe', unitPrice: 35.0, inStock: true },
      { form: 'injection', strength: '7.5mg/0.6ml syringe', unitPrice: 55.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Fondaparinux/Enoxaparin'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Additive anticoagulation',
        clinicalEffect: 'Increased bleeding risk during overlap', clinicalEffectAr: 'زيادة خطر النزيف أثناء التداخل',
        management: 'Monitor closely during transition period', managementAr: 'مراقبة دقيقة أثناء فترة الانتقال' },
    ],
    contraindications: ['Active major bleeding', 'Severe renal impairment (CrCl <20)', 'Body weight <50kg (increased bleeding risk)', 'Bacterial endocarditis'],
    contraindicationsAr: ['نزيف كبير نشط', 'قصور كلوي شديد', 'وزن أقل من 50 كغ', 'التهاب شغاف جرثومي'],
    monitoringRequired: ['Anti-Xa levels', 'Renal function', 'CBC', 'Signs of bleeding'],
    storageConditions: 'Store below 25°C. Do not freeze.',
  },
  {
    id: 'FRM-0085', genericName: 'Rivaroxaban', genericNameAr: 'ريفاروكسابان',
    brandNames: ['Xarelto'], sfda_registration: 'SFDA-2024-RIV-085',
    atcCode: 'B01AF01', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '10mg', unitPrice: 8.5, inStock: true },
      { form: 'tablet', strength: '15mg', unitPrice: 9.0, inStock: true },
      { form: 'tablet', strength: '20mg', unitPrice: 9.5, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Rivaroxaban/Apixaban'],
    interactions: [
      { interactsWith: 'Ketoconazole', severity: 'major', mechanism: 'Strong CYP3A4/P-gp inhibition',
        clinicalEffect: 'Significantly increased rivaroxaban levels and bleeding risk', clinicalEffectAr: 'زيادة كبيرة في مستوى ريفاروكسابان وخطر النزيف',
        management: 'Avoid concomitant use', managementAr: 'تجنب الاستخدام المتزامن' },
      { interactsWith: 'Rifampin', severity: 'major', mechanism: 'Strong CYP3A4/P-gp induction',
        clinicalEffect: 'Decreased rivaroxaban levels; loss of efficacy', clinicalEffectAr: 'انخفاض مستوى ريفاروكسابان؛ فقدان الفعالية',
        management: 'Avoid concomitant use', managementAr: 'تجنب الاستخدام المتزامن' },
    ],
    contraindications: ['Active pathological bleeding', 'Hepatic disease with coagulopathy', 'Pregnancy'],
    contraindicationsAr: ['نزيف مرضي نشط', 'مرض كبدي مع اعتلال تخثر', 'الحمل'],
    monitoringRequired: ['Renal function', 'Hepatic function', 'Signs of bleeding', 'Hgb/Hct'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0086', genericName: 'Apixaban', genericNameAr: 'أبيكسابان',
    brandNames: ['Eliquis'], sfda_registration: 'SFDA-2024-API-086',
    atcCode: 'B01AF02', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '2.5mg', unitPrice: 8.0, inStock: true },
      { form: 'tablet', strength: '5mg', unitPrice: 9.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Apixaban/Rivaroxaban', 'Eliquis/Effient'],
    interactions: [
      { interactsWith: 'Ketoconazole', severity: 'major', mechanism: 'Dual CYP3A4/P-gp inhibition',
        clinicalEffect: 'Doubled apixaban exposure; bleeding risk', clinicalEffectAr: 'مضاعفة التعرض لأبيكسابان؛ خطر النزيف',
        management: 'Reduce apixaban dose by 50% or avoid', managementAr: 'تقليل جرعة أبيكسابان 50% أو تجنب' },
    ],
    contraindications: ['Active pathological bleeding', 'Severe hepatic impairment (Child-Pugh C)'],
    contraindicationsAr: ['نزيف مرضي نشط', 'قصور كبدي شديد (Child-Pugh C)'],
    monitoringRequired: ['Renal function', 'Hepatic function', 'Signs of bleeding', 'Anti-Xa (if needed)'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0087', genericName: 'Edoxaban', genericNameAr: 'إيدوكسابان',
    brandNames: ['Lixiana', 'Savaysa'], sfda_registration: 'SFDA-2024-EDO-087',
    atcCode: 'B01AF03', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '30mg', unitPrice: 9.0, inStock: true },
      { form: 'tablet', strength: '60mg', unitPrice: 10.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Edoxaban/Apixaban'],
    blackBoxWarning: 'Reduced efficacy in nonvalvular AF patients with CrCl >95 mL/min.',
    blackBoxWarningAr: 'فعالية منخفضة في مرضى الرجفان الأذيني غير الصمامي مع CrCl أكثر من 95.',
    interactions: [
      { interactsWith: 'Rifampin', severity: 'major', mechanism: 'P-gp induction',
        clinicalEffect: 'Decreased edoxaban levels', clinicalEffectAr: 'انخفاض مستوى إيدوكسابان',
        management: 'Avoid concomitant use', managementAr: 'تجنب الاستخدام المتزامن' },
    ],
    contraindications: ['Active pathological bleeding', 'CrCl >95 mL/min (AF indication)'],
    contraindicationsAr: ['نزيف مرضي نشط', 'تصفية كرياتينين أعلى من 95 (لمؤشر الرجفان الأذيني)'],
    monitoringRequired: ['Renal function (before and during)', 'Signs of bleeding', 'CBC'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0088', genericName: 'Dabigatran', genericNameAr: 'دابيغاتران',
    brandNames: ['Pradaxa'], sfda_registration: 'SFDA-2024-DAB-088',
    atcCode: 'B01AE07', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'capsule', strength: '75mg', unitPrice: 7.0, inStock: true },
      { form: 'capsule', strength: '110mg', unitPrice: 8.5, inStock: true },
      { form: 'capsule', strength: '150mg', unitPrice: 9.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Pradaxa/Plavix'],
    blackBoxWarning: 'Do not crush or open capsules — bioavailability increases 75% if capsule opened.',
    blackBoxWarningAr: 'لا تسحق أو تفتح الكبسولات — التوافر الحيوي يزداد 75% إذا فُتحت.',
    interactions: [
      { interactsWith: 'Dronedarone', severity: 'major', mechanism: 'P-gp inhibition',
        clinicalEffect: 'Increased dabigatran levels; bleeding', clinicalEffectAr: 'زيادة مستوى دابيغاتران؛ نزيف',
        management: 'Contraindicated combination', managementAr: 'مزيج ممنوع' },
      { interactsWith: 'Ketoconazole', severity: 'major', mechanism: 'P-gp inhibition',
        clinicalEffect: 'Increased dabigatran exposure', clinicalEffectAr: 'زيادة التعرض لدابيغاتران',
        management: 'Reduce dose or avoid in renal impairment', managementAr: 'تقليل الجرعة أو تجنب مع القصور الكلوي' },
    ],
    contraindications: ['Active pathological bleeding', 'Mechanical prosthetic heart valve', 'Severe renal impairment (CrCl <30)'],
    contraindicationsAr: ['نزيف مرضي نشط', 'صمام قلب صناعي ميكانيكي', 'قصور كلوي شديد'],
    monitoringRequired: ['Renal function before and during treatment', 'aPTT (qualitative)', 'Ecarin clotting time', 'Signs of bleeding'],
    storageConditions: 'Store in original packaging. Protect from moisture. Store below 30°C.',
  },
  {
    id: 'FRM-0089', genericName: 'Bivalirudin', genericNameAr: 'بيفاليرودين',
    brandNames: ['Angiomax', 'Angiox'], sfda_registration: 'SFDA-2024-BIV-089',
    atcCode: 'B01AE06', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'restricted', route: ['iv'],
    restrictionCriteria: 'Cardiology/interventional use only. HIT alternative.',
    restrictionCriteriaAr: 'استخدام أمراض القلب/التداخلي فقط. بديل HIT.',
    approverRole: 'cardiologist',
    forms: [
      { form: 'injection', strength: '250mg vial', unitPrice: 350.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Bivalirudin/Argatroban'],
    interactions: [
      { interactsWith: 'Heparin (Unfractionated)', severity: 'major', mechanism: 'Additive anticoagulation',
        clinicalEffect: 'Excessive bleeding', clinicalEffectAr: 'نزيف مفرط',
        management: 'Do not use concurrently', managementAr: 'عدم الاستخدام المتزامن' },
    ],
    contraindications: ['Active major bleeding', 'Hypersensitivity to bivalirudin or hirudin'],
    contraindicationsAr: ['نزيف كبير نشط', 'فرط حساسية للبيفاليرودين أو الهيرودين'],
    monitoringRequired: ['ACT during PCI', 'aPTT', 'Signs of bleeding', 'Renal function'],
    storageConditions: 'Store below 25°C. Reconstituted: use within 24h.',
  },
  {
    id: 'FRM-0090', genericName: 'Argatroban', genericNameAr: 'أرغاتروبان',
    brandNames: ['Argatroban Injection', 'Novastan'], sfda_registration: 'SFDA-2024-ARG-090',
    atcCode: 'B01AE03', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'restricted', route: ['iv'],
    restrictionCriteria: 'HIT-confirmed patients only. Hematology approval required.',
    restrictionCriteriaAr: 'مرضى HIT المؤكدين فقط. يتطلب موافقة أمراض الدم.',
    approverRole: 'hematologist',
    forms: [
      { form: 'injection', strength: '100mg/ml (2.5ml vial)', unitPrice: 280.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Argatroban/Bivalirudin'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Argatroban elevates INR independently',
        clinicalEffect: 'Falsely elevated INR during overlap; complex transition', clinicalEffectAr: 'ارتفاع INR زائف أثناء التداخل؛ انتقال معقد',
        management: 'Use chromogenic factor X assay for warfarin monitoring during overlap', managementAr: 'استخدام فحص العامل X الكروموجيني لمراقبة الوارفارين أثناء التداخل' },
    ],
    contraindications: ['Active major bleeding', 'Severe hepatic impairment'],
    contraindicationsAr: ['نزيف كبير نشط', 'قصور كبدي شديد'],
    monitoringRequired: ['aPTT q2h until stable (target 1.5-3x baseline)', 'INR for warfarin transition', 'LFTs', 'Signs of bleeding'],
    storageConditions: 'Store below 25°C. Protect from light. Diluted solution: use within 24h.',
  },
  {
    id: 'FRM-0091', genericName: 'Protamine Sulfate', genericNameAr: 'بروتامين سلفات',
    brandNames: ['Protamine Sulfate Injection'], sfda_registration: 'SFDA-2024-PRT-091',
    atcCode: 'V03AB14', atcCategory: 'V03 - All other therapeutic products',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['iv'],
    forms: [
      { form: 'injection', strength: '10mg/ml (5ml vial)', unitPrice: 25.0, inStock: true },
      { form: 'injection', strength: '50mg/5ml vial', unitPrice: 30.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Protamine/Protonix'],
    interactions: [
      { interactsWith: 'Heparin (Unfractionated)', severity: 'major', mechanism: 'Heparin reversal agent — ionic binding',
        clinicalEffect: 'Neutralizes heparin anticoagulant effect', clinicalEffectAr: 'يبطل تأثير الهيبارين المضاد للتخثر',
        management: '1mg protamine per 100 units heparin given in last 2-3h', managementAr: '1 ملغ بروتامين لكل 100 وحدة هيبارين في آخر 2-3 ساعات' },
    ],
    contraindications: ['Fish allergy (relative)', 'Previous protamine reactions'],
    contraindicationsAr: ['حساسية السمك (نسبي)', 'تفاعلات بروتامين سابقة'],
    monitoringRequired: ['aPTT after administration', 'Blood pressure (hypotension risk)', 'Anaphylaxis monitoring 30min'],
    storageConditions: 'Store 2-8°C. Do not freeze.',
  },
  {
    id: 'FRM-0092', genericName: 'Phytonadione (Vitamin K1)', genericNameAr: 'فيتونادايون (فيتامين ك1)',
    brandNames: ['Konakion', 'Mephyton'], sfda_registration: 'SFDA-2024-PHK-092',
    atcCode: 'B02BA01', atcCategory: 'B02 - Antihemorrhagics',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'sc', 'im'],
    forms: [
      { form: 'tablet', strength: '5mg', unitPrice: 2.0, inStock: true },
      { form: 'injection', strength: '10mg/ml (1ml ampoule)', unitPrice: 8.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Vitamin K1/Vitamin K3'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Direct pharmacologic antagonism',
        clinicalEffect: 'Reversal of anticoagulant effect; risk of thrombosis if overused', clinicalEffectAr: 'عكس تأثير مضاد التخثر؛ خطر تجلط إذا أُفرط',
        management: 'Use specific doses based on INR; avoid large doses', managementAr: 'استخدام جرعات محددة حسب INR؛ تجنب الجرعات الكبيرة' },
    ],
    contraindications: ['Hypersensitivity to phytonadione'],
    contraindicationsAr: ['فرط حساسية للفيتونادايون'],
    monitoringRequired: ['INR after administration', 'Repeat INR at 6-12h', 'Anaphylaxis with IV (administer slowly)'],
    storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0093', genericName: 'Tranexamic Acid', genericNameAr: 'حمض الترانيكساميك',
    brandNames: ['Cyklokapron', 'Lysteda'], sfda_registration: 'SFDA-2024-TXA-093',
    atcCode: 'B02AA02', atcCategory: 'B02 - Antihemorrhagics',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [
      { form: 'tablet', strength: '500mg', unitPrice: 1.5, inStock: true },
      { form: 'injection', strength: '100mg/ml (5ml ampoule)', unitPrice: 8.0, inStock: true },
    ],
    maxDailyDose: 4000, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Tranexamic Acid/Tramadol'],
    interactions: [
      { interactsWith: 'Factor IX Complex', severity: 'major', mechanism: 'Additive thrombotic risk',
        clinicalEffect: 'Increased risk of thromboembolism', clinicalEffectAr: 'زيادة خطر الانصمام الخثاري',
        management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['Active thromboembolic disease', 'History of convulsions', 'Subarachnoid hemorrhage'],
    contraindicationsAr: ['مرض انصمام خثاري نشط', 'تاريخ نوبات تشنجية', 'نزف تحت العنكبوتية'],
    monitoringRequired: ['Signs of thromboembolism', 'Visual changes (long-term use)', 'Renal function'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0094', genericName: 'Aminocaproic Acid', genericNameAr: 'حمض الأمينوكابرويك',
    brandNames: ['Amicar'], sfda_registration: 'SFDA-2024-ACA-094',
    atcCode: 'B02AA01', atcCategory: 'B02 - Antihemorrhagics',
    therapeuticClass: 'Anticoagulants', therapeuticClassAr: 'مضادات التخثر',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [
      { form: 'tablet', strength: '500mg', unitPrice: 2.0, inStock: true },
      { form: 'injection', strength: '250mg/ml (20ml vial)', unitPrice: 18.0, inStock: true },
      { form: 'syrup', strength: '250mg/ml', unitPrice: 25.0, inStock: true },
    ],
    maxDailyDose: 30000, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Aminocaproic Acid/Tranexamic Acid'],
    interactions: [
      { interactsWith: 'Factor IX Complex', severity: 'major', mechanism: 'Additive thrombotic risk',
        clinicalEffect: 'Thromboembolism', clinicalEffectAr: 'انصمام خثاري',
        management: 'Do not use within 12h of factor administration', managementAr: 'عدم الاستخدام خلال 12 ساعة من إعطاء العامل' },
    ],
    contraindications: ['Active intravascular clotting (DIC)', 'Upper urinary tract bleeding (risk of clot obstruction)'],
    contraindicationsAr: ['تخثر وعائي نشط (DIC)', 'نزيف المسالك البولية العلوية (خطر انسداد الجلطة)'],
    monitoringRequired: ['CPK (myopathy risk)', 'Renal function', 'Signs of thrombosis', 'Urinalysis'],
    storageConditions: 'Store below 30°C',
  },
];

// ─── ANTIHYPERTENSIVES EXTENDED (20) ─────────────────────────────────────────

export const ANTIHYPERTENSIVES_EXT: FormularyDrug[] = [
  {
    id: 'FRM-0095', genericName: 'Amlodipine', genericNameAr: 'أملوديبين',
    brandNames: ['Norvasc', 'Amlor'], sfda_registration: 'SFDA-2024-AML-095',
    atcCode: 'C08CA01', atcCategory: 'C08 - Calcium channel blockers',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '5mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 0.8, inStock: true },
    ],
    maxDailyDose: 10, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Amlodipine/Amiloride', 'Norvasc/Navane'],
    interactions: [
      { interactsWith: 'Simvastatin', severity: 'moderate', mechanism: 'CYP3A4 inhibition',
        clinicalEffect: 'Increased simvastatin levels; myopathy risk', clinicalEffectAr: 'زيادة مستوى سيمفاستاتين؛ خطر اعتلال عضلي',
        management: 'Limit simvastatin to 20mg/day with amlodipine', managementAr: 'تحديد سيمفاستاتين بـ 20 ملغ/يوم مع أملوديبين' },
    ],
    contraindications: ['Severe aortic stenosis', 'Cardiogenic shock', 'Unstable angina'],
    contraindicationsAr: ['تضيق أبهري شديد', 'صدمة قلبية', 'ذبحة غير مستقرة'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'Peripheral edema'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0096', genericName: 'Nifedipine', genericNameAr: 'نيفيديبين',
    brandNames: ['Adalat', 'Procardia'], sfda_registration: 'SFDA-2024-NIF-096',
    atcCode: 'C08CA05', atcCategory: 'C08 - Calcium channel blockers',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '30mg (XL)', unitPrice: 1.2, inStock: true },
      { form: 'tablet', strength: '60mg (XL)', unitPrice: 2.0, inStock: true },
    ],
    maxDailyDose: 120, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Nifedipine/Nicardipine/Nimodipine'],
    interactions: [
      { interactsWith: 'Rifampin', severity: 'major', mechanism: 'CYP3A4 induction',
        clinicalEffect: 'Reduced nifedipine effect', clinicalEffectAr: 'تقليل تأثير نيفيديبين',
        management: 'Avoid combination or use alternative antihypertensive', managementAr: 'تجنب الجمع أو استخدام خافض ضغط بديل' },
    ],
    contraindications: ['Cardiogenic shock', 'Advanced aortic stenosis', 'Acute MI (immediate-release)'],
    contraindicationsAr: ['صدمة قلبية', 'تضيق أبهري متقدم', 'احتشاء حاد (سريع التحرر)'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'Peripheral edema'],
    storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0097', genericName: 'Diltiazem', genericNameAr: 'ديلتيازيم',
    brandNames: ['Cardizem', 'Tilazem'], sfda_registration: 'SFDA-2024-DIL-097',
    atcCode: 'C08DB01', atcCategory: 'C08 - Calcium channel blockers',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [
      { form: 'tablet', strength: '60mg', unitPrice: 0.8, inStock: true },
      { form: 'capsule', strength: '120mg (CD)', unitPrice: 2.0, inStock: true },
      { form: 'injection', strength: '25mg/5ml', unitPrice: 15.0, inStock: true },
    ],
    maxDailyDose: 480, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Diltiazem/Diazepam', 'Cardizem/Cardene'],
    interactions: [
      { interactsWith: 'Simvastatin', severity: 'major', mechanism: 'CYP3A4 inhibition',
        clinicalEffect: 'Increased statin levels; rhabdomyolysis risk', clinicalEffectAr: 'زيادة مستوى الستاتين؛ خطر انحلال الربيدات',
        management: 'Limit simvastatin to 10mg/day', managementAr: 'تحديد سيمفاستاتين بـ 10 ملغ/يوم' },
    ],
    contraindications: ['Sick sinus syndrome (without pacemaker)', 'Second/third degree AV block', 'Severe hypotension', 'Acute MI with pulmonary congestion'],
    contraindicationsAr: ['متلازمة العقدة الجيبية المريضة (بدون ناظم)', 'إحصار AV من الدرجة الثانية/الثالثة', 'انخفاض ضغط شديد', 'احتشاء حاد مع احتقان رئوي'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'ECG (PR interval)', 'LFTs with long-term use'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0098', genericName: 'Verapamil', genericNameAr: 'فيراباميل',
    brandNames: ['Isoptin', 'Calan'], sfda_registration: 'SFDA-2024-VER-098',
    atcCode: 'C08DA01', atcCategory: 'C08 - Calcium channel blockers',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [
      { form: 'tablet', strength: '80mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '240mg (SR)', unitPrice: 2.5, inStock: true },
      { form: 'injection', strength: '5mg/2ml', unitPrice: 10.0, inStock: true },
    ],
    maxDailyDose: 480, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Verapamil/Verelan', 'Isoptin/Isopto'],
    interactions: [
      { interactsWith: 'Metoprolol', severity: 'major', mechanism: 'Additive AV nodal suppression',
        clinicalEffect: 'Severe bradycardia and heart block', clinicalEffectAr: 'بطء قلب شديد وإحصار قلبي',
        management: 'Avoid IV verapamil with IV beta-blockers; oral combination with caution', managementAr: 'تجنب فيراباميل وريدي مع حاصرات بيتا وريدية' },
      { interactsWith: 'Digoxin', severity: 'major', mechanism: 'Inhibits P-gp efflux of digoxin',
        clinicalEffect: 'Increased digoxin levels; toxicity', clinicalEffectAr: 'زيادة مستوى الديجوكسين؛ سمية',
        management: 'Reduce digoxin dose by 25-50%; monitor levels', managementAr: 'تقليل جرعة الديجوكسين 25-50%؛ مراقبة المستويات' },
    ],
    contraindications: ['Severe LV dysfunction', 'Second/third degree AV block', 'Sick sinus syndrome', 'Concurrent IV beta-blockers'],
    contraindicationsAr: ['خلل شديد في البطين الأيسر', 'إحصار AV من الدرجة الثانية/الثالثة', 'متلازمة العقدة الجيبية المريضة', 'حاصرات بيتا وريدية متزامنة'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'ECG', 'LFTs', 'Constipation'],
    storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0099', genericName: 'Losartan', genericNameAr: 'لوسارتان',
    brandNames: ['Cozaar', 'Losartan SPIMACO'], sfda_registration: 'SFDA-2024-LOS-099',
    atcCode: 'C09CA01', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '50mg', unitPrice: 0.6, inStock: true },
      { form: 'tablet', strength: '100mg', unitPrice: 1.0, inStock: true },
    ],
    maxDailyDose: 100, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Losartan/Lorazepam', 'Cozaar/Zocor'],
    blackBoxWarning: 'Can cause fetal harm. Discontinue as soon as pregnancy is detected.',
    blackBoxWarningAr: 'يمكن أن يسبب ضرراً للجنين. يجب التوقف فور اكتشاف الحمل.',
    interactions: [
      { interactsWith: 'Potassium Chloride', severity: 'moderate', mechanism: 'Reduced aldosterone; potassium retention',
        clinicalEffect: 'Hyperkalemia', clinicalEffectAr: 'فرط البوتاسيوم',
        management: 'Monitor potassium; avoid supplements unless hypokalemic', managementAr: 'مراقبة البوتاسيوم؛ تجنب المكملات إلا في نقص البوتاسيوم' },
    ],
    contraindications: ['Pregnancy', 'Bilateral renal artery stenosis', 'Concurrent aliskiren in diabetic patients'],
    contraindicationsAr: ['الحمل', 'تضيق ثنائي في الشريان الكلوي', 'أليسكيرين المتزامن في مرضى السكري'],
    monitoringRequired: ['Blood pressure', 'Serum potassium', 'Renal function (BUN/Cr)', 'Pregnancy test before starting'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0100', genericName: 'Valsartan', genericNameAr: 'فالسارتان',
    brandNames: ['Diovan', 'Tareg'], sfda_registration: 'SFDA-2024-VAL-100',
    atcCode: 'C09CA03', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '80mg', unitPrice: 1.0, inStock: true },
      { form: 'tablet', strength: '160mg', unitPrice: 1.8, inStock: true },
      { form: 'tablet', strength: '320mg', unitPrice: 3.0, inStock: true },
    ],
    maxDailyDose: 320, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Valsartan/Losartan', 'Diovan/Darvon'],
    blackBoxWarning: 'Can cause fetal harm. Discontinue as soon as pregnancy is detected.',
    blackBoxWarningAr: 'يمكن أن يسبب ضرراً للجنين. يجب التوقف فور اكتشاف الحمل.',
    interactions: [
      { interactsWith: 'Lithium', severity: 'moderate', mechanism: 'Reduced renal lithium clearance',
        clinicalEffect: 'Lithium toxicity', clinicalEffectAr: 'سمية الليثيوم',
        management: 'Monitor lithium levels closely', managementAr: 'مراقبة مستوى الليثيوم بدقة' },
    ],
    contraindications: ['Pregnancy', 'Concurrent aliskiren in diabetic patients', 'Severe hepatic impairment'],
    contraindicationsAr: ['الحمل', 'أليسكيرين المتزامن في مرضى السكري', 'قصور كبدي شديد'],
    monitoringRequired: ['Blood pressure', 'Potassium', 'Renal function'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0101', genericName: 'Irbesartan', genericNameAr: 'إربيسارتان',
    brandNames: ['Aprovel', 'Avapro'], sfda_registration: 'SFDA-2024-IRB-101',
    atcCode: 'C09CA04', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '150mg', unitPrice: 1.2, inStock: true },
      { form: 'tablet', strength: '300mg', unitPrice: 2.0, inStock: true },
    ],
    maxDailyDose: 300, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Irbesartan/Losartan'],
    interactions: [
      { interactsWith: 'Spironolactone', severity: 'moderate', mechanism: 'Dual RAAS blockade + K-sparing diuretic',
        clinicalEffect: 'Hyperkalemia', clinicalEffectAr: 'فرط البوتاسيوم',
        management: 'Monitor potassium frequently', managementAr: 'مراقبة البوتاسيوم بشكل متكرر' },
    ],
    contraindications: ['Pregnancy', 'Bilateral renal artery stenosis'],
    contraindicationsAr: ['الحمل', 'تضيق ثنائي في الشريان الكلوي'],
    monitoringRequired: ['Blood pressure', 'Renal function', 'Potassium'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0102', genericName: 'Telmisartan', genericNameAr: 'تلميسارتان',
    brandNames: ['Micardis', 'Pritor'], sfda_registration: 'SFDA-2024-TEL-102',
    atcCode: 'C09CA07', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '40mg', unitPrice: 1.0, inStock: true },
      { form: 'tablet', strength: '80mg', unitPrice: 1.8, inStock: true },
    ],
    maxDailyDose: 80, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Telmisartan/Valsartan', 'Micardis/Miacalcin'],
    interactions: [
      { interactsWith: 'Ramipril', severity: 'major', mechanism: 'Dual RAAS blockade',
        clinicalEffect: 'Hypotension, hyperkalemia, renal impairment', clinicalEffectAr: 'انخفاض ضغط، فرط بوتاسيوم، قصور كلوي',
        management: 'Avoid dual RAAS blockade', managementAr: 'تجنب الحصار المزدوج لنظام الرينين' },
    ],
    contraindications: ['Pregnancy', 'Biliary obstruction', 'Severe hepatic impairment'],
    contraindicationsAr: ['الحمل', 'انسداد صفراوي', 'قصور كبدي شديد'],
    monitoringRequired: ['Blood pressure', 'Potassium', 'Renal function'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0103', genericName: 'Candesartan', genericNameAr: 'كانديسارتان',
    brandNames: ['Atacand', 'Blopress'], sfda_registration: 'SFDA-2024-CAN-103',
    atcCode: 'C09CA06', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '8mg', unitPrice: 1.0, inStock: true },
      { form: 'tablet', strength: '16mg', unitPrice: 1.5, inStock: true },
      { form: 'tablet', strength: '32mg', unitPrice: 2.5, inStock: true },
    ],
    maxDailyDose: 32, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Candesartan/Losartan', 'Atacand/Aricept'],
    interactions: [
      { interactsWith: 'Lithium', severity: 'moderate', mechanism: 'Reduced renal lithium clearance',
        clinicalEffect: 'Lithium toxicity', clinicalEffectAr: 'سمية الليثيوم',
        management: 'Monitor lithium levels', managementAr: 'مراقبة مستوى الليثيوم' },
    ],
    contraindications: ['Pregnancy', 'Severe hepatic impairment'],
    contraindicationsAr: ['الحمل', 'قصور كبدي شديد'],
    monitoringRequired: ['Blood pressure', 'Potassium', 'Renal function'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0104', genericName: 'Olmesartan', genericNameAr: 'أولميسارتان',
    brandNames: ['Benicar', 'Olmetec'], sfda_registration: 'SFDA-2024-OLM-104',
    atcCode: 'C09CA08', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '20mg', unitPrice: 1.5, inStock: true },
      { form: 'tablet', strength: '40mg', unitPrice: 2.5, inStock: true },
    ],
    maxDailyDose: 40, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Olmesartan/Losartan', 'Benicar/Mevacor'],
    interactions: [
      { interactsWith: 'NSAIDs', severity: 'moderate', mechanism: 'Reduced antihypertensive effect and renal impairment',
        clinicalEffect: 'Decreased BP control; AKI risk', clinicalEffectAr: 'تقليل السيطرة على الضغط؛ خطر قصور كلوي حاد',
        management: 'Monitor BP and renal function', managementAr: 'مراقبة الضغط ووظائف الكلى' },
    ],
    contraindications: ['Pregnancy', 'Concurrent aliskiren in diabetes'],
    contraindicationsAr: ['الحمل', 'أليسكيرين المتزامن في السكري'],
    monitoringRequired: ['Blood pressure', 'Potassium', 'Renal function', 'Sprue-like enteropathy symptoms'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0105', genericName: 'Lisinopril', genericNameAr: 'ليزينوبريل',
    brandNames: ['Zestril', 'Prinivil'], sfda_registration: 'SFDA-2024-LIS-105',
    atcCode: 'C09AA03', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '5mg', unitPrice: 0.3, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '20mg', unitPrice: 0.8, inStock: true },
    ],
    maxDailyDose: 40, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Lisinopril/Fosinopril', 'Zestril/Zetia'],
    interactions: [
      { interactsWith: 'Potassium Chloride', severity: 'major', mechanism: 'Additive potassium retention',
        clinicalEffect: 'Hyperkalemia', clinicalEffectAr: 'فرط البوتاسيوم',
        management: 'Monitor potassium closely; avoid supplements unless hypokalemic', managementAr: 'مراقبة البوتاسيوم بدقة' },
    ],
    contraindications: ['Pregnancy', 'History of ACE inhibitor angioedema', 'Bilateral renal artery stenosis'],
    contraindicationsAr: ['الحمل', 'تاريخ وذمة وعائية مع مثبطات ACE', 'تضيق ثنائي في الشريان الكلوي'],
    monitoringRequired: ['Blood pressure', 'Renal function', 'Potassium', 'Cough (ACE cough)'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0106', genericName: 'Enalapril', genericNameAr: 'إنالابريل',
    brandNames: ['Vasotec', 'Renitec'], sfda_registration: 'SFDA-2024-ENA-106',
    atcCode: 'C09AA02', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [
      { form: 'tablet', strength: '5mg', unitPrice: 0.3, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '20mg', unitPrice: 0.8, inStock: true },
    ],
    maxDailyDose: 40, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Enalapril/Ramipril', 'Vasotec/Vasocidin'],
    interactions: [
      { interactsWith: 'Spironolactone', severity: 'major', mechanism: 'Dual RAAS blockade + K-sparing',
        clinicalEffect: 'Severe hyperkalemia', clinicalEffectAr: 'فرط بوتاسيوم شديد',
        management: 'If combined, monitor K+ weekly initially', managementAr: 'إذا تم الجمع، مراقبة البوتاسيوم أسبوعياً في البداية' },
    ],
    contraindications: ['Pregnancy', 'History of ACE inhibitor angioedema', 'Concurrent sacubitril'],
    contraindicationsAr: ['الحمل', 'تاريخ وذمة وعائية مع مثبطات ACE', 'ساكوبيتريل المتزامن'],
    monitoringRequired: ['Blood pressure', 'Renal function', 'Potassium'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0107', genericName: 'Ramipril', genericNameAr: 'راميبريل',
    brandNames: ['Tritace', 'Altace'], sfda_registration: 'SFDA-2024-RAM-107',
    atcCode: 'C09AA05', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'capsule', strength: '2.5mg', unitPrice: 0.5, inStock: true },
      { form: 'capsule', strength: '5mg', unitPrice: 0.8, inStock: true },
      { form: 'capsule', strength: '10mg', unitPrice: 1.2, inStock: true },
    ],
    maxDailyDose: 20, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ramipril/Enalapril', 'Tritace/Tritec'],
    interactions: [
      { interactsWith: 'NSAIDs', severity: 'moderate', mechanism: 'Reduced antihypertensive effect; renal impairment risk',
        clinicalEffect: 'Decreased BP control; AKI risk in volume depletion', clinicalEffectAr: 'تقليل السيطرة على الضغط؛ خطر قصور كلوي حاد',
        management: 'Monitor BP and renal function; hydrate patient', managementAr: 'مراقبة الضغط والكلى؛ ترطيب المريض' },
    ],
    contraindications: ['Pregnancy', 'History of ACE inhibitor angioedema'],
    contraindicationsAr: ['الحمل', 'تاريخ وذمة وعائية مع مثبطات ACE'],
    monitoringRequired: ['Blood pressure', 'Renal function', 'Potassium'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0108', genericName: 'Perindopril', genericNameAr: 'بيريندوبريل',
    brandNames: ['Coversyl', 'Aceon'], sfda_registration: 'SFDA-2024-PER-108',
    atcCode: 'C09AA04', atcCategory: 'C09 - Agents acting on the renin-angiotensin system',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '4mg', unitPrice: 1.0, inStock: true },
      { form: 'tablet', strength: '8mg', unitPrice: 1.5, inStock: true },
    ],
    maxDailyDose: 16, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Perindopril/Enalapril'],
    interactions: [
      { interactsWith: 'Aliskiren', severity: 'major', mechanism: 'Dual RAAS blockade',
        clinicalEffect: 'Hypotension, hyperkalemia, renal failure', clinicalEffectAr: 'انخفاض ضغط، فرط بوتاسيوم، فشل كلوي',
        management: 'Contraindicated in diabetic patients', managementAr: 'ممنوع في مرضى السكري' },
    ],
    contraindications: ['Pregnancy', 'History of ACE inhibitor angioedema'],
    contraindicationsAr: ['الحمل', 'تاريخ وذمة وعائية مع مثبطات ACE'],
    monitoringRequired: ['Blood pressure', 'Renal function', 'Potassium'],
    storageConditions: 'Store below 30°C, protect from moisture',
  },
  {
    id: 'FRM-0109', genericName: 'Hydrochlorothiazide', genericNameAr: 'هيدروكلوروثيازيد',
    brandNames: ['Esidrex', 'HydroDIURIL'], sfda_registration: 'SFDA-2024-HCT-109',
    atcCode: 'C03AA03', atcCategory: 'C03 - Diuretics',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '12.5mg', unitPrice: 0.2, inStock: true },
      { form: 'tablet', strength: '25mg', unitPrice: 0.3, inStock: true },
    ],
    maxDailyDose: 50, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Hydrochlorothiazide/Hydroxychloroquine'],
    interactions: [
      { interactsWith: 'Lithium', severity: 'major', mechanism: 'Reduced renal lithium clearance',
        clinicalEffect: 'Lithium toxicity', clinicalEffectAr: 'سمية الليثيوم',
        management: 'Avoid if possible; monitor lithium levels', managementAr: 'تجنب إذا أمكن؛ مراقبة مستوى الليثيوم' },
    ],
    contraindications: ['Anuria', 'Severe renal impairment', 'Sulfonamide allergy (cross-reactivity)'],
    contraindicationsAr: ['انقطاع البول', 'قصور كلوي شديد', 'حساسية السلفوناميد (تفاعل متبادل)'],
    monitoringRequired: ['Electrolytes (K+, Na+, Mg2+)', 'Renal function', 'Blood glucose', 'Uric acid'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0110', genericName: 'Furosemide', genericNameAr: 'فوروسيميد',
    brandNames: ['Lasix', 'Frusol'], sfda_registration: 'SFDA-2024-FUR-110',
    atcCode: 'C03CA01', atcCategory: 'C03 - Diuretics',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'im'],
    forms: [
      { form: 'tablet', strength: '40mg', unitPrice: 0.3, inStock: true },
      { form: 'tablet', strength: '80mg', unitPrice: 0.5, inStock: true },
      { form: 'injection', strength: '20mg/2ml', unitPrice: 2.0, inStock: true },
    ],
    maxDailyDose: 600, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Furosemide/Torsemide', 'Lasix/Losec'],
    interactions: [
      { interactsWith: 'Gentamicin', severity: 'major', mechanism: 'Additive ototoxicity and nephrotoxicity',
        clinicalEffect: 'Hearing loss and renal damage', clinicalEffectAr: 'فقدان السمع وتلف كلوي',
        management: 'Avoid combination if possible; monitor closely', managementAr: 'تجنب الجمع إذا أمكن؛ مراقبة دقيقة' },
    ],
    contraindications: ['Anuria', 'Severe hypokalemia/hyponatremia', 'Hepatic coma'],
    contraindicationsAr: ['انقطاع البول', 'نقص شديد في البوتاسيوم/الصوديوم', 'غيبوبة كبدية'],
    monitoringRequired: ['Electrolytes (K+, Na+, Mg2+)', 'Renal function', 'Blood pressure', 'Volume status'],
    storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: 'FRM-0111', genericName: 'Spironolactone', genericNameAr: 'سبيرونولاكتون',
    brandNames: ['Aldactone', 'Verospiron'], sfda_registration: 'SFDA-2024-SPI-111',
    atcCode: 'C03DA01', atcCategory: 'C03 - Diuretics',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '25mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '50mg', unitPrice: 1.0, inStock: true },
      { form: 'tablet', strength: '100mg', unitPrice: 1.5, inStock: true },
    ],
    maxDailyDose: 400, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Spironolactone/Eplerenone'],
    interactions: [
      { interactsWith: 'Lisinopril', severity: 'major', mechanism: 'Dual RAAS blockade',
        clinicalEffect: 'Severe hyperkalemia', clinicalEffectAr: 'فرط بوتاسيوم شديد',
        management: 'Monitor potassium frequently; start low', managementAr: 'مراقبة البوتاسيوم بشكل متكرر؛ بدء بجرعة منخفضة' },
    ],
    contraindications: ['Hyperkalemia', 'Addison disease', 'Anuria', 'Severe renal impairment'],
    contraindicationsAr: ['فرط البوتاسيوم', 'مرض أديسون', 'انقطاع البول', 'قصور كلوي شديد'],
    monitoringRequired: ['Potassium', 'Renal function', 'Blood pressure', 'Gynecomastia'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0112', genericName: 'Indapamide', genericNameAr: 'إنداباميد',
    brandNames: ['Natrilix', 'Lozol'], sfda_registration: 'SFDA-2024-IND-112',
    atcCode: 'C03BA11', atcCategory: 'C03 - Diuretics',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '1.5mg (SR)', unitPrice: 0.8, inStock: true },
      { form: 'tablet', strength: '2.5mg', unitPrice: 0.5, inStock: true },
    ],
    maxDailyDose: 5, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Indapamide/Imipenem'],
    interactions: [
      { interactsWith: 'Digoxin', severity: 'major', mechanism: 'Hypokalemia increases digoxin sensitivity',
        clinicalEffect: 'Digoxin toxicity', clinicalEffectAr: 'سمية الديجوكسين',
        management: 'Monitor potassium; supplement as needed', managementAr: 'مراقبة البوتاسيوم؛ تعويض حسب الحاجة' },
    ],
    contraindications: ['Anuria', 'Severe hepatic encephalopathy', 'Severe renal impairment'],
    contraindicationsAr: ['انقطاع البول', 'اعتلال دماغي كبدي شديد', 'قصور كلوي شديد'],
    monitoringRequired: ['Electrolytes', 'Renal function', 'Blood glucose', 'Uric acid'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0113', genericName: 'Doxazosin', genericNameAr: 'دوكسازوسين',
    brandNames: ['Cardura', 'Doxacard'], sfda_registration: 'SFDA-2024-DOX-113',
    atcCode: 'C02CA04', atcCategory: 'C02 - Antihypertensives',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '2mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '4mg', unitPrice: 0.8, inStock: true },
    ],
    maxDailyDose: 16, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Doxazosin/Doxepin', 'Cardura/Coumadin'],
    interactions: [
      { interactsWith: 'Sildenafil', severity: 'major', mechanism: 'Additive hypotension',
        clinicalEffect: 'Severe orthostatic hypotension and syncope', clinicalEffectAr: 'انخفاض ضغط انتصابي شديد وإغماء',
        management: 'Stabilize on alpha-blocker before adding PDE5 inhibitor; start low', managementAr: 'استقرار على حاصر ألفا قبل إضافة مثبط PDE5' },
    ],
    contraindications: ['History of orthostatic hypotension', 'Urinary incontinence'],
    contraindicationsAr: ['تاريخ انخفاض ضغط انتصابي', 'سلس البول'],
    monitoringRequired: ['Blood pressure (standing and supine)', 'Heart rate', 'Dizziness/syncope'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0114', genericName: 'Clonidine', genericNameAr: 'كلونيدين',
    brandNames: ['Catapres', 'Dixarit'], sfda_registration: 'SFDA-2024-CLO-114',
    atcCode: 'C02AC01', atcCategory: 'C02 - Antihypertensives',
    therapeuticClass: 'Antihypertensives', therapeuticClassAr: 'خافضات ضغط الدم',
    formularyStatus: 'formulary', route: ['oral', 'transdermal'],
    forms: [
      { form: 'tablet', strength: '0.1mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '0.2mg', unitPrice: 0.8, inStock: true },
      { form: 'patch', strength: '0.1mg/day (weekly)', unitPrice: 25.0, inStock: true },
    ],
    maxDailyDose: 2.4, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Clonidine/Clonazepam/Klonopin'],
    interactions: [
      { interactsWith: 'Metoprolol', severity: 'major', mechanism: 'Rebound hypertension on clonidine withdrawal amplified by beta-blocker',
        clinicalEffect: 'Hypertensive crisis if clonidine abruptly stopped', clinicalEffectAr: 'أزمة ارتفاع ضغط إذا أُوقف كلونيدين فجأة',
        management: 'Taper clonidine gradually; stop beta-blocker first', managementAr: 'تقليل كلونيدين تدريجياً؛ إيقاف حاصر بيتا أولاً' },
    ],
    contraindications: ['Sick sinus syndrome (without pacemaker)', 'Severe bradycardia'],
    contraindicationsAr: ['متلازمة العقدة الجيبية المريضة (بدون ناظم)', 'بطء قلب شديد'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'Rebound hypertension on discontinuation', 'Sedation'],
    storageConditions: 'Store below 25°C',
  },
];

// ─── ANTIPLATELETS (8) ───────────────────────────────────────────────────────

export const ANTIPLATELETS: FormularyDrug[] = [
  {
    id: 'FRM-0115', genericName: 'Aspirin (Low-Dose)', genericNameAr: 'أسبرين (جرعة منخفضة)',
    brandNames: ['Aspirin Protect', 'Jusprin'], sfda_registration: 'SFDA-2024-ASA-115',
    atcCode: 'B01AC06', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Antiplatelets', therapeuticClassAr: 'مضادات الصفيحات',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '81mg (EC)', unitPrice: 0.15, inStock: true },
      { form: 'tablet', strength: '100mg (EC)', unitPrice: 0.2, inStock: true },
    ],
    maxDailyDose: 325, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: true, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Aspirin/Ascriptin'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Additive anticoagulant/antiplatelet effect',
        clinicalEffect: 'Significantly increased bleeding risk', clinicalEffectAr: 'زيادة كبيرة في خطر النزيف',
        management: 'Avoid unless specifically indicated (e.g., mechanical valve)', managementAr: 'تجنب إلا إذا كان هناك مبرر (مثل صمام ميكانيكي)' },
      { interactsWith: 'Ibuprofen', severity: 'moderate', mechanism: 'Competitive COX-1 binding; ibuprofen blocks aspirin access',
        clinicalEffect: 'Reduced aspirin cardioprotection', clinicalEffectAr: 'تقليل الحماية القلبية للأسبرين',
        management: 'Take aspirin 30min before ibuprofen', managementAr: 'تناول الأسبرين 30 دقيقة قبل الإيبوبروفين' },
    ],
    contraindications: ['Active peptic ulcer', 'Severe bleeding disorders', 'Children with viral illness (Reye syndrome)'],
    contraindicationsAr: ['قرحة هضمية نشطة', 'اضطرابات نزف شديدة', 'الأطفال مع مرض فيروسي (متلازمة راي)'],
    monitoringRequired: ['Signs of GI bleeding', 'CBC', 'Renal function with long-term use'],
    storageConditions: 'Store below 25°C, protect from moisture',
  },
  {
    id: 'FRM-0116', genericName: 'Clopidogrel', genericNameAr: 'كلوبيدوغريل',
    brandNames: ['Plavix', 'Clopilet'], sfda_registration: 'SFDA-2024-CLO-116',
    atcCode: 'B01AC04', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Antiplatelets', therapeuticClassAr: 'مضادات الصفيحات',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '75mg', unitPrice: 1.0, inStock: true },
      { form: 'tablet', strength: '300mg', unitPrice: 4.0, inStock: true },
    ],
    maxDailyDose: 75, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Clopidogrel/Clorazepate', 'Plavix/Pradaxa'],
    blackBoxWarning: 'CYP2C19 poor metabolizers have reduced effectiveness. Consider genetic testing.',
    blackBoxWarningAr: 'المستقلبون البطيئون لـ CYP2C19 لديهم فعالية منخفضة. فكر بالفحص الجيني.',
    interactions: [
      { interactsWith: 'Omeprazole', severity: 'major', mechanism: 'CYP2C19 inhibition reduces active metabolite',
        clinicalEffect: 'Reduced antiplatelet effect; increased CV events', clinicalEffectAr: 'تقليل التأثير المضاد للصفيحات؛ زيادة الأحداث القلبية',
        management: 'Use pantoprazole instead (minimal CYP2C19 interaction)', managementAr: 'استخدام بانتوبرازول بدلاً (تفاعل أقل مع CYP2C19)' },
    ],
    contraindications: ['Active pathological bleeding', 'Severe hepatic impairment'],
    contraindicationsAr: ['نزيف مرضي نشط', 'قصور كبدي شديد'],
    monitoringRequired: ['Signs of bleeding', 'CBC', 'CYP2C19 genotype (if available)', 'Platelet function (if suspected resistance)'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0117', genericName: 'Ticagrelor', genericNameAr: 'تيكاغريلور',
    brandNames: ['Brilinta', 'Brilique'], sfda_registration: 'SFDA-2024-TIC-117',
    atcCode: 'B01AC24', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Antiplatelets', therapeuticClassAr: 'مضادات الصفيحات',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '60mg', unitPrice: 5.0, inStock: true },
      { form: 'tablet', strength: '90mg', unitPrice: 6.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ticagrelor/Tirofiban', 'Brilinta/Brintellix'],
    blackBoxWarning: 'Aspirin doses >100mg/day reduce ticagrelor effectiveness. Maintain aspirin 75-100mg.',
    blackBoxWarningAr: 'جرعات الأسبرين أعلى من 100 ملغ/يوم تقلل فعالية تيكاغريلور. حافظ على أسبرين 75-100 ملغ.',
    interactions: [
      { interactsWith: 'Simvastatin', severity: 'moderate', mechanism: 'CYP3A4 inhibition',
        clinicalEffect: 'Increased simvastatin levels', clinicalEffectAr: 'زيادة مستوى سيمفاستاتين',
        management: 'Limit simvastatin to 40mg/day', managementAr: 'تحديد سيمفاستاتين بـ 40 ملغ/يوم' },
      { interactsWith: 'Digoxin', severity: 'moderate', mechanism: 'P-gp inhibition',
        clinicalEffect: 'Increased digoxin levels', clinicalEffectAr: 'زيادة مستوى الديجوكسين',
        management: 'Monitor digoxin levels', managementAr: 'مراقبة مستوى الديجوكسين' },
    ],
    contraindications: ['Active pathological bleeding', 'History of intracranial hemorrhage', 'Severe hepatic impairment'],
    contraindicationsAr: ['نزيف مرضي نشط', 'تاريخ نزيف داخل الجمجمة', 'قصور كبدي شديد'],
    monitoringRequired: ['Signs of bleeding', 'Dyspnea (common side effect)', 'Bradycardia', 'Uric acid', 'Creatinine'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0118', genericName: 'Prasugrel', genericNameAr: 'براسوغريل',
    brandNames: ['Effient', 'Efient'], sfda_registration: 'SFDA-2024-PRA-118',
    atcCode: 'B01AC22', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Antiplatelets', therapeuticClassAr: 'مضادات الصفيحات',
    formularyStatus: 'restricted', route: ['oral'],
    restrictionCriteria: 'PCI-intended ACS patients only. Cardiology prescribing.',
    restrictionCriteriaAr: 'مرضى متلازمة الشريان التاجي الحادة مع قسطرة مخططة فقط.',
    approverRole: 'cardiologist',
    forms: [
      { form: 'tablet', strength: '5mg', unitPrice: 6.0, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 7.0, inStock: true },
    ],
    maxDailyDose: 10, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Prasugrel/Clopidogrel', 'Effient/Effexor'],
    blackBoxWarning: 'Significant/fatal bleeding risk. Generally not recommended in patients >=75 years, <60kg, or with prior stroke/TIA.',
    blackBoxWarningAr: 'خطر نزيف كبير/مميت. لا يُوصى عموماً للمرضى >=75 سنة، أقل من 60 كغ، أو مع سكتة/نوبة إقفارية سابقة.',
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Additive bleeding risk',
        clinicalEffect: 'Increased hemorrhagic events', clinicalEffectAr: 'زيادة الأحداث النزفية',
        management: 'Avoid combination if possible; use with extreme caution', managementAr: 'تجنب الجمع إذا أمكن؛ استخدام بحذر شديد' },
    ],
    contraindications: ['Active pathological bleeding', 'Prior stroke/TIA', 'Weight <60kg (consider 5mg dose)'],
    contraindicationsAr: ['نزيف مرضي نشط', 'سكتة/نوبة إقفارية سابقة', 'وزن أقل من 60 كغ (فكر بجرعة 5 ملغ)'],
    monitoringRequired: ['Signs of bleeding', 'CBC', 'Hemoglobin/hematocrit'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0119', genericName: 'Dipyridamole', genericNameAr: 'ديبيريدامول',
    brandNames: ['Persantine', 'Aggrenox (combination)'], sfda_registration: 'SFDA-2024-DIP-119',
    atcCode: 'B01AC07', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Antiplatelets', therapeuticClassAr: 'مضادات الصفيحات',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [
      { form: 'tablet', strength: '75mg', unitPrice: 0.8, inStock: true },
      { form: 'capsule', strength: '200mg ER + ASA 25mg (Aggrenox)', unitPrice: 3.5, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Dipyridamole/Disopyramide', 'Persantine/Percocet'],
    interactions: [
      { interactsWith: 'Adenosine', severity: 'major', mechanism: 'Dipyridamole inhibits adenosine uptake',
        clinicalEffect: 'Potentiated adenosine effect; severe bradycardia or AV block', clinicalEffectAr: 'تعزيز تأثير الأدينوزين؛ بطء قلب شديد أو إحصار',
        management: 'Reduce adenosine dose by 50-75%', managementAr: 'تقليل جرعة الأدينوزين 50-75%' },
    ],
    contraindications: ['Hypersensitivity to dipyridamole', 'Severe coronary artery disease (stress testing)'],
    contraindicationsAr: ['فرط حساسية للديبيريدامول', 'مرض شريان تاجي شديد (اختبار الإجهاد)'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'Signs of bleeding', 'Headache (common)'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0120', genericName: 'Cilostazol', genericNameAr: 'سيلوستازول',
    brandNames: ['Pletal', 'Cilostaz'], sfda_registration: 'SFDA-2024-CIL-120',
    atcCode: 'B01AC23', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Antiplatelets', therapeuticClassAr: 'مضادات الصفيحات',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '50mg', unitPrice: 1.5, inStock: true },
      { form: 'tablet', strength: '100mg', unitPrice: 2.5, inStock: true },
    ],
    maxDailyDose: 200, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Cilostazol/Citalopram'],
    interactions: [
      { interactsWith: 'Omeprazole', severity: 'moderate', mechanism: 'CYP2C19 inhibition increases cilostazol metabolite',
        clinicalEffect: 'Increased cilostazol exposure', clinicalEffectAr: 'زيادة التعرض لسيلوستازول',
        management: 'Reduce cilostazol to 50mg BID', managementAr: 'تقليل سيلوستازول إلى 50 ملغ مرتين يومياً' },
    ],
    contraindications: ['Heart failure of any severity', 'Hemostatic disorders', 'Active bleeding'],
    contraindicationsAr: ['قصور قلب بأي درجة', 'اضطرابات الإرقاء', 'نزيف نشط'],
    monitoringRequired: ['Heart failure symptoms', 'CBC', 'Heart rate', 'Signs of bleeding'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0121', genericName: 'Vorapaxar', genericNameAr: 'فورابكسار',
    brandNames: ['Zontivity'], sfda_registration: 'SFDA-2024-VOR-121',
    atcCode: 'B01AC26', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Antiplatelets', therapeuticClassAr: 'مضادات الصفيحات',
    formularyStatus: 'restricted', route: ['oral'],
    restrictionCriteria: 'Post-MI/PAD secondary prevention. Cardiology approval only.',
    restrictionCriteriaAr: 'وقاية ثانوية بعد احتشاء/مرض شرياني محيطي. موافقة أمراض القلب فقط.',
    approverRole: 'cardiologist',
    forms: [
      { form: 'tablet', strength: '2.08mg', unitPrice: 12.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Vorapaxar/Rivaroxaban'],
    blackBoxWarning: 'Increased bleeding risk including ICH. Do not use in patients with prior stroke/TIA.',
    blackBoxWarningAr: 'خطر نزيف متزايد بما في ذلك النزيف داخل الجمجمة. لا تستخدم مع مرضى السكتة/النوبة الإقفارية السابقة.',
    interactions: [
      { interactsWith: 'Ketoconazole', severity: 'major', mechanism: 'Strong CYP3A4 inhibition',
        clinicalEffect: 'Increased vorapaxar levels', clinicalEffectAr: 'زيادة مستوى فورابكسار',
        management: 'Avoid concomitant use with strong CYP3A4 inhibitors', managementAr: 'تجنب الاستخدام مع مثبطات CYP3A4 القوية' },
    ],
    contraindications: ['Prior stroke/TIA/ICH', 'Active pathological bleeding', 'Severe hepatic impairment'],
    contraindicationsAr: ['سكتة/نوبة إقفارية/نزيف داخل الجمجمة سابق', 'نزيف مرضي نشط', 'قصور كبدي شديد'],
    monitoringRequired: ['Signs of bleeding', 'CBC', 'Neurological assessment'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0122', genericName: 'Cangrelor', genericNameAr: 'كانغريلور',
    brandNames: ['Kengreal', 'Kengrexal'], sfda_registration: 'SFDA-2024-CNG-122',
    atcCode: 'B01AC25', atcCategory: 'B01 - Antithrombotic agents',
    therapeuticClass: 'Antiplatelets', therapeuticClassAr: 'مضادات الصفيحات',
    formularyStatus: 'restricted', route: ['iv'],
    restrictionCriteria: 'PCI use only. Cardiac catheterization lab.',
    restrictionCriteriaAr: 'استخدام قسطرة قلبية فقط. مختبر القسطرة القلبية.',
    approverRole: 'cardiologist',
    forms: [
      { form: 'injection', strength: '50mg vial', unitPrice: 450.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Cangrelor/Clopidogrel'],
    interactions: [
      { interactsWith: 'Clopidogrel', severity: 'major', mechanism: 'Cangrelor blocks clopidogrel binding to P2Y12 receptor',
        clinicalEffect: 'Reduced clopidogrel effectiveness if given simultaneously', clinicalEffectAr: 'تقليل فعالية كلوبيدوغريل إذا أُعطي بالتزامن',
        management: 'Administer clopidogrel loading dose after cangrelor discontinuation', managementAr: 'إعطاء جرعة تحميل كلوبيدوغريل بعد إيقاف كانغريلور' },
    ],
    contraindications: ['Active bleeding', 'Significant bleeding risk'],
    contraindicationsAr: ['نزيف نشط', 'خطر نزيف كبير'],
    monitoringRequired: ['ACT during PCI', 'Signs of bleeding', 'Platelet function'],
    storageConditions: 'Store below 25°C. Reconstituted: use within 24h.',
  },
];

// ─── LIPID-LOWERING AGENTS (10) ─────────────────────────────────────────────

export const LIPID_LOWERING: FormularyDrug[] = [
  {
    id: 'FRM-0123', genericName: 'Atorvastatin', genericNameAr: 'أتورفاستاتين',
    brandNames: ['Lipitor', 'Ator'], sfda_registration: 'SFDA-2024-ATO-123',
    atcCode: 'C10AA05', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '10mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '20mg', unitPrice: 0.8, inStock: true },
      { form: 'tablet', strength: '40mg', unitPrice: 1.2, inStock: true },
      { form: 'tablet', strength: '80mg', unitPrice: 2.0, inStock: true },
    ],
    maxDailyDose: 80, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Atorvastatin/Rosuvastatin', 'Lipitor/Levothyroxine'],
    interactions: [
      { interactsWith: 'Clarithromycin', severity: 'major', mechanism: 'CYP3A4 inhibition',
        clinicalEffect: 'Increased atorvastatin levels; rhabdomyolysis risk', clinicalEffectAr: 'زيادة مستوى أتورفاستاتين؛ خطر انحلال الربيدات',
        management: 'Limit atorvastatin to 20mg; consider azithromycin alternative', managementAr: 'تحديد أتورفاستاتين بـ 20 ملغ؛ فكر بأزيثرومايسين بديلاً' },
      { interactsWith: 'Cyclosporine', severity: 'major', mechanism: 'CYP3A4 and OATP1B1 inhibition',
        clinicalEffect: 'Markedly increased statin exposure; myopathy', clinicalEffectAr: 'زيادة كبيرة في التعرض للستاتين؛ اعتلال عضلي',
        management: 'Limit atorvastatin to 10mg/day', managementAr: 'تحديد أتورفاستاتين بـ 10 ملغ/يوم' },
    ],
    contraindications: ['Active liver disease', 'Unexplained persistent transaminase elevation', 'Pregnancy', 'Lactation'],
    contraindicationsAr: ['مرض كبدي نشط', 'ارتفاع ترانسأميناز مستمر غير مفسر', 'الحمل', 'الرضاعة'],
    monitoringRequired: ['Lipid panel (baseline + 4-12 weeks)', 'LFTs', 'CPK if muscle symptoms', 'HbA1c (diabetes risk)'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0124', genericName: 'Rosuvastatin', genericNameAr: 'روسوفاستاتين',
    brandNames: ['Crestor', 'Rosuvas'], sfda_registration: 'SFDA-2024-ROS-124',
    atcCode: 'C10AA07', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '5mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 0.8, inStock: true },
      { form: 'tablet', strength: '20mg', unitPrice: 1.5, inStock: true },
      { form: 'tablet', strength: '40mg', unitPrice: 2.5, inStock: true },
    ],
    maxDailyDose: 40, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Rosuvastatin/Atorvastatin', 'Crestor/Casodex'],
    interactions: [
      { interactsWith: 'Gemfibrozil', severity: 'major', mechanism: 'OATP1B1 inhibition; increased rosuvastatin exposure',
        clinicalEffect: 'Myopathy and rhabdomyolysis', clinicalEffectAr: 'اعتلال عضلي وانحلال الربيدات',
        management: 'Avoid combination; use fenofibrate if fibrate needed', managementAr: 'تجنب الجمع؛ استخدم فينوفيبرات إذا لزم الفايبرات' },
    ],
    contraindications: ['Active liver disease', 'Pregnancy', 'Lactation', 'CrCl <30 with 40mg dose'],
    contraindicationsAr: ['مرض كبدي نشط', 'الحمل', 'الرضاعة', 'تصفية كرياتينين أقل من 30 مع جرعة 40 ملغ'],
    monitoringRequired: ['Lipid panel', 'LFTs', 'CPK if symptomatic', 'Renal function', 'Proteinuria at high doses'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0125', genericName: 'Simvastatin', genericNameAr: 'سيمفاستاتين',
    brandNames: ['Zocor', 'Simvacor'], sfda_registration: 'SFDA-2024-SIM-125',
    atcCode: 'C10AA01', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '10mg', unitPrice: 0.3, inStock: true },
      { form: 'tablet', strength: '20mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '40mg', unitPrice: 0.8, inStock: true },
    ],
    maxDailyDose: 40, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Simvastatin/Atorvastatin', 'Zocor/Cozaar'],
    interactions: [
      { interactsWith: 'Amlodipine', severity: 'moderate', mechanism: 'CYP3A4 inhibition',
        clinicalEffect: 'Increased myopathy risk', clinicalEffectAr: 'زيادة خطر اعتلال عضلي',
        management: 'Limit simvastatin to 20mg/day with amlodipine', managementAr: 'تحديد سيمفاستاتين بـ 20 ملغ/يوم مع أملوديبين' },
      { interactsWith: 'Diltiazem', severity: 'major', mechanism: 'CYP3A4 inhibition',
        clinicalEffect: 'Rhabdomyolysis', clinicalEffectAr: 'انحلال الربيدات',
        management: 'Limit simvastatin to 10mg/day', managementAr: 'تحديد سيمفاستاتين بـ 10 ملغ/يوم' },
    ],
    contraindications: ['Active liver disease', 'Pregnancy', 'Concurrent strong CYP3A4 inhibitors'],
    contraindicationsAr: ['مرض كبدي نشط', 'الحمل', 'مثبطات CYP3A4 القوية المتزامنة'],
    monitoringRequired: ['Lipid panel', 'LFTs', 'CPK if muscle symptoms'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0126', genericName: 'Pravastatin', genericNameAr: 'برافاستاتين',
    brandNames: ['Pravachol', 'Lipostat'], sfda_registration: 'SFDA-2024-PRA-126',
    atcCode: 'C10AA03', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '20mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '40mg', unitPrice: 0.8, inStock: true },
    ],
    maxDailyDose: 80, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Pravastatin/Pitavastatin', 'Pravachol/Prevacid'],
    interactions: [
      { interactsWith: 'Cyclosporine', severity: 'major', mechanism: 'OATP1B1 inhibition',
        clinicalEffect: 'Increased pravastatin levels; myopathy', clinicalEffectAr: 'زيادة مستوى برافاستاتين؛ اعتلال عضلي',
        management: 'Limit pravastatin to 20mg/day', managementAr: 'تحديد برافاستاتين بـ 20 ملغ/يوم' },
    ],
    contraindications: ['Active liver disease', 'Pregnancy', 'Lactation'],
    contraindicationsAr: ['مرض كبدي نشط', 'الحمل', 'الرضاعة'],
    monitoringRequired: ['Lipid panel', 'LFTs', 'CPK if symptomatic'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0127', genericName: 'Fluvastatin', genericNameAr: 'فلوفاستاتين',
    brandNames: ['Lescol', 'Lescol XL'], sfda_registration: 'SFDA-2024-FLU-127',
    atcCode: 'C10AA04', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'capsule', strength: '20mg', unitPrice: 0.8, inStock: true },
      { form: 'tablet', strength: '80mg (XL)', unitPrice: 2.5, inStock: true },
    ],
    maxDailyDose: 80, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Fluvastatin/Fluvoxamine'],
    interactions: [
      { interactsWith: 'Fluconazole', severity: 'moderate', mechanism: 'CYP2C9 inhibition',
        clinicalEffect: 'Increased fluvastatin levels', clinicalEffectAr: 'زيادة مستوى فلوفاستاتين',
        management: 'Monitor for myopathy; consider dose reduction', managementAr: 'مراقبة الاعتلال العضلي؛ فكر بتقليل الجرعة' },
    ],
    contraindications: ['Active liver disease', 'Pregnancy', 'Lactation'],
    contraindicationsAr: ['مرض كبدي نشط', 'الحمل', 'الرضاعة'],
    monitoringRequired: ['Lipid panel', 'LFTs', 'CPK if muscle symptoms'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0128', genericName: 'Ezetimibe', genericNameAr: 'إيزيتيميب',
    brandNames: ['Zetia', 'Ezetrol'], sfda_registration: 'SFDA-2024-EZE-128',
    atcCode: 'C10AX09', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '10mg', unitPrice: 2.0, inStock: true },
    ],
    maxDailyDose: 10, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ezetimibe/Zetia/Zestril'],
    interactions: [
      { interactsWith: 'Fibrates', severity: 'moderate', mechanism: 'Increased biliary cholesterol excretion',
        clinicalEffect: 'Cholelithiasis risk; increased transaminases', clinicalEffectAr: 'خطر حصوات مرارية؛ زيادة ترانسأميناز',
        management: 'Monitor LFTs and gallbladder symptoms', managementAr: 'مراقبة وظائف الكبد وأعراض المرارة' },
    ],
    contraindications: ['Moderate/severe hepatic impairment (with statin)', 'Pregnancy (with statin)'],
    contraindicationsAr: ['قصور كبدي متوسط/شديد (مع ستاتين)', 'الحمل (مع ستاتين)'],
    monitoringRequired: ['Lipid panel', 'LFTs (especially when combined with statin)'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: 'FRM-0129', genericName: 'Fenofibrate', genericNameAr: 'فينوفيبرات',
    brandNames: ['Lipanthyl', 'Tricor'], sfda_registration: 'SFDA-2024-FEN-129',
    atcCode: 'C10AB05', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'capsule', strength: '145mg', unitPrice: 1.5, inStock: true },
      { form: 'capsule', strength: '200mg', unitPrice: 2.0, inStock: true },
    ],
    maxDailyDose: 145, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Fenofibrate/Gemfibrozil', 'Tricor/Tracleer'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Displaces warfarin from protein binding',
        clinicalEffect: 'Increased INR and bleeding risk', clinicalEffectAr: 'زيادة INR وخطر النزيف',
        management: 'Reduce warfarin dose by 30%; monitor INR closely', managementAr: 'تقليل جرعة الوارفارين 30%؛ مراقبة INR بدقة' },
    ],
    contraindications: ['Severe renal impairment', 'Active liver disease', 'Gallbladder disease', 'Lactation'],
    contraindicationsAr: ['قصور كلوي شديد', 'مرض كبدي نشط', 'مرض المرارة', 'الرضاعة'],
    monitoringRequired: ['Lipid panel', 'LFTs', 'Renal function', 'CBC', 'CPK if combined with statin'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0130', genericName: 'Gemfibrozil', genericNameAr: 'جيمفيبروزيل',
    brandNames: ['Lopid', 'Jezil'], sfda_registration: 'SFDA-2024-GEM-130',
    atcCode: 'C10AB04', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '600mg', unitPrice: 1.0, inStock: true },
    ],
    maxDailyDose: 1200, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Gemfibrozil/Fenofibrate'],
    interactions: [
      { interactsWith: 'Rosuvastatin', severity: 'major', mechanism: 'OATP1B1 inhibition; increased statin exposure',
        clinicalEffect: 'Severe myopathy and rhabdomyolysis', clinicalEffectAr: 'اعتلال عضلي شديد وانحلال الربيدات',
        management: 'Avoid combination; use fenofibrate if fibrate needed', managementAr: 'تجنب الجمع؛ استخدم فينوفيبرات بدلاً' },
      { interactsWith: 'Repaglinide', severity: 'major', mechanism: 'CYP2C8 and OATP1B1 inhibition',
        clinicalEffect: 'Severe hypoglycemia', clinicalEffectAr: 'انخفاض سكر شديد',
        management: 'Contraindicated combination', managementAr: 'مزيج ممنوع' },
    ],
    contraindications: ['Severe renal/hepatic disease', 'Gallbladder disease', 'Concurrent statin (preferred: fenofibrate)'],
    contraindicationsAr: ['مرض كلوي/كبدي شديد', 'مرض المرارة', 'ستاتين متزامن (يُفضل: فينوفيبرات)'],
    monitoringRequired: ['Lipid panel', 'LFTs', 'CBC', 'Renal function', 'CPK'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: 'FRM-0131', genericName: 'Evolocumab', genericNameAr: 'إيفولوكوماب',
    brandNames: ['Repatha'], sfda_registration: 'SFDA-2024-EVO-131',
    atcCode: 'C10AX13', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'restricted', route: ['sc'],
    restrictionCriteria: 'ASCVD with inadequate LDL on max statin + ezetimibe, or statin intolerance. Lipid clinic/cardiology approval.',
    restrictionCriteriaAr: 'مرض تصلب شرياني عصيدي مع LDL غير كاف على أقصى ستاتين + إيزيتيميب، أو عدم تحمل الستاتين. موافقة عيادة الدهون/القلب.',
    approverRole: 'cardiologist',
    forms: [
      { form: 'injection', strength: '140mg/ml autoinjector', unitPrice: 550.0, inStock: true },
      { form: 'injection', strength: '420mg/3.5ml cartridge', unitPrice: 1500.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Evolocumab/Alirocumab'],
    interactions: [
      { interactsWith: 'Statins', severity: 'minor', mechanism: 'Additive LDL lowering (beneficial)',
        clinicalEffect: 'Enhanced LDL reduction', clinicalEffectAr: 'تعزيز تخفيض LDL',
        management: 'Monitor lipid panel; adjust statin dose as needed', managementAr: 'مراقبة الدهون؛ تعديل جرعة الستاتين حسب الحاجة' },
    ],
    contraindications: ['Serious hypersensitivity to evolocumab'],
    contraindicationsAr: ['فرط حساسية خطير للإيفولوكوماب'],
    monitoringRequired: ['LDL-C (baseline, 4-8 weeks, then periodically)', 'Injection site reactions', 'Neurocognitive symptoms'],
    storageConditions: 'Store 2-8°C. Can be kept at room temperature (<25°C) for up to 30 days.',
  },
  {
    id: 'FRM-0132', genericName: 'Alirocumab', genericNameAr: 'أليروكوماب',
    brandNames: ['Praluent'], sfda_registration: 'SFDA-2024-ALI-132',
    atcCode: 'C10AX14', atcCategory: 'C10 - Lipid modifying agents',
    therapeuticClass: 'Lipid-Lowering', therapeuticClassAr: 'خافضات الدهون',
    formularyStatus: 'restricted', route: ['sc'],
    restrictionCriteria: 'ASCVD with inadequate LDL on max statin + ezetimibe, or statin intolerance. Lipid clinic/cardiology approval.',
    restrictionCriteriaAr: 'مرض تصلب شرياني عصيدي مع LDL غير كاف على أقصى ستاتين + إيزيتيميب، أو عدم تحمل الستاتين. موافقة عيادة الدهون/القلب.',
    approverRole: 'cardiologist',
    forms: [
      { form: 'injection', strength: '75mg/ml pen', unitPrice: 500.0, inStock: true },
      { form: 'injection', strength: '150mg/ml pen', unitPrice: 500.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Alirocumab/Evolocumab'],
    interactions: [
      { interactsWith: 'Statins', severity: 'minor', mechanism: 'Additive LDL lowering (beneficial)',
        clinicalEffect: 'Enhanced LDL reduction', clinicalEffectAr: 'تعزيز تخفيض LDL',
        management: 'Monitor lipid panel; adjust as needed', managementAr: 'مراقبة الدهون؛ تعديل حسب الحاجة' },
    ],
    contraindications: ['Serious hypersensitivity to alirocumab'],
    contraindicationsAr: ['فرط حساسية خطير للأليروكوماب'],
    monitoringRequired: ['LDL-C (baseline, 4-8 weeks, then periodically)', 'Injection site reactions', 'Allergic reactions'],
    storageConditions: 'Store 2-8°C. Can be kept at room temperature (<25°C) for up to 30 days.',
  },
];
