/**
 * Saudi MOH Drug Formulary — Drug Data Part 13
 * IV Fluids, TPN Components & Electrolytes
 * IDs: FRM-0720 through FRM-0759
 */
import type { FormularyDrug } from './formularyTypes';

export const IV_FLUIDS_ELECTROLYTES: FormularyDrug[] = [
  // ═══════════════════════════════════════════════════════════════
  // 1. CRYSTALLOIDS (FRM-0720 to FRM-0725)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'FRM-0720', genericName: 'Sodium Chloride 0.9% (Normal Saline)', genericNameAr: 'محلول كلوريد الصوديوم 0.9% (ملحي طبيعي)',
    brandNames: ['Normal Saline', 'NS 0.9%'], sfda_registration: 'SFDA-IV-0720', atcCode: 'B05BB01', atcCategory: 'Solutions Affecting the Electrolyte Balance',
    therapeuticClass: 'Isotonic Crystalloid', therapeuticClassAr: 'محلول بلوري متساوي التوتر',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '500 mL', unitPrice: 4.50, inStock: true },
      { form: 'IV Solution', strength: '1000 mL', unitPrice: 6.00, inStock: true },
      { form: 'IV Solution', strength: '100 mL', unitPrice: 3.00, inStock: true },
      { form: 'IV Solution', strength: '250 mL', unitPrice: 3.75, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Sodium Chloride 3%', 'Sodium Chloride 0.45%'],
    interactions: [
      { interactsWith: 'Lithium', severity: 'moderate', mechanism: 'Sodium load increases lithium excretion', clinicalEffect: 'Reduced lithium levels', clinicalEffectAr: 'انخفاض مستوى الليثيوم', management: 'Monitor lithium levels with large volume NS', managementAr: 'مراقبة مستوى الليثيوم مع الكميات الكبيرة' },
    ],
    contraindications: ['Hypernatremia', 'Fluid overload'], contraindicationsAr: ['فرط صوديوم الدم', 'فرط حمل السوائل'],
    monitoringRequired: ['Serum sodium', 'Fluid balance', 'Signs of fluid overload'], storageConditions: 'Room temperature, protect from freezing',
  },
  {
    id: 'FRM-0721', genericName: 'Sodium Chloride 0.45% (Half Normal Saline)', genericNameAr: 'محلول كلوريد الصوديوم 0.45% (نصف ملحي)',
    brandNames: ['Half Normal Saline', 'NS 0.45%'], sfda_registration: 'SFDA-IV-0721', atcCode: 'B05BB01', atcCategory: 'Solutions Affecting the Electrolyte Balance',
    therapeuticClass: 'Hypotonic Crystalloid', therapeuticClassAr: 'محلول بلوري ناقص التوتر',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '500 mL', unitPrice: 4.50, inStock: true },
      { form: 'IV Solution', strength: '1000 mL', unitPrice: 6.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Sodium Chloride 0.9%', 'Sodium Chloride 3%'],
    interactions: [
      { interactsWith: 'Desmopressin', severity: 'major', mechanism: 'Hypotonic fluid with ADH analog increases hyponatremia risk', clinicalEffect: 'Severe hyponatremia', clinicalEffectAr: 'نقص حاد في صوديوم الدم', management: 'Avoid concomitant use; use isotonic fluids instead', managementAr: 'تجنب الاستخدام المتزامن؛ استخدم محاليل متساوية التوتر' },
    ],
    contraindications: ['Hyponatremia', 'Cerebral edema'], contraindicationsAr: ['نقص صوديوم الدم', 'وذمة دماغية'],
    monitoringRequired: ['Serum sodium', 'Fluid balance', 'Neurological status'], storageConditions: 'Room temperature, protect from freezing',
  },
  {
    id: 'FRM-0722', genericName: 'Ringer\'s Lactate (Lactated Ringer\'s)', genericNameAr: 'محلول رينغر لاكتات',
    brandNames: ['Ringer\'s Lactate', 'Hartmann\'s Solution', 'LR'], sfda_registration: 'SFDA-IV-0722', atcCode: 'B05BB01', atcCategory: 'Solutions Affecting the Electrolyte Balance',
    therapeuticClass: 'Balanced Crystalloid', therapeuticClassAr: 'محلول بلوري متوازن',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '500 mL', unitPrice: 5.00, inStock: true },
      { form: 'IV Solution', strength: '1000 mL', unitPrice: 7.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Normal Saline', 'Plasma-Lyte'],
    interactions: [
      { interactsWith: 'Ceftriaxone', severity: 'major', mechanism: 'Calcium in LR forms precipitate with ceftriaxone', clinicalEffect: 'Drug precipitation in IV line', clinicalEffectAr: 'ترسب الدواء في خط الوريد', management: 'Never mix; use separate lines or flush between', managementAr: 'لا تخلط أبداً؛ استخدم خطوط منفصلة أو اغسل بينهما' },
    ],
    contraindications: ['Severe hepatic impairment', 'Lactic acidosis', 'Hyperkalemia'], contraindicationsAr: ['قصور كبدي شديد', 'حماض لبني', 'فرط بوتاسيوم الدم'],
    monitoringRequired: ['Serum electrolytes', 'Lactate levels', 'Fluid balance'], storageConditions: 'Room temperature, protect from freezing',
  },
  {
    id: 'FRM-0723', genericName: 'Dextrose 5% in Water (D5W)', genericNameAr: 'محلول دكستروز 5% في الماء',
    brandNames: ['D5W', 'Dextrose 5%'], sfda_registration: 'SFDA-IV-0723', atcCode: 'B05BA03', atcCategory: 'Solutions for Parenteral Nutrition - Carbohydrates',
    therapeuticClass: 'Dextrose Solution', therapeuticClassAr: 'محلول دكستروز',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '500 mL', unitPrice: 5.00, inStock: true },
      { form: 'IV Solution', strength: '1000 mL', unitPrice: 7.00, inStock: true },
      { form: 'IV Solution', strength: '250 mL', unitPrice: 4.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Dextrose 10%', 'Dextrose 50%'],
    interactions: [
      { interactsWith: 'Insulin', severity: 'moderate', mechanism: 'Dextrose raises blood glucose requiring insulin dose adjustment', clinicalEffect: 'Hyperglycemia or hypoglycemia with insulin', clinicalEffectAr: 'ارتفاع أو انخفاض سكر الدم مع الأنسولين', management: 'Monitor blood glucose frequently; adjust insulin dose', managementAr: 'مراقبة سكر الدم بشكل متكرر وتعديل جرعة الأنسولين' },
    ],
    contraindications: ['Diabetic ketoacidosis (uncontrolled)', 'Hyperglycemia'], contraindicationsAr: ['الحماض الكيتوني السكري (غير المسيطر عليه)', 'فرط سكر الدم'],
    monitoringRequired: ['Blood glucose', 'Fluid balance', 'Serum electrolytes'], storageConditions: 'Room temperature, protect from freezing',
  },
  {
    id: 'FRM-0724', genericName: 'Dextrose 10% in Water (D10W)', genericNameAr: 'محلول دكستروز 10% في الماء',
    brandNames: ['D10W', 'Dextrose 10%'], sfda_registration: 'SFDA-IV-0724', atcCode: 'B05BA03', atcCategory: 'Solutions for Parenteral Nutrition - Carbohydrates',
    therapeuticClass: 'Dextrose Solution', therapeuticClassAr: 'محلول دكستروز',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '500 mL', unitPrice: 6.50, inStock: true },
      { form: 'IV Solution', strength: '1000 mL', unitPrice: 9.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Dextrose 5%', 'Dextrose 50%'],
    interactions: [
      { interactsWith: 'Insulin', severity: 'moderate', mechanism: 'Higher dextrose concentration significantly raises blood glucose', clinicalEffect: 'Hyperglycemia requiring insulin adjustment', clinicalEffectAr: 'ارتفاع سكر الدم يتطلب تعديل الأنسولين', management: 'Monitor blood glucose every 2-4 hours; adjust insulin', managementAr: 'مراقبة سكر الدم كل 2-4 ساعات وتعديل الأنسولين' },
    ],
    contraindications: ['Uncontrolled diabetes', 'Hyperglycemic hyperosmolar state'], contraindicationsAr: ['السكري غير المسيطر عليه', 'حالة فرط الأسمولية'],
    monitoringRequired: ['Blood glucose q2-4h', 'Serum electrolytes', 'Fluid balance'], storageConditions: 'Room temperature, protect from freezing',
  },
  {
    id: 'FRM-0725', genericName: 'Dextrose 50% in Water (D50W)', genericNameAr: 'محلول دكستروز 50% في الماء',
    brandNames: ['D50W', 'Dextrose 50%'], sfda_registration: 'SFDA-IV-0725', atcCode: 'B05BA03', atcCategory: 'Solutions for Parenteral Nutrition - Carbohydrates',
    therapeuticClass: 'Hypertonic Dextrose Solution', therapeuticClassAr: 'محلول دكستروز مفرط التوتر',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'IV Solution - Syringe', strength: '50 mL', unitPrice: 8.00, inStock: true },
      { form: 'IV Solution', strength: '500 mL', unitPrice: 18.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Dextrose 5%', 'Dextrose 10%'],
    blackBoxWarning: 'Hypertonic solution — must be given via central line for continuous infusion. Peripheral bolus for hypoglycemia only.',
    blackBoxWarningAr: 'محلول مفرط التوتر — يجب إعطاؤه عبر خط مركزي للتسريب المستمر. البلعة الطرفية لنقص السكر فقط.',
    interactions: [
      { interactsWith: 'Insulin', severity: 'major', mechanism: 'Concurrent insulin with D50W requires careful titration', clinicalEffect: 'Rebound hypoglycemia or persistent hyperglycemia', clinicalEffectAr: 'نقص سكر ارتدادي أو ارتفاع سكر مستمر', management: 'Use for emergent hypoglycemia; monitor glucose q15min post-dose', managementAr: 'استخدم لنقص السكر الطارئ؛ مراقبة السكر كل 15 دقيقة بعد الجرعة' },
    ],
    contraindications: ['Anuria', 'Intracranial hemorrhage', 'Delirium tremens in dehydrated patients'], contraindicationsAr: ['انقطاع البول', 'نزيف داخل الجمجمة', 'هذيان ارتعاشي في المرضى المجففين'],
    monitoringRequired: ['Blood glucose q15min post-dose', 'IV site for extravasation', 'Serum electrolytes'], storageConditions: 'Room temperature',
  },

  // ═══════════════════════════════════════════════════════════════
  // 2. COLLOIDS (FRM-0726 to FRM-0729)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'FRM-0726', genericName: 'Albumin 5% (Human)', genericNameAr: 'ألبومين بشري 5%',
    brandNames: ['Albuminar-5', 'Flexbumin 5%', 'AlbuRx 5'], sfda_registration: 'SFDA-BP-0726', atcCode: 'B05AA01', atcCategory: 'Blood Substitutes and Plasma Protein Fractions',
    therapeuticClass: 'Plasma Volume Expander', therapeuticClassAr: 'موسع حجم البلازما',
    formularyStatus: 'restricted', restrictionCriteria: 'Requires blood bank or ICU attending approval; documented hypoalbuminemia <2.5 g/dL or acute volume resuscitation',
    restrictionCriteriaAr: 'يتطلب موافقة بنك الدم أو استشاري العناية المركزة؛ نقص ألبومين موثق أقل من 2.5 أو إنعاش حجمي حاد',
    approverRole: 'blood_bank', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '250 mL', unitPrice: 185.00, inStock: true },
      { form: 'IV Solution', strength: '500 mL', unitPrice: 340.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Albumin 20%', 'Albumin 25%'],
    interactions: [
      { interactsWith: 'ACE Inhibitors', severity: 'moderate', mechanism: 'Albumin may potentiate hypotension with ACE inhibitors', clinicalEffect: 'Hypotensive episodes', clinicalEffectAr: 'نوبات انخفاض ضغط الدم', management: 'Monitor blood pressure closely during infusion', managementAr: 'مراقبة ضغط الدم عن كثب أثناء التسريب' },
    ],
    contraindications: ['Severe anemia', 'Heart failure', 'Known allergy to albumin'], contraindicationsAr: ['فقر دم شديد', 'فشل القلب', 'حساسية معروفة للألبومين'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'CVP', 'Serum albumin', 'Signs of fluid overload'], storageConditions: 'Store at 2-25°C, do not freeze, use within 4 hours of opening',
  },
  {
    id: 'FRM-0727', genericName: 'Albumin 20% (Human)', genericNameAr: 'ألبومين بشري 20%',
    brandNames: ['Albuminar-20', 'Flexbumin 20%', 'AlbuRx 20'], sfda_registration: 'SFDA-BP-0727', atcCode: 'B05AA01', atcCategory: 'Blood Substitutes and Plasma Protein Fractions',
    therapeuticClass: 'Hyperoncotic Colloid', therapeuticClassAr: 'غرواني مفرط الضغط التناضحي',
    formularyStatus: 'restricted', restrictionCriteria: 'Requires blood bank or ICU attending approval; for intravascular volume expansion and hypoalbuminemia',
    restrictionCriteriaAr: 'يتطلب موافقة بنك الدم أو استشاري العناية المركزة؛ لتوسيع الحجم داخل الأوعية ونقص الألبومين',
    approverRole: 'blood_bank', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '50 mL', unitPrice: 145.00, inStock: true },
      { form: 'IV Solution', strength: '100 mL', unitPrice: 260.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Albumin 5%', 'Albumin 25%'],
    interactions: [
      { interactsWith: 'Loop Diuretics', severity: 'moderate', mechanism: 'Synergistic fluid shift; albumin pulls fluid intravascularly then diuretic removes it', clinicalEffect: 'Enhanced diuresis in nephrotic syndrome', clinicalEffectAr: 'تعزيز إدرار البول في المتلازمة الكلوية', management: 'Intentional combination in nephrotic syndrome; monitor fluid balance and electrolytes', managementAr: 'توليفة مقصودة في المتلازمة الكلوية؛ مراقبة توازن السوائل والإلكتروليتات' },
    ],
    contraindications: ['Severe heart failure', 'Pulmonary edema'], contraindicationsAr: ['فشل قلبي شديد', 'وذمة رئوية'],
    monitoringRequired: ['Blood pressure', 'Serum albumin', 'CVP', 'Urine output', 'Pulmonary status'], storageConditions: 'Store at 2-25°C, do not freeze, use within 4 hours of opening',
  },
  {
    id: 'FRM-0728', genericName: 'Gelatin (Succinylated Gelatin)', genericNameAr: 'جيلاتين (جيلاتين سكسينيل)',
    brandNames: ['Gelofusine', 'Geloplasma'], sfda_registration: 'SFDA-IV-0728', atcCode: 'B05AA06', atcCategory: 'Blood Substitutes and Plasma Protein Fractions',
    therapeuticClass: 'Colloid Plasma Expander', therapeuticClassAr: 'موسع بلازما غرواني',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '500 mL', unitPrice: 32.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Gelatin (food grade)', 'HES solutions'],
    interactions: [
      { interactsWith: 'Aminoglycosides', severity: 'moderate', mechanism: 'Gelatin may mask nephrotoxicity signs through volume expansion', clinicalEffect: 'Delayed detection of nephrotoxicity', clinicalEffectAr: 'تأخر اكتشاف السمية الكلوية', management: 'Monitor renal function and aminoglycoside levels', managementAr: 'مراقبة وظائف الكلى ومستويات الأمينوغليكوزيد' },
    ],
    contraindications: ['Known gelatin allergy', 'Severe hypervolemia', 'Severe renal impairment'], contraindicationsAr: ['حساسية معروفة للجيلاتين', 'فرط حجم شديد', 'قصور كلوي شديد'],
    monitoringRequired: ['Blood pressure', 'Renal function', 'Signs of anaphylaxis', 'Coagulation parameters'], storageConditions: 'Room temperature, do not freeze',
  },
  {
    id: 'FRM-0729', genericName: 'Hydroxyethyl Starch (HES) 6%', genericNameAr: 'هيدروكسي إيثيل نشا 6%',
    brandNames: ['Voluven', 'Volulyte'], sfda_registration: 'SFDA-IV-0729', atcCode: 'B05AA07', atcCategory: 'Blood Substitutes and Plasma Protein Fractions',
    therapeuticClass: 'Synthetic Colloid', therapeuticClassAr: 'غرواني صناعي',
    formularyStatus: 'restricted', restrictionCriteria: 'Restricted due to safety concerns; only for acute hypovolemia when crystalloids insufficient. Max 24h use. Contraindicated in critically ill, sepsis, renal impairment.',
    restrictionCriteriaAr: 'مقيد بسبب مخاوف السلامة؛ فقط لنقص حجم الدم الحاد عند عدم كفاية المحاليل البلورية. استخدام أقصى 24 ساعة.',
    approverRole: 'icu_consultant', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '500 mL', unitPrice: 55.00, inStock: true },
    ],
    maxDailyDose: 30, maxDailyDoseUnit: 'mL/kg',
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Gelofusine', 'Albumin'],
    blackBoxWarning: 'Increased risk of mortality and renal replacement therapy in critically ill patients including sepsis. Do not use in these populations.',
    blackBoxWarningAr: 'خطر متزايد للوفاة والعلاج بالبدائل الكلوية في المرضى ذوي الحالات الحرجة بما في ذلك الإنتان. لا تستخدم في هذه الفئات.',
    interactions: [
      { interactsWith: 'Anticoagulants', severity: 'major', mechanism: 'HES impairs coagulation by dilutional coagulopathy and direct factor inhibition', clinicalEffect: 'Increased bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف', management: 'Monitor coagulation closely; avoid in patients on full anticoagulation', managementAr: 'مراقبة التخثر عن كثب؛ تجنب في المرضى على مضادات التخثر الكاملة' },
    ],
    contraindications: ['Sepsis', 'Critical illness', 'Renal impairment', 'Coagulopathy', 'Intracranial hemorrhage', 'Burns'], contraindicationsAr: ['إنتان', 'حالة حرجة', 'قصور كلوي', 'اعتلال تخثر', 'نزيف داخل الجمجمة', 'حروق'],
    monitoringRequired: ['Renal function daily', 'Coagulation parameters', 'Fluid balance', 'Maximum dose limit'], storageConditions: 'Room temperature, do not freeze',
  },

  // ═══════════════════════════════════════════════════════════════
  // 3. ELECTROLYTES IV (FRM-0730 to FRM-0737)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'FRM-0730', genericName: 'Potassium Chloride Injection', genericNameAr: 'حقن كلوريد البوتاسيوم',
    brandNames: ['KCl Injection', 'K-Rider'], sfda_registration: 'SFDA-IV-0730', atcCode: 'B05XA01', atcCategory: 'Electrolyte Solutions',
    therapeuticClass: 'Potassium Supplement IV', therapeuticClassAr: 'مكمل بوتاسيوم وريدي',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'Concentrate for Injection', strength: '20 mEq/10 mL', unitPrice: 5.50, inStock: true },
      { form: 'Concentrate for Injection', strength: '40 mEq/20 mL', unitPrice: 8.00, inStock: true },
      { form: 'Premixed IV', strength: '20 mEq/1000 mL NS', unitPrice: 12.00, inStock: true },
      { form: 'Premixed IV', strength: '40 mEq/1000 mL NS', unitPrice: 14.00, inStock: true },
    ],
    maxDailyDose: 200, maxDailyDoseUnit: 'mEq',
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Potassium Phosphate', 'Sodium Chloride'],
    blackBoxWarning: 'FATAL if given undiluted or by IV push. Must always be diluted and given by slow infusion. Max peripheral rate 10 mEq/hr, max central 20 mEq/hr.',
    blackBoxWarningAr: 'قاتل إذا أعطي بدون تخفيف أو بالحقن المباشر. يجب تخفيفه دائماً وإعطاؤه بالتسريب البطيء. أقصى معدل طرفي 10 ملي مكافئ/ساعة.',
    interactions: [
      { interactsWith: 'ACE Inhibitors', severity: 'major', mechanism: 'ACE inhibitors reduce aldosterone causing potassium retention', clinicalEffect: 'Life-threatening hyperkalemia', clinicalEffectAr: 'فرط بوتاسيوم الدم المهدد للحياة', management: 'Monitor potassium closely; reduce KCl dose when on ACEI/ARB', managementAr: 'مراقبة البوتاسيوم عن كثب؛ تقليل جرعة كلوريد البوتاسيوم مع مثبطات الإنزيم' },
      { interactsWith: 'Potassium-sparing Diuretics', severity: 'major', mechanism: 'Additive potassium retention', clinicalEffect: 'Hyperkalemia with cardiac arrhythmias', clinicalEffectAr: 'فرط بوتاسيوم مع اضطراب نظم القلب', management: 'Avoid combination; if needed, monitor K+ levels q4-6h', managementAr: 'تجنب الجمع؛ إذا لزم الأمر، مراقبة البوتاسيوم كل 4-6 ساعات' },
    ],
    contraindications: ['Hyperkalemia', 'Severe renal failure (anuria)', 'Untreated Addison\'s disease', 'Crush injury'], contraindicationsAr: ['فرط بوتاسيوم الدم', 'فشل كلوي شديد (انقطاع البول)', 'داء أديسون غير المعالج', 'إصابة السحق'],
    monitoringRequired: ['Serum potassium before and during infusion', 'Continuous cardiac monitoring if >10 mEq/hr', 'Renal function', 'IV site for phlebitis'], storageConditions: 'Room temperature, protect from light',
  },
  {
    id: 'FRM-0731', genericName: 'Magnesium Sulfate Injection', genericNameAr: 'حقن كبريتات المغنيسيوم',
    brandNames: ['MgSO4', 'Magnesium Sulfate Inj'], sfda_registration: 'SFDA-IV-0731', atcCode: 'B05XA05', atcCategory: 'Electrolyte Solutions',
    therapeuticClass: 'Magnesium Supplement IV', therapeuticClassAr: 'مكمل مغنيسيوم وريدي',
    formularyStatus: 'formulary', route: ['IV', 'IM'], forms: [
      { form: 'Injection', strength: '50% (500 mg/mL) 10 mL', unitPrice: 4.00, inStock: true },
      { form: 'Injection', strength: '50% (500 mg/mL) 2 mL', unitPrice: 2.50, inStock: true },
      { form: 'Premixed IV', strength: '4 g/100 mL D5W', unitPrice: 15.00, inStock: true },
    ],
    maxDailyDose: 40, maxDailyDoseUnit: 'g',
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Magnesium Oxide', 'Manganese Sulfate'],
    blackBoxWarning: 'Rapid IV administration can cause respiratory depression, hypotension, and cardiac arrest. Calcium gluconate must be available as antidote.',
    blackBoxWarningAr: 'الإعطاء الوريدي السريع يمكن أن يسبب اكتئاب تنفسي وانخفاض ضغط الدم وسكتة قلبية. يجب توفر غلوكونات الكالسيوم كمضاد.',
    interactions: [
      { interactsWith: 'Neuromuscular Blocking Agents', severity: 'major', mechanism: 'Magnesium potentiates neuromuscular blockade', clinicalEffect: 'Prolonged paralysis and respiratory depression', clinicalEffectAr: 'شلل مطول واكتئاب تنفسي', management: 'Reduce NMBA dose by 25-50%; monitor neuromuscular function', managementAr: 'تقليل جرعة مرخيات العضلات 25-50٪؛ مراقبة الوظيفة العصبية العضلية' },
      { interactsWith: 'Calcium Channel Blockers', severity: 'major', mechanism: 'Additive cardiovascular depression', clinicalEffect: 'Severe hypotension and bradycardia', clinicalEffectAr: 'انخفاض حاد في ضغط الدم وبطء القلب', management: 'Use with extreme caution; continuous cardiac monitoring', managementAr: 'استخدام بحذر شديد؛ مراقبة قلبية مستمرة' },
    ],
    contraindications: ['Heart block', 'Myocardial damage', 'Severe renal impairment (without monitoring)'], contraindicationsAr: ['إحصار القلب', 'تلف عضلة القلب', 'قصور كلوي شديد (بدون مراقبة)'],
    monitoringRequired: ['Serum magnesium', 'Deep tendon reflexes', 'Respiratory rate', 'Urine output', 'Cardiac monitoring'], storageConditions: 'Room temperature',
  },
  {
    id: 'FRM-0732', genericName: 'Calcium Gluconate Injection', genericNameAr: 'حقن غلوكونات الكالسيوم',
    brandNames: ['Calcium Gluconate 10%'], sfda_registration: 'SFDA-IV-0732', atcCode: 'A12AA03', atcCategory: 'Calcium Supplements',
    therapeuticClass: 'Calcium Supplement IV', therapeuticClassAr: 'مكمل كالسيوم وريدي',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'Injection', strength: '10% (100 mg/mL) 10 mL', unitPrice: 4.50, inStock: true },
      { form: 'Injection', strength: '10% (100 mg/mL) 50 mL', unitPrice: 12.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Calcium Chloride', 'Calcium Carbonate'],
    interactions: [
      { interactsWith: 'Digoxin', severity: 'major', mechanism: 'IV calcium potentiates digoxin toxicity via increased cardiac contractility', clinicalEffect: 'Fatal cardiac arrhythmias', clinicalEffectAr: 'اضطرابات نظم القلب القاتلة', management: 'Avoid rapid IV calcium in digitalized patients; infuse slowly with cardiac monitoring', managementAr: 'تجنب الكالسيوم الوريدي السريع في مرضى الديجوكسين؛ تسريب بطيء مع مراقبة القلب' },
      { interactsWith: 'Ceftriaxone', severity: 'major', mechanism: 'Calcium-ceftriaxone precipitates can form in lungs and kidneys', clinicalEffect: 'Organ damage from precipitates (especially neonates)', clinicalEffectAr: 'تلف الأعضاء من الترسبات (خاصة حديثي الولادة)', management: 'Do not mix; use separate lines; contraindicated in neonates', managementAr: 'لا تخلط؛ استخدم خطوط منفصلة؛ ممنوع في حديثي الولادة' },
    ],
    contraindications: ['Hypercalcemia', 'Digitalis toxicity', 'Ventricular fibrillation'], contraindicationsAr: ['فرط كالسيوم الدم', 'تسمم الديجيتال', 'رجفان بطيني'],
    monitoringRequired: ['Serum calcium (ionized)', 'Cardiac monitoring during infusion', 'IV site (extravasation causes necrosis)', 'Renal function'], storageConditions: 'Room temperature, protect from freezing',
  },
  {
    id: 'FRM-0733', genericName: 'Sodium Chloride 3% (Hypertonic Saline)', genericNameAr: 'محلول كلوريد الصوديوم 3% (ملحي مفرط التوتر)',
    brandNames: ['Hypertonic Saline 3%', 'NaCl 3%'], sfda_registration: 'SFDA-IV-0733', atcCode: 'B05XA03', atcCategory: 'Electrolyte Solutions',
    therapeuticClass: 'Hypertonic Saline', therapeuticClassAr: 'محلول ملحي مفرط التوتر',
    formularyStatus: 'restricted', restrictionCriteria: 'ICU-only use; requires intensivist or neurologist order for symptomatic hyponatremia or cerebral edema',
    restrictionCriteriaAr: 'استخدام العناية المركزة فقط؛ يتطلب أمر طبيب العناية المركزة أو أخصائي الأعصاب لنقص الصوديوم العرضي أو الوذمة الدماغية',
    approverRole: 'icu_consultant', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '500 mL', unitPrice: 18.00, inStock: true },
      { form: 'IV Solution', strength: '250 mL', unitPrice: 12.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Sodium Chloride 0.9%', 'Sodium Chloride 0.45%'],
    blackBoxWarning: 'Rapid correction of hyponatremia can cause osmotic demyelination syndrome (ODS). Do not exceed 8 mEq/L/24h correction rate.',
    blackBoxWarningAr: 'التصحيح السريع لنقص الصوديوم يمكن أن يسبب متلازمة إزالة الميالين التناضحية. لا تتجاوز معدل التصحيح 8 ملي مكافئ/لتر/24 ساعة.',
    interactions: [
      { interactsWith: 'Lithium', severity: 'major', mechanism: 'Rapid sodium load increases lithium clearance unpredictably', clinicalEffect: 'Fluctuating lithium levels', clinicalEffectAr: 'تذبذب مستويات الليثيوم', management: 'Monitor lithium levels frequently during and after hypertonic saline', managementAr: 'مراقبة مستويات الليثيوم بشكل متكرر أثناء وبعد المحلول الملحي مفرط التوتر' },
    ],
    contraindications: ['Hypernatremia', 'Fluid overload without hyponatremia'], contraindicationsAr: ['فرط صوديوم الدم', 'فرط حمل السوائل بدون نقص صوديوم'],
    monitoringRequired: ['Serum sodium q2h during infusion', 'Neurological checks q1h', 'Correction rate calculation', 'Fluid balance'], storageConditions: 'Room temperature',
  },
  {
    id: 'FRM-0734', genericName: 'Sodium Bicarbonate 8.4% Injection', genericNameAr: 'حقن بيكربونات الصوديوم 8.4%',
    brandNames: ['NaHCO3 8.4%', 'Sodium Bicarbonate Inj'], sfda_registration: 'SFDA-IV-0734', atcCode: 'B05XA02', atcCategory: 'Electrolyte Solutions',
    therapeuticClass: 'Alkalinizing Agent', therapeuticClassAr: 'عامل قلوية',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'Injection', strength: '8.4% (1 mEq/mL) 50 mL', unitPrice: 8.00, inStock: true },
      { form: 'Injection', strength: '8.4% (1 mEq/mL) 10 mL', unitPrice: 3.50, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Sodium Chloride', 'Sodium Phosphate'],
    interactions: [
      { interactsWith: 'Methotrexate', severity: 'moderate', mechanism: 'Urinary alkalinization increases methotrexate clearance', clinicalEffect: 'Reduced methotrexate toxicity (therapeutic use)', clinicalEffectAr: 'تقليل سمية الميثوتريكسات (استخدام علاجي)', management: 'Used intentionally for high-dose MTX; monitor urine pH', managementAr: 'يستخدم عمداً مع جرعات الميثوتريكسات العالية؛ مراقبة pH البول' },
    ],
    contraindications: ['Metabolic or respiratory alkalosis', 'Hypocalcemia', 'Hypokalemia'], contraindicationsAr: ['قلاء استقلابي أو تنفسي', 'نقص كالسيوم الدم', 'نقص بوتاسيوم الدم'],
    monitoringRequired: ['ABG', 'Serum electrolytes (K+, Ca++, Na+)', 'Fluid balance', 'IV site'], storageConditions: 'Room temperature',
  },
  {
    id: 'FRM-0735', genericName: 'Potassium Phosphate Injection', genericNameAr: 'حقن فوسفات البوتاسيوم',
    brandNames: ['KPhos', 'Potassium Phosphate Inj'], sfda_registration: 'SFDA-IV-0735', atcCode: 'B05XA06', atcCategory: 'Electrolyte Solutions',
    therapeuticClass: 'Phosphate and Potassium Supplement', therapeuticClassAr: 'مكمل فوسفات وبوتاسيوم',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'Concentrate for Injection', strength: '15 mmol phosphate + 22 mEq K / 5 mL', unitPrice: 9.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Sodium Phosphate', 'Potassium Chloride'],
    interactions: [
      { interactsWith: 'ACE Inhibitors', severity: 'major', mechanism: 'Potassium content plus ACE inhibitor potassium retention', clinicalEffect: 'Hyperkalemia', clinicalEffectAr: 'فرط بوتاسيوم الدم', management: 'Monitor potassium closely; consider sodium phosphate alternative', managementAr: 'مراقبة البوتاسيوم عن كثب؛ النظر في بديل فوسفات الصوديوم' },
    ],
    contraindications: ['Hyperkalemia', 'Hyperphosphatemia', 'Severe renal failure'], contraindicationsAr: ['فرط بوتاسيوم الدم', 'فرط فوسفات الدم', 'فشل كلوي شديد'],
    monitoringRequired: ['Serum phosphate', 'Serum potassium', 'Serum calcium (inverse relationship)', 'Renal function', 'Cardiac monitoring'], storageConditions: 'Room temperature, protect from freezing',
  },
  {
    id: 'FRM-0736', genericName: 'Sodium Phosphate Injection', genericNameAr: 'حقن فوسفات الصوديوم',
    brandNames: ['Na Phosphate Inj'], sfda_registration: 'SFDA-IV-0736', atcCode: 'B05XA09', atcCategory: 'Electrolyte Solutions',
    therapeuticClass: 'Phosphate Supplement', therapeuticClassAr: 'مكمل فوسفات',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'Concentrate for Injection', strength: '15 mmol phosphate / 5 mL', unitPrice: 8.50, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Potassium Phosphate', 'Sodium Chloride'],
    interactions: [
      { interactsWith: 'Calcium-containing IV Solutions', severity: 'major', mechanism: 'Calcium-phosphate precipitation in IV line', clinicalEffect: 'IV line occlusion and microembolism', clinicalEffectAr: 'انسداد خط الوريد وانصمام مجهري', management: 'Never mix with calcium; flush line between infusions', managementAr: 'لا تخلط أبداً مع الكالسيوم؛ اغسل الخط بين التسريبات' },
    ],
    contraindications: ['Hyperphosphatemia', 'Hypocalcemia', 'Hypernatremia', 'Severe renal impairment'], contraindicationsAr: ['فرط فوسفات الدم', 'نقص كالسيوم الدم', 'فرط صوديوم الدم', 'قصور كلوي شديد'],
    monitoringRequired: ['Serum phosphate', 'Serum calcium', 'Serum sodium', 'Renal function'], storageConditions: 'Room temperature, protect from freezing',
  },
  {
    id: 'FRM-0737', genericName: 'Mannitol 20% Injection', genericNameAr: 'حقن مانيتول 20%',
    brandNames: ['Osmitrol', 'Mannitol 20%'], sfda_registration: 'SFDA-IV-0737', atcCode: 'B05BC01', atcCategory: 'Solutions Producing Osmotic Diuresis',
    therapeuticClass: 'Osmotic Diuretic', therapeuticClassAr: 'مدر بول تناضحي',
    formularyStatus: 'formulary', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '20% (200 mg/mL) 250 mL', unitPrice: 22.00, inStock: true },
      { form: 'IV Solution', strength: '20% (200 mg/mL) 500 mL', unitPrice: 35.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Mannitol 10%', 'Sorbitol'],
    interactions: [
      { interactsWith: 'Lithium', severity: 'major', mechanism: 'Osmotic diuresis increases lithium clearance', clinicalEffect: 'Sub-therapeutic lithium levels', clinicalEffectAr: 'مستويات ليثيوم دون العلاجية', management: 'Monitor lithium levels; may need dose adjustment', managementAr: 'مراقبة مستويات الليثيوم؛ قد تحتاج لتعديل الجرعة' },
      { interactsWith: 'Nephrotoxic drugs', severity: 'moderate', mechanism: 'Mannitol can potentiate or mask nephrotoxicity', clinicalEffect: 'Renal impairment', clinicalEffectAr: 'قصور كلوي', management: 'Monitor renal function and osmol gap', managementAr: 'مراقبة وظائف الكلى وفجوة الأسمولية' },
    ],
    contraindications: ['Anuria', 'Severe dehydration', 'Active intracranial bleeding', 'Severe pulmonary congestion', 'Severe heart failure'], contraindicationsAr: ['انقطاع البول', 'جفاف شديد', 'نزيف داخل الجمجمة نشط', 'احتقان رئوي شديد', 'فشل قلبي شديد'],
    monitoringRequired: ['Serum osmolality (hold if >320)', 'Renal function', 'Serum electrolytes', 'Fluid balance', 'Intracranial pressure'], storageConditions: 'Room temperature; inspect for crystals before use, warm and redissolve if needed',
  },

  // ═══════════════════════════════════════════════════════════════
  // 4. ELECTROLYTES ORAL (FRM-0738 to FRM-0741)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'FRM-0738', genericName: 'Oral Rehydration Salts (ORS)', genericNameAr: 'أملاح الإماهة الفموية',
    brandNames: ['ORS', 'Rehydran', 'Dioralyte'], sfda_registration: 'SFDA-OTC-0738', atcCode: 'A07CA', atcCategory: 'Oral Rehydration Salt Formulations',
    therapeuticClass: 'Oral Rehydration Solution', therapeuticClassAr: 'محلول إماهة فموي',
    formularyStatus: 'formulary', route: ['oral'], forms: [
      { form: 'Powder Sachet', strength: 'WHO formula per sachet (to make 1L)', unitPrice: 2.00, inStock: true },
      { form: 'Ready-to-drink', strength: '200 mL', unitPrice: 3.50, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Intestinal obstruction', 'Severe vomiting (use IV route)'], contraindicationsAr: ['انسداد معوي', 'قيء شديد (استخدم الطريق الوريدي)'],
    monitoringRequired: ['Hydration status', 'Urine output', 'Stool output'], storageConditions: 'Room temperature; use within 24 hours of reconstitution',
  },
  {
    id: 'FRM-0739', genericName: 'Potassium Chloride Oral', genericNameAr: 'كلوريد البوتاسيوم فموي',
    brandNames: ['Slow-K', 'K-Dur', 'Klor-Con'], sfda_registration: 'SFDA-GEN-0739', atcCode: 'A12BA01', atcCategory: 'Potassium',
    therapeuticClass: 'Oral Potassium Supplement', therapeuticClassAr: 'مكمل بوتاسيوم فموي',
    formularyStatus: 'formulary', route: ['oral'], forms: [
      { form: 'Slow-release Tablet', strength: '600 mg (8 mEq)', unitPrice: 0.80, inStock: true },
      { form: 'Oral Solution', strength: '20 mEq/15 mL', unitPrice: 5.00, inStock: true },
      { form: 'Effervescent Tablet', strength: '25 mEq', unitPrice: 1.20, inStock: true },
    ],
    maxDailyDose: 100, maxDailyDoseUnit: 'mEq',
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Potassium Phosphate', 'Potassium Citrate'],
    interactions: [
      { interactsWith: 'ACE Inhibitors / ARBs', severity: 'major', mechanism: 'Additive potassium retention', clinicalEffect: 'Hyperkalemia', clinicalEffectAr: 'فرط بوتاسيوم الدم', management: 'Monitor serum potassium regularly', managementAr: 'مراقبة بوتاسيوم الدم بانتظام' },
    ],
    contraindications: ['Hyperkalemia', 'Severe renal impairment', 'GI obstruction (for solid forms)'], contraindicationsAr: ['فرط بوتاسيوم الدم', 'قصور كلوي شديد', 'انسداد معدي معوي (للأقراص)'],
    monitoringRequired: ['Serum potassium', 'Renal function', 'GI tolerance'], storageConditions: 'Room temperature, protect from moisture',
  },
  {
    id: 'FRM-0740', genericName: 'Magnesium Oxide Oral', genericNameAr: 'أكسيد المغنيسيوم فموي',
    brandNames: ['Mag-Ox 400', 'MagOx'], sfda_registration: 'SFDA-GEN-0740', atcCode: 'A12CC10', atcCategory: 'Magnesium',
    therapeuticClass: 'Oral Magnesium Supplement', therapeuticClassAr: 'مكمل مغنيسيوم فموي',
    formularyStatus: 'formulary', route: ['oral'], forms: [
      { form: 'Tablet', strength: '400 mg (241 mg elemental Mg)', unitPrice: 0.50, inStock: true },
      { form: 'Capsule', strength: '500 mg', unitPrice: 0.65, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Magnesium Sulfate', 'Magnesium Citrate'],
    interactions: [
      { interactsWith: 'Tetracyclines', severity: 'moderate', mechanism: 'Magnesium chelates tetracyclines reducing absorption', clinicalEffect: 'Reduced antibiotic efficacy', clinicalEffectAr: 'تقليل فعالية المضاد الحيوي', management: 'Separate administration by at least 2 hours', managementAr: 'فصل الإعطاء بساعتين على الأقل' },
      { interactsWith: 'Bisphosphonates', severity: 'moderate', mechanism: 'Divalent cations reduce bisphosphonate absorption', clinicalEffect: 'Reduced bisphosphonate efficacy', clinicalEffectAr: 'تقليل فعالية البيسفوسفونات', management: 'Take bisphosphonate at least 30 min before magnesium', managementAr: 'تناول البيسفوسفونات قبل 30 دقيقة على الأقل من المغنيسيوم' },
    ],
    contraindications: ['Severe renal impairment', 'Heart block'], contraindicationsAr: ['قصور كلوي شديد', 'إحصار القلب'],
    monitoringRequired: ['Serum magnesium', 'Renal function', 'GI symptoms (diarrhea)'], storageConditions: 'Room temperature, protect from moisture',
  },
  {
    id: 'FRM-0741', genericName: 'Calcium Carbonate Oral', genericNameAr: 'كربونات الكالسيوم فموي',
    brandNames: ['Caltrate', 'Os-Cal', 'Tums'], sfda_registration: 'SFDA-OTC-0741', atcCode: 'A12AA04', atcCategory: 'Calcium Supplements',
    therapeuticClass: 'Oral Calcium Supplement', therapeuticClassAr: 'مكمل كالسيوم فموي',
    formularyStatus: 'formulary', route: ['oral'], forms: [
      { form: 'Chewable Tablet', strength: '500 mg (200 mg elemental Ca)', unitPrice: 0.30, inStock: true },
      { form: 'Tablet', strength: '1250 mg (500 mg elemental Ca)', unitPrice: 0.45, inStock: true },
    ],
    maxDailyDose: 2500, maxDailyDoseUnit: 'mg elemental calcium',
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Calcium Gluconate', 'Calcium Citrate'],
    interactions: [
      { interactsWith: 'Levothyroxine', severity: 'moderate', mechanism: 'Calcium reduces levothyroxine absorption', clinicalEffect: 'Hypothyroidism due to reduced T4 absorption', clinicalEffectAr: 'قصور الغدة الدرقية بسبب نقص امتصاص T4', management: 'Separate by at least 4 hours', managementAr: 'فصل الإعطاء بأربع ساعات على الأقل' },
      { interactsWith: 'Iron supplements', severity: 'moderate', mechanism: 'Calcium reduces iron absorption', clinicalEffect: 'Reduced iron bioavailability', clinicalEffectAr: 'تقليل التوافر البيولوجي للحديد', management: 'Separate by at least 2 hours', managementAr: 'فصل الإعطاء بساعتين على الأقل' },
    ],
    contraindications: ['Hypercalcemia', 'Renal calculi', 'Hypophosphatemia'], contraindicationsAr: ['فرط كالسيوم الدم', 'حصوات كلوية', 'نقص فوسفات الدم'],
    monitoringRequired: ['Serum calcium', 'Renal function', 'Vitamin D status'], storageConditions: 'Room temperature, protect from moisture',
  },

  // ═══════════════════════════════════════════════════════════════
  // 5. TPN COMPONENTS (FRM-0742 to FRM-0749)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'FRM-0742', genericName: 'Amino Acid 10% Solution (TPN)', genericNameAr: 'محلول أحماض أمينية 10% (تغذية وريدية)',
    brandNames: ['Travasol 10%', 'Aminosyn 10%', 'Freamine III'], sfda_registration: 'SFDA-TPN-0742', atcCode: 'B05BA01', atcCategory: 'Amino Acids for Parenteral Nutrition',
    therapeuticClass: 'TPN - Amino Acid Solution', therapeuticClassAr: 'تغذية وريدية - محلول أحماض أمينية',
    formularyStatus: 'conditional', restrictionCriteria: 'Requires clinical nutrition team or ICU attending order; documented inability to use enteral nutrition',
    restrictionCriteriaAr: 'يتطلب أمر فريق التغذية السريرية أو استشاري العناية المركزة؛ عدم القدرة الموثق على استخدام التغذية المعوية',
    approverRole: 'clinical_nutrition', route: ['IV'], forms: [
      { form: 'IV Solution', strength: '10% 500 mL', unitPrice: 65.00, inStock: true },
      { form: 'IV Solution', strength: '10% 1000 mL', unitPrice: 110.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Amino Acid 8.5%', 'Amino Acid 15%'],
    interactions: [
      { interactsWith: 'Tetracyclines', severity: 'minor', mechanism: 'Amino acids may chelate tetracyclines in TPN admixture', clinicalEffect: 'Reduced antibiotic concentration in TPN', clinicalEffectAr: 'تقليل تركيز المضاد الحيوي في التغذية الوريدية', management: 'Do not add tetracyclines to TPN bags; administer separately', managementAr: 'لا تضف التتراسيكلين لأكياس التغذية الوريدية؛ أعطها بشكل منفصل' },
    ],
    contraindications: ['Inborn errors of amino acid metabolism', 'Severe hepatic encephalopathy', 'Anuria without dialysis'], contraindicationsAr: ['أخطاء خلقية في استقلاب الأحماض الأمينية', 'اعتلال دماغي كبدي شديد', 'انقطاع بول بدون غسيل كلوي'],
    monitoringRequired: ['BUN/Creatinine', 'Hepatic function', 'Serum electrolytes', 'Blood glucose', 'Prealbumin/Albumin', 'Nitrogen balance'], storageConditions: 'Refrigerate 2-8°C until use; room temperature during infusion',
  },
  {
    id: 'FRM-0743', genericName: 'Lipid Emulsion 20% (Intralipid)', genericNameAr: 'مستحلب دهني 20% (إنتراليبيد)',
    brandNames: ['Intralipid 20%', 'Lipofundin 20%', 'SMOFlipid'], sfda_registration: 'SFDA-TPN-0743', atcCode: 'B05BA02', atcCategory: 'Fat Emulsions for Parenteral Nutrition',
    therapeuticClass: 'TPN - Lipid Emulsion', therapeuticClassAr: 'تغذية وريدية - مستحلب دهني',
    formularyStatus: 'conditional', restrictionCriteria: 'Requires clinical nutrition team order; part of TPN regimen',
    restrictionCriteriaAr: 'يتطلب أمر فريق التغذية السريرية؛ جزء من نظام التغذية الوريدية',
    approverRole: 'clinical_nutrition', route: ['IV'], forms: [
      { form: 'IV Emulsion', strength: '20% 250 mL', unitPrice: 55.00, inStock: true },
      { form: 'IV Emulsion', strength: '20% 500 mL', unitPrice: 95.00, inStock: true },
    ],
    maxDailyDose: 2.5, maxDailyDoseUnit: 'g/kg/day',
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Lipid Emulsion 10%', 'Propofol (lipid-based)'],
    interactions: [
      { interactsWith: 'Propofol', severity: 'moderate', mechanism: 'Both contain lipid; concurrent use can cause fat overload', clinicalEffect: 'Hypertriglyceridemia and fat overload syndrome', clinicalEffectAr: 'فرط الدهون الثلاثية ومتلازمة فرط حمل الدهون', management: 'Account for propofol lipid calories in TPN lipid calculation', managementAr: 'احسب سعرات دهون البروبوفول في حساب دهون التغذية الوريدية' },
    ],
    contraindications: ['Severe hyperlipidemia (TG >400)', 'Severe egg allergy', 'Severe soy allergy', 'Acute pancreatitis with hyperlipidemia'], contraindicationsAr: ['فرط شحميات الدم الشديد (الدهون الثلاثية >400)', 'حساسية شديدة للبيض', 'حساسية شديدة للصويا', 'التهاب بنكرياس حاد مع فرط شحميات'],
    monitoringRequired: ['Serum triglycerides', 'Liver function', 'CBC (platelet count)', 'Inspect emulsion integrity before use'], storageConditions: 'Refrigerate 2-8°C; do not freeze; use within 24 hours of opening',
  },
  {
    id: 'FRM-0744', genericName: 'Dextrose 70% (TPN Additive)', genericNameAr: 'دكستروز 70% (مضاف للتغذية الوريدية)',
    brandNames: ['Dextrose 70%', 'D70W'], sfda_registration: 'SFDA-TPN-0744', atcCode: 'B05BA03', atcCategory: 'Solutions for Parenteral Nutrition - Carbohydrates',
    therapeuticClass: 'TPN - Concentrated Dextrose', therapeuticClassAr: 'تغذية وريدية - دكستروز مركز',
    formularyStatus: 'conditional', restrictionCriteria: 'TPN compounding use only; must be prepared by pharmacy TPN team',
    restrictionCriteriaAr: 'للاستخدام في تركيب التغذية الوريدية فقط؛ يجب تحضيره بواسطة فريق صيدلية التغذية الوريدية',
    approverRole: 'clinical_nutrition', route: ['IV'], forms: [
      { form: 'IV Solution (pharmacy bulk)', strength: '70% 500 mL', unitPrice: 20.00, inStock: true },
      { form: 'IV Solution (pharmacy bulk)', strength: '70% 1000 mL', unitPrice: 35.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Dextrose 5%', 'Dextrose 50%', 'Dextrose 10%'],
    blackBoxWarning: 'Must NEVER be administered undiluted. For TPN compounding only. Direct IV infusion causes severe hyperglycemia and hyperosmolarity.',
    blackBoxWarningAr: 'يجب ألا يُعطى بدون تخفيف أبداً. لتركيب التغذية الوريدية فقط. الحقن الوريدي المباشر يسبب فرط سكر شديد وفرط أسمولية.',
    interactions: [
      { interactsWith: 'Insulin', severity: 'moderate', mechanism: 'High dextrose concentration in TPN requires insulin co-administration', clinicalEffect: 'Hyperglycemia without adequate insulin', clinicalEffectAr: 'ارتفاع سكر الدم بدون أنسولين كافٍ', management: 'Add insulin to TPN or give separate infusion; monitor glucose q6h', managementAr: 'أضف الأنسولين للتغذية الوريدية أو أعطِ تسريباً منفصلاً؛ راقب السكر كل 6 ساعات' },
    ],
    contraindications: ['Direct IV administration', 'Uncontrolled hyperglycemia'], contraindicationsAr: ['الإعطاء الوريدي المباشر', 'فرط سكر الدم غير المسيطر عليه'],
    monitoringRequired: ['Blood glucose q6h during TPN', 'Serum electrolytes', 'Hepatic function weekly'], storageConditions: 'Room temperature',
  },
  {
    id: 'FRM-0745', genericName: 'Trace Elements Solution (TPN)', genericNameAr: 'محلول العناصر النزرة (تغذية وريدية)',
    brandNames: ['MTE-5', 'Addamel N', 'Multi-Trace Element'], sfda_registration: 'SFDA-TPN-0745', atcCode: 'B05XA31', atcCategory: 'Trace Elements for Parenteral Nutrition',
    therapeuticClass: 'TPN - Trace Elements', therapeuticClassAr: 'تغذية وريدية - عناصر نزرة',
    formularyStatus: 'conditional', restrictionCriteria: 'Part of TPN regimen; added by pharmacy during compounding',
    restrictionCriteriaAr: 'جزء من نظام التغذية الوريدية؛ يضاف بواسطة الصيدلية أثناء التركيب',
    approverRole: 'clinical_nutrition', route: ['IV'], forms: [
      { form: 'Concentrate for Addition', strength: '10 mL vial (Zn, Cu, Mn, Cr, Se)', unitPrice: 18.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['MVI (multivitamin injection)'],
    interactions: [],
    contraindications: ['Wilson\'s disease (copper component)', 'Cholestatic liver disease (manganese accumulation)'], contraindicationsAr: ['مرض ويلسون (مكون النحاس)', 'مرض الكبد الركودي (تراكم المنغنيز)'],
    monitoringRequired: ['Serum zinc', 'Serum copper', 'Manganese levels (with prolonged TPN)', 'Hepatic function'], storageConditions: 'Room temperature, protect from light',
  },
  {
    id: 'FRM-0746', genericName: 'Multivitamin Injection (MVI)', genericNameAr: 'حقن فيتامينات متعددة',
    brandNames: ['MVI-12', 'Infuvite Adult', 'Cernevit'], sfda_registration: 'SFDA-TPN-0746', atcCode: 'A11BA', atcCategory: 'Multivitamins, Combinations',
    therapeuticClass: 'TPN - Multivitamin Additive', therapeuticClassAr: 'تغذية وريدية - مضاف فيتامينات متعددة',
    formularyStatus: 'conditional', restrictionCriteria: 'Part of TPN regimen; added daily to TPN by pharmacy',
    restrictionCriteriaAr: 'جزء من نظام التغذية الوريدية؛ يضاف يومياً للتغذية الوريدية بواسطة الصيدلية',
    approverRole: 'clinical_nutrition', route: ['IV'], forms: [
      { form: 'Lyophilized Powder + Diluent', strength: '1 vial/day', unitPrice: 25.00, inStock: true },
      { form: 'Solution for Addition', strength: '10 mL vial', unitPrice: 22.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Trace Elements', 'Vitamin B Complex'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Vitamin K in MVI antagonizes warfarin', clinicalEffect: 'Reduced anticoagulant effect', clinicalEffectAr: 'تقليل تأثير مضاد التخثر', management: 'Use MVI without vitamin K for warfarin patients; monitor INR', managementAr: 'استخدم حقن الفيتامينات بدون فيتامين ك لمرضى الوارفارين؛ مراقبة INR' },
    ],
    contraindications: ['Hypervitaminosis A or D', 'Known allergy to any component'], contraindicationsAr: ['فرط فيتامين أ أو د', 'حساسية معروفة لأي مكون'],
    monitoringRequired: ['Vitamin levels (if prolonged TPN)', 'INR if on anticoagulants'], storageConditions: 'Refrigerate 2-8°C, protect from light; add to TPN immediately before infusion',
  },
  {
    id: 'FRM-0747', genericName: 'Sodium Chloride Additive (TPN)', genericNameAr: 'كلوريد الصوديوم المضاف (تغذية وريدية)',
    brandNames: ['NaCl Concentrate 23.4%', 'Sodium Chloride Additive'], sfda_registration: 'SFDA-TPN-0747', atcCode: 'B05XA03', atcCategory: 'Electrolyte Solutions',
    therapeuticClass: 'TPN - Sodium Additive', therapeuticClassAr: 'تغذية وريدية - مضاف صوديوم',
    formularyStatus: 'conditional', restrictionCriteria: 'TPN compounding use only; concentration adjusted by clinical nutrition team',
    restrictionCriteriaAr: 'للاستخدام في تركيب التغذية الوريدية فقط؛ التركيز يعدل بواسطة فريق التغذية السريرية',
    approverRole: 'clinical_nutrition', route: ['IV'], forms: [
      { form: 'Concentrate for Addition', strength: '23.4% (4 mEq/mL) 30 mL', unitPrice: 5.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Sodium Chloride 0.9%', 'Sodium Chloride 3%'],
    blackBoxWarning: 'Highly concentrated (23.4%). Must NEVER be given undiluted. For TPN pharmacy compounding only.',
    blackBoxWarningAr: 'مركز للغاية (23.4٪). يجب ألا يُعطى بدون تخفيف أبداً. لتركيب صيدلية التغذية الوريدية فقط.',
    interactions: [],
    contraindications: ['Direct IV injection', 'Hypernatremia'], contraindicationsAr: ['الحقن الوريدي المباشر', 'فرط صوديوم الدم'],
    monitoringRequired: ['Serum sodium', 'Fluid balance'], storageConditions: 'Room temperature',
  },
  {
    id: 'FRM-0748', genericName: 'Potassium Acetate Injection (TPN)', genericNameAr: 'حقن أسيتات البوتاسيوم (تغذية وريدية)',
    brandNames: ['Potassium Acetate Inj'], sfda_registration: 'SFDA-TPN-0748', atcCode: 'B05XA01', atcCategory: 'Electrolyte Solutions',
    therapeuticClass: 'TPN - Potassium Additive', therapeuticClassAr: 'تغذية وريدية - مضاف بوتاسيوم',
    formularyStatus: 'conditional', restrictionCriteria: 'TPN compounding use only; preferred over KCl for TPN to provide acetate buffer',
    restrictionCriteriaAr: 'للاستخدام في تركيب التغذية الوريدية فقط؛ يفضل على كلوريد البوتاسيوم للتغذية الوريدية لتوفير مخزون الأسيتات',
    approverRole: 'clinical_nutrition', route: ['IV'], forms: [
      { form: 'Concentrate for Addition', strength: '2 mEq/mL 20 mL', unitPrice: 7.50, inStock: true },
      { form: 'Concentrate for Addition', strength: '4 mEq/mL 50 mL', unitPrice: 14.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Potassium Chloride', 'Potassium Phosphate', 'Sodium Acetate'],
    interactions: [
      { interactsWith: 'ACE Inhibitors', severity: 'major', mechanism: 'Additive potassium retention', clinicalEffect: 'Hyperkalemia risk', clinicalEffectAr: 'خطر فرط بوتاسيوم الدم', management: 'Monitor serum potassium daily during TPN', managementAr: 'مراقبة بوتاسيوم الدم يومياً أثناء التغذية الوريدية' },
    ],
    contraindications: ['Hyperkalemia', 'Severe renal impairment without dialysis', 'Metabolic alkalosis'], contraindicationsAr: ['فرط بوتاسيوم الدم', 'قصور كلوي شديد بدون غسيل كلوي', 'قلاء استقلابي'],
    monitoringRequired: ['Serum potassium', 'ABG (acid-base status)', 'Renal function'], storageConditions: 'Room temperature',
  },
  {
    id: 'FRM-0749', genericName: 'Zinc Sulfate Injection (TPN)', genericNameAr: 'حقن كبريتات الزنك (تغذية وريدية)',
    brandNames: ['Zinc Sulfate Inj', 'Zinca'], sfda_registration: 'SFDA-TPN-0749', atcCode: 'A12CB01', atcCategory: 'Zinc Supplements',
    therapeuticClass: 'TPN - Zinc Supplement', therapeuticClassAr: 'تغذية وريدية - مكمل زنك',
    formularyStatus: 'conditional', restrictionCriteria: 'For TPN patients with zinc deficiency or high-output fistulas/ostomies',
    restrictionCriteriaAr: 'لمرضى التغذية الوريدية مع نقص الزنك أو الناسور/الفتحات ذات النتاج العالي',
    approverRole: 'clinical_nutrition', route: ['IV'], forms: [
      { form: 'Injection', strength: '1 mg/mL (as Zn) 10 mL', unitPrice: 12.00, inStock: true },
      { form: 'Injection', strength: '5 mg/mL (as Zn) 5 mL', unitPrice: 15.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Zinc Oxide', 'Trace Elements'],
    interactions: [],
    contraindications: ['Hyperzincemia'], contraindicationsAr: ['فرط زنك الدم'],
    monitoringRequired: ['Serum zinc', 'Serum copper (zinc can deplete copper with prolonged use)', 'Wound healing status'], storageConditions: 'Room temperature, protect from light',
  },

  // ═══════════════════════════════════════════════════════════════
  // 6. BLOOD PRODUCTS (FRM-0750 to FRM-0753)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'FRM-0750', genericName: 'Packed Red Blood Cells (PRBC)', genericNameAr: 'كريات دم حمراء مكدسة',
    brandNames: ['PRBC', 'Packed RBC', 'Red Cell Concentrate'], sfda_registration: 'SFDA-BP-0750', atcCode: 'B05AX01', atcCategory: 'Blood Products',
    therapeuticClass: 'Blood Product - Red Cells', therapeuticClassAr: 'منتج دم - كريات حمراء',
    formularyStatus: 'restricted', restrictionCriteria: 'Requires blood bank authorization; type and crossmatch mandatory; transfusion threshold Hb <7 g/dL (stable) or <8 g/dL (cardiac)',
    restrictionCriteriaAr: 'يتطلب تصريح بنك الدم؛ فحص التوافق إلزامي؛ عتبة نقل الدم هيموغلوبين أقل من 7 (مستقر) أو أقل من 8 (قلبي)',
    approverRole: 'blood_bank', route: ['IV'], forms: [
      { form: 'Blood Bag', strength: '~300 mL per unit', unitPrice: 280.00, inStock: true },
      { form: 'Blood Bag (Leukoreduced)', strength: '~300 mL per unit', unitPrice: 320.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Whole Blood', 'Platelet Concentrate'],
    blackBoxWarning: 'Fatal hemolytic transfusion reactions from ABO incompatibility. Two-person bedside verification of patient ID and blood product MANDATORY before transfusion.',
    blackBoxWarningAr: 'تفاعلات نقل انحلالية قاتلة من عدم توافق فصائل الدم. التحقق من هوية المريض ومنتج الدم بشخصين عند السرير إلزامي قبل النقل.',
    interactions: [
      { interactsWith: 'Ringer\'s Lactate', severity: 'major', mechanism: 'Calcium in LR can cause clotting of blood products in the line', clinicalEffect: 'Clot formation in IV tubing', clinicalEffectAr: 'تكون خثرة في أنبوب الوريد', management: 'Only use Normal Saline 0.9% with blood products; never LR', managementAr: 'استخدم المحلول الملحي 0.9٪ فقط مع منتجات الدم؛ لا تستخدم رينغر لاكتات أبداً' },
    ],
    contraindications: ['Patient refusal', 'Religious objection (Jehovah\'s Witness — respect autonomy)'], contraindicationsAr: ['رفض المريض', 'اعتراض ديني (احترام استقلالية المريض)'],
    monitoringRequired: ['Vital signs q15min × 4 then q1h', 'Signs of transfusion reaction', 'Pre/post Hb', 'Two-person ID verification', 'Complete within 4 hours'], storageConditions: 'Blood bank refrigerator 1-6°C; use within 30 min of removal; complete transfusion within 4 hours',
  },
  {
    id: 'FRM-0751', genericName: 'Fresh Frozen Plasma (FFP)', genericNameAr: 'بلازما طازجة مجمدة',
    brandNames: ['FFP', 'Fresh Frozen Plasma'], sfda_registration: 'SFDA-BP-0751', atcCode: 'B05AX01', atcCategory: 'Blood Products',
    therapeuticClass: 'Blood Product - Plasma', therapeuticClassAr: 'منتج دم - بلازما',
    formularyStatus: 'restricted', restrictionCriteria: 'Requires blood bank authorization; for active bleeding with coagulopathy, DIC, TTP, or massive transfusion protocol',
    restrictionCriteriaAr: 'يتطلب تصريح بنك الدم؛ للنزيف النشط مع اعتلال التخثر أو التخثر المنتشر أو فرفرية نقص الصفائح أو بروتوكول النقل الكتلي',
    approverRole: 'blood_bank', route: ['IV'], forms: [
      { form: 'Blood Bag (Frozen)', strength: '~200-250 mL per unit', unitPrice: 250.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Cryoprecipitate', 'Platelets'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'FFP contains clotting factors that reverse warfarin', clinicalEffect: 'Reversal of anticoagulation', clinicalEffectAr: 'عكس تأثير مضاد التخثر', management: 'Intended use for warfarin reversal in bleeding; monitor INR', managementAr: 'استخدام مقصود لعكس الوارفارين في النزيف؛ مراقبة INR' },
    ],
    contraindications: ['Volume expansion alone (use crystalloids)', 'IgA deficiency (risk of anaphylaxis)'], contraindicationsAr: ['توسيع الحجم فقط (استخدم المحاليل البلورية)', 'نقص IgA (خطر تأق)'],
    monitoringRequired: ['Vital signs during transfusion', 'PT/INR', 'Fibrinogen', 'Transfusion reaction signs'], storageConditions: 'Frozen at -18°C or colder; thaw at 30-37°C; use within 24 hours of thawing',
  },
  {
    id: 'FRM-0752', genericName: 'Platelet Concentrate', genericNameAr: 'مركز صفائح دموية',
    brandNames: ['Platelet Concentrate', 'Random Donor Platelets', 'Apheresis Platelets'], sfda_registration: 'SFDA-BP-0752', atcCode: 'B05AX02', atcCategory: 'Blood Products',
    therapeuticClass: 'Blood Product - Platelets', therapeuticClassAr: 'منتج دم - صفائح دموية',
    formularyStatus: 'restricted', restrictionCriteria: 'Requires blood bank and hematology authorization; threshold: <10,000 (prophylactic) or <50,000 (active bleeding/pre-procedure)',
    restrictionCriteriaAr: 'يتطلب تصريح بنك الدم وأمراض الدم؛ العتبة: أقل من 10,000 (وقائي) أو أقل من 50,000 (نزيف نشط/قبل إجراء)',
    approverRole: 'blood_bank', route: ['IV'], forms: [
      { form: 'Blood Bag (Random Donor)', strength: '~50 mL per unit (pool 4-6 units)', unitPrice: 180.00, inStock: true },
      { form: 'Blood Bag (Apheresis)', strength: '~200-300 mL (single donor)', unitPrice: 850.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Cryoprecipitate', 'FFP'],
    interactions: [
      { interactsWith: 'Heparin', severity: 'moderate', mechanism: 'Heparin-induced thrombocytopenia can worsen with platelet transfusion', clinicalEffect: 'Paradoxical thrombosis in HIT', clinicalEffectAr: 'تخثر متناقض في نقص الصفائح المحرض بالهيبارين', management: 'CONTRAINDICATED in confirmed HIT; stop heparin first', managementAr: 'ممنوع في نقص الصفائح المحرض بالهيبارين المؤكد؛ أوقف الهيبارين أولاً' },
    ],
    contraindications: ['TTP (thrombotic thrombocytopenic purpura)', 'HIT (heparin-induced thrombocytopenia)'], contraindicationsAr: ['فرفرية نقص الصفائح التخثرية', 'نقص الصفائح المحرض بالهيبارين'],
    monitoringRequired: ['Platelet count 1 hour and 24 hours post-transfusion', 'Vital signs', 'Signs of transfusion reaction', 'Bleeding assessment'], storageConditions: 'Room temperature 20-24°C with continuous agitation; use within 5 days of collection',
  },
  {
    id: 'FRM-0753', genericName: 'Cryoprecipitate', genericNameAr: 'راسب بارد (كرايو)',
    brandNames: ['Cryoprecipitate', 'Cryo'], sfda_registration: 'SFDA-BP-0753', atcCode: 'B05AX01', atcCategory: 'Blood Products',
    therapeuticClass: 'Blood Product - Cryoprecipitate', therapeuticClassAr: 'منتج دم - راسب بارد',
    formularyStatus: 'restricted', restrictionCriteria: 'Requires blood bank authorization; for fibrinogen <150 mg/dL with active bleeding, DIC, or massive transfusion',
    restrictionCriteriaAr: 'يتطلب تصريح بنك الدم؛ لفيبرينوجين أقل من 150 مع نزيف نشط أو تخثر منتشر أو نقل كتلي',
    approverRole: 'blood_bank', route: ['IV'], forms: [
      { form: 'Blood Bag (Frozen)', strength: '~15 mL per unit (pool 5-10 units)', unitPrice: 150.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['FFP', 'Platelet Concentrate'],
    interactions: [
      { interactsWith: 'Tranexamic Acid', severity: 'minor', mechanism: 'Synergistic hemostatic effect', clinicalEffect: 'Enhanced clot stability', clinicalEffectAr: 'تعزيز استقرار الخثرة', management: 'Commonly used together in massive hemorrhage; monitor for thrombosis', managementAr: 'يستخدمان معاً عادةً في النزيف الكتلي؛ مراقبة التخثر' },
    ],
    contraindications: ['No absolute contraindications in life-threatening bleeding'], contraindicationsAr: ['لا موانع مطلقة في النزيف المهدد للحياة'],
    monitoringRequired: ['Fibrinogen level post-transfusion', 'PT/aPTT', 'Vital signs', 'Transfusion reaction signs'], storageConditions: 'Frozen at -18°C or colder; thaw at 30-37°C; use within 6 hours of thawing; do not refreeze',
  },

  // ═══════════════════════════════════════════════════════════════
  // 7. VITAMINS INJECTABLE (FRM-0754 to FRM-0759)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'FRM-0754', genericName: 'Thiamine (Vitamin B1) Injection', genericNameAr: 'حقن ثيامين (فيتامين ب1)',
    brandNames: ['Thiamine HCl Inj', 'Vitamin B1 Inj'], sfda_registration: 'SFDA-VIT-0754', atcCode: 'A11DA01', atcCategory: 'Vitamin B1',
    therapeuticClass: 'Vitamin B1 - Injectable', therapeuticClassAr: 'فيتامين ب1 - حقن',
    formularyStatus: 'formulary', route: ['IV', 'IM'], forms: [
      { form: 'Injection', strength: '100 mg/mL 2 mL', unitPrice: 6.00, inStock: true },
      { form: 'Injection', strength: '200 mg/2 mL', unitPrice: 8.50, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Pyridoxine (B6)', 'Cyanocobalamin (B12)'],
    interactions: [],
    contraindications: ['Known thiamine hypersensitivity'], contraindicationsAr: ['فرط حساسية معروف للثيامين'],
    monitoringRequired: ['Neurological status (Wernicke encephalopathy)', 'Anaphylaxis risk with IV (have epinephrine ready)'], storageConditions: 'Room temperature, protect from light',
  },
  {
    id: 'FRM-0755', genericName: 'Pyridoxine (Vitamin B6) Injection', genericNameAr: 'حقن بيريدوكسين (فيتامين ب6)',
    brandNames: ['Pyridoxine HCl Inj', 'Vitamin B6 Inj'], sfda_registration: 'SFDA-VIT-0755', atcCode: 'A11HA02', atcCategory: 'Vitamin B6',
    therapeuticClass: 'Vitamin B6 - Injectable', therapeuticClassAr: 'فيتامين ب6 - حقن',
    formularyStatus: 'formulary', route: ['IV', 'IM'], forms: [
      { form: 'Injection', strength: '100 mg/mL 1 mL', unitPrice: 5.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Thiamine (B1)', 'Cyanocobalamin (B12)'],
    interactions: [
      { interactsWith: 'Levodopa', severity: 'major', mechanism: 'Pyridoxine increases peripheral decarboxylation of levodopa', clinicalEffect: 'Reduced levodopa efficacy (without carbidopa)', clinicalEffectAr: 'تقليل فعالية ليفودوبا (بدون كاربيدوبا)', management: 'Not significant with carbidopa/levodopa combination; avoid with levodopa alone', managementAr: 'غير مهم مع توليفة كاربيدوبا/ليفودوبا؛ تجنب مع ليفودوبا وحده' },
      { interactsWith: 'Phenobarbital', severity: 'moderate', mechanism: 'Pyridoxine may increase phenobarbital metabolism', clinicalEffect: 'Reduced phenobarbital levels', clinicalEffectAr: 'انخفاض مستويات الفينوباربيتال', management: 'Monitor phenobarbital levels', managementAr: 'مراقبة مستويات الفينوباربيتال' },
    ],
    contraindications: ['Known pyridoxine hypersensitivity'], contraindicationsAr: ['فرط حساسية معروف للبيريدوكسين'],
    monitoringRequired: ['INH toxicity signs (main indication)', 'Neurological status'], storageConditions: 'Room temperature, protect from light',
  },
  {
    id: 'FRM-0756', genericName: 'Cyanocobalamin (Vitamin B12) Injection', genericNameAr: 'حقن سيانوكوبالامين (فيتامين ب12)',
    brandNames: ['Vitamin B12 Inj', 'Cyanocobalamin Inj', 'Nascobal'], sfda_registration: 'SFDA-VIT-0756', atcCode: 'B03BA01', atcCategory: 'Vitamin B12',
    therapeuticClass: 'Vitamin B12 - Injectable', therapeuticClassAr: 'فيتامين ب12 - حقن',
    formularyStatus: 'formulary', route: ['IM', 'SC'], forms: [
      { form: 'Injection', strength: '1000 mcg/mL 1 mL', unitPrice: 4.50, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Hydroxocobalamin', 'Thiamine (B1)'],
    interactions: [
      { interactsWith: 'Colchicine', severity: 'moderate', mechanism: 'Colchicine reduces B12 absorption from GI tract', clinicalEffect: 'B12 deficiency with chronic colchicine use', clinicalEffectAr: 'نقص ب12 مع الاستخدام المزمن للكولشيسين', management: 'Monitor B12 levels; parenteral route bypasses absorption issue', managementAr: 'مراقبة مستويات ب12؛ الطريق بالحقن يتجاوز مشكلة الامتصاص' },
    ],
    contraindications: ['Cobalt hypersensitivity', 'Leber\'s hereditary optic neuropathy'], contraindicationsAr: ['فرط حساسية الكوبالت', 'اعتلال العصب البصري الوراثي لليبر'],
    monitoringRequired: ['Serum B12 level', 'CBC and reticulocyte count', 'Serum potassium (hypokalemia in initial treatment)'], storageConditions: 'Room temperature, protect from light',
  },
  {
    id: 'FRM-0757', genericName: 'Ascorbic Acid (Vitamin C) Injection', genericNameAr: 'حقن حمض الأسكوربيك (فيتامين ج)',
    brandNames: ['Vitamin C Inj', 'Ascorbic Acid Inj', 'Cenolate'], sfda_registration: 'SFDA-VIT-0757', atcCode: 'A11GA01', atcCategory: 'Ascorbic Acid (Vitamin C)',
    therapeuticClass: 'Vitamin C - Injectable', therapeuticClassAr: 'فيتامين ج - حقن',
    formularyStatus: 'formulary', route: ['IV', 'IM'], forms: [
      { form: 'Injection', strength: '500 mg/5 mL', unitPrice: 5.50, inStock: true },
      { form: 'Injection', strength: '1000 mg/10 mL', unitPrice: 8.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ascorbic Acid oral'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'High-dose vitamin C may reduce warfarin effect', clinicalEffect: 'Decreased INR', clinicalEffectAr: 'انخفاض INR', management: 'Monitor INR; usually significant only at doses >1g/day', managementAr: 'مراقبة INR؛ عادةً مهم فقط بجرعات أكثر من 1 غ/يوم' },
    ],
    contraindications: ['G6PD deficiency (high doses)', 'Oxalate nephropathy risk', 'Hemochromatosis'], contraindicationsAr: ['نقص G6PD (جرعات عالية)', 'خطر اعتلال الكلية بالأوكسالات', 'داء ترسب الأصبغة الدموية'],
    monitoringRequired: ['Renal function (oxalate stones)', 'Blood glucose (may interfere with glucometer readings)'], storageConditions: 'Room temperature, protect from light; use immediately after opening',
  },
  {
    id: 'FRM-0758', genericName: 'Phytomenadione (Vitamin K1) Injection', genericNameAr: 'حقن فيتوميناديون (فيتامين ك1)',
    brandNames: ['Konakion', 'Phytonadione Inj', 'Vitamin K1 Inj'], sfda_registration: 'SFDA-VIT-0758', atcCode: 'B02BA01', atcCategory: 'Vitamin K',
    therapeuticClass: 'Vitamin K1 - Injectable', therapeuticClassAr: 'فيتامين ك1 - حقن',
    formularyStatus: 'formulary', route: ['IV', 'IM', 'SC', 'oral'], forms: [
      { form: 'Injection (Mixed Micelle)', strength: '10 mg/mL 1 mL', unitPrice: 12.00, inStock: true },
      { form: 'Injection (Neonatal)', strength: '2 mg/0.2 mL', unitPrice: 8.00, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: false, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Vitamin K3 (menadione)', 'Vitamin D'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Vitamin K directly antagonizes warfarin mechanism of action', clinicalEffect: 'Complete reversal of anticoagulation', clinicalEffectAr: 'عكس كامل لتأثير مضاد التخثر', management: 'Use only for significant bleeding or supratherapeutic INR; dose-dependent reversal', managementAr: 'استخدم فقط للنزيف المهم أو INR فوق العلاجي؛ العكس يعتمد على الجرعة' },
    ],
    contraindications: ['Known phytomenadione hypersensitivity'], contraindicationsAr: ['فرط حساسية معروف للفيتوميناديون'],
    monitoringRequired: ['INR/PT', 'Signs of anaphylaxis with IV route', 'Bleeding status'], storageConditions: 'Room temperature, protect from light',
  },
  {
    id: 'FRM-0759', genericName: 'Ergocalciferol (Vitamin D2) Injection', genericNameAr: 'حقن إرغوكالسيفيرول (فيتامين د2)',
    brandNames: ['Vitamin D2 Inj', 'Ergocalciferol Inj'], sfda_registration: 'SFDA-VIT-0759', atcCode: 'A11CC01', atcCategory: 'Vitamin D and Analogues',
    therapeuticClass: 'Vitamin D2 - Injectable', therapeuticClassAr: 'فيتامين د2 - حقن',
    formularyStatus: 'formulary', route: ['IM'], forms: [
      { form: 'Injection', strength: '300,000 IU/mL 1 mL', unitPrice: 15.00, inStock: true },
      { form: 'Injection', strength: '600,000 IU/mL 1 mL', unitPrice: 22.00, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Cholecalciferol (D3)', 'Calcitriol'],
    interactions: [
      { interactsWith: 'Thiazide Diuretics', severity: 'moderate', mechanism: 'Thiazides reduce calcium excretion; vitamin D increases calcium absorption', clinicalEffect: 'Hypercalcemia', clinicalEffectAr: 'فرط كالسيوم الدم', management: 'Monitor serum calcium; adjust vitamin D dose', managementAr: 'مراقبة كالسيوم الدم؛ تعديل جرعة فيتامين د' },
      { interactsWith: 'Digoxin', severity: 'moderate', mechanism: 'Vitamin D-induced hypercalcemia potentiates digoxin toxicity', clinicalEffect: 'Cardiac arrhythmias from digoxin toxicity', clinicalEffectAr: 'اضطراب نظم القلب من سمية الديجوكسين', management: 'Monitor calcium and digoxin levels closely', managementAr: 'مراقبة مستويات الكالسيوم والديجوكسين عن كثب' },
    ],
    contraindications: ['Hypercalcemia', 'Hypervitaminosis D', 'Malabsorption syndrome (may need calcitriol instead)'], contraindicationsAr: ['فرط كالسيوم الدم', 'فرط فيتامين د', 'متلازمة سوء الامتصاص (قد يحتاج كالسيتريول بدلاً)'],
    monitoringRequired: ['25-OH Vitamin D level', 'Serum calcium', 'Serum phosphate', 'Renal function', 'PTH levels'], storageConditions: 'Room temperature, protect from light',
  },
];
