/**
 * Saudi MOH Drug Formulary — Drug Data Part 2
 * Diabetes, Pain, GI, Respiratory, Psychiatric, and Others
 */

import type { FormularyDrug } from './formularyTypes';

let _idCounter = 27; // continue from Part 1
function nextId(): string {
  _idCounter += 1;
  return `FRM-${String(_idCounter).padStart(4, '0')}`;
}

// ─── DIABETES (8) ─────────────────────────────────────────────────────────────

const DIABETES: FormularyDrug[] = [
  {
    id: nextId(), genericName: 'Metformin', genericNameAr: 'ميتفورمين',
    brandNames: ['Glucophage', 'Diaformin'], sfda_registration: 'SFDA-2024-MET-028',
    atcCode: 'A10BA02', atcCategory: 'A10 - Drugs used in diabetes',
    therapeuticClass: 'Diabetes', therapeuticClassAr: 'أدوية السكري',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '500mg', unitPrice: 0.3, inStock: true },
      { form: 'tablet', strength: '850mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '1000mg', unitPrice: 0.6, inStock: true },
    ],
    maxDailyDose: 2550, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Metformin/Metronidazole'],
    interactions: [
      { interactsWith: 'IV Contrast Dye', severity: 'major', mechanism: 'Lactic acidosis risk with renal impairment',
        clinicalEffect: 'Potentially fatal lactic acidosis', clinicalEffectAr: 'حماض لبني قد يكون قاتلاً',
        management: 'Hold metformin 48h before and after contrast; check renal function', managementAr: 'إيقاف الميتفورمين 48 ساعة قبل وبعد المادة الظليلة' },
    ],
    contraindications: ['eGFR <30 mL/min', 'Metabolic acidosis', 'Severe hepatic impairment'],
    contraindicationsAr: ['معدل الترشيح الكبيبي أقل من 30', 'الحماض الاستقلابي', 'قصور كبدي شديد'],
    monitoringRequired: ['Renal function', 'Vitamin B12 levels annually', 'HbA1c', 'Lactic acidosis symptoms'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Glimepiride', genericNameAr: 'غليميبيريد',
    brandNames: ['Amaryl'], sfda_registration: 'SFDA-2024-GLI-029',
    atcCode: 'A10BB12', atcCategory: 'A10 - Drugs used in diabetes',
    therapeuticClass: 'Diabetes', therapeuticClassAr: 'أدوية السكري',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '1mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '2mg', unitPrice: 0.8, inStock: true },
      { form: 'tablet', strength: '4mg', unitPrice: 1.2, inStock: true },
    ],
    maxDailyDose: 8, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Glimepiride/Glipizide'],
    interactions: [
      { interactsWith: 'Fluconazole', severity: 'major', mechanism: 'CYP2C9 inhibition',
        clinicalEffect: 'Severe hypoglycemia', clinicalEffectAr: 'انخفاض شديد في سكر الدم',
        management: 'Reduce glimepiride dose; monitor glucose closely', managementAr: 'تقليل الجرعة؛ مراقبة السكر بدقة' },
    ],
    contraindications: ['Type 1 diabetes', 'DKA', 'Severe renal/hepatic impairment'],
    contraindicationsAr: ['سكري النوع الأول', 'الحماض الكيتوني', 'قصور كلوي/كبدي شديد'],
    monitoringRequired: ['Blood glucose', 'HbA1c', 'Signs of hypoglycemia'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: nextId(), genericName: 'Insulin Aspart', genericNameAr: 'إنسولين أسبارت',
    brandNames: ['NovoRapid', 'Fiasp'], sfda_registration: 'SFDA-2024-INS-030',
    atcCode: 'A10AB05', atcCategory: 'A10 - Drugs used in diabetes',
    therapeuticClass: 'Diabetes', therapeuticClassAr: 'أدوية السكري',
    formularyStatus: 'formulary', route: ['sc', 'iv'],
    forms: [
      { form: 'injection', strength: '100 IU/ml (FlexPen)', unitPrice: 45.0, inStock: true },
      { form: 'injection', strength: '100 IU/ml (vial)', unitPrice: 35.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Insulin Aspart/Insulin Glargine', 'NovoRapid/NovoMix'],
    interactions: [],
    contraindications: ['Hypoglycemia'],
    contraindicationsAr: ['انخفاض سكر الدم'],
    monitoringRequired: ['Blood glucose frequently', 'HbA1c', 'Potassium levels (IV use)', 'Injection site rotation'],
    storageConditions: 'Unopened: 2-8°C. In-use: below 30°C for up to 28 days.',
  },
  {
    id: nextId(), genericName: 'Insulin Glargine', genericNameAr: 'إنسولين غلارجين',
    brandNames: ['Lantus', 'Basaglar', 'Toujeo'], sfda_registration: 'SFDA-2024-INS-031',
    atcCode: 'A10AE04', atcCategory: 'A10 - Drugs used in diabetes',
    therapeuticClass: 'Diabetes', therapeuticClassAr: 'أدوية السكري',
    formularyStatus: 'formulary', route: ['sc'],
    forms: [
      { form: 'injection', strength: '100 IU/ml (SoloStar)', unitPrice: 55.0, inStock: true },
      { form: 'injection', strength: '300 IU/ml (Toujeo)', unitPrice: 75.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Insulin Glargine/Insulin Aspart', 'Lantus/Lente'],
    blackBoxWarning: 'Never administer IV. For SC injection only.',
    blackBoxWarningAr: 'لا يُعطى وريدياً أبداً. للحقن تحت الجلد فقط.',
    interactions: [],
    contraindications: ['Hypoglycemia', 'IV administration'],
    contraindicationsAr: ['انخفاض سكر الدم', 'الإعطاء الوريدي'],
    monitoringRequired: ['Fasting blood glucose', 'HbA1c', 'Injection site rotation'],
    storageConditions: 'Unopened: 2-8°C. In-use: below 30°C for up to 28 days.',
  },
  {
    id: nextId(), genericName: 'Sitagliptin', genericNameAr: 'سيتاغلبتين',
    brandNames: ['Januvia'], sfda_registration: 'SFDA-2024-SIT-032',
    atcCode: 'A10BH01', atcCategory: 'A10 - Drugs used in diabetes',
    therapeuticClass: 'Diabetes', therapeuticClassAr: 'أدوية السكري',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '25mg', unitPrice: 3.0, inStock: true },
      { form: 'tablet', strength: '50mg', unitPrice: 4.5, inStock: true },
      { form: 'tablet', strength: '100mg', unitPrice: 6.0, inStock: true },
    ],
    maxDailyDose: 100, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Sitagliptin/Saxagliptin', 'Januvia/Jantoven'],
    interactions: [],
    contraindications: ['Type 1 diabetes', 'DKA'],
    contraindicationsAr: ['سكري النوع الأول', 'الحماض الكيتوني'],
    monitoringRequired: ['HbA1c', 'Renal function', 'Signs of pancreatitis'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: nextId(), genericName: 'Empagliflozin', genericNameAr: 'إمباغليفلوزين',
    brandNames: ['Jardiance'], sfda_registration: 'SFDA-2024-EMP-033',
    atcCode: 'A10BK03', atcCategory: 'A10 - Drugs used in diabetes',
    therapeuticClass: 'Diabetes', therapeuticClassAr: 'أدوية السكري',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '10mg', unitPrice: 8.0, inStock: true },
      { form: 'tablet', strength: '25mg', unitPrice: 10.0, inStock: true },
    ],
    maxDailyDose: 25, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Empagliflozin/Dapagliflozin'],
    interactions: [
      { interactsWith: 'Furosemide', severity: 'moderate', mechanism: 'Additive diuretic effect',
        clinicalEffect: 'Dehydration and hypotension', clinicalEffectAr: 'جفاف وانخفاض ضغط',
        management: 'Monitor volume status and blood pressure', managementAr: 'مراقبة حالة السوائل وضغط الدم' },
    ],
    contraindications: ['eGFR <20 mL/min for glycemic control', 'Type 1 diabetes', 'DKA'],
    contraindicationsAr: ['معدل ترشيح أقل من 20 للسيطرة على السكر', 'سكري النوع الأول', 'الحماض الكيتوني'],
    monitoringRequired: ['Renal function', 'Blood glucose', 'Signs of DKA', 'Genital infections', 'Volume status'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Liraglutide', genericNameAr: 'ليراجلوتايد',
    brandNames: ['Victoza', 'Saxenda'], sfda_registration: 'SFDA-2024-LIR-034',
    atcCode: 'A10BJ02', atcCategory: 'A10 - Drugs used in diabetes',
    therapeuticClass: 'Diabetes', therapeuticClassAr: 'أدوية السكري',
    formularyStatus: 'conditional', route: ['sc'],
    restrictionCriteria: 'Endocrinologist initiation required. For T2DM with BMI >= 30 or cardiovascular disease.',
    restrictionCriteriaAr: 'يتطلب بدء من أخصائي الغدد. لمرضى السكري النوع 2 مع مؤشر كتلة >= 30 أو أمراض قلبية.',
    approverRole: 'endocrinologist',
    forms: [
      { form: 'injection', strength: '6mg/ml pen', unitPrice: 250.0, inStock: true },
    ],
    maxDailyDose: 1.8, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Liraglutide/Lixisenatide'],
    blackBoxWarning: 'Thyroid C-cell tumors in rodents. Contraindicated in MEN 2 or medullary thyroid carcinoma history.',
    blackBoxWarningAr: 'أورام خلايا C الدرقية في القوارض. ممنوع في متلازمة MEN 2 أو تاريخ سرطان درقي نخاعي.',
    interactions: [],
    contraindications: ['Personal/family history of medullary thyroid carcinoma', 'MEN 2 syndrome', 'Type 1 diabetes'],
    contraindicationsAr: ['تاريخ شخصي/عائلي لسرطان الغدة الدرقية النخاعي', 'متلازمة MEN 2', 'سكري النوع الأول'],
    monitoringRequired: ['Blood glucose', 'HbA1c', 'Signs of pancreatitis', 'Thyroid nodules', 'Heart rate'],
    storageConditions: 'Unopened: 2-8°C. In-use: below 30°C for 30 days.',
  },
  {
    id: nextId(), genericName: 'Pioglitazone', genericNameAr: 'بيوغليتازون',
    brandNames: ['Actos'], sfda_registration: 'SFDA-2024-PIO-035',
    atcCode: 'A10BG03', atcCategory: 'A10 - Drugs used in diabetes',
    therapeuticClass: 'Diabetes', therapeuticClassAr: 'أدوية السكري',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '15mg', unitPrice: 2.0, inStock: true },
      { form: 'tablet', strength: '30mg', unitPrice: 3.5, inStock: true },
      { form: 'tablet', strength: '45mg', unitPrice: 5.0, inStock: true },
    ],
    maxDailyDose: 45, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Pioglitazone/Rosiglitazone'],
    interactions: [],
    contraindications: ['NYHA Class III-IV heart failure', 'Active liver disease', 'Bladder cancer history'],
    contraindicationsAr: ['قصور قلب NYHA III-IV', 'مرض كبد نشط', 'تاريخ سرطان المثانة'],
    monitoringRequired: ['LFTs before and periodically', 'Weight/edema', 'HbA1c', 'Bone density in women'],
    storageConditions: 'Store below 25°C',
  },
];

// ─── PAIN / ANALGESICS (8) ────────────────────────────────────────────────────

const ANALGESICS: FormularyDrug[] = [
  {
    id: nextId(), genericName: 'Paracetamol', genericNameAr: 'باراسيتامول',
    brandNames: ['Panadol', 'Adol', 'Tylenol'], sfda_registration: 'SFDA-2024-PAR-036',
    atcCode: 'N02BE01', atcCategory: 'N02 - Analgesics',
    therapeuticClass: 'Analgesics', therapeuticClassAr: 'مسكنات الألم',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'rectal'],
    forms: [
      { form: 'tablet', strength: '500mg', unitPrice: 0.2, inStock: true },
      { form: 'tablet', strength: '1000mg', unitPrice: 0.3, inStock: true },
      { form: 'syrup', strength: '120mg/5ml', unitPrice: 5.0, inStock: true },
      { form: 'injection', strength: '1g/100ml', unitPrice: 10.0, inStock: true },
      { form: 'suppository', strength: '125mg', unitPrice: 1.0, inStock: true },
    ],
    maxDailyDose: 4000, maxDailyDoseUnit: 'mg (2000mg in hepatic impairment)',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Panadol/Panamax'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Increased INR with regular use >2g/day',
        clinicalEffect: 'Increased bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف',
        management: 'Limit to <2g/day; monitor INR', managementAr: 'الحد من أقل من 2غ/يوم؛ مراقبة INR' },
    ],
    contraindications: ['Severe hepatic impairment', 'Active liver disease'],
    contraindicationsAr: ['قصور كبدي شديد', 'مرض كبد نشط'],
    monitoringRequired: ['Hepatic function with prolonged use', 'Total daily dose from all sources'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Ibuprofen', genericNameAr: 'إيبوبروفين',
    brandNames: ['Brufen', 'Advil', 'Nurofen'], sfda_registration: 'SFDA-2024-IBU-037',
    atcCode: 'M01AE01', atcCategory: 'M01 - Anti-inflammatory products',
    therapeuticClass: 'Analgesics', therapeuticClassAr: 'مسكنات الألم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '200mg', unitPrice: 0.3, inStock: true },
      { form: 'tablet', strength: '400mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '600mg', unitPrice: 0.8, inStock: true },
      { form: 'suspension', strength: '100mg/5ml', unitPrice: 8.0, inStock: true },
    ],
    maxDailyDose: 2400, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ibuprofen/Indomethacin'],
    interactions: [
      { interactsWith: 'Aspirin', severity: 'moderate', mechanism: 'Competitive COX-1 binding',
        clinicalEffect: 'Reduced aspirin cardioprotection', clinicalEffectAr: 'تقليل الحماية القلبية للأسبرين',
        management: 'Take aspirin 30min before ibuprofen', managementAr: 'تناول الأسبرين 30 دقيقة قبل' },
      { interactsWith: 'Lisinopril', severity: 'moderate', mechanism: 'Reduced antihypertensive effect + renal risk',
        clinicalEffect: 'Decreased BP control; AKI risk', clinicalEffectAr: 'تقليل السيطرة على الضغط؛ خطر قصور كلوي',
        management: 'Monitor BP and renal function', managementAr: 'مراقبة الضغط ووظائف الكلى' },
    ],
    contraindications: ['Active GI bleeding', 'Severe renal impairment', 'Third trimester pregnancy', 'CABG surgery'],
    contraindicationsAr: ['نزيف هضمي نشط', 'قصور كلوي شديد', 'الثلث الأخير من الحمل', 'جراحة مجازة تاجية'],
    monitoringRequired: ['Renal function', 'GI symptoms', 'Blood pressure'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Diclofenac', genericNameAr: 'ديكلوفيناك',
    brandNames: ['Voltaren', 'Cataflam'], sfda_registration: 'SFDA-2024-DIC-038',
    atcCode: 'M01AB05', atcCategory: 'M01 - Anti-inflammatory products',
    therapeuticClass: 'Analgesics', therapeuticClassAr: 'مسكنات الألم',
    formularyStatus: 'formulary', route: ['oral', 'im', 'topical', 'rectal'],
    forms: [
      { form: 'tablet', strength: '25mg', unitPrice: 0.3, inStock: true },
      { form: 'tablet', strength: '50mg', unitPrice: 0.5, inStock: true },
      { form: 'injection', strength: '75mg/3ml', unitPrice: 3.0, inStock: true },
      { form: 'gel', strength: '1%', unitPrice: 10.0, inStock: true },
      { form: 'suppository', strength: '100mg', unitPrice: 2.0, inStock: true },
    ],
    maxDailyDose: 150, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Diclofenac/Diflunisal'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Antiplatelet + GI erosion',
        clinicalEffect: 'Increased GI bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف الهضمي',
        management: 'Avoid combination; use PPI if necessary', managementAr: 'تجنب الجمع؛ استخدام مثبط مضخة البروتون إذا لزم' },
    ],
    contraindications: ['Active GI bleeding', 'Severe heart failure', 'Severe renal/hepatic impairment'],
    contraindicationsAr: ['نزيف هضمي نشط', 'قصور قلب شديد', 'قصور كلوي/كبدي شديد'],
    monitoringRequired: ['Renal function', 'Blood pressure', 'GI symptoms', 'Hepatic function'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: nextId(), genericName: 'Tramadol', genericNameAr: 'ترامادول',
    brandNames: ['Tramal', 'Ultram'], sfda_registration: 'SFDA-2024-TRA-039',
    atcCode: 'N02AX02', atcCategory: 'N02 - Analgesics',
    therapeuticClass: 'Analgesics', therapeuticClassAr: 'مسكنات الألم',
    formularyStatus: 'restricted', route: ['oral', 'iv', 'im'],
    restrictionCriteria: 'Saudi MOH Schedule IV controlled substance. Requires narcotic prescription form.',
    restrictionCriteriaAr: 'مادة مراقبة جدول 4 حسب وزارة الصحة السعودية. يتطلب وصفة مخدرات.',
    approverRole: 'physician',
    forms: [
      { form: 'capsule', strength: '50mg', unitPrice: 1.0, inStock: true },
      { form: 'injection', strength: '100mg/2ml', unitPrice: 5.0, inStock: true },
    ],
    maxDailyDose: 400, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: true, controlSchedule: 'Saudi MOH Schedule IV',
    lookAlikeSoundAlike: ['Tramadol/Trazodone', 'Tramal/Trandate'],
    interactions: [
      { interactsWith: 'Sertraline', severity: 'major', mechanism: 'Serotonin syndrome risk',
        clinicalEffect: 'Serotonin syndrome', clinicalEffectAr: 'متلازمة السيروتونين',
        management: 'Use with extreme caution; monitor for symptoms', managementAr: 'استخدام بحذر شديد؛ مراقبة الأعراض' },
      { interactsWith: 'Carbamazepine', severity: 'major', mechanism: 'CYP3A4 induction reduces tramadol effect',
        clinicalEffect: 'Reduced analgesic effect + seizure risk', clinicalEffectAr: 'تقليل التأثير المسكن + خطر نوبات',
        management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['Epilepsy (uncontrolled)', 'Concurrent MAOIs', 'Acute intoxication', 'Severe respiratory depression'],
    contraindicationsAr: ['صرع غير مسيطر عليه', 'مثبطات MAO المتزامنة', 'تسمم حاد', 'تثبيط تنفسي شديد'],
    monitoringRequired: ['Pain scores', 'Respiratory rate', 'Signs of dependence', 'Seizure risk'],
    storageConditions: 'Store below 25°C. Controlled substance storage requirements.',
  },
  {
    id: nextId(), genericName: 'Morphine', genericNameAr: 'مورفين',
    brandNames: ['MS Contin', 'Oramorph'], sfda_registration: 'SFDA-2024-MOR-040',
    atcCode: 'N02AA01', atcCategory: 'N02 - Analgesics',
    therapeuticClass: 'Analgesics', therapeuticClassAr: 'مسكنات الألم',
    formularyStatus: 'restricted', route: ['oral', 'iv', 'im', 'sc'],
    restrictionCriteria: 'Saudi MOH Schedule I narcotic. Double-lock storage. Two-nurse verification for administration.',
    restrictionCriteriaAr: 'مخدر جدول 1 حسب وزارة الصحة السعودية. تخزين بقفل مزدوج. تحقق ممرضتين للإعطاء.',
    approverRole: 'physician',
    forms: [
      { form: 'tablet', strength: '10mg', unitPrice: 3.0, inStock: true },
      { form: 'tablet', strength: '30mg (SR)', unitPrice: 8.0, inStock: true },
      { form: 'injection', strength: '10mg/ml', unitPrice: 5.0, inStock: true },
      { form: 'syrup', strength: '10mg/5ml', unitPrice: 15.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: true, controlSchedule: 'Saudi MOH Schedule I',
    lookAlikeSoundAlike: ['Morphine/Hydromorphone', 'MS Contin/OxyContin'],
    blackBoxWarning: 'Risk of addiction, abuse, misuse; life-threatening respiratory depression; neonatal opioid withdrawal syndrome.',
    blackBoxWarningAr: 'خطر الإدمان وسوء الاستخدام؛ تثبيط تنفسي مهدد للحياة؛ متلازمة انسحاب أفيوني لحديثي الولادة.',
    interactions: [
      { interactsWith: 'Diazepam', severity: 'major', mechanism: 'Additive CNS and respiratory depression',
        clinicalEffect: 'Profound sedation and respiratory depression', clinicalEffectAr: 'تخدير عميق وتثبيط تنفسي',
        management: 'Avoid combination; if unavoidable use lowest doses', managementAr: 'تجنب الجمع؛ إذا لزم استخدام أقل الجرعات' },
    ],
    contraindications: ['Severe respiratory depression', 'Acute/severe bronchial asthma', 'GI obstruction', 'Concurrent MAOIs'],
    contraindicationsAr: ['تثبيط تنفسي شديد', 'ربو حاد/شديد', 'انسداد هضمي', 'مثبطات MAO المتزامنة'],
    monitoringRequired: ['Respiratory rate', 'Pain scores', 'Sedation level', 'Bowel function', 'Signs of dependence'],
    storageConditions: 'Controlled substance safe. Double-lock narcotic cabinet.',
  },
  {
    id: nextId(), genericName: 'Fentanyl', genericNameAr: 'فنتانيل',
    brandNames: ['Sublimaze', 'Durogesic'], sfda_registration: 'SFDA-2024-FEN-041',
    atcCode: 'N02AB03', atcCategory: 'N02 - Analgesics',
    therapeuticClass: 'Analgesics', therapeuticClassAr: 'مسكنات الألم',
    formularyStatus: 'restricted', route: ['iv', 'transdermal', 'sc'],
    restrictionCriteria: 'Saudi MOH Schedule I narcotic. ICU/OR/palliative care settings only.',
    restrictionCriteriaAr: 'مخدر جدول 1. فقط في العناية المركزة/غرفة العمليات/الرعاية التلطيفية.',
    approverRole: 'physician',
    forms: [
      { form: 'injection', strength: '50mcg/ml', unitPrice: 8.0, inStock: true },
      { form: 'patch', strength: '25mcg/h', unitPrice: 35.0, inStock: true },
      { form: 'patch', strength: '50mcg/h', unitPrice: 55.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: true, controlSchedule: 'Saudi MOH Schedule I',
    lookAlikeSoundAlike: ['Fentanyl/Sufentanil', 'Fentanyl/Alfentanil'],
    blackBoxWarning: 'Transdermal: opioid-naive patients must NOT use patches. Risk of fatal respiratory depression.',
    blackBoxWarningAr: 'اللاصقات: يجب ألا يستخدمها المرضى غير المعتادين على المواد الأفيونية. خطر تثبيط تنفسي قاتل.',
    interactions: [
      { interactsWith: 'Diazepam', severity: 'major', mechanism: 'Additive CNS depression',
        clinicalEffect: 'Profound sedation, respiratory arrest', clinicalEffectAr: 'تخدير عميق، توقف تنفسي',
        management: 'Reduce doses of both; monitor continuously', managementAr: 'تقليل جرعتي الدواءين؛ مراقبة مستمرة' },
    ],
    contraindications: ['Opioid-naive patients (patches)', 'Severe respiratory depression', 'Acute/severe asthma'],
    contraindicationsAr: ['مرضى غير معتادين على الأفيونات (اللاصقات)', 'تثبيط تنفسي شديد', 'ربو حاد/شديد'],
    monitoringRequired: ['Continuous SpO2 and RR', 'Sedation level', 'Pain scores', 'Patch integrity'],
    storageConditions: 'Controlled substance safe. 20-25°C.',
  },
  {
    id: nextId(), genericName: 'Ketorolac', genericNameAr: 'كيتورولاك',
    brandNames: ['Toradol'], sfda_registration: 'SFDA-2024-KET-042',
    atcCode: 'M01AB15', atcCategory: 'M01 - Anti-inflammatory products',
    therapeuticClass: 'Analgesics', therapeuticClassAr: 'مسكنات الألم',
    formularyStatus: 'formulary', route: ['iv', 'im', 'oral'],
    forms: [
      { form: 'injection', strength: '30mg/ml', unitPrice: 5.0, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 1.5, inStock: true },
    ],
    maxDailyDose: 120, maxDailyDoseUnit: 'mg (IV/IM day 1); 40mg oral; max 5 days',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ketorolac/Ketoprofen'],
    interactions: [
      { interactsWith: 'Enoxaparin', severity: 'major', mechanism: 'Additive bleeding risk',
        clinicalEffect: 'Increased hemorrhage risk', clinicalEffectAr: 'زيادة خطر النزيف',
        management: 'Avoid combination if possible', managementAr: 'تجنب الجمع إذا أمكن' },
    ],
    contraindications: ['Active GI bleeding', 'Renal impairment', 'Use >5 days', 'Perioperative CABG pain'],
    contraindicationsAr: ['نزيف هضمي نشط', 'قصور كلوي', 'استخدام أكثر من 5 أيام', 'ألم بعد مجازة تاجية'],
    monitoringRequired: ['Renal function', 'GI symptoms', 'Duration (max 5 days)'],
    storageConditions: 'Store below 30°C, protect from light',
  },
  {
    id: nextId(), genericName: 'Celecoxib', genericNameAr: 'سيليكوكسيب',
    brandNames: ['Celebrex'], sfda_registration: 'SFDA-2024-CEL-043',
    atcCode: 'M01AH01', atcCategory: 'M01 - Anti-inflammatory products',
    therapeuticClass: 'Analgesics', therapeuticClassAr: 'مسكنات الألم',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'capsule', strength: '100mg', unitPrice: 2.0, inStock: true },
      { form: 'capsule', strength: '200mg', unitPrice: 3.5, inStock: true },
    ],
    maxDailyDose: 400, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Celebrex/Celexa/Cerebyx'],
    blackBoxWarning: 'Increased risk of serious cardiovascular thrombotic events, MI, and stroke.',
    blackBoxWarningAr: 'زيادة خطر الأحداث الخثارية القلبية الوعائية الخطيرة واحتشاء عضلة القلب والسكتة.',
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'CYP2C9 inhibition',
        clinicalEffect: 'Increased INR', clinicalEffectAr: 'ارتفاع INR',
        management: 'Monitor INR closely', managementAr: 'مراقبة INR بدقة' },
    ],
    contraindications: ['Sulfonamide allergy', 'Active GI bleeding', 'Severe heart failure', 'CABG surgery'],
    contraindicationsAr: ['حساسية السلفوناميد', 'نزيف هضمي نشط', 'قصور قلب شديد', 'جراحة مجازة تاجية'],
    monitoringRequired: ['Renal function', 'Blood pressure', 'Cardiovascular risk assessment'],
    storageConditions: 'Store below 25°C',
  },
];

// ─── GI (6) ───────────────────────────────────────────────────────────────────

const GI: FormularyDrug[] = [
  {
    id: nextId(), genericName: 'Omeprazole', genericNameAr: 'أوميبرازول',
    brandNames: ['Losec', 'Prilosec'], sfda_registration: 'SFDA-2024-OME-044',
    atcCode: 'A02BC01', atcCategory: 'A02 - Drugs for acid related disorders',
    therapeuticClass: 'Gastrointestinal', therapeuticClassAr: 'أدوية الجهاز الهضمي',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [
      { form: 'capsule', strength: '20mg', unitPrice: 0.5, inStock: true },
      { form: 'capsule', strength: '40mg', unitPrice: 1.0, inStock: true },
      { form: 'injection', strength: '40mg', unitPrice: 12.0, inStock: true },
    ],
    maxDailyDose: 40, maxDailyDoseUnit: 'mg (80mg for Zollinger-Ellison)',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Omeprazole/Pantoprazole'],
    interactions: [
      { interactsWith: 'Clopidogrel', severity: 'major', mechanism: 'CYP2C19 inhibition blocks clopidogrel activation',
        clinicalEffect: 'Reduced antiplatelet effect', clinicalEffectAr: 'تقليل التأثير المضاد للصفيحات',
        management: 'Use pantoprazole instead', managementAr: 'استخدام بانتوبرازول بدلاً' },
    ],
    contraindications: ['PPI allergy'],
    contraindicationsAr: ['حساسية مثبطات مضخة البروتون'],
    monitoringRequired: ['Magnesium with long-term use', 'Vitamin B12 with long-term use', 'Bone density'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Pantoprazole', genericNameAr: 'بانتوبرازول',
    brandNames: ['Pantoloc', 'Protonix'], sfda_registration: 'SFDA-2024-PAN-045',
    atcCode: 'A02BC02', atcCategory: 'A02 - Drugs for acid related disorders',
    therapeuticClass: 'Gastrointestinal', therapeuticClassAr: 'أدوية الجهاز الهضمي',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [
      { form: 'tablet', strength: '20mg', unitPrice: 0.8, inStock: true },
      { form: 'tablet', strength: '40mg', unitPrice: 1.5, inStock: true },
      { form: 'injection', strength: '40mg', unitPrice: 15.0, inStock: true },
    ],
    maxDailyDose: 80, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Pantoprazole/Omeprazole'],
    interactions: [],
    contraindications: ['PPI allergy'],
    contraindicationsAr: ['حساسية مثبطات مضخة البروتون'],
    monitoringRequired: ['Magnesium with long-term use'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Ranitidine', genericNameAr: 'رانيتيدين',
    brandNames: ['Zantac'], sfda_registration: 'SFDA-2024-RAN-046',
    atcCode: 'A02BA02', atcCategory: 'A02 - Drugs for acid related disorders',
    therapeuticClass: 'Gastrointestinal', therapeuticClassAr: 'أدوية الجهاز الهضمي',
    formularyStatus: 'non_formulary', route: ['oral', 'iv'],
    forms: [
      { form: 'tablet', strength: '150mg', unitPrice: 0.5, inStock: false },
      { form: 'injection', strength: '50mg/2ml', unitPrice: 5.0, inStock: false },
    ],
    maxDailyDose: 300, maxDailyDoseUnit: 'mg',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ranitidine/Rimantadine'],
    interactions: [],
    contraindications: ['NDMA contamination concern — product recalled in many markets'],
    contraindicationsAr: ['مخاوف تلوث NDMA — المنتج مسحوب من أسواق عديدة'],
    monitoringRequired: ['Consider switching to alternative H2RA or PPI'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Ondansetron', genericNameAr: 'أوندانسيترون',
    brandNames: ['Zofran'], sfda_registration: 'SFDA-2024-OND-047',
    atcCode: 'A04AA01', atcCategory: 'A04 - Antiemetics',
    therapeuticClass: 'Gastrointestinal', therapeuticClassAr: 'أدوية الجهاز الهضمي',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'im'],
    forms: [
      { form: 'tablet', strength: '4mg', unitPrice: 2.0, inStock: true },
      { form: 'tablet', strength: '8mg', unitPrice: 3.5, inStock: true },
      { form: 'injection', strength: '4mg/2ml', unitPrice: 8.0, inStock: true },
    ],
    maxDailyDose: 16, maxDailyDoseUnit: 'mg (IV)',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ondansetron/Granisetron'],
    interactions: [],
    contraindications: ['Congenital long QT syndrome', 'Concurrent apomorphine'],
    contraindicationsAr: ['متلازمة QT الطويلة الخلقية', 'استخدام متزامن مع أبومورفين'],
    monitoringRequired: ['ECG in at-risk patients', 'QT interval'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: nextId(), genericName: 'Metoclopramide', genericNameAr: 'ميتوكلوبراميد',
    brandNames: ['Primperan', 'Reglan'], sfda_registration: 'SFDA-2024-MTC-048',
    atcCode: 'A03FA01', atcCategory: 'A03 - Drugs for functional GI disorders',
    therapeuticClass: 'Gastrointestinal', therapeuticClassAr: 'أدوية الجهاز الهضمي',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'im'],
    forms: [
      { form: 'tablet', strength: '10mg', unitPrice: 0.3, inStock: true },
      { form: 'injection', strength: '10mg/2ml', unitPrice: 2.0, inStock: true },
    ],
    maxDailyDose: 30, maxDailyDoseUnit: 'mg (max 5 days)',
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Metoclopramide/Metolazone'],
    blackBoxWarning: 'Risk of tardive dyskinesia with prolonged use. Do not use >12 weeks.',
    blackBoxWarningAr: 'خطر خلل الحركة المتأخر مع الاستخدام المطول. لا يستخدم أكثر من 12 أسبوعاً.',
    interactions: [],
    contraindications: ['GI obstruction', 'Pheochromocytoma', 'Epilepsy', 'Concurrent drugs causing EPS'],
    contraindicationsAr: ['انسداد هضمي', 'ورم القواتم', 'الصرع', 'أدوية تسبب أعراض خارج هرمية'],
    monitoringRequired: ['Extrapyramidal symptoms', 'Duration of use (max 5 days recommended)'],
    storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: nextId(), genericName: 'Lactulose', genericNameAr: 'لاكتولوز',
    brandNames: ['Duphalac'], sfda_registration: 'SFDA-2024-LAC-049',
    atcCode: 'A06AD11', atcCategory: 'A06 - Drugs for constipation',
    therapeuticClass: 'Gastrointestinal', therapeuticClassAr: 'أدوية الجهاز الهضمي',
    formularyStatus: 'formulary', route: ['oral', 'rectal'],
    forms: [
      { form: 'syrup', strength: '10g/15ml', unitPrice: 8.0, inStock: true },
    ],
    maxDailyDose: 60, maxDailyDoseUnit: 'ml (constipation); 200ml (hepatic encephalopathy)',
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Galactosemia', 'GI obstruction'],
    contraindicationsAr: ['الجالاكتوزيمية', 'انسداد هضمي'],
    monitoringRequired: ['Electrolytes with prolonged use', 'Bowel function'],
    storageConditions: 'Store below 25°C. Do not freeze.',
  },
];

// ─── RESPIRATORY (5) ──────────────────────────────────────────────────────────

const RESPIRATORY: FormularyDrug[] = [
  {
    id: nextId(), genericName: 'Salbutamol', genericNameAr: 'سالبوتامول',
    brandNames: ['Ventolin'], sfda_registration: 'SFDA-2024-SAL-050',
    atcCode: 'R03AC02', atcCategory: 'R03 - Drugs for obstructive airway diseases',
    therapeuticClass: 'Respiratory', therapeuticClassAr: 'أدوية الجهاز التنفسي',
    formularyStatus: 'formulary', route: ['inhaled', 'oral', 'iv'],
    forms: [
      { form: 'inhaler', strength: '100mcg/puff (MDI)', unitPrice: 12.0, inStock: true },
      { form: 'nebule', strength: '2.5mg/2.5ml', unitPrice: 1.5, inStock: true },
      { form: 'syrup', strength: '2mg/5ml', unitPrice: 5.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Salbutamol/Salmeterol'],
    interactions: [],
    contraindications: [],
    contraindicationsAr: [],
    monitoringRequired: ['Heart rate', 'Potassium with high doses', 'Frequency of use (rescue indicator)'],
    storageConditions: 'Store below 30°C. Protect inhaler from sunlight.',
  },
  {
    id: nextId(), genericName: 'Ipratropium', genericNameAr: 'إبراتروبيوم',
    brandNames: ['Atrovent'], sfda_registration: 'SFDA-2024-IPR-051',
    atcCode: 'R03BB01', atcCategory: 'R03 - Drugs for obstructive airway diseases',
    therapeuticClass: 'Respiratory', therapeuticClassAr: 'أدوية الجهاز التنفسي',
    formularyStatus: 'formulary', route: ['inhaled'],
    forms: [
      { form: 'nebule', strength: '500mcg/2ml', unitPrice: 2.0, inStock: true },
      { form: 'inhaler', strength: '20mcg/puff', unitPrice: 15.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Ipratropium/Tiotropium'],
    interactions: [],
    contraindications: ['Atropine allergy', 'Soy/peanut allergy (MDI formulation)'],
    contraindicationsAr: ['حساسية الأتروبين', 'حساسية الصويا/الفول السوداني (تركيبة MDI)'],
    monitoringRequired: ['Respiratory status', 'Urinary retention in elderly'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Budesonide', genericNameAr: 'بوديسونيد',
    brandNames: ['Pulmicort', 'Rhinocort'], sfda_registration: 'SFDA-2024-BUD-052',
    atcCode: 'R03BA02', atcCategory: 'R03 - Drugs for obstructive airway diseases',
    therapeuticClass: 'Respiratory', therapeuticClassAr: 'أدوية الجهاز التنفسي',
    formularyStatus: 'formulary', route: ['inhaled', 'nasal'],
    forms: [
      { form: 'nebule', strength: '0.5mg/2ml', unitPrice: 3.0, inStock: true },
      { form: 'nebule', strength: '1mg/2ml', unitPrice: 5.0, inStock: true },
      { form: 'nasal spray', strength: '64mcg/spray', unitPrice: 18.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Budesonide/Beclomethasone'],
    interactions: [],
    contraindications: ['Active pulmonary tuberculosis', 'Untreated fungal infections'],
    contraindicationsAr: ['سل رئوي نشط', 'عدوى فطرية غير معالجة'],
    monitoringRequired: ['Oral candidiasis (rinse mouth after use)', 'Growth in children', 'Adrenal function with high doses'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: nextId(), genericName: 'Montelukast', genericNameAr: 'مونتيلوكاست',
    brandNames: ['Singulair'], sfda_registration: 'SFDA-2024-MON-053',
    atcCode: 'R03DC03', atcCategory: 'R03 - Drugs for obstructive airway diseases',
    therapeuticClass: 'Respiratory', therapeuticClassAr: 'أدوية الجهاز التنفسي',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '4mg (chewable)', unitPrice: 3.0, inStock: true },
      { form: 'tablet', strength: '5mg (chewable)', unitPrice: 3.5, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 4.0, inStock: true },
    ],
    maxDailyDose: 10, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Montelukast/Monteleukast'],
    blackBoxWarning: 'Neuropsychiatric events including suicidal thoughts reported.',
    blackBoxWarningAr: 'تم الإبلاغ عن أحداث نفسية عصبية بما في ذلك أفكار انتحارية.',
    interactions: [],
    contraindications: ['Montelukast allergy'],
    contraindicationsAr: ['حساسية مونتيلوكاست'],
    monitoringRequired: ['Neuropsychiatric symptoms (mood changes, suicidality)', 'Asthma control'],
    storageConditions: 'Store below 30°C, protect from moisture and light',
  },
  {
    id: nextId(), genericName: 'Dexamethasone', genericNameAr: 'ديكساميثازون',
    brandNames: ['Decadron'], sfda_registration: 'SFDA-2024-DEX-054',
    atcCode: 'H02AB02', atcCategory: 'H02 - Corticosteroids for systemic use',
    therapeuticClass: 'Respiratory', therapeuticClassAr: 'أدوية الجهاز التنفسي',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'im'],
    forms: [
      { form: 'tablet', strength: '0.5mg', unitPrice: 0.3, inStock: true },
      { form: 'tablet', strength: '4mg', unitPrice: 1.0, inStock: true },
      { form: 'injection', strength: '4mg/ml', unitPrice: 3.0, inStock: true },
      { form: 'injection', strength: '8mg/2ml', unitPrice: 5.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Dexamethasone/Desoximetasone'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Variable effect on INR',
        clinicalEffect: 'Unpredictable INR changes', clinicalEffectAr: 'تغيرات غير متوقعة في INR',
        management: 'Monitor INR frequently when starting/stopping', managementAr: 'مراقبة INR بشكل متكرر عند البدء/الإيقاف' },
    ],
    contraindications: ['Systemic fungal infections (relative)', 'Live vaccines during high-dose therapy'],
    contraindicationsAr: ['عدوى فطرية جهازية (نسبي)', 'لقاحات حية أثناء الجرعات العالية'],
    monitoringRequired: ['Blood glucose', 'Blood pressure', 'Electrolytes', 'Signs of infection', 'Adrenal suppression'],
    storageConditions: 'Store below 25°C, protect from light',
  },
];

// ─── PSYCHIATRIC (6) ──────────────────────────────────────────────────────────

const PSYCHIATRIC: FormularyDrug[] = [
  {
    id: nextId(), genericName: 'Sertraline', genericNameAr: 'سيرترالين',
    brandNames: ['Zoloft', 'Lustral'], sfda_registration: 'SFDA-2024-SER-055',
    atcCode: 'N06AB06', atcCategory: 'N06 - Psychoanaleptics',
    therapeuticClass: 'Psychiatric', therapeuticClassAr: 'أدوية نفسية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '50mg', unitPrice: 1.5, inStock: true },
      { form: 'tablet', strength: '100mg', unitPrice: 2.5, inStock: true },
    ],
    maxDailyDose: 200, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Sertraline/Cetirizine'],
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults.',
    blackBoxWarningAr: 'خطر الميول الانتحارية عند الأطفال والمراهقين والشباب.',
    interactions: [
      { interactsWith: 'Tramadol', severity: 'major', mechanism: 'Serotonin syndrome risk',
        clinicalEffect: 'Serotonin syndrome', clinicalEffectAr: 'متلازمة السيروتونين',
        management: 'Use with caution; monitor closely', managementAr: 'استخدام بحذر؛ مراقبة دقيقة' },
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Antiplatelet effect of SSRIs',
        clinicalEffect: 'Increased bleeding risk', clinicalEffectAr: 'زيادة خطر النزيف',
        management: 'Monitor INR and signs of bleeding', managementAr: 'مراقبة INR وعلامات النزيف' },
    ],
    contraindications: ['Concurrent MAOIs (allow 14-day washout)', 'Concurrent pimozide'],
    contraindicationsAr: ['مثبطات MAO المتزامنة (فترة غسل 14 يوم)', 'بيموزيد متزامن'],
    monitoringRequired: ['Suicidal ideation (first 4-8 weeks)', 'Serotonin syndrome symptoms', 'Sodium levels'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Escitalopram', genericNameAr: 'إسيتالوبرام',
    brandNames: ['Lexapro', 'Cipralex'], sfda_registration: 'SFDA-2024-ESC-056',
    atcCode: 'N06AB10', atcCategory: 'N06 - Psychoanaleptics',
    therapeuticClass: 'Psychiatric', therapeuticClassAr: 'أدوية نفسية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '5mg', unitPrice: 2.0, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 3.0, inStock: true },
      { form: 'tablet', strength: '20mg', unitPrice: 5.0, inStock: true },
    ],
    maxDailyDose: 20, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Escitalopram/Citalopram'],
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults.',
    blackBoxWarningAr: 'خطر الميول الانتحارية عند الأطفال والمراهقين والشباب.',
    interactions: [],
    contraindications: ['Concurrent MAOIs', 'QT prolongation'],
    contraindicationsAr: ['مثبطات MAO المتزامنة', 'إطالة QT'],
    monitoringRequired: ['Suicidal ideation', 'QT interval', 'Sodium levels'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Quetiapine', genericNameAr: 'كويتيابين',
    brandNames: ['Seroquel'], sfda_registration: 'SFDA-2024-QUE-057',
    atcCode: 'N05AH04', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Psychiatric', therapeuticClassAr: 'أدوية نفسية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [
      { form: 'tablet', strength: '25mg', unitPrice: 1.0, inStock: true },
      { form: 'tablet', strength: '100mg', unitPrice: 2.5, inStock: true },
      { form: 'tablet', strength: '200mg', unitPrice: 4.0, inStock: true },
      { form: 'tablet', strength: '300mg (XR)', unitPrice: 8.0, inStock: true },
    ],
    maxDailyDose: 800, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Quetiapine/Olanzapine', 'Seroquel/Serzone'],
    blackBoxWarning: 'Increased mortality in elderly patients with dementia-related psychosis.',
    blackBoxWarningAr: 'زيادة الوفيات عند كبار السن المصابين بذهان مرتبط بالخرف.',
    interactions: [],
    contraindications: ['Concurrent strong CYP3A4 inhibitors at high quetiapine doses'],
    contraindicationsAr: ['مثبطات CYP3A4 القوية المتزامنة بجرعات كويتيابين عالية'],
    monitoringRequired: ['Metabolic parameters (glucose, lipids, weight)', 'Blood pressure', 'EPS', 'Prolactin'],
    storageConditions: 'Store below 30°C',
  },
  {
    id: nextId(), genericName: 'Olanzapine', genericNameAr: 'أولانزابين',
    brandNames: ['Zyprexa'], sfda_registration: 'SFDA-2024-OLA-058',
    atcCode: 'N05AH03', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Psychiatric', therapeuticClassAr: 'أدوية نفسية',
    formularyStatus: 'formulary', route: ['oral', 'im'],
    forms: [
      { form: 'tablet', strength: '5mg', unitPrice: 2.0, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 3.5, inStock: true },
      { form: 'injection', strength: '10mg', unitPrice: 25.0, inStock: true },
    ],
    maxDailyDose: 20, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Olanzapine/Quetiapine', 'Zyprexa/Zyrtec'],
    blackBoxWarning: 'Increased mortality in elderly patients with dementia-related psychosis.',
    blackBoxWarningAr: 'زيادة الوفيات عند كبار السن المصابين بذهان مرتبط بالخرف.',
    interactions: [],
    contraindications: ['IM olanzapine + IM benzodiazepines (cardiac/respiratory depression)'],
    contraindicationsAr: ['أولانزابين عضلي + بنزوديازيبينات عضلية (تثبيط قلبي/تنفسي)'],
    monitoringRequired: ['Weight/BMI', 'Fasting glucose', 'Lipid panel', 'Blood pressure'],
    storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Haloperidol', genericNameAr: 'هالوبيريدول',
    brandNames: ['Haldol'], sfda_registration: 'SFDA-2024-HAL-059',
    atcCode: 'N05AD01', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Psychiatric', therapeuticClassAr: 'أدوية نفسية',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'im'],
    forms: [
      { form: 'tablet', strength: '0.5mg', unitPrice: 0.3, inStock: true },
      { form: 'tablet', strength: '5mg', unitPrice: 0.8, inStock: true },
      { form: 'injection', strength: '5mg/ml', unitPrice: 3.0, inStock: true },
    ],
    maxDailyDose: 20, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Haloperidol/Haldol'],
    blackBoxWarning: 'Increased mortality in elderly patients with dementia-related psychosis.',
    blackBoxWarningAr: 'زيادة الوفيات عند كبار السن المصابين بذهان مرتبط بالخرف.',
    interactions: [
      { interactsWith: 'QT-prolonging drugs', severity: 'major', mechanism: 'Additive QT prolongation',
        clinicalEffect: 'Torsades de pointes', clinicalEffectAr: 'تورساد دي بوانت',
        management: 'Monitor ECG; avoid with other QT-prolonging agents', managementAr: 'مراقبة ECG؛ تجنب مع أدوية أخرى تطيل QT' },
    ],
    contraindications: ['QT prolongation', 'Parkinson disease', 'CNS depression', 'Coma'],
    contraindicationsAr: ['إطالة QT', 'مرض باركنسون', 'تثبيط الجهاز العصبي المركزي', 'غيبوبة'],
    monitoringRequired: ['ECG (QTc)', 'EPS/akathisia', 'NMS symptoms', 'Blood pressure'],
    storageConditions: 'Store below 30°C, protect from light',
  },
  {
    id: nextId(), genericName: 'Diazepam', genericNameAr: 'ديازيبام',
    brandNames: ['Valium'], sfda_registration: 'SFDA-2024-DIA-060',
    atcCode: 'N05BA01', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Psychiatric', therapeuticClassAr: 'أدوية نفسية',
    formularyStatus: 'restricted', route: ['oral', 'iv', 'im', 'rectal'],
    restrictionCriteria: 'Saudi MOH Schedule IV. Max 2-week supply. Benzodiazepine prescribing restrictions apply.',
    restrictionCriteriaAr: 'جدول 4 وزارة الصحة السعودية. إمداد أقصى أسبوعين. تطبق قيود وصف البنزوديازيبينات.',
    approverRole: 'physician',
    forms: [
      { form: 'tablet', strength: '2mg', unitPrice: 0.5, inStock: true },
      { form: 'tablet', strength: '5mg', unitPrice: 0.8, inStock: true },
      { form: 'tablet', strength: '10mg', unitPrice: 1.0, inStock: true },
      { form: 'injection', strength: '10mg/2ml', unitPrice: 3.0, inStock: true },
    ],
    maxDailyDose: 40, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: true, controlSchedule: 'Saudi MOH Schedule IV',
    lookAlikeSoundAlike: ['Diazepam/Ditropan', 'Valium/Valsartan'],
    interactions: [
      { interactsWith: 'Morphine', severity: 'major', mechanism: 'Additive CNS depression',
        clinicalEffect: 'Profound sedation and respiratory depression', clinicalEffectAr: 'تخدير عميق وتثبيط تنفسي',
        management: 'Avoid combination; if unavoidable, use lowest doses', managementAr: 'تجنب الجمع؛ إذا لزم استخدام أقل الجرعات' },
      { interactsWith: 'Fentanyl', severity: 'major', mechanism: 'Additive CNS depression',
        clinicalEffect: 'Respiratory arrest', clinicalEffectAr: 'توقف تنفسي',
        management: 'Reduce doses significantly; continuous monitoring', managementAr: 'تقليل الجرعات بشكل كبير؛ مراقبة مستمرة' },
    ],
    contraindications: ['Acute narrow-angle glaucoma', 'Severe respiratory insufficiency', 'Sleep apnea', 'Myasthenia gravis'],
    contraindicationsAr: ['زرق ضيق الزاوية الحاد', 'قصور تنفسي شديد', 'انقطاع التنفس أثناء النوم', 'الوهن العضلي الوبيل'],
    monitoringRequired: ['Respiratory rate', 'Sedation level', 'Duration of use', 'Signs of dependence'],
    storageConditions: 'Controlled substance storage. Store below 25°C.',
  },
];

// ─── OTHERS (20) ──────────────────────────────────────────────────────────────

const OTHERS: FormularyDrug[] = [
  {
    id: nextId(), genericName: 'Furosemide', genericNameAr: 'فوروسيميد',
    brandNames: ['Lasix'], sfda_registration: 'SFDA-2024-FUR-061',
    atcCode: 'C03CA01', atcCategory: 'C03 - Diuretics',
    therapeuticClass: 'Diuretics', therapeuticClassAr: 'مدرات البول',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'im'],
    forms: [
      { form: 'tablet', strength: '40mg', unitPrice: 0.3, inStock: true },
      { form: 'injection', strength: '20mg/2ml', unitPrice: 2.0, inStock: true },
    ],
    maxDailyDose: 600, maxDailyDoseUnit: 'mg',
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Furosemide/Flurosemide (spelling)', 'Lasix/Losec'],
    interactions: [
      { interactsWith: 'Gentamicin', severity: 'major', mechanism: 'Additive ototoxicity',
        clinicalEffect: 'Increased hearing loss risk', clinicalEffectAr: 'زيادة خطر فقدان السمع',
        management: 'Avoid combination if possible', managementAr: 'تجنب الجمع إذا أمكن' },
      { interactsWith: 'Digoxin', severity: 'major', mechanism: 'Hypokalemia increases digoxin sensitivity',
        clinicalEffect: 'Digoxin toxicity risk', clinicalEffectAr: 'خطر سمية الديجوكسين',
        management: 'Monitor potassium closely; supplement if needed', managementAr: 'مراقبة البوتاسيوم؛ تعويض إذا لزم' },
    ],
    contraindications: ['Anuria', 'Severe hypokalemia/hyponatremia', 'Hepatic coma'],
    contraindicationsAr: ['انقطاع البول', 'نقص شديد في البوتاسيوم/الصوديوم', 'غيبوبة كبدية'],
    monitoringRequired: ['Electrolytes (K+, Na+, Mg2+)', 'Renal function', 'Blood pressure', 'Volume status'],
    storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: nextId(), genericName: 'Spironolactone', genericNameAr: 'سبيرونولاكتون',
    brandNames: ['Aldactone'], sfda_registration: 'SFDA-2024-SPI-062',
    atcCode: 'C03DA01', atcCategory: 'C03 - Diuretics',
    therapeuticClass: 'Diuretics', therapeuticClassAr: 'مدرات البول',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '25mg', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '100mg', unitPrice: 1.5, inStock: true }],
    maxDailyDose: 400, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Spironolactone/Spirapril'],
    interactions: [{ interactsWith: 'Lisinopril', severity: 'major', mechanism: 'Dual RAAS blockade', clinicalEffect: 'Severe hyperkalemia', clinicalEffectAr: 'فرط بوتاسيوم شديد', management: 'Monitor K+ frequently', managementAr: 'مراقبة البوتاسيوم بشكل متكرر' }],
    contraindications: ['Hyperkalemia', 'Addison disease', 'Anuria'], contraindicationsAr: ['فرط البوتاسيوم', 'مرض أديسون', 'انقطاع البول'],
    monitoringRequired: ['Potassium', 'Renal function', 'Blood pressure'], storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Potassium Chloride', genericNameAr: 'كلوريد البوتاسيوم',
    brandNames: ['K-Dur', 'Slow-K'], sfda_registration: 'SFDA-2024-KCL-063',
    atcCode: 'A12BA01', atcCategory: 'A12 - Mineral supplements',
    therapeuticClass: 'Electrolytes', therapeuticClassAr: 'الشوارد',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [{ form: 'tablet', strength: '600mg (8mEq)', unitPrice: 0.3, inStock: true }, { form: 'injection', strength: '20mEq/10ml', unitPrice: 5.0, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: ['KCl/NaCl'],
    interactions: [{ interactsWith: 'Lisinopril', severity: 'major', mechanism: 'Additive potassium retention', clinicalEffect: 'Hyperkalemia', clinicalEffectAr: 'فرط البوتاسيوم', management: 'Monitor K+ closely', managementAr: 'مراقبة البوتاسيوم بدقة' }],
    contraindications: ['Hyperkalemia', 'Severe renal impairment', 'Addison disease'], contraindicationsAr: ['فرط البوتاسيوم', 'قصور كلوي شديد', 'مرض أديسون'],
    monitoringRequired: ['Serum potassium', 'ECG with IV', 'Renal function'], storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Calcium Carbonate', genericNameAr: 'كربونات الكالسيوم',
    brandNames: ['Caltrate', 'Tums'], sfda_registration: 'SFDA-2024-CAL-064',
    atcCode: 'A12AA04', atcCategory: 'A12 - Mineral supplements',
    therapeuticClass: 'Supplements', therapeuticClassAr: 'مكملات غذائية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '500mg', unitPrice: 0.2, inStock: true }, { form: 'tablet', strength: '1250mg', unitPrice: 0.3, inStock: true }],
    maxDailyDose: 2500, maxDailyDoseUnit: 'mg elemental calcium', renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [], contraindications: ['Hypercalcemia', 'Severe renal impairment'], contraindicationsAr: ['فرط الكالسيوم', 'قصور كلوي شديد'],
    monitoringRequired: ['Calcium levels with high doses'], storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Iron Sulfate (Ferrous Sulfate)', genericNameAr: 'كبريتات الحديد',
    brandNames: ['Ferose', 'Ferrograd'], sfda_registration: 'SFDA-2024-FES-065',
    atcCode: 'B03AA07', atcCategory: 'B03 - Antianemic preparations',
    therapeuticClass: 'Supplements', therapeuticClassAr: 'مكملات غذائية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '325mg (65mg elemental Fe)', unitPrice: 0.2, inStock: true }, { form: 'syrup', strength: '300mg/5ml', unitPrice: 5.0, inStock: true }],
    maxDailyDose: 200, maxDailyDoseUnit: 'mg elemental iron', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'A', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Ferrous Sulfate/Ferrous Gluconate'],
    interactions: [{ interactsWith: 'Levothyroxine', severity: 'moderate', mechanism: 'Reduced absorption', clinicalEffect: 'Decreased thyroid hormone effect', clinicalEffectAr: 'تقليل تأثير هرمون الغدة الدرقية', management: 'Separate by 4 hours', managementAr: 'فصل 4 ساعات' }],
    contraindications: ['Hemochromatosis', 'Hemolytic anemia'], contraindicationsAr: ['فرط ترسب الحديد', 'فقر دم انحلالي'],
    monitoringRequired: ['Ferritin', 'CBC', 'Reticulocyte count'], storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Folic Acid', genericNameAr: 'حمض الفوليك',
    brandNames: ['Folvite'], sfda_registration: 'SFDA-2024-FOL-066',
    atcCode: 'B03BB01', atcCategory: 'B03 - Antianemic preparations',
    therapeuticClass: 'Supplements', therapeuticClassAr: 'مكملات غذائية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '1mg', unitPrice: 0.1, inStock: true }, { form: 'tablet', strength: '5mg', unitPrice: 0.2, inStock: true }],
    maxDailyDose: 5, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'A', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Folic Acid/Folinic Acid'],
    interactions: [], contraindications: ['Untreated vitamin B12 deficiency (may mask)'], contraindicationsAr: ['نقص فيتامين B12 غير معالج (قد يخفيه)'],
    monitoringRequired: ['B12 levels before starting'], storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: nextId(), genericName: 'Vitamin D (Cholecalciferol)', genericNameAr: 'فيتامين د (كوليكالسيفيرول)',
    brandNames: ['Vi-De-3', 'D3 Drops'], sfda_registration: 'SFDA-2024-VIT-067',
    atcCode: 'A11CC05', atcCategory: 'A11 - Vitamins',
    therapeuticClass: 'Supplements', therapeuticClassAr: 'مكملات غذائية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '1000 IU', unitPrice: 0.2, inStock: true }, { form: 'drops', strength: '50000 IU/ml', unitPrice: 15.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [], contraindications: ['Hypercalcemia', 'Vitamin D toxicity'], contraindicationsAr: ['فرط الكالسيوم', 'سمية فيتامين د'],
    monitoringRequired: ['25-OH Vitamin D levels', 'Calcium levels'], storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: nextId(), genericName: 'Hydrocortisone', genericNameAr: 'هيدروكورتيزون',
    brandNames: ['Solu-Cortef'], sfda_registration: 'SFDA-2024-HYD-068',
    atcCode: 'H02AB09', atcCategory: 'H02 - Corticosteroids',
    therapeuticClass: 'Corticosteroids', therapeuticClassAr: 'كورتيكوستيرويدات',
    formularyStatus: 'formulary', route: ['iv', 'im', 'oral', 'topical'],
    forms: [{ form: 'injection', strength: '100mg', unitPrice: 8.0, inStock: true }, { form: 'tablet', strength: '10mg', unitPrice: 1.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Hydrocortisone/Hydroxychloroquine'],
    interactions: [], contraindications: ['Systemic fungal infections'], contraindicationsAr: ['عدوى فطرية جهازية'],
    monitoringRequired: ['Blood glucose', 'Blood pressure', 'Electrolytes'], storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Prednisolone', genericNameAr: 'بريدنيزولون',
    brandNames: ['Predsol'], sfda_registration: 'SFDA-2024-PRD-069',
    atcCode: 'H02AB06', atcCategory: 'H02 - Corticosteroids',
    therapeuticClass: 'Corticosteroids', therapeuticClassAr: 'كورتيكوستيرويدات',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '5mg', unitPrice: 0.3, inStock: true }, { form: 'syrup', strength: '15mg/5ml', unitPrice: 8.0, inStock: true }],
    maxDailyDose: 60, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Prednisolone/Prednisone/Methylprednisolone'],
    interactions: [], contraindications: ['Systemic fungal infections', 'Live vaccines with immunosuppressive doses'],
    contraindicationsAr: ['عدوى فطرية جهازية', 'لقاحات حية مع جرعات مثبطة للمناعة'],
    monitoringRequired: ['Blood glucose', 'Blood pressure', 'Weight', 'Bone density with long-term use'], storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Methylprednisolone', genericNameAr: 'ميثيل بريدنيزولون',
    brandNames: ['Solu-Medrol', 'Medrol'], sfda_registration: 'SFDA-2024-MPR-070',
    atcCode: 'H02AB04', atcCategory: 'H02 - Corticosteroids',
    therapeuticClass: 'Corticosteroids', therapeuticClassAr: 'كورتيكوستيرويدات',
    formularyStatus: 'formulary', route: ['iv', 'im', 'oral'],
    forms: [{ form: 'injection', strength: '40mg', unitPrice: 10.0, inStock: true }, { form: 'injection', strength: '125mg', unitPrice: 18.0, inStock: true }, { form: 'injection', strength: '500mg', unitPrice: 45.0, inStock: true }, { form: 'tablet', strength: '4mg', unitPrice: 1.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Methylprednisolone/Prednisolone/Medroxyprogesterone'],
    interactions: [], contraindications: ['Systemic fungal infections'], contraindicationsAr: ['عدوى فطرية جهازية'],
    monitoringRequired: ['Blood glucose', 'Blood pressure', 'Electrolytes'], storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Levothyroxine', genericNameAr: 'ليفوثيروكسين',
    brandNames: ['Euthyrox', 'Synthroid'], sfda_registration: 'SFDA-2024-LEV-071',
    atcCode: 'H03AA01', atcCategory: 'H03 - Thyroid therapy',
    therapeuticClass: 'Endocrine', therapeuticClassAr: 'أدوية الغدد الصماء',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '25mcg', unitPrice: 0.3, inStock: true }, { form: 'tablet', strength: '50mcg', unitPrice: 0.3, inStock: true }, { form: 'tablet', strength: '100mcg', unitPrice: 0.4, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'A', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Levothyroxine/Levofloxacin/Liothyronine'],
    interactions: [{ interactsWith: 'Iron Sulfate (Ferrous Sulfate)', severity: 'moderate', mechanism: 'Reduced absorption', clinicalEffect: 'Decreased levothyroxine effect', clinicalEffectAr: 'تقليل تأثير ليفوثيروكسين', management: 'Separate by 4 hours', managementAr: 'فصل 4 ساعات' }],
    contraindications: ['Untreated adrenal insufficiency', 'Acute MI (relative)'], contraindicationsAr: ['قصور كظري غير معالج', 'احتشاء حاد (نسبي)'],
    monitoringRequired: ['TSH every 6-8 weeks until stable', 'Free T4'], storageConditions: 'Store below 25°C, protect from moisture',
  },
  {
    id: nextId(), genericName: 'Phenytoin', genericNameAr: 'فينيتوين',
    brandNames: ['Dilantin', 'Epanutin'], sfda_registration: 'SFDA-2024-PHE-072',
    atcCode: 'N03AB02', atcCategory: 'N03 - Antiepileptics',
    therapeuticClass: 'Anticonvulsants', therapeuticClassAr: 'مضادات الاختلاج',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [{ form: 'capsule', strength: '100mg', unitPrice: 0.5, inStock: true }, { form: 'injection', strength: '250mg/5ml', unitPrice: 10.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'D', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: ['Phenytoin/Fosphenytoin'],
    interactions: [{ interactsWith: 'Warfarin', severity: 'major', mechanism: 'Complex CYP interaction', clinicalEffect: 'Unpredictable INR changes', clinicalEffectAr: 'تغيرات غير متوقعة في INR', management: 'Monitor INR frequently; adjust doses', managementAr: 'مراقبة INR بشكل متكرر؛ تعديل الجرعات' }],
    contraindications: ['Sinus bradycardia', 'SA/AV block', 'Adams-Stokes syndrome'], contraindicationsAr: ['بطء القلب الجيبي', 'إحصار SA/AV', 'متلازمة آدمز-ستوكس'],
    monitoringRequired: ['Drug levels (10-20 mcg/mL)', 'CBC', 'Hepatic function', 'Albumin (for free level calculation)'], storageConditions: 'Store below 30°C',
  },
  {
    id: nextId(), genericName: 'Carbamazepine', genericNameAr: 'كاربامازيبين',
    brandNames: ['Tegretol'], sfda_registration: 'SFDA-2024-CBZ-073',
    atcCode: 'N03AF01', atcCategory: 'N03 - Antiepileptics',
    therapeuticClass: 'Anticonvulsants', therapeuticClassAr: 'مضادات الاختلاج',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '200mg', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '400mg (CR)', unitPrice: 1.5, inStock: true }],
    maxDailyDose: 1600, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Carbamazepine/Oxcarbazepine'],
    blackBoxWarning: 'HLA-B*1502 testing required before initiation (risk of SJS/TEN, especially in Asian populations).',
    blackBoxWarningAr: 'يتطلب فحص HLA-B*1502 قبل البدء (خطر SJS/TEN، خاصة في الآسيويين).',
    interactions: [{ interactsWith: 'Warfarin', severity: 'major', mechanism: 'CYP3A4 induction', clinicalEffect: 'Reduced warfarin effect', clinicalEffectAr: 'تقليل تأثير الوارفارين', management: 'Increase warfarin dose; monitor INR', managementAr: 'زيادة جرعة الوارفارين؛ مراقبة INR' }],
    contraindications: ['Bone marrow depression', 'Concurrent MAOIs', 'HLA-B*1502 positive'], contraindicationsAr: ['تثبيط نخاع العظم', 'مثبطات MAO المتزامنة', 'إيجابي HLA-B*1502'],
    monitoringRequired: ['Drug levels (4-12 mcg/mL)', 'CBC', 'LFTs', 'Sodium', 'HLA-B*1502 before starting'], storageConditions: 'Store below 30°C, protect from moisture',
  },
  {
    id: nextId(), genericName: 'Valproic Acid', genericNameAr: 'حمض الفالبرويك',
    brandNames: ['Depakene', 'Depakote', 'Epilim'], sfda_registration: 'SFDA-2024-VPA-074',
    atcCode: 'N03AG01', atcCategory: 'N03 - Antiepileptics',
    therapeuticClass: 'Anticonvulsants', therapeuticClassAr: 'مضادات الاختلاج',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [{ form: 'tablet', strength: '250mg', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '500mg (DR)', unitPrice: 1.0, inStock: true }, { form: 'syrup', strength: '250mg/5ml', unitPrice: 8.0, inStock: true }],
    maxDailyDose: 60, maxDailyDoseUnit: 'mg/kg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: ['Depakene/Depakote'],
    blackBoxWarning: 'Hepatotoxicity (especially <2 years), pancreatitis, and teratogenicity (neural tube defects).',
    blackBoxWarningAr: 'سمية كبدية (خاصة أقل من سنتين)، التهاب البنكرياس، وتشوهات خلقية (عيوب الأنبوب العصبي).',
    interactions: [{ interactsWith: 'Meropenem', severity: 'major', mechanism: 'Rapid reduction of valproic acid levels', clinicalEffect: 'Loss of seizure control', clinicalEffectAr: 'فقدان السيطرة على النوبات', management: 'Avoid combination', managementAr: 'تجنب الجمع' }],
    contraindications: ['Hepatic disease', 'Urea cycle disorders', 'Pregnancy (for migraine/bipolar)', 'Mitochondrial disease (POLG mutation)'], contraindicationsAr: ['أمراض كبدية', 'اضطرابات دورة اليوريا', 'الحمل (للصداع النصفي/ثنائي القطب)', 'أمراض الميتوكوندريا'],
    monitoringRequired: ['Drug levels (50-100 mcg/mL)', 'LFTs', 'CBC/Platelets', 'Ammonia if symptomatic', 'Lipase if abdominal pain'], storageConditions: 'Store below 30°C',
  },
  {
    id: nextId(), genericName: 'Levetiracetam', genericNameAr: 'ليفيتيراسيتام',
    brandNames: ['Keppra'], sfda_registration: 'SFDA-2024-LEV-075',
    atcCode: 'N03AX14', atcCategory: 'N03 - Antiepileptics',
    therapeuticClass: 'Anticonvulsants', therapeuticClassAr: 'مضادات الاختلاج',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [{ form: 'tablet', strength: '250mg', unitPrice: 1.0, inStock: true }, { form: 'tablet', strength: '500mg', unitPrice: 1.8, inStock: true }, { form: 'tablet', strength: '1000mg', unitPrice: 3.0, inStock: true }, { form: 'injection', strength: '500mg/5ml', unitPrice: 15.0, inStock: true }],
    maxDailyDose: 3000, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Keppra/Keflex'],
    interactions: [], contraindications: [], contraindicationsAr: [],
    monitoringRequired: ['Mood/behavior changes', 'Renal function', 'CBC'], storageConditions: 'Store below 25°C',
  },
  {
    id: nextId(), genericName: 'Midazolam', genericNameAr: 'ميدازولام',
    brandNames: ['Dormicum', 'Versed'], sfda_registration: 'SFDA-2024-MID-076',
    atcCode: 'N05CD08', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Sedatives', therapeuticClassAr: 'مهدئات',
    formularyStatus: 'restricted', route: ['iv', 'im', 'oral', 'intranasal'],
    restrictionCriteria: 'Saudi MOH Schedule IV. ICU/OR/procedural sedation settings.',
    restrictionCriteriaAr: 'جدول 4 وزارة الصحة. إعدادات العناية المركزة/غرفة العمليات/التخدير الإجرائي.',
    approverRole: 'physician',
    forms: [{ form: 'injection', strength: '5mg/ml', unitPrice: 3.0, inStock: true }, { form: 'injection', strength: '5mg/5ml', unitPrice: 3.0, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: true, controlSchedule: 'Saudi MOH Schedule IV',
    lookAlikeSoundAlike: ['Midazolam/Metadoxine'],
    interactions: [{ interactsWith: 'Fentanyl', severity: 'major', mechanism: 'Additive CNS/respiratory depression', clinicalEffect: 'Respiratory arrest', clinicalEffectAr: 'توقف تنفسي', management: 'Reduce doses; continuous monitoring', managementAr: 'تقليل الجرعات؛ مراقبة مستمرة' }],
    contraindications: ['Acute narrow-angle glaucoma', 'Severe respiratory depression'], contraindicationsAr: ['زرق ضيق الزاوية الحاد', 'تثبيط تنفسي شديد'],
    monitoringRequired: ['Respiratory rate', 'SpO2', 'Sedation score', 'Blood pressure'], storageConditions: 'Controlled substance storage. Store below 25°C.',
  },
  {
    id: nextId(), genericName: 'Propofol', genericNameAr: 'بروبوفول',
    brandNames: ['Diprivan'], sfda_registration: 'SFDA-2024-PRO-077',
    atcCode: 'N01AX10', atcCategory: 'N01 - Anesthetics',
    therapeuticClass: 'Anesthetics', therapeuticClassAr: 'مواد تخدير',
    formularyStatus: 'restricted', route: ['iv'],
    restrictionCriteria: 'Anesthesiologist/intensivist only. TIVA/ICU sedation.',
    restrictionCriteriaAr: 'أخصائي تخدير/عناية مركزة فقط.',
    approverRole: 'anesthesiologist',
    forms: [{ form: 'injection', strength: '10mg/ml (20ml)', unitPrice: 15.0, inStock: true }, { form: 'injection', strength: '10mg/ml (50ml)', unitPrice: 30.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: ['Propofol/Fospropofol'],
    interactions: [], contraindications: ['Egg/soy allergy', 'Children <3 years (ICU sedation)'], contraindicationsAr: ['حساسية البيض/الصويا', 'الأطفال أقل من 3 سنوات (تخدير العناية المركزة)'],
    monitoringRequired: ['Continuous BP/HR/SpO2/RR', 'Triglycerides with prolonged infusion', 'Signs of propofol infusion syndrome'], storageConditions: 'Store below 25°C. Do not freeze. Use within 12h of opening.',
  },
  {
    id: nextId(), genericName: 'Atropine', genericNameAr: 'أتروبين',
    brandNames: ['Atropine Sulfate'], sfda_registration: 'SFDA-2024-ATR-078',
    atcCode: 'A03BA01', atcCategory: 'A03 - Drugs for functional GI disorders',
    therapeuticClass: 'Emergency', therapeuticClassAr: 'أدوية الطوارئ',
    formularyStatus: 'formulary', route: ['iv', 'im', 'sc'],
    forms: [{ form: 'injection', strength: '0.5mg/ml', unitPrice: 3.0, inStock: true }, { form: 'injection', strength: '1mg/ml', unitPrice: 5.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: ['Atropine/Adrenaline (Epinephrine)'],
    interactions: [], contraindications: ['Angle-closure glaucoma', 'Pyloric stenosis', 'Myasthenia gravis'], contraindicationsAr: ['زرق مغلق الزاوية', 'تضيق البواب', 'الوهن العضلي الوبيل'],
    monitoringRequired: ['Heart rate', 'Urinary retention', 'Pupil size'], storageConditions: 'Store below 25°C, protect from light',
  },
  {
    id: nextId(), genericName: 'Epinephrine (Adrenaline)', genericNameAr: 'إبينفرين (أدرينالين)',
    brandNames: ['Adrenaline', 'EpiPen'], sfda_registration: 'SFDA-2024-EPI-079',
    atcCode: 'C01CA24', atcCategory: 'C01 - Cardiac therapy',
    therapeuticClass: 'Emergency', therapeuticClassAr: 'أدوية الطوارئ',
    formularyStatus: 'formulary', route: ['iv', 'im', 'sc', 'endotracheal'],
    forms: [{ form: 'injection', strength: '1mg/ml (1:1000)', unitPrice: 3.0, inStock: true }, { form: 'injection', strength: '0.1mg/ml (1:10000)', unitPrice: 5.0, inStock: true }, { form: 'auto-injector', strength: '0.3mg', unitPrice: 120.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: ['Epinephrine 1:1000/Epinephrine 1:10000 (CRITICAL concentration difference)', 'Epinephrine/Ephedrine'],
    interactions: [],
    contraindications: ['No absolute contraindications in cardiac arrest/anaphylaxis'],
    contraindicationsAr: ['لا موانع مطلقة في السكتة القلبية/التأق'],
    monitoringRequired: ['Continuous ECG', 'Blood pressure', 'Heart rate', 'Lactate'],
    storageConditions: 'Store below 25°C, protect from light. Check expiry regularly.',
  },
];

export { DIABETES, ANALGESICS, GI, RESPIRATORY, PSYCHIATRIC, OTHERS };
