/**
 * Saudi MOH Drug Formulary — Part 18: Critical Care & Additional Essential Drugs
 * IDs: FRM-0970 through FRM-0989
 */
import type { FormularyDrug } from './formularyTypes';

export const CRITICAL_CARE_ESSENTIAL: FormularyDrug[] = [
  {
    id: 'FRM-0970', genericName: 'Propofol', genericNameAr: 'بروبوفول',
    brandNames: ['Diprivan'], sfda_registration: 'SFDA-2024-CCE-970',
    atcCode: 'N01AX10', atcCategory: 'N01A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '10mg/ml', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: true, controlSchedule: 'Schedule IV',
    lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Opioids', severity: 'major', mechanism: 'Synergistic respiratory/CNS depression', clinicalEffect: 'Apnea and cardiovascular collapse', clinicalEffectAr: 'انقطاع التنفس وانهيار القلب والأوعية', management: 'Reduce propofol dose when used with opioids', managementAr: 'تقليل جرعة البروبوفول عند استخدامه مع الأفيونات' }],
    contraindications: ['Allergy to egg/soy lecithin', 'Not for pediatric ICU sedation (propofol infusion syndrome)'],
    contraindicationsAr: ['حساسية البيض/ليسيثين الصويا', 'ليس لتخدير الأطفال في العناية المركزة (متلازمة تسريب البروبوفول)'],
    monitoringRequired: ['Respiratory rate', 'Blood pressure', 'Triglycerides q48h for prolonged infusion', 'Propofol infusion syndrome signs'], storageConditions: 'Store below 25°C, do not freeze, use within 12h of opening'
  },
  {
    id: 'FRM-0971', genericName: 'Ketamine', genericNameAr: 'كيتامين',
    brandNames: ['Ketalar'], sfda_registration: 'SFDA-2024-CCE-971',
    atcCode: 'N01AX03', atcCategory: 'N01A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['intravenous', 'intramuscular'], forms: [{ form: 'injection', strength: '50mg/ml', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: true, controlSchedule: 'Schedule III',
    lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Theophylline', severity: 'major', mechanism: 'Lowered seizure threshold', clinicalEffect: 'Seizures', clinicalEffectAr: 'نوبات صرعية', management: 'Avoid combination', managementAr: 'تجنب الجمع' }],
    contraindications: ['Conditions where elevated BP is hazardous', 'Eclampsia', 'Severe cardiac decompensation'],
    contraindicationsAr: ['حالات يكون فيها ارتفاع ضغط الدم خطيراً', 'تسمم الحمل', 'معاوضة قلبية شديدة'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'Emergence reactions', 'Respiratory function'], storageConditions: 'Store below 30°C, protect from light'
  },
  {
    id: 'FRM-0972', genericName: 'Fentanyl', genericNameAr: 'فنتانيل',
    brandNames: ['Sublimaze', 'Durogesic'], sfda_registration: 'SFDA-2024-CCE-972',
    atcCode: 'N01AH01', atcCategory: 'N01A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['intravenous', 'transdermal', 'sublingual'], forms: [{ form: 'injection', strength: '50mcg/ml', unitPrice: 3, inStock: true }, { form: 'transdermal patch', strength: '25mcg/hr', unitPrice: 35, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: true, controlSchedule: 'Schedule II',
    lookAlikeSoundAlike: ['Sufentanil', 'Alfentanil'],
    blackBoxWarning: 'Risk of addiction, abuse, misuse. Life-threatening respiratory depression. Transdermal: accidental exposure can cause fatal overdose in children.',
    blackBoxWarningAr: 'خطر الإدمان وسوء الاستخدام. تثبيط تنفسي مهدد للحياة. اللصقة: التعرض العرضي قد يسبب جرعة زائدة مميتة في الأطفال.',
    interactions: [{ interactsWith: 'CYP3A4 inhibitors', severity: 'major', mechanism: 'Increased fentanyl levels', clinicalEffect: 'Fatal respiratory depression', clinicalEffectAr: 'تثبيط تنفسي مميت', management: 'Reduce fentanyl dose or avoid potent inhibitors', managementAr: 'تقليل جرعة الفنتانيل أو تجنب المثبطات القوية' }],
    contraindications: ['Opioid-naive patients (transdermal)', 'Severe respiratory depression', 'Acute or postoperative pain (transdermal)'],
    contraindicationsAr: ['المرضى غير المعتادين على الأفيونات (اللصقة)', 'تثبيط تنفسي شديد', 'ألم حاد أو بعد العملية (اللصقة)'],
    monitoringRequired: ['Respiratory rate', 'Sedation level', 'Pain score', 'Signs of respiratory depression'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0973', genericName: 'Rocuronium', genericNameAr: 'روكورونيوم',
    brandNames: ['Esmeron', 'Zemuron'], sfda_registration: 'SFDA-2024-CCE-973',
    atcCode: 'M03AC09', atcCategory: 'M03A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '10mg/ml', unitPrice: 18, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Vecuronium'],
    interactions: [{ interactsWith: 'Aminoglycosides', severity: 'major', mechanism: 'Enhanced neuromuscular blockade', clinicalEffect: 'Prolonged paralysis', clinicalEffectAr: 'شلل مطول', management: 'Monitor neuromuscular function carefully', managementAr: 'مراقبة الوظيفة العصبية العضلية بعناية' }],
    contraindications: ['Hypersensitivity to rocuronium'],
    contraindicationsAr: ['فرط الحساسية للروكورونيوم'],
    monitoringRequired: ['Train-of-four monitoring', 'Respiratory function', 'Recovery of muscle function'], storageConditions: 'Refrigerate 2-8°C'
  },
  {
    id: 'FRM-0974', genericName: 'Sugammadex', genericNameAr: 'سوغامادكس',
    brandNames: ['Bridion'], sfda_registration: 'SFDA-2024-CCE-974',
    atcCode: 'V03AB35', atcCategory: 'V03A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'restricted',
    restrictionCriteria: 'Reversal of rocuronium/vecuronium neuromuscular blockade', restrictionCriteriaAr: 'عكس الحصار العصبي العضلي بالروكورونيوم/فيكورونيوم', approverRole: 'anesthesiologist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '100mg/ml', unitPrice: 120, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Hormonal contraceptives', severity: 'moderate', mechanism: 'May reduce progestogen levels', clinicalEffect: 'Contraceptive failure', clinicalEffectAr: 'فشل منع الحمل', management: 'Use backup contraception for 7 days', managementAr: 'استخدام وسيلة احتياطية لمدة 7 أيام' }],
    contraindications: ['Severe renal impairment (CrCl <30ml/min)', 'Hypersensitivity'],
    contraindicationsAr: ['قصور كلوي شديد', 'فرط الحساسية'],
    monitoringRequired: ['Neuromuscular recovery (TOF ratio)', 'Anaphylaxis signs', 'Recurrence of blockade'], storageConditions: 'Store below 30°C, do not freeze'
  },
  {
    id: 'FRM-0975', genericName: 'Amiodarone', genericNameAr: 'أميودارون',
    brandNames: ['Cordarone'], sfda_registration: 'SFDA-2024-CCE-975',
    atcCode: 'C01BD01', atcCategory: 'C01B', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '200mg', unitPrice: 3, inStock: true }, { form: 'injection', strength: '150mg/3ml', unitPrice: 15, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'D', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Amrinone'],
    blackBoxWarning: 'Pulmonary toxicity, hepatotoxicity, proarrhythmia. Use only for life-threatening arrhythmias.',
    blackBoxWarningAr: 'سمية رئوية وكبدية وعدم انتظام ضربات القلب. يستخدم فقط لاضطرابات النظم المهددة للحياة.',
    interactions: [{ interactsWith: 'Warfarin', severity: 'major', mechanism: 'CYP2C9 inhibition', clinicalEffect: 'Markedly increased INR and bleeding', clinicalEffectAr: 'زيادة ملحوظة في INR والنزيف', management: 'Reduce warfarin dose by 33-50%', managementAr: 'تقليل جرعة الوارفارين بنسبة 33-50%' }],
    contraindications: ['Cardiogenic shock', 'Severe sinus node disease', 'AV block >1st degree without pacemaker', 'Thyroid dysfunction (relative)'],
    contraindicationsAr: ['صدمة قلبية', 'مرض شديد في العقدة الجيبية', 'إحصار أذيني بطيني بدون منظم', 'اضطراب الغدة الدرقية (نسبي)'],
    monitoringRequired: ['Thyroid function q6months', 'Liver function tests', 'Pulmonary function tests annually', 'ECG for QTc', 'Eye exam annually'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0976', genericName: 'Adenosine', genericNameAr: 'أدينوسين',
    brandNames: ['Adenocard'], sfda_registration: 'SFDA-2024-CCE-976',
    atcCode: 'C01EB10', atcCategory: 'C01E', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '3mg/ml', unitPrice: 25, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Dipyridamole', severity: 'major', mechanism: 'Potentiated adenosine effect', clinicalEffect: 'Prolonged and exaggerated AV block', clinicalEffectAr: 'إحصار أذيني بطيني مطول ومبالغ فيه', management: 'Reduce adenosine dose by 75%', managementAr: 'تقليل جرعة الأدينوسين بنسبة 75%' }],
    contraindications: ['2nd/3rd degree AV block without pacemaker', 'Sick sinus syndrome', 'Known bronchospastic disease'],
    contraindicationsAr: ['إحصار أذيني بطيني من الدرجة الثانية/الثالثة بدون منظم', 'متلازمة العقدة الجيبية المريضة', 'مرض تشنج قصبي معروف'],
    monitoringRequired: ['Continuous ECG', 'Blood pressure', 'Respiratory function', 'Must be given as rapid IV push with flush'], storageConditions: 'Store below 25°C, do not refrigerate'
  },
  {
    id: 'FRM-0977', genericName: 'Nitroglycerin (GTN)', genericNameAr: 'نيتروغليسرين',
    brandNames: ['Nitrostat', 'Tridil'], sfda_registration: 'SFDA-2024-CCE-977',
    atcCode: 'C01DA02', atcCategory: 'C01D', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['sublingual', 'intravenous', 'transdermal', 'oral'], forms: [{ form: 'sublingual tablet', strength: '0.5mg', unitPrice: 1, inStock: true }, { form: 'injection', strength: '5mg/ml', unitPrice: 8, inStock: true }, { form: 'patch', strength: '5mg/24hr', unitPrice: 5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Nitroprusside'],
    interactions: [{ interactsWith: 'Sildenafil', severity: 'major', mechanism: 'Synergistic vasodilation', clinicalEffect: 'Severe life-threatening hypotension', clinicalEffectAr: 'انخفاض شديد في ضغط الدم مهدد للحياة', management: 'Contraindicated within 24-48h of PDE5 inhibitors', managementAr: 'ممنوع خلال 24-48 ساعة من مثبطات PDE5' }],
    contraindications: ['Concurrent PDE5 inhibitors', 'Severe anemia', 'Increased ICP', 'Constrictive pericarditis'],
    contraindicationsAr: ['مثبطات PDE5 المتزامنة', 'فقر دم شديد', 'ارتفاع الضغط داخل القحف', 'التهاب التامور التضيقي'],
    monitoringRequired: ['Blood pressure continuously', 'Heart rate', 'Headache (tolerance indicator)', 'Nitrate-free interval for patches'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0978', genericName: 'Sodium Nitroprusside', genericNameAr: 'نيتروبروسيد الصوديوم',
    brandNames: ['Nipride', 'Nitropress'], sfda_registration: 'SFDA-2024-CCE-978',
    atcCode: 'C02DD01', atcCategory: 'C02D', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'restricted',
    restrictionCriteria: 'ICU hypertensive emergency only', restrictionCriteriaAr: 'طوارئ ارتفاع ضغط الدم في العناية المركزة فقط', approverRole: 'intensivist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '50mg', unitPrice: 35, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Nitroglycerin'],
    blackBoxWarning: 'Cyanide toxicity risk. Must not exceed 10mcg/kg/min or 3 days of continuous infusion.',
    blackBoxWarningAr: 'خطر سمية السيانيد. يجب ألا تتجاوز 10 ميكروغرام/كغ/دقيقة أو 3 أيام تسريب مستمر.',
    interactions: [],
    contraindications: ['Compensatory hypertension (coarctation, AV shunt)', 'Severe hepatic/renal impairment', 'Tobacco amblyopia', 'Leber optic atrophy'],
    contraindicationsAr: ['ارتفاع الضغط التعويضي', 'قصور كبدي/كلوي شديد', 'غمش التبغ', 'ضمور ليبر البصري'],
    monitoringRequired: ['Continuous arterial BP', 'Thiocyanate levels if >3 days', 'Cyanide levels', 'Metabolic acidosis'], storageConditions: 'Store below 25°C, protect from light, wrap infusion in foil'
  },
  {
    id: 'FRM-0979', genericName: 'Labetalol', genericNameAr: 'لابيتالول',
    brandNames: ['Trandate', 'Normodyne'], sfda_registration: 'SFDA-2024-CCE-979',
    atcCode: 'C07AG01', atcCategory: 'C07A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '200mg', unitPrice: 3, inStock: true }, { form: 'injection', strength: '5mg/ml', unitPrice: 12, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Lamotrigine'],
    interactions: [{ interactsWith: 'Verapamil', severity: 'major', mechanism: 'Additive cardiodepressant effects', clinicalEffect: 'Severe bradycardia and heart failure', clinicalEffectAr: 'بطء قلب شديد وفشل القلب', management: 'Avoid IV combination', managementAr: 'تجنب الجمع الوريدي' }],
    contraindications: ['Cardiogenic shock', 'Severe bradycardia', 'Heart block >1st degree', 'Asthma'],
    contraindicationsAr: ['صدمة قلبية', 'بطء قلب شديد', 'إحصار القلب', 'الربو'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'Liver function tests', 'Signs of heart failure'], storageConditions: 'Store below 30°C, protect from light'
  },
  {
    id: 'FRM-0980', genericName: 'Hydralazine', genericNameAr: 'هيدرالازين',
    brandNames: ['Apresoline'], sfda_registration: 'SFDA-2024-CCE-980',
    atcCode: 'C02DB02', atcCategory: 'C02D', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '25mg', unitPrice: 2, inStock: true }, { form: 'injection', strength: '20mg/ml', unitPrice: 8, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Hydroxyzine'],
    interactions: [{ interactsWith: 'Diazoxide', severity: 'major', mechanism: 'Severe additive hypotension', clinicalEffect: 'Dangerous blood pressure drop', clinicalEffectAr: 'انخفاض خطير في ضغط الدم', management: 'Avoid combination', managementAr: 'تجنب الجمع' }],
    contraindications: ['Coronary artery disease', 'Mitral valve disease', 'SLE (drug-induced lupus risk)'],
    contraindicationsAr: ['مرض الشريان التاجي', 'مرض الصمام التاجي', 'الذئبة (خطر الذئبة المحرضة بالأدوية)'],
    monitoringRequired: ['Blood pressure', 'Heart rate', 'ANA titers for prolonged use', 'CBC'], storageConditions: 'Store below 30°C'
  },
  {
    id: 'FRM-0981', genericName: 'Furosemide', genericNameAr: 'فوروسيميد',
    brandNames: ['Lasix'], sfda_registration: 'SFDA-2024-CCE-981',
    atcCode: 'C03CA01', atcCategory: 'C03C', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [{ form: 'tablet', strength: '40mg', unitPrice: 0.5, inStock: true }, { form: 'injection', strength: '10mg/ml', unitPrice: 3, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Torsemide'],
    interactions: [{ interactsWith: 'Aminoglycosides', severity: 'major', mechanism: 'Additive ototoxicity', clinicalEffect: 'Irreversible hearing loss', clinicalEffectAr: 'فقدان سمع لا رجعي', management: 'Avoid combination if possible', managementAr: 'تجنب الجمع إن أمكن' }],
    contraindications: ['Anuria', 'Hepatic coma', 'Severe electrolyte depletion'],
    contraindicationsAr: ['انقطاع البول', 'غيبوبة كبدية', 'استنفاد شديد للشوارد'],
    monitoringRequired: ['Serum electrolytes', 'Renal function', 'Blood pressure', 'Urine output', 'Hearing if high-dose IV'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0982', genericName: 'Pantoprazole', genericNameAr: 'بانتوبرازول',
    brandNames: ['Protonix', 'Controloc'], sfda_registration: 'SFDA-2024-CCE-982',
    atcCode: 'A02BC02', atcCategory: 'A02B', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '40mg', unitPrice: 2, inStock: true }, { form: 'injection', strength: '40mg', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Omeprazole'],
    interactions: [{ interactsWith: 'Clopidogrel', severity: 'moderate', mechanism: 'CYP2C19 inhibition (less than omeprazole)', clinicalEffect: 'Slightly reduced antiplatelet effect', clinicalEffectAr: 'انخفاض طفيف في تأثير مضاد الصفيحات', management: 'Pantoprazole preferred over omeprazole with clopidogrel', managementAr: 'يفضل البانتوبرازول على الأوميبرازول مع كلوبيدوغريل' }],
    contraindications: ['Hypersensitivity to PPIs'],
    contraindicationsAr: ['فرط الحساسية لمثبطات مضخة البروتون'],
    monitoringRequired: ['Magnesium levels with prolonged use', 'Bone density for long-term', 'B12 levels'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0983', genericName: 'Ondansetron', genericNameAr: 'أوندانسيترون',
    brandNames: ['Zofran'], sfda_registration: 'SFDA-2024-CCE-983',
    atcCode: 'A04AA01', atcCategory: 'A04A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['oral', 'intravenous'], forms: [{ form: 'tablet', strength: '4mg', unitPrice: 2, inStock: true }, { form: 'injection', strength: '2mg/ml', unitPrice: 5, inStock: true }, { form: 'ODT', strength: '4mg', unitPrice: 4, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: ['Granisetron'],
    interactions: [{ interactsWith: 'Apomorphine', severity: 'major', mechanism: 'Profound hypotension and loss of consciousness', clinicalEffect: 'Cardiovascular collapse', clinicalEffectAr: 'انهيار قلبي وعائي', management: 'Contraindicated combination', managementAr: 'تركيبة ممنوعة' }],
    contraindications: ['Concurrent apomorphine', 'Congenital long QT syndrome'],
    contraindicationsAr: ['أبومورفين المتزامن', 'متلازمة QT الطويلة الخلقية'],
    monitoringRequired: ['ECG for QTc in at-risk patients', 'Constipation'], storageConditions: 'Store below 30°C, protect from light'
  },
  {
    id: 'FRM-0984', genericName: 'Metoclopramide', genericNameAr: 'ميتوكلوبراميد',
    brandNames: ['Reglan', 'Primperan'], sfda_registration: 'SFDA-2024-CCE-984',
    atcCode: 'A03FA01', atcCategory: 'A03F', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['oral', 'intravenous', 'intramuscular'], forms: [{ form: 'tablet', strength: '10mg', unitPrice: 0.5, inStock: true }, { form: 'injection', strength: '5mg/ml', unitPrice: 2, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: false,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: false,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Tardive dyskinesia risk with chronic use (>12 weeks). Risk increases in elderly.',
    blackBoxWarningAr: 'خطر خلل الحركة المتأخر مع الاستخدام المزمن (أكثر من 12 أسبوعاً). يزداد الخطر في كبار السن.',
    interactions: [{ interactsWith: 'Levodopa', severity: 'major', mechanism: 'Dopamine receptor antagonism', clinicalEffect: 'Worsening of Parkinson symptoms', clinicalEffectAr: 'تفاقم أعراض باركنسون', management: 'Avoid in Parkinson disease', managementAr: 'تجنب في مرض باركنسون' }],
    contraindications: ['GI obstruction or perforation', 'Pheochromocytoma', 'Epilepsy', 'Parkinson disease'],
    contraindicationsAr: ['انسداد أو ثقب معدي معوي', 'ورم القواتم', 'الصرع', 'مرض باركنسون'],
    monitoringRequired: ['Extrapyramidal symptoms', 'Duration of use (<12 weeks)', 'Tardive dyskinesia signs'], storageConditions: 'Store below 25°C, protect from light'
  },
  {
    id: 'FRM-0985', genericName: 'Dexmedetomidine', genericNameAr: 'ديكسميديتوميدين',
    brandNames: ['Precedex'], sfda_registration: 'SFDA-2024-CCE-985',
    atcCode: 'N05CM18', atcCategory: 'N05C', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'restricted',
    restrictionCriteria: 'ICU sedation for intubated patients', restrictionCriteriaAr: 'تخدير العناية المركزة للمرضى المنببين', approverRole: 'intensivist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '100mcg/ml', unitPrice: 45, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [{ interactsWith: 'Other sedatives', severity: 'moderate', mechanism: 'Additive CNS depression', clinicalEffect: 'Enhanced sedation and bradycardia', clinicalEffectAr: 'تعزيز التخدير وبطء القلب', management: 'Reduce doses of other sedatives', managementAr: 'تقليل جرعات المهدئات الأخرى' }],
    contraindications: ['Advanced heart block without pacemaker'],
    contraindicationsAr: ['إحصار قلب متقدم بدون منظم'],
    monitoringRequired: ['Heart rate (bradycardia common)', 'Blood pressure', 'Level of sedation (RASS scale)', 'Respiratory function'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0986', genericName: 'Insulin Regular (Human)', genericNameAr: 'إنسولين عادي (بشري)',
    brandNames: ['Humulin R', 'Actrapid'], sfda_registration: 'SFDA-2024-CCE-986',
    atcCode: 'A10AB01', atcCategory: 'A10A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['subcutaneous', 'intravenous'], forms: [{ form: 'injection', strength: '100IU/ml', unitPrice: 18, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Insulin Glargine', 'Insulin Lispro'],
    interactions: [{ interactsWith: 'Beta-blockers', severity: 'moderate', mechanism: 'Mask hypoglycemia symptoms', clinicalEffect: 'Unrecognized hypoglycemia', clinicalEffectAr: 'نقص سكر غير معروف', management: 'Increase blood glucose monitoring frequency', managementAr: 'زيادة تكرار مراقبة سكر الدم' }],
    contraindications: ['Hypoglycemia'],
    contraindicationsAr: ['نقص سكر الدم'],
    monitoringRequired: ['Blood glucose q1-4h when IV', 'Serum potassium (insulin shifts K+ intracellularly)', 'Hypoglycemia signs'], storageConditions: 'Refrigerate 2-8°C, use within 28 days at room temp'
  },
  {
    id: 'FRM-0987', genericName: 'Alteplase (tPA)', genericNameAr: 'ألتيبلاز',
    brandNames: ['Activase', 'Actilyse'], sfda_registration: 'SFDA-2024-CCE-987',
    atcCode: 'B01AD02', atcCategory: 'B01A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'restricted',
    restrictionCriteria: 'Acute MI, ischemic stroke, PE — specialist only', restrictionCriteriaAr: 'احتشاء حاد أو سكتة إقفارية أو انسداد رئوي — أخصائي فقط', approverRole: 'consultant_specialist',
    route: ['intravenous'], forms: [{ form: 'injection', strength: '50mg', unitPrice: 950, inStock: true }, { form: 'injection', strength: '100mg', unitPrice: 1800, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: false,
    pediatricApproved: false, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Reteplase', 'Tenecteplase'],
    blackBoxWarning: 'Risk of fatal intracranial hemorrhage. Strict contraindication screening required.',
    blackBoxWarningAr: 'خطر نزيف داخل القحف مميت. يتطلب فحص صارم لموانع الاستعمال.',
    interactions: [{ interactsWith: 'Anticoagulants', severity: 'major', mechanism: 'Additive bleeding risk', clinicalEffect: 'Life-threatening hemorrhage', clinicalEffectAr: 'نزيف مهدد للحياة', management: 'Careful risk-benefit assessment', managementAr: 'تقييم دقيق للمخاطر والفوائد' }],
    contraindications: ['Active internal bleeding', 'Recent (3 months) stroke or head trauma', 'Intracranial neoplasm', 'Uncontrolled hypertension >185/110'],
    contraindicationsAr: ['نزيف داخلي نشط', 'سكتة أو إصابة رأس حديثة (3 أشهر)', 'ورم داخل القحف', 'ارتفاع ضغط دم غير منضبط أكثر من 185/110'],
    monitoringRequired: ['Neurological checks q15min', 'Blood pressure', 'Bleeding signs', 'Fibrinogen', 'CT scan before and after'], storageConditions: 'Refrigerate 2-8°C, use within 8h of reconstitution'
  },
  {
    id: 'FRM-0988', genericName: 'Enoxaparin', genericNameAr: 'إينوكسابارين',
    brandNames: ['Clexane', 'Lovenox'], sfda_registration: 'SFDA-2024-CCE-988',
    atcCode: 'B01AB05', atcCategory: 'B01A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['subcutaneous', 'intravenous'], forms: [{ form: 'injection', strength: '40mg/0.4ml', unitPrice: 15, inStock: true }, { form: 'injection', strength: '60mg/0.6ml', unitPrice: 22, inStock: true }, { form: 'injection', strength: '80mg/0.8ml', unitPrice: 28, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false, pregnancyCategory: 'B', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Dalteparin'],
    interactions: [{ interactsWith: 'NSAIDs', severity: 'major', mechanism: 'Additive bleeding risk', clinicalEffect: 'Major hemorrhage', clinicalEffectAr: 'نزيف كبير', management: 'Avoid combination if possible, monitor closely', managementAr: 'تجنب الجمع إن أمكن ومراقبة دقيقة' }],
    contraindications: ['Active major bleeding', 'HIT (heparin-induced thrombocytopenia)', 'Hypersensitivity to heparin'],
    contraindicationsAr: ['نزيف كبير نشط', 'نقص الصفيحات المحرض بالهيبارين', 'فرط الحساسية للهيبارين'],
    monitoringRequired: ['Anti-Xa levels in renal impairment', 'Platelet count (HIT screening)', 'Signs of bleeding', 'Renal function'], storageConditions: 'Store below 25°C'
  },
  {
    id: 'FRM-0989', genericName: 'Heparin (Unfractionated)', genericNameAr: 'هيبارين (غير مجزأ)',
    brandNames: ['Heparin Sodium'], sfda_registration: 'SFDA-2024-CCE-989',
    atcCode: 'B01AB01', atcCategory: 'B01A', therapeuticClass: 'Critical Care Essential',
    therapeuticClassAr: 'أدوية العناية الحرجة الأساسية', formularyStatus: 'formulary',
    route: ['intravenous', 'subcutaneous'], forms: [{ form: 'injection', strength: '5000IU/ml', unitPrice: 3, inStock: true }, { form: 'injection', strength: '25000IU/5ml', unitPrice: 8, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false, pregnancyCategory: 'C', lactationSafe: true,
    pediatricApproved: true, geriatricCaution: true, highAlertMedication: true,
    controlledSubstance: false, lookAlikeSoundAlike: ['Hespan'],
    interactions: [{ interactsWith: 'Antiplatelet agents', severity: 'major', mechanism: 'Additive bleeding risk', clinicalEffect: 'Major hemorrhage', clinicalEffectAr: 'نزيف كبير', management: 'Monitor aPTT and bleeding signs', managementAr: 'مراقبة aPTT وعلامات النزيف' }],
    contraindications: ['Active bleeding', 'Severe thrombocytopenia', 'HIT history', 'Uncontrolled hypertension'],
    contraindicationsAr: ['نزيف نشط', 'نقص صفيحات شديد', 'تاريخ نقص الصفيحات المحرض بالهيبارين', 'ارتفاع ضغط الدم غير المنضبط'],
    monitoringRequired: ['aPTT every 6h until stable', 'Platelet count q2-3 days', 'Signs of bleeding', 'HIT monitoring'], storageConditions: 'Store below 30°C'
  },
];

