/**
 * Saudi MOH Drug Formulary — Drug Data Part 4
 * Dermatology, Ophthalmology, ENT, Urology, Endocrine
 * IDs: FRM-0133 through FRM-0182
 */

import type { FormularyDrug } from './formularyTypes';

// ─── DERMATOLOGY (10) ─────────────────────────────────────────────────────────

export const DERMATOLOGY: FormularyDrug[] = [
  {
    id: 'FRM-0133', genericName: 'Isotretinoin', genericNameAr: 'آيزوتريتينوين',
    brandNames: ['Roaccutane', 'Accutane', 'Sotret'], sfda_registration: 'SFDA-2024-ISO-133',
    atcCode: 'D10BA01', atcCategory: 'D10 - Anti-acne preparations',
    therapeuticClass: 'Dermatology - Retinoids', therapeuticClassAr: 'أدوية جلدية - ريتينويدات',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Dermatologist only. iPLEDGE-equivalent program required. Two negative pregnancy tests before initiation.',
    restrictionCriteriaAr: 'طبيب جلدية فقط. برنامج مكافئ لـ iPLEDGE مطلوب. اختباري حمل سلبيين قبل البدء.',
    approverRole: 'dermatologist',
    route: ['Oral'], forms: [
      { form: 'Capsule', strength: '10mg', unitPrice: 8.5, inStock: true },
      { form: 'Capsule', strength: '20mg', unitPrice: 14.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: true, controlledSubstance: false,
    lookAlikeSoundAlike: ['Isotretinoin/Tretinoin'],
    blackBoxWarning: 'CONTRAINDICATED in pregnancy. Must use two forms of contraception. Associated with depression, psychosis, and suicidal ideation.',
    blackBoxWarningAr: 'ممنوع في الحمل. يجب استخدام وسيلتين لمنع الحمل. مرتبط بالاكتئاب والذهان والأفكار الانتحارية.',
    interactions: [
      { interactsWith: 'Tetracyclines', severity: 'major', mechanism: 'Additive intracranial pressure elevation',
        clinicalEffect: 'Pseudotumor cerebri', clinicalEffectAr: 'ورم كاذب دماغي',
        management: 'Contraindicated combination', managementAr: 'تركيبة ممنوعة' },
    ],
    contraindications: ['Pregnancy', 'Hyperlipidemia uncontrolled', 'Hepatic insufficiency', 'Hypervitaminosis A'],
    contraindicationsAr: ['الحمل', 'فرط شحميات الدم غير المسيطر عليه', 'قصور كبدي', 'فرط فيتامين أ'],
    monitoringRequired: ['Pregnancy test monthly', 'LFTs monthly', 'Fasting lipids monthly', 'CBC', 'Mood assessment'],
    storageConditions: 'Store below 25°C, protect from light.',
  },
  {
    id: 'FRM-0134', genericName: 'Acitretin', genericNameAr: 'أسيتريتين',
    brandNames: ['Soriatane', 'Neotigason'], sfda_registration: 'SFDA-2024-ACI-134',
    atcCode: 'D05BB02', atcCategory: 'D05 - Antipsoriatics',
    therapeuticClass: 'Dermatology - Retinoids', therapeuticClassAr: 'أدوية جلدية - ريتينويدات',
    formularyStatus: 'restricted', restrictionCriteria: 'Dermatologist only for severe psoriasis.',
    restrictionCriteriaAr: 'طبيب جلدية فقط للصدفية الشديدة.', approverRole: 'dermatologist',
    route: ['Oral'], forms: [{ form: 'Capsule', strength: '25mg', unitPrice: 12.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Acitretin/Tretinoin'],
    blackBoxWarning: 'Must not become pregnant during treatment or for 3 years after discontinuation.',
    blackBoxWarningAr: 'يجب عدم الحمل أثناء العلاج أو لمدة 3 سنوات بعد التوقف.',
    interactions: [
      { interactsWith: 'Methotrexate', severity: 'major', mechanism: 'Additive hepatotoxicity',
        clinicalEffect: 'Severe liver damage', clinicalEffectAr: 'تلف كبدي شديد',
        management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['Pregnancy', 'Severe hepatic/renal impairment', 'Chronic hyperlipidemia'],
    contraindicationsAr: ['الحمل', 'قصور كبدي/كلوي شديد', 'فرط شحميات دم مزمن'],
    monitoringRequired: ['LFTs every 1-2 weeks initially then monthly', 'Fasting lipids', 'Pregnancy test'],
    storageConditions: 'Store below 25°C, protect from moisture.',
  },
  {
    id: 'FRM-0135', genericName: 'Calcipotriol', genericNameAr: 'كالسيبوتريول',
    brandNames: ['Daivonex', 'Dovonex'], sfda_registration: 'SFDA-2024-CAL-135',
    atcCode: 'D05AX02', atcCategory: 'D05 - Antipsoriatics',
    therapeuticClass: 'Dermatology - Vitamin D Analogues', therapeuticClassAr: 'أدوية جلدية - نظائر فيتامين د',
    formularyStatus: 'formulary', route: ['Topical'],
    forms: [{ form: 'Ointment', strength: '50mcg/g', unitPrice: 35.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false,
    lookAlikeSoundAlike: ['Calcipotriol/Calcitriol'],
    interactions: [
      { interactsWith: 'Calcium supplements', severity: 'moderate', mechanism: 'Additive hypercalcemia risk',
        clinicalEffect: 'Hypercalcemia', clinicalEffectAr: 'فرط كالسيوم الدم',
        management: 'Monitor calcium if using on large areas', managementAr: 'مراقبة الكالسيوم عند الاستخدام على مساحات كبيرة' },
    ],
    contraindications: ['Hypercalcemia', 'Calcium metabolism disorders'],
    contraindicationsAr: ['فرط كالسيوم الدم', 'اضطرابات استقلاب الكالسيوم'],
    monitoringRequired: ['Serum calcium if applied to >30% BSA'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0136', genericName: 'Tacrolimus Ointment', genericNameAr: 'تاكروليموس مرهم',
    brandNames: ['Protopic'], sfda_registration: 'SFDA-2024-TAC-136',
    atcCode: 'D11AH01', atcCategory: 'D11 - Other dermatological preparations',
    therapeuticClass: 'Dermatology - Calcineurin Inhibitors', therapeuticClassAr: 'أدوية جلدية - مثبطات الكالسينيورين',
    formularyStatus: 'conditional', restrictionCriteria: 'Second-line for atopic dermatitis after topical steroids.',
    restrictionCriteriaAr: 'خط ثانٍ لالتهاب الجلد التأتبي بعد الستيرويدات الموضعية.', approverRole: 'dermatologist',
    route: ['Topical'], forms: [
      { form: 'Ointment', strength: '0.03%', unitPrice: 65.0, inStock: true },
      { form: 'Ointment', strength: '0.1%', unitPrice: 75.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Long-term safety not established. Rare cases of malignancy (lymphoma, skin cancer) reported.',
    blackBoxWarningAr: 'السلامة طويلة الأمد غير مثبتة. حالات نادرة من الأورام الخبيثة.',
    interactions: [
      { interactsWith: 'CYP3A4 inhibitors', severity: 'moderate', mechanism: 'Increased systemic absorption possible',
        clinicalEffect: 'Immunosuppression if extensive use', clinicalEffectAr: 'تثبيط مناعي مع الاستخدام الواسع',
        management: 'Limit area of application', managementAr: 'تحديد مساحة التطبيق' },
    ],
    contraindications: ['Netherton syndrome', 'Generalized erythroderma', 'Immunocompromised'],
    contraindicationsAr: ['متلازمة نيثرتون', 'احمرار الجلد المعمم', 'ضعف المناعة'],
    monitoringRequired: ['Skin examination annually', 'Sun protection counseling'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0137', genericName: 'Pimecrolimus', genericNameAr: 'بيميكروليموس',
    brandNames: ['Elidel'], sfda_registration: 'SFDA-2024-PIM-137',
    atcCode: 'D11AH02', atcCategory: 'D11 - Other dermatological preparations',
    therapeuticClass: 'Dermatology - Calcineurin Inhibitors', therapeuticClassAr: 'أدوية جلدية - مثبطات الكالسينيورين',
    formularyStatus: 'formulary', route: ['Topical'],
    forms: [{ form: 'Cream', strength: '1%', unitPrice: 55.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Pimecrolimus/Tacrolimus'],
    interactions: [],
    contraindications: ['Immunocompromised patients', 'Active skin infections'],
    contraindicationsAr: ['مرضى ضعف المناعة', 'عدوى جلدية نشطة'],
    monitoringRequired: ['Annual skin check'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0138', genericName: 'Dapsone', genericNameAr: 'دابسون',
    brandNames: ['Avlosulfon'], sfda_registration: 'SFDA-2024-DAP-138',
    atcCode: 'D10AX05', atcCategory: 'D10 - Anti-acne preparations',
    therapeuticClass: 'Dermatology - Sulfones', therapeuticClassAr: 'أدوية جلدية - سلفونات',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet', strength: '100mg', unitPrice: 3.0, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'Trimethoprim', severity: 'major', mechanism: 'Increased methemoglobin levels',
        clinicalEffect: 'Methemoglobinemia', clinicalEffectAr: 'ميتهيموغلوبينية الدم',
        management: 'Monitor methemoglobin levels', managementAr: 'مراقبة مستويات الميتهيموغلوبين' },
    ],
    contraindications: ['G6PD deficiency (severe)', 'Severe anemia', 'Sulfonamide allergy'],
    contraindicationsAr: ['نقص G6PD شديد', 'فقر دم شديد', 'حساسية السلفوناميد'],
    monitoringRequired: ['G6PD before starting', 'CBC weekly x4 then monthly', 'LFTs', 'Methemoglobin if symptomatic'],
    storageConditions: 'Store below 25°C, protect from light.',
  },
  {
    id: 'FRM-0139', genericName: 'Apremilast', genericNameAr: 'أبريميلاست',
    brandNames: ['Otezla'], sfda_registration: 'SFDA-2024-APR-139',
    atcCode: 'D05AX02', atcCategory: 'D05 - Antipsoriatics',
    therapeuticClass: 'Dermatology - PDE4 Inhibitors', therapeuticClassAr: 'أدوية جلدية - مثبطات PDE4',
    formularyStatus: 'restricted', restrictionCriteria: 'Dermatologist or rheumatologist for moderate-severe psoriasis/PsA.',
    restrictionCriteriaAr: 'طبيب جلدية أو روماتيزم للصدفية المتوسطة-الشديدة.', approverRole: 'dermatologist',
    route: ['Oral'], forms: [{ form: 'Tablet', strength: '30mg', unitPrice: 55.0, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'Strong CYP3A4 inducers (Rifampicin)', severity: 'major', mechanism: 'Decreased apremilast levels',
        clinicalEffect: 'Loss of efficacy', clinicalEffectAr: 'فقدان الفعالية',
        management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['Hypersensitivity', 'Severe renal impairment (CrCl <30) without dose adjustment'],
    contraindicationsAr: ['فرط حساسية', 'قصور كلوي شديد بدون تعديل الجرعة'],
    monitoringRequired: ['Weight', 'Mood/depression screening', 'Renal function'],
    storageConditions: 'Store below 30°C.',
  },
  {
    id: 'FRM-0140', genericName: 'Hydroxychloroquine', genericNameAr: 'هيدروكسي كلوروكين',
    brandNames: ['Plaquenil'], sfda_registration: 'SFDA-2024-HCQ-140',
    atcCode: 'P01BA02', atcCategory: 'P01 - Antiprotozoals',
    therapeuticClass: 'Dermatology - Antimalarials', therapeuticClassAr: 'أدوية جلدية - مضادات الملاريا',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet', strength: '200mg', unitPrice: 4.0, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Hydroxychloroquine/Chloroquine'],
    interactions: [
      { interactsWith: 'QT-prolonging drugs', severity: 'major', mechanism: 'Additive QT prolongation',
        clinicalEffect: 'Cardiac arrhythmias', clinicalEffectAr: 'اضطرابات نظم القلب',
        management: 'Monitor ECG', managementAr: 'مراقبة تخطيط القلب' },
    ],
    contraindications: ['Retinal disease', 'G6PD deficiency', 'Porphyria'],
    contraindicationsAr: ['مرض الشبكية', 'نقص G6PD', 'البورفيريا'],
    monitoringRequired: ['Ophthalmology exam at baseline then annually after 5 years', 'CBC', 'LFTs'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0141', genericName: 'Secukinumab', genericNameAr: 'سيكيوكينوماب',
    brandNames: ['Cosentyx'], sfda_registration: 'SFDA-2024-SEC-141',
    atcCode: 'L04AC10', atcCategory: 'L04 - Immunosuppressants',
    therapeuticClass: 'Dermatology - IL-17A Inhibitors', therapeuticClassAr: 'أدوية جلدية - مثبطات IL-17A',
    formularyStatus: 'restricted', restrictionCriteria: 'Dermatologist. For moderate-severe plaque psoriasis failing conventional therapy.',
    restrictionCriteriaAr: 'طبيب جلدية. للصدفية اللويحية المتوسطة-الشديدة بعد فشل العلاج التقليدي.', approverRole: 'dermatologist',
    route: ['Subcutaneous'], forms: [{ form: 'Pre-filled pen', strength: '150mg/mL', unitPrice: 2800.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Secukinumab/Ustekinumab'],
    interactions: [
      { interactsWith: 'Live vaccines', severity: 'major', mechanism: 'Immunosuppression reduces vaccine efficacy',
        clinicalEffect: 'Risk of vaccine-strain infection', clinicalEffectAr: 'خطر العدوى من سلالة اللقاح',
        management: 'Avoid live vaccines during treatment', managementAr: 'تجنب اللقاحات الحية أثناء العلاج' },
    ],
    contraindications: ['Active TB', 'Serious active infection', 'Hypersensitivity'],
    contraindicationsAr: ['سل نشط', 'عدوى خطيرة نشطة', 'فرط حساسية'],
    monitoringRequired: ['TB screening before initiation', 'Hepatitis B/C screening', 'Signs of infection', 'IBD symptoms'],
    storageConditions: 'Store 2-8°C. Do not freeze. Protect from light.',
  },
  {
    id: 'FRM-0142', genericName: 'Dupilumab', genericNameAr: 'دوبيلوماب',
    brandNames: ['Dupixent'], sfda_registration: 'SFDA-2024-DUP-142',
    atcCode: 'D11AH05', atcCategory: 'D11 - Other dermatological preparations',
    therapeuticClass: 'Dermatology - IL-4/IL-13 Inhibitors', therapeuticClassAr: 'أدوية جلدية - مثبطات IL-4/IL-13',
    formularyStatus: 'restricted', restrictionCriteria: 'Dermatologist or allergist for moderate-severe atopic dermatitis.',
    restrictionCriteriaAr: 'طبيب جلدية أو حساسية لالتهاب الجلد التأتبي المتوسط-الشديد.', approverRole: 'dermatologist',
    route: ['Subcutaneous'], forms: [{ form: 'Pre-filled syringe', strength: '300mg/2mL', unitPrice: 3200.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'Live vaccines', severity: 'major', mechanism: 'May alter immune response',
        clinicalEffect: 'Reduced vaccine efficacy', clinicalEffectAr: 'انخفاض فعالية اللقاح',
        management: 'Avoid live vaccines', managementAr: 'تجنب اللقاحات الحية' },
    ],
    contraindications: ['Hypersensitivity', 'Active helminth infection'],
    contraindicationsAr: ['فرط حساسية', 'عدوى طفيلية نشطة'],
    monitoringRequired: ['Conjunctivitis/keratitis monitoring', 'Eosinophil count', 'Parasitic infection screening'],
    storageConditions: 'Store 2-8°C. Do not freeze.',
  },
];

// ─── OPHTHALMOLOGY (10) ───────────────────────────────────────────────────────

export const OPHTHALMOLOGY: FormularyDrug[] = [
  {
    id: 'FRM-0143', genericName: 'Timolol', genericNameAr: 'تيمولول',
    brandNames: ['Timoptic', 'Cusimolol'], sfda_registration: 'SFDA-2024-TIM-143',
    atcCode: 'S01ED01', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Beta-Blockers', therapeuticClassAr: 'طب العيون - حاصرات بيتا',
    formularyStatus: 'formulary', route: ['Ophthalmic'],
    forms: [{ form: 'Eye drops', strength: '0.5%', unitPrice: 12.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Timolol/Atenolol'],
    interactions: [
      { interactsWith: 'Systemic beta-blockers', severity: 'major', mechanism: 'Additive beta-blockade',
        clinicalEffect: 'Bradycardia and hypotension', clinicalEffectAr: 'بطء القلب وانخفاض ضغط الدم',
        management: 'Monitor heart rate and blood pressure', managementAr: 'مراقبة معدل القلب وضغط الدم' },
    ],
    contraindications: ['Asthma', 'COPD', 'Bradycardia', 'Heart block', 'Decompensated heart failure'],
    contraindicationsAr: ['الربو', 'مرض رئوي انسدادي مزمن', 'بطء القلب', 'إحصار القلب', 'قصور قلب غير معاوض'],
    monitoringRequired: ['IOP', 'Heart rate', 'Respiratory status in asthma/COPD patients'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0144', genericName: 'Latanoprost', genericNameAr: 'لاتانوبروست',
    brandNames: ['Xalatan', 'Latanox'], sfda_registration: 'SFDA-2024-LAT-144',
    atcCode: 'S01EE01', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Prostaglandin Analogues', therapeuticClassAr: 'طب العيون - نظائر البروستاغلاندين',
    formularyStatus: 'formulary', route: ['Ophthalmic'],
    forms: [{ form: 'Eye drops', strength: '0.005%', unitPrice: 45.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Latanoprost/Travoprost'],
    interactions: [],
    contraindications: ['Hypersensitivity to benzalkonium chloride'],
    contraindicationsAr: ['حساسية لكلوريد البنزالكونيوم'],
    monitoringRequired: ['IOP', 'Iris color change', 'Eyelash growth'],
    storageConditions: 'Store 2-8°C unopened. Once opened, use within 4 weeks at room temperature.',
  },
  {
    id: 'FRM-0145', genericName: 'Dorzolamide', genericNameAr: 'دورزولاميد',
    brandNames: ['Trusopt'], sfda_registration: 'SFDA-2024-DOR-145',
    atcCode: 'S01EC03', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Carbonic Anhydrase Inhibitors', therapeuticClassAr: 'طب العيون - مثبطات الأنهيدراز الكربوني',
    formularyStatus: 'formulary', route: ['Ophthalmic'],
    forms: [{ form: 'Eye drops', strength: '2%', unitPrice: 30.0, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'Oral carbonic anhydrase inhibitors', severity: 'moderate', mechanism: 'Additive inhibition',
        clinicalEffect: 'Increased side effects', clinicalEffectAr: 'زيادة الآثار الجانبية',
        management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['Sulfonamide allergy', 'Severe renal impairment'],
    contraindicationsAr: ['حساسية السلفوناميد', 'قصور كلوي شديد'],
    monitoringRequired: ['IOP', 'Corneal health'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0146', genericName: 'Brimonidine', genericNameAr: 'بريمونيدين',
    brandNames: ['Alphagan', 'Alphagan P'], sfda_registration: 'SFDA-2024-BRI-146',
    atcCode: 'S01EA05', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Alpha-2 Agonists', therapeuticClassAr: 'طب العيون - ناهضات ألفا-2',
    formularyStatus: 'formulary', route: ['Ophthalmic'],
    forms: [{ form: 'Eye drops', strength: '0.15%', unitPrice: 35.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'MAO inhibitors', severity: 'major', mechanism: 'Enhanced alpha-adrenergic effect',
        clinicalEffect: 'Hypertensive crisis', clinicalEffectAr: 'أزمة ارتفاع ضغط الدم',
        management: 'Contraindicated', managementAr: 'ممنوع الجمع' },
    ],
    contraindications: ['Children <2 years (CNS depression)', 'MAO inhibitor therapy'],
    contraindicationsAr: ['أطفال أقل من سنتين (اكتئاب الجهاز العصبي)', 'علاج مثبطات MAO'],
    monitoringRequired: ['IOP', 'CNS depression in pediatrics'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0147', genericName: 'Pilocarpine', genericNameAr: 'بيلوكاربين',
    brandNames: ['Isopto Carpine', 'Pilocar'], sfda_registration: 'SFDA-2024-PIL-147',
    atcCode: 'S01EB01', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Miotics', therapeuticClassAr: 'طب العيون - مقبضات الحدقة',
    formularyStatus: 'formulary', route: ['Ophthalmic'],
    forms: [{ form: 'Eye drops', strength: '2%', unitPrice: 10.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Acute iritis', 'Conditions with pupillary constriction undesirable'],
    contraindicationsAr: ['التهاب القزحية الحاد', 'حالات يكون فيها تقبض الحدقة غير مرغوب'],
    monitoringRequired: ['IOP', 'Visual acuity'],
    storageConditions: 'Store 2-8°C. Protect from light.',
  },
  {
    id: 'FRM-0148', genericName: 'Tropicamide', genericNameAr: 'تروبيكاميد',
    brandNames: ['Mydriacyl'], sfda_registration: 'SFDA-2024-TRO-148',
    atcCode: 'S01FA06', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Mydriatics', therapeuticClassAr: 'طب العيون - موسعات الحدقة',
    formularyStatus: 'formulary', route: ['Ophthalmic'],
    forms: [{ form: 'Eye drops', strength: '1%', unitPrice: 8.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Narrow-angle glaucoma', 'Adhesions between iris and lens'],
    contraindicationsAr: ['الزرق ضيق الزاوية', 'التصاقات بين القزحية والعدسة'],
    monitoringRequired: ['IOP in glaucoma suspects'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0149', genericName: 'Cyclopentolate', genericNameAr: 'سيكلوبنتولات',
    brandNames: ['Cyclogyl'], sfda_registration: 'SFDA-2024-CYC-149',
    atcCode: 'S01FA04', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Cycloplegics', therapeuticClassAr: 'طب العيون - شالات الهدبية',
    formularyStatus: 'formulary', route: ['Ophthalmic'],
    forms: [{ form: 'Eye drops', strength: '1%', unitPrice: 9.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Cyclopentolate/Cyclosporine'],
    interactions: [],
    contraindications: ['Narrow-angle glaucoma'],
    contraindicationsAr: ['الزرق ضيق الزاوية'],
    monitoringRequired: ['CNS effects in children (feeding intolerance, seizures)'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0150', genericName: 'Prednisolone Acetate Ophthalmic', genericNameAr: 'بريدنيزولون أسيتات عيني',
    brandNames: ['Pred Forte', 'Econopred Plus'], sfda_registration: 'SFDA-2024-PRE-150',
    atcCode: 'S01BA04', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Steroids', therapeuticClassAr: 'طب العيون - ستيرويدات',
    formularyStatus: 'formulary', route: ['Ophthalmic'],
    forms: [{ form: 'Eye drops suspension', strength: '1%', unitPrice: 25.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Viral eye infection (herpes simplex)', 'Fungal eye infection', 'Mycobacterial eye infection'],
    contraindicationsAr: ['عدوى عينية فيروسية', 'عدوى عينية فطرية', 'عدوى عينية بالمتفطرات'],
    monitoringRequired: ['IOP (steroid-induced glaucoma)', 'Lens for cataracts', 'Signs of secondary infection'],
    storageConditions: 'Store 2-8°C. Shake well before use.',
  },
  {
    id: 'FRM-0151', genericName: 'Moxifloxacin Ophthalmic', genericNameAr: 'موكسيفلوكساسين عيني',
    brandNames: ['Vigamox', 'Moxeza'], sfda_registration: 'SFDA-2024-MOX-151',
    atcCode: 'S01AE07', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Fluoroquinolones', therapeuticClassAr: 'طب العيون - فلوروكينولونات',
    formularyStatus: 'formulary', route: ['Ophthalmic'],
    forms: [{ form: 'Eye drops', strength: '0.5%', unitPrice: 28.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [],
    contraindications: ['Fluoroquinolone hypersensitivity'],
    contraindicationsAr: ['فرط حساسية الفلوروكينولونات'],
    monitoringRequired: ['Clinical response', 'Corneal healing'],
    storageConditions: 'Store 2-25°C.',
  },
  {
    id: 'FRM-0152', genericName: 'Ranibizumab', genericNameAr: 'رانيبيزوماب',
    brandNames: ['Lucentis'], sfda_registration: 'SFDA-2024-RAN-152',
    atcCode: 'S01LA04', atcCategory: 'S01 - Ophthalmologicals',
    therapeuticClass: 'Ophthalmology - Anti-VEGF', therapeuticClassAr: 'طب العيون - مضادات VEGF',
    formularyStatus: 'restricted', restrictionCriteria: 'Retinal specialist. For wet AMD, DME, RVO.',
    restrictionCriteriaAr: 'أخصائي شبكية. للتنكس البقعي الرطب، وذمة البقعة السكرية.', approverRole: 'ophthalmologist',
    route: ['Intravitreal'], forms: [{ form: 'Intravitreal injection', strength: '0.5mg/0.05mL', unitPrice: 3500.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Ranibizumab/Bevacizumab'],
    interactions: [],
    contraindications: ['Active ocular/periocular infection', 'Active intraocular inflammation'],
    contraindicationsAr: ['عدوى عينية/حول عينية نشطة', 'التهاب داخل العين نشط'],
    monitoringRequired: ['IOP post-injection', 'Endophthalmitis signs', 'Visual acuity', 'OCT retinal thickness'],
    storageConditions: 'Store 2-8°C. Do not freeze. Protect from light.',
  },
];

// ─── ENT DRUGS (10) ───────────────────────────────────────────────────────────

export const ENT_DRUGS: FormularyDrug[] = [
  {
    id: 'FRM-0153', genericName: 'Oxymetazoline Nasal', genericNameAr: 'أوكسيميتازولين أنفي',
    brandNames: ['Afrin', 'Otrivin Oxy'], sfda_registration: 'SFDA-2024-OXY-153',
    atcCode: 'R01AA05', atcCategory: 'R01 - Nasal preparations',
    therapeuticClass: 'ENT - Nasal Decongestants', therapeuticClassAr: 'أنف أذن حنجرة - مزيلات احتقان الأنف',
    formularyStatus: 'formulary', route: ['Nasal'],
    forms: [{ form: 'Nasal spray', strength: '0.05%', unitPrice: 8.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'MAO inhibitors', severity: 'major', mechanism: 'Enhanced sympathomimetic effect',
        clinicalEffect: 'Hypertensive crisis', clinicalEffectAr: 'أزمة ارتفاع ضغط الدم',
        management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['Use >3 days (rhinitis medicamentosa)', 'MAO inhibitor therapy'],
    contraindicationsAr: ['الاستخدام أكثر من 3 أيام (التهاب أنف دوائي)', 'علاج مثبطات MAO'],
    monitoringRequired: ['Duration of use (max 3 days)'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0154', genericName: 'Fluticasone Furoate Nasal', genericNameAr: 'فلوتيكازون فيوروات أنفي',
    brandNames: ['Avamys', 'Flonase Sensimist'], sfda_registration: 'SFDA-2024-FLU-154',
    atcCode: 'R01AD12', atcCategory: 'R01 - Nasal preparations',
    therapeuticClass: 'ENT - Intranasal Steroids', therapeuticClassAr: 'أنف أذن حنجرة - ستيرويدات أنفية',
    formularyStatus: 'formulary', route: ['Nasal'],
    forms: [{ form: 'Nasal spray', strength: '27.5mcg/spray', unitPrice: 35.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Fluticasone/Fluticasone propionate'],
    interactions: [
      { interactsWith: 'Ritonavir', severity: 'major', mechanism: 'CYP3A4 inhibition increases systemic steroid levels',
        clinicalEffect: 'Cushing syndrome', clinicalEffectAr: 'متلازمة كوشينغ',
        management: 'Avoid combination or use alternative steroid', managementAr: 'تجنب الجمع أو استخدام ستيرويد بديل' },
    ],
    contraindications: ['Active nasal infection untreated', 'Recent nasal surgery/trauma'],
    contraindicationsAr: ['عدوى أنفية نشطة غير معالجة', 'جراحة أو إصابة أنفية حديثة'],
    monitoringRequired: ['Growth velocity in children', 'Nasal septum examination'],
    storageConditions: 'Store below 30°C.',
  },
  {
    id: 'FRM-0155', genericName: 'Mometasone Nasal', genericNameAr: 'موميتازون أنفي',
    brandNames: ['Nasonex'], sfda_registration: 'SFDA-2024-MOM-155',
    atcCode: 'R01AD09', atcCategory: 'R01 - Nasal preparations',
    therapeuticClass: 'ENT - Intranasal Steroids', therapeuticClassAr: 'أنف أذن حنجرة - ستيرويدات أنفية',
    formularyStatus: 'formulary', route: ['Nasal'],
    forms: [{ form: 'Nasal spray', strength: '50mcg/spray', unitPrice: 32.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Mometasone nasal/Mometasone topical'],
    interactions: [], contraindications: ['Untreated nasal infections'],
    contraindicationsAr: ['عدوى أنفية غير معالجة'],
    monitoringRequired: ['Growth in pediatric patients', 'Nasal mucosa'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0156', genericName: 'Azelastine Nasal', genericNameAr: 'أزيلاستين أنفي',
    brandNames: ['Astelin', 'Astepro'], sfda_registration: 'SFDA-2024-AZE-156',
    atcCode: 'R01AC03', atcCategory: 'R01 - Nasal preparations',
    therapeuticClass: 'ENT - Antihistamines Nasal', therapeuticClassAr: 'أنف أذن حنجرة - مضادات هيستامين أنفية',
    formularyStatus: 'formulary', route: ['Nasal'],
    forms: [{ form: 'Nasal spray', strength: '137mcg/spray', unitPrice: 28.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'CNS depressants', severity: 'moderate', mechanism: 'Additive sedation',
        clinicalEffect: 'Excessive drowsiness', clinicalEffectAr: 'نعاس مفرط',
        management: 'Warn about drowsiness', managementAr: 'تحذير من النعاس' },
    ],
    contraindications: ['Hypersensitivity'],
    contraindicationsAr: ['فرط حساسية'],
    monitoringRequired: ['Drowsiness assessment'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0157', genericName: 'Ciprofloxacin/Dexamethasone Otic', genericNameAr: 'سيبروفلوكساسين/ديكساميثازون أذني',
    brandNames: ['Ciprodex'], sfda_registration: 'SFDA-2024-CIP-157',
    atcCode: 'S02CA05', atcCategory: 'S02 - Otologicals',
    therapeuticClass: 'ENT - Otic Antibiotics', therapeuticClassAr: 'أنف أذن حنجرة - مضادات حيوية أذنية',
    formularyStatus: 'formulary', route: ['Otic'],
    forms: [{ form: 'Ear drops', strength: '0.3%/0.1%', unitPrice: 38.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [], contraindications: ['Viral otic infections', 'Perforated tympanic membrane (relative)'],
    contraindicationsAr: ['عدوى أذنية فيروسية', 'ثقب طبلة الأذن (نسبي)'],
    monitoringRequired: ['Clinical response after 7 days'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0158', genericName: 'Carbamide Peroxide Otic', genericNameAr: 'بيروكسيد كارباميد أذني',
    brandNames: ['Debrox', 'Murine Ear'], sfda_registration: 'SFDA-2024-CBP-158',
    atcCode: 'S02AA', atcCategory: 'S02 - Otologicals',
    therapeuticClass: 'ENT - Cerumenolytics', therapeuticClassAr: 'أنف أذن حنجرة - مذيبات شمع الأذن',
    formularyStatus: 'formulary', route: ['Otic'],
    forms: [{ form: 'Ear drops', strength: '6.5%', unitPrice: 12.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [], contraindications: ['Perforated eardrum', 'Ear drainage', 'Ear pain/infection'],
    contraindicationsAr: ['ثقب طبلة الأذن', 'إفراز أذني', 'ألم أو عدوى الأذن'],
    monitoringRequired: ['Follow up if no improvement in 4 days'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0159', genericName: 'Montelukast', genericNameAr: 'مونتيلوكاست',
    brandNames: ['Singulair', 'Montelair'], sfda_registration: 'SFDA-2024-MON-159',
    atcCode: 'R03DC03', atcCategory: 'R03 - Drugs for obstructive airway diseases',
    therapeuticClass: 'ENT - Leukotriene Receptor Antagonists', therapeuticClassAr: 'أنف أذن حنجرة - مضادات مستقبلات الليكوترين',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [
      { form: 'Tablet', strength: '10mg', unitPrice: 6.0, inStock: true },
      { form: 'Chewable tablet', strength: '5mg', unitPrice: 5.5, inStock: true },
      { form: 'Granules', strength: '4mg', unitPrice: 5.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Neuropsychiatric events including agitation, aggression, depression, suicidal thinking reported.',
    blackBoxWarningAr: 'أحداث نفسية عصبية بما في ذلك الهياج والعدوان والاكتئاب والأفكار الانتحارية.',
    interactions: [
      { interactsWith: 'Phenobarbital', severity: 'moderate', mechanism: 'CYP3A4 induction decreases montelukast levels',
        clinicalEffect: 'Reduced efficacy', clinicalEffectAr: 'انخفاض الفعالية',
        management: 'Monitor clinical response', managementAr: 'مراقبة الاستجابة السريرية' },
    ],
    contraindications: ['Hypersensitivity', 'Phenylketonuria (chewable contains aspartame)'],
    contraindicationsAr: ['فرط حساسية', 'بيلة فينيل كيتون (القابلة للمضغ تحتوي أسبارتام)'],
    monitoringRequired: ['Neuropsychiatric symptoms', 'Eosinophilia (Churg-Strauss)'],
    storageConditions: 'Store below 25°C, protect from light and moisture.',
  },
  {
    id: 'FRM-0160', genericName: 'Desloratadine', genericNameAr: 'ديسلوراتادين',
    brandNames: ['Aerius', 'Clarinex'], sfda_registration: 'SFDA-2024-DES-160',
    atcCode: 'R06AX27', atcCategory: 'R06 - Antihistamines for systemic use',
    therapeuticClass: 'ENT - Antihistamines', therapeuticClassAr: 'أنف أذن حنجرة - مضادات الهيستامين',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [
      { form: 'Tablet', strength: '5mg', unitPrice: 4.0, inStock: true },
      { form: 'Syrup', strength: '0.5mg/mL', unitPrice: 15.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Desloratadine/Loratadine'],
    interactions: [], contraindications: ['Hypersensitivity to desloratadine or loratadine'],
    contraindicationsAr: ['فرط حساسية للديسلوراتادين أو اللوراتادين'],
    monitoringRequired: ['Clinical response'],
    storageConditions: 'Store below 30°C.',
  },
  {
    id: 'FRM-0161', genericName: 'Cetirizine', genericNameAr: 'سيتيريزين',
    brandNames: ['Zyrtec', 'Alerid'], sfda_registration: 'SFDA-2024-CET-161',
    atcCode: 'R06AE07', atcCategory: 'R06 - Antihistamines for systemic use',
    therapeuticClass: 'ENT - Antihistamines', therapeuticClassAr: 'أنف أذن حنجرة - مضادات الهيستامين',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [
      { form: 'Tablet', strength: '10mg', unitPrice: 2.5, inStock: true },
      { form: 'Syrup', strength: '5mg/5mL', unitPrice: 10.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Cetirizine/Sertraline'],
    interactions: [], contraindications: ['Severe renal impairment without dose adjustment', 'Hydroxyzine hypersensitivity'],
    contraindicationsAr: ['قصور كلوي شديد بدون تعديل الجرعة', 'فرط حساسية الهيدروكسيزين'],
    monitoringRequired: ['Drowsiness', 'Renal function in elderly'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0162', genericName: 'Fexofenadine', genericNameAr: 'فيكسوفينادين',
    brandNames: ['Telfast', 'Allegra'], sfda_registration: 'SFDA-2024-FEX-162',
    atcCode: 'R06AX26', atcCategory: 'R06 - Antihistamines for systemic use',
    therapeuticClass: 'ENT - Antihistamines', therapeuticClassAr: 'أنف أذن حنجرة - مضادات الهيستامين',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [
      { form: 'Tablet', strength: '120mg', unitPrice: 3.5, inStock: true },
      { form: 'Tablet', strength: '180mg', unitPrice: 4.5, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Fexofenadine/Terfenadine'],
    interactions: [], contraindications: ['Hypersensitivity'],
    contraindicationsAr: ['فرط حساسية'],
    monitoringRequired: ['Clinical response'],
    storageConditions: 'Store below 25°C.',
  },
];

// ─── UROLOGY (10) ─────────────────────────────────────────────────────────────

export const UROLOGY: FormularyDrug[] = [
  {
    id: 'FRM-0163', genericName: 'Tamsulosin', genericNameAr: 'تامسولوسين',
    brandNames: ['Flomax', 'Omnic'], sfda_registration: 'SFDA-2024-TAM-163',
    atcCode: 'G04CA02', atcCategory: 'G04 - Urologicals',
    therapeuticClass: 'Urology - Alpha-Blockers', therapeuticClassAr: 'المسالك البولية - حاصرات ألفا',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Capsule MR', strength: '0.4mg', unitPrice: 4.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Tamsulosin/Terazosin'],
    interactions: [
      { interactsWith: 'CYP3A4 inhibitors', severity: 'moderate', mechanism: 'Increased tamsulosin levels',
        clinicalEffect: 'Hypotension and dizziness', clinicalEffectAr: 'انخفاض ضغط الدم والدوار',
        management: 'Use with caution, monitor BP', managementAr: 'استخدام بحذر ومراقبة الضغط' },
    ],
    contraindications: ['Orthostatic hypotension history', 'Severe hepatic impairment'],
    contraindicationsAr: ['تاريخ انخفاض ضغط وضعي', 'قصور كبدي شديد'],
    monitoringRequired: ['Blood pressure', 'Intraoperative floppy iris syndrome warning for cataract surgery'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0164', genericName: 'Alfuzosin', genericNameAr: 'ألفوزوسين',
    brandNames: ['Xatral', 'Uroxatral'], sfda_registration: 'SFDA-2024-ALF-164',
    atcCode: 'G04CA01', atcCategory: 'G04 - Urologicals',
    therapeuticClass: 'Urology - Alpha-Blockers', therapeuticClassAr: 'المسالك البولية - حاصرات ألفا',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet XL', strength: '10mg', unitPrice: 5.0, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'PDE5 inhibitors', severity: 'moderate', mechanism: 'Additive hypotension',
        clinicalEffect: 'Postural hypotension', clinicalEffectAr: 'انخفاض ضغط وضعي',
        management: 'Stable alpha-blocker dose before adding PDE5i', managementAr: 'جرعة مستقرة من حاصر ألفا قبل إضافة مثبط PDE5' },
    ],
    contraindications: ['Hepatic insufficiency', 'Concomitant CYP3A4 inhibitors', 'QT prolongation'],
    contraindicationsAr: ['قصور كبدي', 'مثبطات CYP3A4 المتزامنة', 'إطالة QT'],
    monitoringRequired: ['Blood pressure', 'QT interval if risk factors'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0165', genericName: 'Finasteride', genericNameAr: 'فيناسترايد',
    brandNames: ['Proscar', 'Propecia'], sfda_registration: 'SFDA-2024-FIN-165',
    atcCode: 'G04CB01', atcCategory: 'G04 - Urologicals',
    therapeuticClass: 'Urology - 5-Alpha Reductase Inhibitors', therapeuticClassAr: 'المسالك البولية - مثبطات 5-ألفا ريدكتيز',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [
      { form: 'Tablet', strength: '5mg', unitPrice: 3.0, inStock: true },
      { form: 'Tablet', strength: '1mg', unitPrice: 5.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Finasteride/Dutasteride'],
    interactions: [],
    contraindications: ['Women of childbearing potential (teratogenic)', 'Pregnancy', 'Children'],
    contraindicationsAr: ['نساء في سن الإنجاب (ماسخ)', 'الحمل', 'الأطفال'],
    monitoringRequired: ['PSA (halves PSA levels - double result for screening)', 'Sexual function'],
    storageConditions: 'Store below 25°C. Women must not handle crushed tablets.',
  },
  {
    id: 'FRM-0166', genericName: 'Dutasteride', genericNameAr: 'دوتاسترايد',
    brandNames: ['Avodart'], sfda_registration: 'SFDA-2024-DUT-166',
    atcCode: 'G04CB02', atcCategory: 'G04 - Urologicals',
    therapeuticClass: 'Urology - 5-Alpha Reductase Inhibitors', therapeuticClassAr: 'المسالك البولية - مثبطات 5-ألفا ريدكتيز',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Capsule', strength: '0.5mg', unitPrice: 6.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'X', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Dutasteride/Finasteride'],
    interactions: [
      { interactsWith: 'CYP3A4 inhibitors', severity: 'moderate', mechanism: 'Increased dutasteride levels',
        clinicalEffect: 'Enhanced side effects', clinicalEffectAr: 'تعزيز الآثار الجانبية',
        management: 'Monitor for sexual side effects', managementAr: 'مراقبة الآثار الجانبية الجنسية' },
    ],
    contraindications: ['Women', 'Children', 'Severe hepatic impairment'],
    contraindicationsAr: ['النساء', 'الأطفال', 'قصور كبدي شديد'],
    monitoringRequired: ['PSA', 'Liver function'],
    storageConditions: 'Store below 25°C. Do not handle leaking capsules (absorption through skin).',
  },
  {
    id: 'FRM-0167', genericName: 'Solifenacin', genericNameAr: 'سوليفيناسين',
    brandNames: ['Vesicare'], sfda_registration: 'SFDA-2024-SOL-167',
    atcCode: 'G04BD08', atcCategory: 'G04 - Urologicals',
    therapeuticClass: 'Urology - Antimuscarinics', therapeuticClassAr: 'المسالك البولية - مضادات الموسكارين',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet', strength: '5mg', unitPrice: 7.0, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'CYP3A4 inhibitors', severity: 'moderate', mechanism: 'Increased solifenacin levels',
        clinicalEffect: 'Enhanced anticholinergic effects', clinicalEffectAr: 'تعزيز التأثيرات المضادة للكولين',
        management: 'Max 5mg/day with CYP3A4 inhibitors', managementAr: 'حد أقصى 5 ملغ/يوم مع مثبطات CYP3A4' },
    ],
    contraindications: ['Urinary retention', 'Gastric retention', 'Uncontrolled narrow-angle glaucoma', 'Severe hepatic impairment'],
    contraindicationsAr: ['احتباس بولي', 'احتباس معدي', 'زرق ضيق الزاوية غير مسيطر', 'قصور كبدي شديد'],
    monitoringRequired: ['Post-void residual', 'Cognitive function in elderly', 'IOP in glaucoma patients'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0168', genericName: 'Mirabegron', genericNameAr: 'ميرابيغرون',
    brandNames: ['Betmiga', 'Myrbetriq'], sfda_registration: 'SFDA-2024-MIR-168',
    atcCode: 'G04BD12', atcCategory: 'G04 - Urologicals',
    therapeuticClass: 'Urology - Beta-3 Agonists', therapeuticClassAr: 'المسالك البولية - ناهضات بيتا-3',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet MR', strength: '50mg', unitPrice: 12.0, inStock: true }],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'Digoxin', severity: 'moderate', mechanism: 'Increased digoxin levels',
        clinicalEffect: 'Digoxin toxicity', clinicalEffectAr: 'تسمم الديجوكسين',
        management: 'Use lowest digoxin dose, monitor levels', managementAr: 'استخدام أقل جرعة ديجوكسين ومراقبة المستويات' },
    ],
    contraindications: ['Severe uncontrolled hypertension', 'Severe renal impairment', 'Severe hepatic impairment'],
    contraindicationsAr: ['ارتفاع ضغط دم شديد غير مسيطر', 'قصور كلوي شديد', 'قصور كبدي شديد'],
    monitoringRequired: ['Blood pressure', 'Urinary retention', 'UTI symptoms'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0169', genericName: 'Oxybutynin', genericNameAr: 'أوكسيبوتينين',
    brandNames: ['Ditropan', 'Lyrinel'], sfda_registration: 'SFDA-2024-OXB-169',
    atcCode: 'G04BD04', atcCategory: 'G04 - Urologicals',
    therapeuticClass: 'Urology - Antimuscarinics', therapeuticClassAr: 'المسالك البولية - مضادات الموسكارين',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet', strength: '5mg', unitPrice: 3.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Oxybutynin/Oxycodone'],
    interactions: [
      { interactsWith: 'Anticholinergics', severity: 'moderate', mechanism: 'Additive anticholinergic effects',
        clinicalEffect: 'Cognitive impairment, urinary retention, constipation', clinicalEffectAr: 'ضعف إدراكي، احتباس بولي، إمساك',
        management: 'Avoid combining multiple anticholinergics in elderly', managementAr: 'تجنب جمع مضادات كولين متعددة في المسنين' },
    ],
    contraindications: ['Urinary retention', 'Gastric retention', 'Uncontrolled glaucoma', 'Myasthenia gravis'],
    contraindicationsAr: ['احتباس بولي', 'احتباس معدي', 'زرق غير مسيطر', 'الوهن العضلي الوبيل'],
    monitoringRequired: ['Cognitive function', 'Post-void residual', 'Anticholinergic burden'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0170', genericName: 'Sildenafil', genericNameAr: 'سيلدينافيل',
    brandNames: ['Viagra', 'Revatio'], sfda_registration: 'SFDA-2024-SIL-170',
    atcCode: 'G04BE03', atcCategory: 'G04 - Urologicals',
    therapeuticClass: 'Urology - PDE5 Inhibitors', therapeuticClassAr: 'المسالك البولية - مثبطات PDE5',
    formularyStatus: 'conditional', restrictionCriteria: 'Prescription only. Requires cardiovascular screening.',
    restrictionCriteriaAr: 'بوصفة طبية فقط. يتطلب فحص القلب والأوعية الدموية.', approverRole: 'urologist',
    route: ['Oral'], forms: [
      { form: 'Tablet', strength: '25mg', unitPrice: 15.0, inStock: true },
      { form: 'Tablet', strength: '50mg', unitPrice: 20.0, inStock: true },
      { form: 'Tablet', strength: '100mg', unitPrice: 25.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Sildenafil/Tadalafil'],
    interactions: [
      { interactsWith: 'Nitrates', severity: 'major', mechanism: 'Synergistic hypotension',
        clinicalEffect: 'Potentially fatal hypotension', clinicalEffectAr: 'انخفاض ضغط دم قد يكون مميتاً',
        management: 'CONTRAINDICATED. Do not use within 24h of nitrates.', managementAr: 'ممنوع. عدم الاستخدام خلال 24 ساعة من النيترات.' },
    ],
    contraindications: ['Nitrate therapy', 'Severe cardiovascular disease', 'Recent MI/stroke', 'Hereditary retinal disorders'],
    contraindicationsAr: ['علاج النيترات', 'مرض قلبي وعائي شديد', 'احتشاء عضلة القلب/سكتة حديثة', 'اضطرابات شبكية وراثية'],
    monitoringRequired: ['Blood pressure', 'Cardiovascular status', 'Vision changes'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0171', genericName: 'Tadalafil', genericNameAr: 'تادالافيل',
    brandNames: ['Cialis', 'Adcirca'], sfda_registration: 'SFDA-2024-TAD-171',
    atcCode: 'G04BE08', atcCategory: 'G04 - Urologicals',
    therapeuticClass: 'Urology - PDE5 Inhibitors', therapeuticClassAr: 'المسالك البولية - مثبطات PDE5',
    formularyStatus: 'conditional', restrictionCriteria: 'Prescription only.',
    restrictionCriteriaAr: 'بوصفة طبية فقط.', approverRole: 'urologist',
    route: ['Oral'], forms: [
      { form: 'Tablet', strength: '5mg', unitPrice: 10.0, inStock: true },
      { form: 'Tablet', strength: '20mg', unitPrice: 22.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Tadalafil/Sildenafil'],
    interactions: [
      { interactsWith: 'Nitrates', severity: 'major', mechanism: 'Synergistic hypotension',
        clinicalEffect: 'Severe hypotension', clinicalEffectAr: 'انخفاض ضغط دم شديد',
        management: 'CONTRAINDICATED. Do not use within 48h of nitrates (long half-life).', managementAr: 'ممنوع. عدم الاستخدام خلال 48 ساعة من النيترات.' },
    ],
    contraindications: ['Nitrate therapy', 'Severe hepatic impairment', 'Recent stroke'],
    contraindicationsAr: ['علاج النيترات', 'قصور كبدي شديد', 'سكتة دماغية حديثة'],
    monitoringRequired: ['Blood pressure', 'Cardiovascular status'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0172', genericName: 'Desmopressin', genericNameAr: 'ديسموبريسين',
    brandNames: ['Minirin', 'DDAVP'], sfda_registration: 'SFDA-2024-DES-172',
    atcCode: 'H01BA02', atcCategory: 'H01 - Pituitary and hypothalamic hormones',
    therapeuticClass: 'Urology - ADH Analogues', therapeuticClassAr: 'المسالك البولية - نظائر الهرمون المضاد لإدرار البول',
    formularyStatus: 'formulary', route: ['Oral', 'Intranasal', 'Subcutaneous'],
    forms: [
      { form: 'Tablet', strength: '0.2mg', unitPrice: 8.0, inStock: true },
      { form: 'Nasal spray', strength: '10mcg/spray', unitPrice: 85.0, inStock: true },
    ],
    renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Desmopressin/Vasopressin'],
    interactions: [
      { interactsWith: 'NSAIDs', severity: 'moderate', mechanism: 'Enhanced water retention',
        clinicalEffect: 'Hyponatremia', clinicalEffectAr: 'نقص صوديوم الدم',
        management: 'Monitor sodium levels', managementAr: 'مراقبة مستويات الصوديوم' },
    ],
    contraindications: ['Habitual polydipsia', 'Cardiac insufficiency requiring diuretics', 'Hyponatremia'],
    contraindicationsAr: ['عطاش معتاد', 'قصور قلبي يتطلب مدرات', 'نقص صوديوم الدم'],
    monitoringRequired: ['Sodium levels (especially first week)', 'Fluid intake', 'Body weight'],
    storageConditions: 'Store 2-8°C.',
  },
];

// ─── ENDOCRINE (10) ───────────────────────────────────────────────────────────

export const ENDOCRINE: FormularyDrug[] = [
  {
    id: 'FRM-0173', genericName: 'Methimazole', genericNameAr: 'ميثيمازول',
    brandNames: ['Tapazole'], sfda_registration: 'SFDA-2024-MET-173',
    atcCode: 'H03BB02', atcCategory: 'H03 - Thyroid therapy',
    therapeuticClass: 'Endocrine - Antithyroid', therapeuticClassAr: 'الغدد الصماء - مضادات الدرقية',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet', strength: '5mg', unitPrice: 2.5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Methimazole/Metolazone'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Thyroid status affects warfarin metabolism',
        clinicalEffect: 'INR changes as euthyroid achieved', clinicalEffectAr: 'تغيرات INR عند تحقيق سواء الدرقية',
        management: 'Monitor INR frequently during dose adjustment', managementAr: 'مراقبة INR بشكل متكرر أثناء تعديل الجرعة' },
    ],
    contraindications: ['Hypersensitivity', 'First trimester pregnancy (use PTU instead)'],
    contraindicationsAr: ['فرط حساسية', 'الثلث الأول من الحمل (استخدم PTU بدلاً)'],
    monitoringRequired: ['TFTs every 4-6 weeks initially', 'CBC (agranulocytosis risk)', 'LFTs'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0174', genericName: 'Propylthiouracil', genericNameAr: 'بروبيل ثيويوراسيل',
    brandNames: ['PTU'], sfda_registration: 'SFDA-2024-PTU-174',
    atcCode: 'H03BA02', atcCategory: 'H03 - Thyroid therapy',
    therapeuticClass: 'Endocrine - Antithyroid', therapeuticClassAr: 'الغدد الصماء - مضادات الدرقية',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet', strength: '50mg', unitPrice: 2.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: [],
    blackBoxWarning: 'Severe liver injury and acute liver failure reported. Reserve for first trimester pregnancy or methimazole intolerance.',
    blackBoxWarningAr: 'إصابة كبدية شديدة وفشل كبدي حاد. يُحفظ للثلث الأول من الحمل أو عدم تحمل الميثيمازول.',
    interactions: [
      { interactsWith: 'Anticoagulants', severity: 'moderate', mechanism: 'Hepatotoxicity may alter coagulation',
        clinicalEffect: 'Bleeding risk', clinicalEffectAr: 'خطر النزيف',
        management: 'Monitor coagulation parameters', managementAr: 'مراقبة معاملات التخثر' },
    ],
    contraindications: ['Hypersensitivity', 'Liver disease'],
    contraindicationsAr: ['فرط حساسية', 'مرض كبدي'],
    monitoringRequired: ['LFTs at baseline and regularly', 'CBC', 'TFTs every 4-6 weeks'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0175', genericName: 'Cabergoline', genericNameAr: 'كابيرغولين',
    brandNames: ['Dostinex'], sfda_registration: 'SFDA-2024-CAB-175',
    atcCode: 'G02CB03', atcCategory: 'G02 - Other gynecologicals',
    therapeuticClass: 'Endocrine - Dopamine Agonists', therapeuticClassAr: 'الغدد الصماء - ناهضات الدوبامين',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet', strength: '0.5mg', unitPrice: 45.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Cabergoline/Bromocriptine'],
    interactions: [
      { interactsWith: 'Dopamine antagonists', severity: 'major', mechanism: 'Opposing mechanisms',
        clinicalEffect: 'Reduced efficacy of both drugs', clinicalEffectAr: 'انخفاض فعالية كلا الدواءين',
        management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['Uncontrolled hypertension', 'Cardiac valvular disease', 'Pulmonary fibrosis history'],
    contraindicationsAr: ['ارتفاع ضغط غير مسيطر', 'مرض صمامات القلب', 'تاريخ تليف رئوي'],
    monitoringRequired: ['Prolactin levels', 'Echocardiogram if long-term use', 'Blood pressure'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0176', genericName: 'Bromocriptine', genericNameAr: 'بروموكريبتين',
    brandNames: ['Parlodel'], sfda_registration: 'SFDA-2024-BRO-176',
    atcCode: 'G02CB01', atcCategory: 'G02 - Other gynecologicals',
    therapeuticClass: 'Endocrine - Dopamine Agonists', therapeuticClassAr: 'الغدد الصماء - ناهضات الدوبامين',
    formularyStatus: 'formulary', route: ['Oral'],
    forms: [{ form: 'Tablet', strength: '2.5mg', unitPrice: 8.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Bromocriptine/Cabergoline'],
    interactions: [
      { interactsWith: 'Ergot alkaloids', severity: 'major', mechanism: 'Additive vasospasm',
        clinicalEffect: 'Peripheral ischemia', clinicalEffectAr: 'نقص تروية طرفي',
        management: 'Contraindicated', managementAr: 'ممنوع الجمع' },
    ],
    contraindications: ['Uncontrolled hypertension', 'Pregnancy-induced hypertension', 'Coronary artery disease'],
    contraindicationsAr: ['ارتفاع ضغط غير مسيطر', 'ارتفاع ضغط الحمل', 'مرض الشريان التاجي'],
    monitoringRequired: ['Blood pressure', 'Prolactin', 'Pregnancy test'],
    storageConditions: 'Store below 25°C, protect from light.',
  },
  {
    id: 'FRM-0177', genericName: 'Somatropin', genericNameAr: 'سوماتروبين',
    brandNames: ['Genotropin', 'Norditropin', 'Humatrope'], sfda_registration: 'SFDA-2024-SOM-177',
    atcCode: 'H01AC01', atcCategory: 'H01 - Pituitary and hypothalamic hormones',
    therapeuticClass: 'Endocrine - Growth Hormone', therapeuticClassAr: 'الغدد الصماء - هرمون النمو',
    formularyStatus: 'restricted', restrictionCriteria: 'Pediatric endocrinologist. Documented GH deficiency required.',
    restrictionCriteriaAr: 'أخصائي غدد صماء أطفال. يتطلب توثيق نقص هرمون النمو.', approverRole: 'endocrinologist',
    route: ['Subcutaneous'], forms: [{ form: 'Injection pen', strength: '5.3mg/mL', unitPrice: 850.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'Glucocorticoids', severity: 'moderate', mechanism: 'Glucocorticoids inhibit GH effects',
        clinicalEffect: 'Reduced growth response', clinicalEffectAr: 'انخفاض استجابة النمو',
        management: 'Minimize glucocorticoid dose', managementAr: 'تقليل جرعة الغلوكوكورتيكويد' },
    ],
    contraindications: ['Active malignancy', 'Acute critical illness', 'Closed epiphyses (for growth)', 'Active diabetic retinopathy'],
    contraindicationsAr: ['ورم خبيث نشط', 'مرض حاد حرج', 'انغلاق المشاشات (للنمو)', 'اعتلال شبكية سكري نشط'],
    monitoringRequired: ['IGF-1 levels', 'Growth velocity', 'Glucose/HbA1c', 'Thyroid function', 'Scoliosis'],
    storageConditions: 'Store 2-8°C. Do not freeze.',
  },
  {
    id: 'FRM-0178', genericName: 'Octreotide', genericNameAr: 'أوكتريوتيد',
    brandNames: ['Sandostatin', 'Sandostatin LAR'], sfda_registration: 'SFDA-2024-OCT-178',
    atcCode: 'H01CB02', atcCategory: 'H01 - Pituitary and hypothalamic hormones',
    therapeuticClass: 'Endocrine - Somatostatin Analogues', therapeuticClassAr: 'الغدد الصماء - نظائر السوماتوستاتين',
    formularyStatus: 'restricted', restrictionCriteria: 'Endocrinologist or GI specialist. For acromegaly, carcinoid, VIPomas.',
    restrictionCriteriaAr: 'أخصائي غدد أو جهاز هضمي. للأكروميجالي، الكارسينويد.', approverRole: 'endocrinologist',
    route: ['Subcutaneous', 'Intramuscular'], forms: [
      { form: 'Injection', strength: '100mcg/mL', unitPrice: 35.0, inStock: true },
      { form: 'LAR injection', strength: '20mg', unitPrice: 4500.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Octreotide/Lanreotide'],
    interactions: [
      { interactsWith: 'Cyclosporine', severity: 'moderate', mechanism: 'Decreased cyclosporine absorption',
        clinicalEffect: 'Transplant rejection risk', clinicalEffectAr: 'خطر رفض الزرع',
        management: 'Monitor cyclosporine levels', managementAr: 'مراقبة مستويات السيكلوسبورين' },
    ],
    contraindications: ['Hypersensitivity'],
    contraindicationsAr: ['فرط حساسية'],
    monitoringRequired: ['GH/IGF-1 levels', 'Thyroid function', 'Glucose', 'Gallbladder ultrasound', 'Vitamin B12 (long-term)'],
    storageConditions: 'Store 2-8°C. LAR: allow to reach room temperature before injection.',
  },
  {
    id: 'FRM-0179', genericName: 'Cinacalcet', genericNameAr: 'سيناكالسيت',
    brandNames: ['Mimpara', 'Sensipar'], sfda_registration: 'SFDA-2024-CIN-179',
    atcCode: 'H05BX01', atcCategory: 'H05 - Calcium homeostasis',
    therapeuticClass: 'Endocrine - Calcimimetics', therapeuticClassAr: 'الغدد الصماء - محاكيات الكالسيوم',
    formularyStatus: 'restricted', restrictionCriteria: 'Nephrologist or endocrinologist for secondary hyperparathyroidism on dialysis.',
    restrictionCriteriaAr: 'أخصائي كلى أو غدد صماء لفرط جارات الدرقية الثانوي على الغسيل.', approverRole: 'nephrologist',
    route: ['Oral'], forms: [{ form: 'Tablet', strength: '30mg', unitPrice: 25.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: [],
    interactions: [
      { interactsWith: 'Strong CYP3A4 inhibitors', severity: 'moderate', mechanism: 'Increased cinacalcet levels',
        clinicalEffect: 'Hypocalcemia', clinicalEffectAr: 'نقص كالسيوم الدم',
        management: 'Monitor calcium closely', managementAr: 'مراقبة الكالسيوم عن كثب' },
    ],
    contraindications: ['Hypocalcemia', 'Serum calcium <8.4mg/dL'],
    contraindicationsAr: ['نقص كالسيوم الدم', 'كالسيوم المصل أقل من 8.4'],
    monitoringRequired: ['Calcium within 1 week of dose change', 'PTH', 'Phosphorus'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0180', genericName: 'Calcitriol', genericNameAr: 'كالسيتريول',
    brandNames: ['Rocaltrol', 'Calcijex'], sfda_registration: 'SFDA-2024-CLT-180',
    atcCode: 'A11CC04', atcCategory: 'A11 - Vitamins',
    therapeuticClass: 'Endocrine - Vitamin D Active', therapeuticClassAr: 'الغدد الصماء - فيتامين د النشط',
    formularyStatus: 'formulary', route: ['Oral', 'Intravenous'],
    forms: [
      { form: 'Capsule', strength: '0.25mcg', unitPrice: 4.0, inStock: true },
      { form: 'Injection', strength: '1mcg/mL', unitPrice: 25.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Calcitriol/Calcipotriol/Calcifediol'],
    interactions: [
      { interactsWith: 'Thiazide diuretics', severity: 'moderate', mechanism: 'Reduced calcium excretion',
        clinicalEffect: 'Hypercalcemia', clinicalEffectAr: 'فرط كالسيوم الدم',
        management: 'Monitor calcium levels', managementAr: 'مراقبة مستويات الكالسيوم' },
    ],
    contraindications: ['Hypercalcemia', 'Vitamin D toxicity', 'Hyperphosphatemia'],
    contraindicationsAr: ['فرط كالسيوم الدم', 'سمية فيتامين د', 'فرط فوسفات الدم'],
    monitoringRequired: ['Calcium every 2 weeks initially then monthly', 'Phosphorus', 'PTH', '24h urine calcium'],
    storageConditions: 'Store below 25°C, protect from light.',
  },
  {
    id: 'FRM-0181', genericName: 'Paricalcitol', genericNameAr: 'باريكالسيتول',
    brandNames: ['Zemplar'], sfda_registration: 'SFDA-2024-PAR-181',
    atcCode: 'H05BX02', atcCategory: 'H05 - Calcium homeostasis',
    therapeuticClass: 'Endocrine - Vitamin D Analogues', therapeuticClassAr: 'الغدد الصماء - نظائر فيتامين د',
    formularyStatus: 'restricted', restrictionCriteria: 'Nephrologist. For secondary hyperparathyroidism in CKD.',
    restrictionCriteriaAr: 'أخصائي كلى. لفرط جارات الدرقية الثانوي في مرض الكلى المزمن.', approverRole: 'nephrologist',
    route: ['Oral', 'Intravenous'], forms: [
      { form: 'Capsule', strength: '1mcg', unitPrice: 12.0, inStock: true },
      { form: 'Injection', strength: '5mcg/mL', unitPrice: 45.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Paricalcitol/Calcitriol'],
    interactions: [
      { interactsWith: 'Ketoconazole', severity: 'moderate', mechanism: 'CYP3A4 inhibition increases paricalcitol',
        clinicalEffect: 'Hypercalcemia', clinicalEffectAr: 'فرط كالسيوم الدم',
        management: 'Monitor calcium', managementAr: 'مراقبة الكالسيوم' },
    ],
    contraindications: ['Hypercalcemia', 'Vitamin D toxicity'],
    contraindicationsAr: ['فرط كالسيوم الدم', 'سمية فيتامين د'],
    monitoringRequired: ['Calcium', 'Phosphorus', 'PTH', 'Ca x P product'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: 'FRM-0182', genericName: 'Hydrocortisone', genericNameAr: 'هيدروكورتيزون',
    brandNames: ['Cortef', 'Solu-Cortef'], sfda_registration: 'SFDA-2024-HYD-182',
    atcCode: 'H02AB09', atcCategory: 'H02 - Corticosteroids for systemic use',
    therapeuticClass: 'Endocrine - Adrenal Replacement', therapeuticClassAr: 'الغدد الصماء - بديل كظري',
    formularyStatus: 'formulary', route: ['Oral', 'Intravenous', 'Intramuscular'],
    forms: [
      { form: 'Tablet', strength: '10mg', unitPrice: 3.0, inStock: true },
      { form: 'Tablet', strength: '20mg', unitPrice: 4.5, inStock: true },
      { form: 'Injection', strength: '100mg vial', unitPrice: 15.0, inStock: true },
    ],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Hydrocortisone/Hydrocortisone topical'],
    interactions: [
      { interactsWith: 'NSAIDs', severity: 'moderate', mechanism: 'Additive GI toxicity',
        clinicalEffect: 'GI bleeding risk', clinicalEffectAr: 'خطر نزيف معدي معوي',
        management: 'Use GI protection if combination needed', managementAr: 'استخدام حماية المعدة إذا لزم الجمع' },
    ],
    contraindications: ['Systemic fungal infections', 'Live vaccines in immunosuppressive doses'],
    contraindicationsAr: ['عدوى فطرية جهازية', 'لقاحات حية بجرعات مثبطة للمناعة'],
    monitoringRequired: ['Glucose', 'Blood pressure', 'Electrolytes', 'Bone density (long-term)', 'Adrenal crisis awareness in patients'],
    storageConditions: 'Store below 25°C.',
  },
];
