/**
 * Saudi MOH Drug Formulary — Drug Data Part 9
 * GI Extended, Hematology, Psychiatric Extended, Musculoskeletal, Hospital Miscellaneous
 */

import type { FormularyDrug } from './formularyTypes';

let _idCounter = 460;
function nextId(): string { _idCounter += 1; return `FRM-${String(_idCounter).padStart(4, '0')}`; }

// ─── GI EXTENDED (15) ─────────────────────────────────────────────────────────

const GI_EXTENDED: FormularyDrug[] = [
  {
    id: nextId(), genericName: 'Esomeprazole', genericNameAr: 'إيسوميبرازول',
    brandNames: ['Nexium', 'Esomac'], sfda_registration: 'SFDA-2024-ESO-461',
    atcCode: 'A02BC05', atcCategory: 'A02 - Drugs for acid related disorders',
    therapeuticClass: 'Proton Pump Inhibitors', therapeuticClassAr: 'مثبطات مضخة البروتون',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [{ form: 'capsule', strength: '20mg', unitPrice: 2.5, inStock: true }, { form: 'capsule', strength: '40mg', unitPrice: 4.0, inStock: true }, { form: 'injection', strength: '40mg', unitPrice: 35.0, inStock: true }],
    maxDailyDose: 80, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Esomeprazole/Omeprazole', 'Nexium/Naxen'],
    interactions: [
      { interactsWith: 'Clopidogrel', severity: 'major', mechanism: 'CYP2C19 inhibition reduces active metabolite formation', clinicalEffect: 'Reduced antiplatelet effect and increased cardiovascular risk', clinicalEffectAr: 'تقليل تأثير مضاد الصفيحات وزيادة خطر القلب والأوعية', management: 'Avoid combination; use pantoprazole as alternative PPI', managementAr: 'تجنب الجمع؛ استخدام بانتوبرازول كبديل' },
      { interactsWith: 'Methotrexate', severity: 'moderate', mechanism: 'Decreased renal elimination of methotrexate', clinicalEffect: 'Increased methotrexate toxicity risk', clinicalEffectAr: 'زيادة خطر سمية الميثوتريكسات', management: 'Consider temporary PPI withdrawal with high-dose methotrexate', managementAr: 'النظر في إيقاف مؤقت مع جرعات الميثوتريكسات العالية' },
    ],
    contraindications: ['Hypersensitivity to substituted benzimidazoles', 'Co-administration with rilpivirine'],
    contraindicationsAr: ['فرط حساسية لمشتقات البنزيميدازول', 'الإعطاء المتزامن مع ريلبيفيرين'],
    monitoringRequired: ['Magnesium levels with prolonged use', 'Vitamin B12 with long-term therapy', 'Bone density in high-risk patients'],
    storageConditions: 'Store below 25°C. Protect from moisture.',
  },
  {
    id: nextId(), genericName: 'Lansoprazole', genericNameAr: 'لانسوبرازول',
    brandNames: ['Prevacid', 'Lansopral'], sfda_registration: 'SFDA-2024-LAN-462',
    atcCode: 'A02BC03', atcCategory: 'A02 - Drugs for acid related disorders',
    therapeuticClass: 'Proton Pump Inhibitors', therapeuticClassAr: 'مثبطات مضخة البروتون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'capsule', strength: '15mg', unitPrice: 2.0, inStock: true }, { form: 'capsule', strength: '30mg', unitPrice: 3.5, inStock: true }, { form: 'orally disintegrating tablet', strength: '15mg', unitPrice: 4.5, inStock: true }],
    maxDailyDose: 60, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Lansoprazole/Omeprazole', 'Prevacid/Prevpac'],
    interactions: [
      { interactsWith: 'Sucralfate', severity: 'moderate', mechanism: 'Sucralfate requires acidic pH for binding', clinicalEffect: 'Reduced sucralfate efficacy', clinicalEffectAr: 'تقليل فعالية السكرالفات', management: 'Give lansoprazole 30 min before sucralfate', managementAr: 'إعطاء لانسوبرازول 30 دقيقة قبل السكرالفات' },
    ],
    contraindications: ['PPI hypersensitivity', 'Co-administration with rilpivirine or atazanavir'],
    contraindicationsAr: ['فرط حساسية لمثبطات مضخة البروتون', 'الإعطاء المتزامن مع ريلبيفيرين أو أتازانافير'],
    monitoringRequired: ['Magnesium levels', 'C. difficile signs', 'Bone health'],
    storageConditions: 'Store below 25°C. Protect from moisture and light.',
  },
  {
    id: nextId(), genericName: 'Rabeprazole', genericNameAr: 'رابيبرازول',
    brandNames: ['Pariet', 'Rabecid'], sfda_registration: 'SFDA-2024-RAB-463',
    atcCode: 'A02BC04', atcCategory: 'A02 - Drugs for acid related disorders',
    therapeuticClass: 'Proton Pump Inhibitors', therapeuticClassAr: 'مثبطات مضخة البروتون',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '10mg', unitPrice: 2.0, inStock: true }, { form: 'tablet', strength: '20mg', unitPrice: 3.0, inStock: true }],
    maxDailyDose: 60, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Rabeprazole/Aripiprazole'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'moderate', mechanism: 'Minor CYP inhibition altering warfarin metabolism', clinicalEffect: 'Potential INR elevation', clinicalEffectAr: 'احتمال ارتفاع INR', management: 'Monitor INR when starting or stopping', managementAr: 'مراقبة INR عند البدء أو الإيقاف' },
    ],
    contraindications: ['Substituted benzimidazole hypersensitivity'],
    contraindicationsAr: ['فرط حساسية لمشتقات البنزيميدازول'],
    monitoringRequired: ['Magnesium levels with prolonged use', 'Vitamin B12 annually'],
    storageConditions: 'Store below 25°C. Protect from moisture.',
  },
  {
    id: nextId(), genericName: 'Famotidine', genericNameAr: 'فاموتيدين',
    brandNames: ['Pepcid', 'Famocid'], sfda_registration: 'SFDA-2024-FAM-464',
    atcCode: 'A02BA03', atcCategory: 'A02 - Drugs for acid related disorders',
    therapeuticClass: 'H2 Receptor Antagonists', therapeuticClassAr: 'مضادات مستقبلات الهيستامين H2',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [{ form: 'tablet', strength: '20mg', unitPrice: 0.8, inStock: true }, { form: 'tablet', strength: '40mg', unitPrice: 1.2, inStock: true }, { form: 'injection', strength: '20mg/2ml', unitPrice: 5.0, inStock: true }],
    maxDailyDose: 80, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Famotidine/Furosemide'],
    interactions: [
      { interactsWith: 'Ketoconazole', severity: 'moderate', mechanism: 'Reduced gastric acidity decreases ketoconazole absorption', clinicalEffect: 'Decreased antifungal efficacy', clinicalEffectAr: 'تقليل فعالية مضاد الفطريات', management: 'Give ketoconazole with acidic beverage or separate by 2h', managementAr: 'إعطاء كيتوكونازول مع مشروب حمضي أو فصل بساعتين' },
    ],
    contraindications: ['Hypersensitivity to H2 blockers'],
    contraindicationsAr: ['فرط حساسية لحاصرات H2'],
    monitoringRequired: ['Renal function for dose adjustment', 'CBC with prolonged use'],
    storageConditions: 'Store below 30°C. Protect from light.',
  },
  {
    id: nextId(), genericName: 'Metoclopramide', genericNameAr: 'ميتوكلوبراميد',
    brandNames: ['Maxolon', 'Primperan', 'Reglan'], sfda_registration: 'SFDA-2024-MCP-465',
    atcCode: 'A03FA01', atcCategory: 'A03 - Drugs for functional gastrointestinal disorders',
    therapeuticClass: 'Prokinetics / Antiemetics', therapeuticClassAr: 'محفزات حركة الأمعاء / مضادات القيء',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'im'],
    forms: [{ form: 'tablet', strength: '10mg', unitPrice: 0.5, inStock: true }, { form: 'injection', strength: '10mg/2ml', unitPrice: 3.0, inStock: true }, { form: 'syrup', strength: '5mg/5ml', unitPrice: 6.0, inStock: true }],
    maxDailyDose: 30, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Metoclopramide/Metolazone'],
    blackBoxWarning: 'Tardive dyskinesia risk with prolonged use (>12 weeks). Risk increases with duration and total cumulative dose.',
    blackBoxWarningAr: 'خطر خلل الحركة المتأخر مع الاستخدام المطول (أكثر من 12 أسبوع). يزداد الخطر مع المدة والجرعة التراكمية.',
    interactions: [
      { interactsWith: 'Haloperidol', severity: 'major', mechanism: 'Additive dopamine blockade', clinicalEffect: 'Increased risk of extrapyramidal symptoms and tardive dyskinesia', clinicalEffectAr: 'زيادة خطر الأعراض خارج الهرمية وخلل الحركة المتأخر', management: 'Avoid combination; use alternative antiemetic', managementAr: 'تجنب الجمع؛ استخدام مضاد قيء بديل' },
      { interactsWith: 'Levodopa', severity: 'major', mechanism: 'Dopamine antagonism opposes levodopa effect', clinicalEffect: 'Worsening of Parkinson symptoms', clinicalEffectAr: 'تفاقم أعراض باركنسون', management: 'Contraindicated in Parkinson disease', managementAr: 'ممنوع في مرض باركنسون' },
    ],
    contraindications: ['GI obstruction or perforation', 'Pheochromocytoma', 'Parkinson disease', 'Seizure disorder'],
    contraindicationsAr: ['انسداد أو ثقب الجهاز الهضمي', 'ورم القواتم', 'مرض باركنسون', 'اضطراب الصرع'],
    monitoringRequired: ['Extrapyramidal symptoms', 'Duration of use (max 12 weeks)', 'Prolactin levels if symptoms occur'],
    storageConditions: 'Store below 25°C. Protect from light.',
  },
  {
    id: nextId(), genericName: 'Hyoscine Butylbromide', genericNameAr: 'هيوسين بوتيل بروميد',
    brandNames: ['Buscopan'], sfda_registration: 'SFDA-2024-HYO-466',
    atcCode: 'A03BB01', atcCategory: 'A03 - Drugs for functional gastrointestinal disorders',
    therapeuticClass: 'Antispasmodics', therapeuticClassAr: 'مضادات التشنج',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [{ form: 'tablet', strength: '10mg', unitPrice: 0.8, inStock: true }, { form: 'injection', strength: '20mg/ml', unitPrice: 4.0, inStock: true }],
    maxDailyDose: 80, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Hyoscine butylbromide/Hyoscine hydrobromide'],
    interactions: [
      { interactsWith: 'Metoclopramide', severity: 'moderate', mechanism: 'Opposing effects on GI motility', clinicalEffect: 'Mutual antagonism of GI effects', clinicalEffectAr: 'تضاد متبادل لتأثيرات الجهاز الهضمي', management: 'Avoid concurrent use', managementAr: 'تجنب الاستخدام المتزامن' },
    ],
    contraindications: ['Myasthenia gravis', 'Megacolon', 'Narrow-angle glaucoma', 'Prostatic hypertrophy with urinary retention'],
    contraindicationsAr: ['الوهن العضلي الوبيل', 'تضخم القولون', 'الجلوكوما ضيقة الزاوية', 'تضخم البروستات مع احتباس البول'],
    monitoringRequired: ['Heart rate (IV use)', 'Urinary retention symptoms in elderly'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: nextId(), genericName: 'Polyethylene Glycol 3350', genericNameAr: 'بولي إيثيلين غليكول',
    brandNames: ['Movicol', 'MiraLAX'], sfda_registration: 'SFDA-2024-PEG-467',
    atcCode: 'A06AD65', atcCategory: 'A06 - Drugs for constipation',
    therapeuticClass: 'Osmotic Laxatives', therapeuticClassAr: 'ملينات أسموزية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'powder sachet', strength: '13.125g', unitPrice: 2.0, inStock: true }, { form: 'powder sachet', strength: '6.563g', unitPrice: 1.5, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Movicol/Mucinex'],
    interactions: [
      { interactsWith: 'Oral medications (general)', severity: 'minor', mechanism: 'Accelerated GI transit may reduce absorption', clinicalEffect: 'Potential decreased absorption of co-administered drugs', clinicalEffectAr: 'احتمال تقليل امتصاص الأدوية الفموية الأخرى', management: 'Give other meds 1h before or 2h after PEG', managementAr: 'إعطاء الأدوية الأخرى ساعة قبل أو ساعتين بعد' },
    ],
    contraindications: ['Intestinal obstruction', 'Bowel perforation', 'Toxic megacolon'],
    contraindicationsAr: ['انسداد معوي', 'ثقب الأمعاء', 'تضخم القولون السمي'],
    monitoringRequired: ['Electrolytes if prolonged use', 'Hydration status'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: nextId(), genericName: 'Bismuth Subsalicylate', genericNameAr: 'بزموت سبساليسيلات',
    brandNames: ['Pepto-Bismol', 'De-Nol'], sfda_registration: 'SFDA-2024-BIS-468',
    atcCode: 'A02BX05', atcCategory: 'A02 - Drugs for acid related disorders',
    therapeuticClass: 'GI Protectants', therapeuticClassAr: 'واقيات الجهاز الهضمي',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'chewable tablet', strength: '262mg', unitPrice: 0.5, inStock: true }, { form: 'suspension', strength: '262mg/15ml', unitPrice: 12.0, inStock: true }],
    maxDailyDose: 4200, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Bismuth/Bisoprolol'],
    interactions: [
      { interactsWith: 'Aspirin/NSAIDs', severity: 'moderate', mechanism: 'Contains salicylate; additive salicylate load', clinicalEffect: 'Salicylate toxicity risk', clinicalEffectAr: 'خطر سمية الساليسيلات', management: 'Monitor for tinnitus; avoid with high-dose aspirin', managementAr: 'مراقبة طنين الأذن؛ تجنب مع جرعات الأسبرين العالية' },
      { interactsWith: 'Tetracyclines', severity: 'moderate', mechanism: 'Chelation reduces tetracycline absorption', clinicalEffect: 'Decreased antibiotic efficacy', clinicalEffectAr: 'تقليل فعالية المضاد الحيوي', management: 'Separate by at least 2 hours', managementAr: 'فصل الإعطاء بساعتين على الأقل' },
    ],
    contraindications: ['Aspirin/salicylate allergy', 'Children under 12 (Reye syndrome)', 'Active GI bleeding'],
    contraindicationsAr: ['حساسية الأسبرين/الساليسيلات', 'الأطفال أقل من 12 سنة (متلازمة راي)', 'نزيف هضمي نشط'],
    monitoringRequired: ['Signs of salicylate toxicity', 'Black stool (normal vs bleeding)'],
    storageConditions: 'Store below 25°C. Shake suspension before use.',
  },
  {
    id: nextId(), genericName: 'Mesalazine', genericNameAr: 'ميسالازين',
    brandNames: ['Pentasa', 'Asacol', 'Salofalk'], sfda_registration: 'SFDA-2024-MES-469',
    atcCode: 'A07EC02', atcCategory: 'A07 - Antidiarrheals and intestinal antiinflammatories',
    therapeuticClass: 'Aminosalicylates', therapeuticClassAr: 'أمينوساليسيلات',
    formularyStatus: 'formulary', route: ['oral', 'rectal'],
    forms: [{ form: 'tablet', strength: '500mg', unitPrice: 2.0, inStock: true }, { form: 'tablet', strength: '1g', unitPrice: 3.5, inStock: true }, { form: 'suppository', strength: '500mg', unitPrice: 3.0, inStock: true }, { form: 'enema', strength: '4g/60ml', unitPrice: 25.0, inStock: true }],
    maxDailyDose: 4800, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Mesalazine/Memantine'],
    interactions: [
      { interactsWith: 'Azathioprine', severity: 'major', mechanism: 'Inhibition of thiopurine methyltransferase (TPMT)', clinicalEffect: 'Increased azathioprine toxicity and myelosuppression', clinicalEffectAr: 'زيادة سمية الآزاثيوبرين وتثبيط نقي العظم', management: 'Monitor CBC closely; may need azathioprine dose reduction', managementAr: 'مراقبة تعداد الدم؛ قد يلزم تقليل جرعة الآزاثيوبرين' },
    ],
    contraindications: ['Salicylate hypersensitivity', 'Severe renal impairment', 'Severe hepatic impairment'],
    contraindicationsAr: ['فرط حساسية للساليسيلات', 'قصور كلوي شديد', 'قصور كبدي شديد'],
    monitoringRequired: ['Renal function (baseline and periodic)', 'CBC', 'Hepatic function', 'Urinalysis'],
    storageConditions: 'Store below 25°C. Protect from moisture.',
  },
  {
    id: nextId(), genericName: 'Sulfasalazine', genericNameAr: 'سلفاسالازين',
    brandNames: ['Salazopyrin', 'Azulfidine'], sfda_registration: 'SFDA-2024-SSZ-470',
    atcCode: 'A07EC01', atcCategory: 'A07 - Antidiarrheals and intestinal antiinflammatories',
    therapeuticClass: 'Aminosalicylates', therapeuticClassAr: 'أمينوساليسيلات',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '500mg', unitPrice: 0.8, inStock: true }, { form: 'enteric-coated tablet', strength: '500mg', unitPrice: 1.2, inStock: true }],
    maxDailyDose: 4000, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Sulfasalazine/Sulfadiazine'],
    interactions: [
      { interactsWith: 'Digoxin', severity: 'moderate', mechanism: 'Reduced digoxin absorption', clinicalEffect: 'Decreased digoxin levels', clinicalEffectAr: 'انخفاض مستويات الديجوكسين', management: 'Monitor digoxin levels', managementAr: 'مراقبة مستويات الديجوكسين' },
      { interactsWith: 'Folic acid', severity: 'moderate', mechanism: 'Inhibits folate absorption and metabolism', clinicalEffect: 'Folate deficiency and megaloblastic anemia', clinicalEffectAr: 'نقص حمض الفوليك وفقر الدم الضخم الأرومات', management: 'Supplement with folic acid 1mg daily', managementAr: 'إعطاء حمض الفوليك 1 مغ يومياً' },
    ],
    contraindications: ['Sulfonamide allergy', 'Salicylate allergy', 'Porphyria', 'GI or urinary obstruction'],
    contraindicationsAr: ['حساسية السلفوناميدات', 'حساسية الساليسيلات', 'البورفيريا', 'انسداد هضمي أو بولي'],
    monitoringRequired: ['CBC every 2 weeks first 3 months', 'Renal function', 'Hepatic function', 'Folate levels'],
    storageConditions: 'Store below 25°C. Protect from light.',
  },
  {
    id: nextId(), genericName: 'Infliximab', genericNameAr: 'إنفليكسيماب',
    brandNames: ['Remicade', 'Remsima'], sfda_registration: 'SFDA-2024-INF-471',
    atcCode: 'L04AB02', atcCategory: 'L04 - Immunosuppressants',
    therapeuticClass: 'Biologic DMARDs - Anti-TNF', therapeuticClassAr: 'الأدوية البيولوجية المضادة لعامل نخر الورم',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Gastroenterologist or rheumatologist approval. For moderate-severe Crohn disease or UC refractory to conventional therapy.',
    restrictionCriteriaAr: 'يتطلب موافقة أخصائي الجهاز الهضمي أو الروماتيزم. لمرض كرون أو التهاب القولون التقرحي المتوسط-الشديد المقاوم للعلاج التقليدي.',
    approverRole: 'gastroenterologist', route: ['iv'],
    forms: [{ form: 'injection', strength: '100mg vial', unitPrice: 850.0, inStock: true }],
    maxDailyDose: 10, maxDailyDoseUnit: 'mg/kg per infusion', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Infliximab/Rituximab'],
    blackBoxWarning: 'Serious infections including TB reactivation, invasive fungal infections, and opportunistic infections. Lymphoma and other malignancies reported in children and adolescents.',
    blackBoxWarningAr: 'عدوى خطيرة بما في ذلك إعادة تنشيط السل والعدوى الفطرية الغازية. تم الإبلاغ عن أورام لمفاوية وأورام خبيثة أخرى في الأطفال والمراهقين.',
    interactions: [
      { interactsWith: 'Live vaccines', severity: 'major', mechanism: 'Immunosuppression may allow vaccine strain infection', clinicalEffect: 'Risk of disseminated vaccine infection', clinicalEffectAr: 'خطر عدوى اللقاح المنتشرة', management: 'Contraindicated; give live vaccines at least 3 months before starting', managementAr: 'ممنوع؛ إعطاء اللقاحات الحية 3 أشهر قبل البدء على الأقل' },
      { interactsWith: 'Anakinra', severity: 'major', mechanism: 'Additive immunosuppression', clinicalEffect: 'Significantly increased serious infection risk', clinicalEffectAr: 'زيادة كبيرة في خطر العدوى الخطيرة', management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['Active serious infection', 'Heart failure NYHA III-IV at doses >5mg/kg', 'Active TB', 'Demyelinating disease'],
    contraindicationsAr: ['عدوى خطيرة نشطة', 'قصور القلب NYHA III-IV بجرعات أكثر من 5مغ/كغ', 'سل نشط', 'مرض إزالة الميالين'],
    monitoringRequired: ['TB screening before and during', 'Hepatitis B screening', 'CBC', 'LFTs', 'Infusion reactions', 'Signs of infection'],
    storageConditions: 'Refrigerate 2-8°C. Do not freeze. Protect from light.',
  },
  {
    id: nextId(), genericName: 'Adalimumab', genericNameAr: 'أداليموماب',
    brandNames: ['Humira', 'Hadlima'], sfda_registration: 'SFDA-2024-ADA-472',
    atcCode: 'L04AB04', atcCategory: 'L04 - Immunosuppressants',
    therapeuticClass: 'Biologic DMARDs - Anti-TNF', therapeuticClassAr: 'الأدوية البيولوجية المضادة لعامل نخر الورم',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Gastroenterologist or rheumatologist approval. For moderate-severe Crohn disease or UC refractory to conventional therapy.',
    restrictionCriteriaAr: 'يتطلب موافقة أخصائي الجهاز الهضمي أو الروماتيزم. لمرض كرون أو التهاب القولون التقرحي المقاوم للعلاج التقليدي.',
    approverRole: 'gastroenterologist', route: ['sc'],
    forms: [{ form: 'prefilled syringe', strength: '40mg/0.4ml', unitPrice: 750.0, inStock: true }, { form: 'prefilled pen', strength: '40mg/0.4ml', unitPrice: 780.0, inStock: true }],
    maxDailyDose: 80, maxDailyDoseUnit: 'mg (induction dose)', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Adalimumab/Infliximab'],
    blackBoxWarning: 'Serious infections and malignancy risk. TB reactivation. Hepatosplenic T-cell lymphoma in young patients on combination immunosuppression.',
    blackBoxWarningAr: 'خطر العدوى الخطيرة والأورام الخبيثة. إعادة تنشيط السل. ورم الخلايا التائية الكبدي الطحالي في المرضى الشباب على العلاج المناعي المشترك.',
    interactions: [
      { interactsWith: 'Live vaccines', severity: 'major', mechanism: 'Immunosuppression risk', clinicalEffect: 'Disseminated vaccine infection risk', clinicalEffectAr: 'خطر عدوى اللقاح المنتشرة', management: 'Avoid live vaccines during therapy', managementAr: 'تجنب اللقاحات الحية أثناء العلاج' },
    ],
    contraindications: ['Active serious infection', 'Active TB', 'Moderate-severe heart failure'],
    contraindicationsAr: ['عدوى خطيرة نشطة', 'سل نشط', 'قصور القلب المتوسط-الشديد'],
    monitoringRequired: ['TB screening', 'Hepatitis B status', 'CBC', 'LFTs', 'Signs of infection', 'Injection site reactions'],
    storageConditions: 'Refrigerate 2-8°C. Do not freeze. Protect from light. May store at room temp up to 14 days.',
  },
  {
    id: nextId(), genericName: 'Octreotide', genericNameAr: 'أوكتريوتيد',
    brandNames: ['Sandostatin', 'Octride'], sfda_registration: 'SFDA-2024-OCT-473',
    atcCode: 'H01CB02', atcCategory: 'H01 - Pituitary and hypothalamic hormones',
    therapeuticClass: 'Somatostatin Analogues', therapeuticClassAr: 'نظائر السوماتوستاتين',
    formularyStatus: 'formulary', route: ['iv', 'sc'],
    forms: [{ form: 'injection', strength: '100mcg/ml', unitPrice: 15.0, inStock: true }, { form: 'injection', strength: '500mcg/ml', unitPrice: 45.0, inStock: true }, { form: 'LAR injection', strength: '20mg', unitPrice: 1200.0, inStock: true }],
    maxDailyDose: 1500, maxDailyDoseUnit: 'mcg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Octreotide/Oxytocin'],
    interactions: [
      { interactsWith: 'Insulin/Oral hypoglycemics', severity: 'moderate', mechanism: 'Alters insulin and glucagon secretion', clinicalEffect: 'Unpredictable hypo- or hyperglycemia', clinicalEffectAr: 'نقص أو ارتفاع سكر الدم غير متوقع', management: 'Monitor blood glucose closely; adjust insulin doses', managementAr: 'مراقبة سكر الدم؛ تعديل جرعات الإنسولين' },
      { interactsWith: 'Cyclosporine', severity: 'moderate', mechanism: 'Reduced cyclosporine absorption', clinicalEffect: 'Decreased cyclosporine levels', clinicalEffectAr: 'انخفاض مستويات السيكلوسبورين', management: 'Monitor cyclosporine levels', managementAr: 'مراقبة مستويات السيكلوسبورين' },
    ],
    contraindications: ['Hypersensitivity to octreotide'],
    contraindicationsAr: ['فرط حساسية للأوكتريوتيد'],
    monitoringRequired: ['Blood glucose', 'Thyroid function', 'Gallbladder ultrasound (cholelithiasis)', 'Vitamin B12 with long-term use'],
    storageConditions: 'Refrigerate 2-8°C. May store at room temp up to 14 days. Protect from light.',
  },
  {
    id: nextId(), genericName: 'Ursodeoxycholic Acid', genericNameAr: 'حمض أورسوديوكسيكوليك',
    brandNames: ['Ursofalk', 'Actigall'], sfda_registration: 'SFDA-2024-UDC-474',
    atcCode: 'A05AA02', atcCategory: 'A05 - Bile and liver therapy',
    therapeuticClass: 'Bile Acid Therapy', therapeuticClassAr: 'علاج الأحماض الصفراوية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'capsule', strength: '250mg', unitPrice: 1.5, inStock: true }, { form: 'capsule', strength: '500mg', unitPrice: 2.8, inStock: true }, { form: 'suspension', strength: '250mg/5ml', unitPrice: 35.0, inStock: true }],
    maxDailyDose: 15, maxDailyDoseUnit: 'mg/kg', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['UDCA/CDCA (chenodeoxycholic acid)'],
    interactions: [
      { interactsWith: 'Cholestyramine', severity: 'moderate', mechanism: 'Bile acid sequestrants bind UDCA in gut', clinicalEffect: 'Reduced UDCA absorption and efficacy', clinicalEffectAr: 'تقليل امتصاص وفعالية حمض أورسوديوكسيكوليك', management: 'Separate administration by at least 2 hours', managementAr: 'فصل الإعطاء بساعتين على الأقل' },
    ],
    contraindications: ['Calcified gallstones', 'Non-functioning gallbladder', 'Acute cholecystitis', 'Biliary obstruction'],
    contraindicationsAr: ['حصى مرارية متكلسة', 'مرارة غير فعالة', 'التهاب مرارة حاد', 'انسداد صفراوي'],
    monitoringRequired: ['LFTs monthly for first 3 months', 'Gallbladder ultrasound periodically'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: nextId(), genericName: 'Pancrelipase', genericNameAr: 'بانكريليباز',
    brandNames: ['Creon', 'Zenpep'], sfda_registration: 'SFDA-2024-PAN-475',
    atcCode: 'A09AA02', atcCategory: 'A09 - Digestives including enzymes',
    therapeuticClass: 'Pancreatic Enzyme Replacement', therapeuticClassAr: 'بدائل إنزيمات البنكرياس',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'capsule', strength: '10,000 units lipase', unitPrice: 5.0, inStock: true }, { form: 'capsule', strength: '25,000 units lipase', unitPrice: 8.0, inStock: true }, { form: 'capsule', strength: '40,000 units lipase', unitPrice: 12.0, inStock: true }],
    maxDailyDose: 10000, maxDailyDoseUnit: 'units lipase/kg/day', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Creon/Crestor'],
    interactions: [
      { interactsWith: 'Acarbose', severity: 'moderate', mechanism: 'Pancreatic enzymes may counteract acarbose alpha-glucosidase inhibition', clinicalEffect: 'Reduced acarbose efficacy in diabetes', clinicalEffectAr: 'تقليل فعالية الأكاربوز في السكري', management: 'Monitor blood glucose if used together', managementAr: 'مراقبة سكر الدم عند الاستخدام المتزامن' },
    ],
    contraindications: ['Pork protein allergy', 'Acute pancreatitis'],
    contraindicationsAr: ['حساسية بروتين لحم الخنزير', 'التهاب البنكرياس الحاد'],
    monitoringRequired: ['Stool fat content', 'Nutritional status', 'Weight gain in children', 'Signs of fibrosing colonopathy with high doses'],
    storageConditions: 'Store below 25°C. Do not crush or chew capsules. Protect from moisture.',
  },
];

// ─── PLACEHOLDER_SECTIONS ─────────────────────────────────────────────────────

const HEMATOLOGY: FormularyDrug[] = [
  {
    id: nextId(), genericName: 'Iron Sucrose', genericNameAr: 'سكروز الحديد',
    brandNames: ['Venofer'], sfda_registration: 'SFDA-2024-FES-476',
    atcCode: 'B03AC02', atcCategory: 'B03 - Antianemic preparations',
    therapeuticClass: 'Parenteral Iron', therapeuticClassAr: 'حديد وريدي',
    formularyStatus: 'formulary', route: ['iv'],
    forms: [{ form: 'injection', strength: '100mg/5ml', unitPrice: 25.0, inStock: true }],
    maxDailyDose: 300, maxDailyDoseUnit: 'mg per session', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'B', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Iron sucrose/Iron dextran'],
    interactions: [
      { interactsWith: 'Oral iron supplements', severity: 'moderate', mechanism: 'Oral iron absorption reduced by high serum iron after IV dose', clinicalEffect: 'Reduced oral iron efficacy', clinicalEffectAr: 'تقليل فعالية الحديد الفموي', management: 'Wait at least 5 days after IV iron before starting oral', managementAr: 'الانتظار 5 أيام على الأقل بعد الحديد الوريدي قبل البدء بالفموي' },
    ],
    contraindications: ['Iron overload', 'Hemochromatosis', 'Anemia not caused by iron deficiency', 'First trimester pregnancy'],
    contraindicationsAr: ['فرط حمل الحديد', 'داء ترسب الأصبغة الدموية', 'فقر دم ليس بسبب نقص الحديد', 'الثلث الأول من الحمل'],
    monitoringRequired: ['Serum ferritin and transferrin saturation', 'Hemoglobin', 'Infusion reactions', 'Phosphate levels'],
    storageConditions: 'Store below 25°C. Do not freeze. Use immediately after dilution.',
  },
  {
    id: nextId(), genericName: 'Ferric Carboxymaltose', genericNameAr: 'كاربوكسيمالتوز الحديديك',
    brandNames: ['Ferinject'], sfda_registration: 'SFDA-2024-FCM-477',
    atcCode: 'B03AC01', atcCategory: 'B03 - Antianemic preparations',
    therapeuticClass: 'Parenteral Iron', therapeuticClassAr: 'حديد وريدي',
    formularyStatus: 'formulary', route: ['iv'],
    forms: [{ form: 'injection', strength: '500mg/10ml', unitPrice: 120.0, inStock: true }, { form: 'injection', strength: '1000mg/20ml', unitPrice: 220.0, inStock: true }],
    maxDailyDose: 1000, maxDailyDoseUnit: 'mg per session (max 20mg/kg)', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Ferinject/Ferrlecit'],
    interactions: [
      { interactsWith: 'Oral iron supplements', severity: 'moderate', mechanism: 'Saturated transferrin reduces oral iron absorption', clinicalEffect: 'Wasted oral iron supplementation', clinicalEffectAr: 'إهدار مكملات الحديد الفموية', management: 'Do not give oral iron for at least 5 days post infusion', managementAr: 'عدم إعطاء حديد فموي لمدة 5 أيام بعد التسريب على الأقل' },
    ],
    contraindications: ['Iron overload', 'Hemochromatosis', 'Non-iron-deficiency anemia', 'Hypersensitivity to IV iron products'],
    contraindicationsAr: ['فرط حمل الحديد', 'داء ترسب الأصبغة الدموية', 'فقر دم غير ناتج عن نقص الحديد', 'فرط حساسية لمنتجات الحديد الوريدية'],
    monitoringRequired: ['Serum ferritin', 'Phosphate (hypophosphatemia risk)', 'Hemoglobin response', 'Infusion reactions'],
    storageConditions: 'Store below 30°C. Do not freeze.',
  },
  {
    id: nextId(), genericName: 'Erythropoietin (Epoetin Alfa)', genericNameAr: 'إريثروبويتين (إيبويتين ألفا)',
    brandNames: ['Eprex', 'Epogen'], sfda_registration: 'SFDA-2024-EPO-478',
    atcCode: 'B03XA01', atcCategory: 'B03 - Antianemic preparations',
    therapeuticClass: 'Erythropoiesis-Stimulating Agents', therapeuticClassAr: 'عوامل تحفيز تكوين كريات الدم الحمراء',
    formularyStatus: 'formulary', route: ['sc', 'iv'],
    forms: [{ form: 'prefilled syringe', strength: '2000 IU', unitPrice: 35.0, inStock: true }, { form: 'prefilled syringe', strength: '4000 IU', unitPrice: 55.0, inStock: true }, { form: 'prefilled syringe', strength: '10000 IU', unitPrice: 120.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Epoetin alfa/Darbepoetin alfa'],
    blackBoxWarning: 'Increased risk of death, MI, stroke, venous thromboembolism when targeting hemoglobin >11 g/dL. Shortened overall survival and increased tumor progression in cancer patients.',
    blackBoxWarningAr: 'زيادة خطر الوفاة واحتشاء القلب والسكتة والجلطات الوريدية عند استهداف هيموغلوبين أكثر من 11 غ/دل. تقصير البقاء وزيادة تطور الورم في مرضى السرطان.',
    interactions: [
      { interactsWith: 'ACE Inhibitors', severity: 'moderate', mechanism: 'ACE inhibitors may blunt erythropoietic response', clinicalEffect: 'Reduced EPO efficacy', clinicalEffectAr: 'تقليل فعالية الإريثروبويتين', management: 'May need higher EPO doses; monitor hemoglobin response', managementAr: 'قد يلزم جرعات أعلى؛ مراقبة استجابة الهيموغلوبين' },
    ],
    contraindications: ['Uncontrolled hypertension', 'Pure red cell aplasia from prior EPO use', 'Hypersensitivity'],
    contraindicationsAr: ['ارتفاع ضغط الدم غير المنضبط', 'عدم تنسج الخلايا الحمراء الصرف من استخدام سابق', 'فرط حساسية'],
    monitoringRequired: ['Hemoglobin (target 10-11 g/dL, do not exceed 12)', 'Blood pressure', 'Iron stores', 'Reticulocyte count', 'Thrombotic events'],
    storageConditions: 'Refrigerate 2-8°C. Do not freeze. Do not shake.',
  },
  {
    id: nextId(), genericName: 'Filgrastim', genericNameAr: 'فيلغراستيم',
    brandNames: ['Neupogen', 'Zarxio'], sfda_registration: 'SFDA-2024-FIL-479',
    atcCode: 'L03AA02', atcCategory: 'L03 - Immunostimulants',
    therapeuticClass: 'Colony-Stimulating Factors (G-CSF)', therapeuticClassAr: 'عوامل تحفيز المستعمرات',
    formularyStatus: 'formulary', route: ['sc'],
    forms: [{ form: 'prefilled syringe', strength: '300mcg/0.5ml', unitPrice: 80.0, inStock: true }, { form: 'prefilled syringe', strength: '480mcg/0.8ml', unitPrice: 120.0, inStock: true }],
    maxDailyDose: 10, maxDailyDoseUnit: 'mcg/kg', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Filgrastim/Pegfilgrastim'],
    interactions: [
      { interactsWith: 'Chemotherapy', severity: 'major', mechanism: 'Rapidly dividing myeloid cells more susceptible to cytotoxic agents', clinicalEffect: 'Enhanced myelosuppression if given concurrently', clinicalEffectAr: 'تعزيز تثبيط نقي العظم عند الإعطاء المتزامن', management: 'Give filgrastim at least 24h after chemotherapy', managementAr: 'إعطاء فيلغراستيم بعد 24 ساعة على الأقل من العلاج الكيميائي' },
    ],
    contraindications: ['Hypersensitivity to E. coli-derived proteins', 'Do not use 24h before or after chemotherapy'],
    contraindicationsAr: ['فرط حساسية لبروتينات مشتقة من الإي كولاي', 'عدم الاستخدام 24 ساعة قبل أو بعد العلاج الكيميائي'],
    monitoringRequired: ['CBC with differential', 'Spleen size (splenic rupture risk)', 'Bone pain management', 'Platelet count'],
    storageConditions: 'Refrigerate 2-8°C. Do not freeze. Protect from light.',
  },
  {
    id: nextId(), genericName: 'Factor VIII Concentrate', genericNameAr: 'مركز العامل الثامن',
    brandNames: ['Advate', 'Kogenate', 'Recombinate'], sfda_registration: 'SFDA-2024-F8C-480',
    atcCode: 'B02BD02', atcCategory: 'B02 - Antihemorrhagics',
    therapeuticClass: 'Coagulation Factors', therapeuticClassAr: 'عوامل التخثر',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Hematologist approval only. For hemophilia A treatment and prophylaxis.',
    restrictionCriteriaAr: 'موافقة أخصائي أمراض الدم فقط. لعلاج والوقاية من الهيموفيليا أ.',
    approverRole: 'hematologist', route: ['iv'],
    forms: [{ form: 'injection', strength: '250 IU vial', unitPrice: 350.0, inStock: true }, { form: 'injection', strength: '500 IU vial', unitPrice: 650.0, inStock: true }, { form: 'injection', strength: '1000 IU vial', unitPrice: 1200.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: ['Factor VIII/Factor IX', 'Advate/Activate'],
    interactions: [
      { interactsWith: 'Emicizumab', severity: 'major', mechanism: 'Emicizumab mimics Factor VIII; additive effect', clinicalEffect: 'Thrombotic risk from excess factor activity', clinicalEffectAr: 'خطر جلطات من نشاط عامل التخثر الزائد', management: 'Use reduced Factor VIII doses in patients on emicizumab; consult hematologist', managementAr: 'استخدام جرعات مخفضة في مرضى الإيميسيزوماب؛ استشارة أخصائي الدم' },
    ],
    contraindications: ['Known inhibitors to Factor VIII at high titer', 'Hypersensitivity to mouse/hamster protein (recombinant products)'],
    contraindicationsAr: ['أجسام مضادة معروفة للعامل الثامن بعيار مرتفع', 'فرط حساسية لبروتين الفأر/الهامستر (المنتجات المؤتلفة)'],
    monitoringRequired: ['Factor VIII levels', 'Inhibitor titer', 'Bleeding symptoms', 'aPTT'],
    storageConditions: 'Refrigerate 2-8°C. Do not freeze. Use within 3 hours of reconstitution.',
  },
  {
    id: nextId(), genericName: 'Factor IX Concentrate', genericNameAr: 'مركز العامل التاسع',
    brandNames: ['BeneFIX', 'Alprolix'], sfda_registration: 'SFDA-2024-F9C-481',
    atcCode: 'B02BD04', atcCategory: 'B02 - Antihemorrhagics',
    therapeuticClass: 'Coagulation Factors', therapeuticClassAr: 'عوامل التخثر',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Hematologist approval only. For hemophilia B treatment and prophylaxis.',
    restrictionCriteriaAr: 'موافقة أخصائي أمراض الدم فقط. لعلاج والوقاية من الهيموفيليا ب.',
    approverRole: 'hematologist', route: ['iv'],
    forms: [{ form: 'injection', strength: '500 IU vial', unitPrice: 700.0, inStock: true }, { form: 'injection', strength: '1000 IU vial', unitPrice: 1300.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: ['Factor IX/Factor VIII', 'BeneFIX/BeneProtein'],
    interactions: [
      { interactsWith: 'Aminocaproic acid', severity: 'moderate', mechanism: 'Combined prothrombotic effect', clinicalEffect: 'Increased thrombosis risk', clinicalEffectAr: 'زيادة خطر الجلطات', management: 'Use with caution; do not administer within 12 hours of each other', managementAr: 'استخدام بحذر؛ عدم الإعطاء خلال 12 ساعة من بعضهما' },
    ],
    contraindications: ['DIC', 'Known inhibitors at high titer', 'Hypersensitivity to hamster protein'],
    contraindicationsAr: ['التخثر المنتشر داخل الأوعية', 'أجسام مضادة بعيار مرتفع', 'فرط حساسية لبروتين الهامستر'],
    monitoringRequired: ['Factor IX levels', 'Inhibitor screening', 'Thrombotic signs (especially with repeated doses)', 'aPTT'],
    storageConditions: 'Refrigerate 2-8°C. Do not freeze. Use within 3 hours of reconstitution.',
  },
  {
    id: nextId(), genericName: 'Fresh Frozen Plasma', genericNameAr: 'بلازما مجمدة طازجة',
    brandNames: ['FFP'], sfda_registration: 'SFDA-2024-FFP-482',
    atcCode: 'B05AA01', atcCategory: 'B05 - Blood substitutes and perfusion solutions',
    therapeuticClass: 'Blood Products', therapeuticClassAr: 'مشتقات الدم',
    formularyStatus: 'formulary', route: ['iv'],
    forms: [{ form: 'bag', strength: '200-250ml unit', unitPrice: 150.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['FFP/Platelets/Cryoprecipitate'],
    interactions: [
      { interactsWith: 'ACE Inhibitors', severity: 'moderate', mechanism: 'Bradykinin accumulation with ACEi plus plasma products', clinicalEffect: 'Increased risk of hypotensive transfusion reactions', clinicalEffectAr: 'زيادة خطر تفاعلات نقل الدم مع انخفاض الضغط', management: 'Monitor blood pressure closely; consider holding ACEi before transfusion', managementAr: 'مراقبة ضغط الدم؛ النظر في إيقاف مثبطات ACE قبل النقل' },
    ],
    contraindications: ['ABO incompatibility', 'IgA deficiency with anti-IgA antibodies', 'Volume overload without clinical indication'],
    contraindicationsAr: ['عدم توافق فصيلة الدم ABO', 'نقص IgA مع أجسام مضادة لـ IgA', 'فرط حمل السوائل بدون استطباب سريري'],
    monitoringRequired: ['ABO/Rh compatibility', 'Transfusion reactions', 'Coagulation studies post-transfusion', 'Volume status', 'Calcium (citrate toxicity with massive transfusion)'],
    storageConditions: 'Store frozen at -18°C or below. Thaw at 30-37°C. Use within 24h after thawing (store 1-6°C). Do not refreeze.',
  },
  {
    id: nextId(), genericName: 'Cryoprecipitate', genericNameAr: 'راسب بردي',
    brandNames: ['Cryoprecipitate AHF'], sfda_registration: 'SFDA-2024-CRY-483',
    atcCode: 'B02BD06', atcCategory: 'B02 - Antihemorrhagics',
    therapeuticClass: 'Blood Products', therapeuticClassAr: 'مشتقات الدم',
    formularyStatus: 'formulary', route: ['iv'],
    forms: [{ form: 'bag', strength: '10-20ml unit (contains fibrinogen, Factor VIII, vWF, Factor XIII)', unitPrice: 100.0, inStock: true }],
    renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Cryoprecipitate/FFP'],
    interactions: [
      { interactsWith: 'Tranexamic acid', severity: 'minor', mechanism: 'Complementary hemostatic effects', clinicalEffect: 'Enhanced clot formation; may increase thrombosis risk in some settings', clinicalEffectAr: 'تعزيز تكوين الجلطات؛ قد يزيد خطر الجلطات في بعض الحالات', management: 'Use in combination per massive transfusion protocol', managementAr: 'استخدام معاً حسب بروتوكول نقل الدم الكثيف' },
    ],
    contraindications: ['ABO incompatibility', 'Not indicated when fibrinogen >200 mg/dL'],
    contraindicationsAr: ['عدم توافق فصيلة الدم ABO', 'غير مستطب عندما الفبرينوجين أكثر من 200 مغ/دل'],
    monitoringRequired: ['Fibrinogen levels pre- and post-transfusion', 'Transfusion reactions', 'Volume status'],
    storageConditions: 'Store frozen at -18°C or below. Thaw at 30-37°C. Use within 6 hours of thawing. Do not refreeze.',
  },
  {
    id: nextId(), genericName: 'Phytonadione (Vitamin K1)', genericNameAr: 'فيتوناديون (فيتامين ك1)',
    brandNames: ['Konakion', 'Mephyton'], sfda_registration: 'SFDA-2024-VK1-484',
    atcCode: 'B02BA01', atcCategory: 'B02 - Antihemorrhagics',
    therapeuticClass: 'Vitamin K', therapeuticClassAr: 'فيتامين ك',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'im'],
    forms: [{ form: 'tablet', strength: '5mg', unitPrice: 1.0, inStock: true }, { form: 'injection', strength: '10mg/ml', unitPrice: 5.0, inStock: true }, { form: 'injection', strength: '2mg/0.2ml (neonatal)', unitPrice: 3.0, inStock: true }],
    maxDailyDose: 25, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Vitamin K/Vitamin D'],
    interactions: [
      { interactsWith: 'Warfarin', severity: 'major', mechanism: 'Vitamin K directly antagonizes warfarin anticoagulation', clinicalEffect: 'Reversal of anticoagulant effect', clinicalEffectAr: 'عكس تأثير مضاد التخثر', management: 'Use specific doses for warfarin reversal per INR and bleeding status', managementAr: 'استخدام جرعات محددة لعكس الوارفارين حسب INR وحالة النزيف' },
    ],
    contraindications: ['Hypersensitivity to phytonadione'],
    contraindicationsAr: ['فرط حساسية للفيتوناديون'],
    monitoringRequired: ['INR (when used for warfarin reversal)', 'Anaphylaxis with IV use (administer slowly)', 'Response to therapy'],
    storageConditions: 'Store below 25°C. Protect from light.',
  },
  {
    id: nextId(), genericName: 'Eltrombopag', genericNameAr: 'إلترومبوباغ',
    brandNames: ['Revolade', 'Promacta'], sfda_registration: 'SFDA-2024-ELT-485',
    atcCode: 'B02BX05', atcCategory: 'B02 - Antihemorrhagics',
    therapeuticClass: 'Thrombopoietin Receptor Agonists', therapeuticClassAr: 'ناهضات مستقبلات الثرومبوبويتين',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Hematologist approval. For chronic ITP refractory to corticosteroids and immunoglobulins.',
    restrictionCriteriaAr: 'موافقة أخصائي أمراض الدم. لفرفرية نقص الصفيحات المناعية المزمنة المقاومة للكورتيزون والغلوبولينات المناعية.',
    approverRole: 'hematologist', route: ['oral'],
    forms: [{ form: 'tablet', strength: '25mg', unitPrice: 85.0, inStock: true }, { form: 'tablet', strength: '50mg', unitPrice: 150.0, inStock: true }, { form: 'tablet', strength: '75mg', unitPrice: 200.0, inStock: true }],
    maxDailyDose: 75, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Eltrombopag/Romiplostim'],
    blackBoxWarning: 'Hepatotoxicity: monitor LFTs. Risk of hepatic decompensation in patients with chronic hepatitis C.',
    blackBoxWarningAr: 'سمية كبدية: مراقبة وظائف الكبد. خطر عدم المعاوضة الكبدية في مرضى التهاب الكبد سي المزمن.',
    interactions: [
      { interactsWith: 'Antacids/Calcium/Iron supplements', severity: 'major', mechanism: 'Chelation with polyvalent cations significantly reduces absorption', clinicalEffect: 'Markedly reduced eltrombopag levels', clinicalEffectAr: 'انخفاض ملحوظ في مستويات إلترومبوباغ', management: 'Separate by at least 4 hours', managementAr: 'فصل الإعطاء بأربع ساعات على الأقل' },
    ],
    contraindications: ['Hypersensitivity to eltrombopag'],
    contraindicationsAr: ['فرط حساسية للإلترومبوباغ'],
    monitoringRequired: ['Platelet count weekly until stable', 'LFTs every 2 weeks', 'Peripheral blood smear', 'Thrombotic events'],
    storageConditions: 'Store below 30°C.',
  },
  {
    id: nextId(), genericName: 'Romiplostim', genericNameAr: 'روميبلوستيم',
    brandNames: ['Nplate'], sfda_registration: 'SFDA-2024-ROM-486',
    atcCode: 'B02BX04', atcCategory: 'B02 - Antihemorrhagics',
    therapeuticClass: 'Thrombopoietin Receptor Agonists', therapeuticClassAr: 'ناهضات مستقبلات الثرومبوبويتين',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Hematologist approval. For chronic ITP with insufficient response to other treatments.',
    restrictionCriteriaAr: 'موافقة أخصائي أمراض الدم. لفرفرية نقص الصفيحات المناعية المزمنة مع استجابة غير كافية للعلاجات الأخرى.',
    approverRole: 'hematologist', route: ['sc'],
    forms: [{ form: 'injection', strength: '250mcg vial', unitPrice: 900.0, inStock: true }, { form: 'injection', strength: '500mcg vial', unitPrice: 1700.0, inStock: true }],
    maxDailyDose: 10, maxDailyDoseUnit: 'mcg/kg weekly', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Romiplostim/Eltrombopag'],
    interactions: [
      { interactsWith: 'Anticoagulants', severity: 'moderate', mechanism: 'Platelet increase may alter thrombotic/bleeding balance', clinicalEffect: 'Unpredictable hemostatic response', clinicalEffectAr: 'استجابة مرقئية غير متوقعة', management: 'Monitor platelet counts and adjust anticoagulation accordingly', managementAr: 'مراقبة عدد الصفيحات وتعديل مضادات التخثر' },
    ],
    contraindications: ['Hypersensitivity to romiplostim or E. coli-derived proteins'],
    contraindicationsAr: ['فرط حساسية للروميبلوستيم أو البروتينات المشتقة من الإي كولاي'],
    monitoringRequired: ['Platelet count weekly during dose adjustment', 'CBC with differential', 'Peripheral blood smear for morphological abnormalities', 'Bone marrow reticulin (consider with prolonged use)'],
    storageConditions: 'Refrigerate 2-8°C. Do not freeze. Protect from light. Use within 24h of reconstitution.',
  },
  {
    id: nextId(), genericName: 'Hydroxyurea', genericNameAr: 'هيدروكسي يوريا',
    brandNames: ['Hydrea', 'Droxia'], sfda_registration: 'SFDA-2024-HYU-487',
    atcCode: 'L01XX05', atcCategory: 'L01 - Antineoplastic agents',
    therapeuticClass: 'Antimetabolites', therapeuticClassAr: 'مضادات الأيض',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Hematologist/oncologist approval. For sickle cell disease, myeloproliferative disorders, or CML.',
    restrictionCriteriaAr: 'موافقة أخصائي أمراض الدم/الأورام. لمرض الخلايا المنجلية أو اضطرابات التكاثر النقوي أو ابيضاض الدم النقوي المزمن.',
    approverRole: 'hematologist', route: ['oral'],
    forms: [{ form: 'capsule', strength: '500mg', unitPrice: 3.0, inStock: true }, { form: 'tablet', strength: '1000mg', unitPrice: 5.5, inStock: true }],
    maxDailyDose: 35, maxDailyDoseUnit: 'mg/kg', renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Hydroxyurea/Hydroxyzine'],
    blackBoxWarning: 'Myelosuppression: may be severe and require dose interruption. Secondary leukemia reported with long-term use.',
    blackBoxWarningAr: 'تثبيط نقي العظم: قد يكون شديداً ويستلزم إيقاف الجرعة. تم الإبلاغ عن ابيضاض دم ثانوي مع الاستخدام طويل المدى.',
    interactions: [
      { interactsWith: 'Didanosine/Stavudine', severity: 'major', mechanism: 'Enhanced mitochondrial toxicity', clinicalEffect: 'Fatal pancreatitis, hepatotoxicity, and neuropathy', clinicalEffectAr: 'التهاب بنكرياس قاتل وسمية كبدية واعتلال عصبي', management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['Severe myelosuppression (WBC <2500 or platelets <100,000)', 'Pregnancy', 'Severe hepatic impairment', 'Severe renal impairment'],
    contraindicationsAr: ['تثبيط نقي عظم شديد', 'الحمل', 'قصور كبدي شديد', 'قصور كلوي شديد'],
    monitoringRequired: ['CBC every 2 weeks initially then monthly', 'Renal function', 'Hepatic function', 'HbF levels in sickle cell', 'MCV (expected to rise)'],
    storageConditions: 'Store below 25°C. Cytotoxic handling precautions.',
  },
];
const PSYCHIATRIC_EXTENDED: FormularyDrug[] = [
  {
    id: nextId(), genericName: 'Olanzapine', genericNameAr: 'أولانزابين',
    brandNames: ['Zyprexa', 'Zalasta'], sfda_registration: 'SFDA-2024-OLZ-488',
    atcCode: 'N05AH03', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Atypical Antipsychotics', therapeuticClassAr: 'مضادات الذهان غير النمطية',
    formularyStatus: 'formulary', route: ['oral', 'im'],
    forms: [{ form: 'tablet', strength: '5mg', unitPrice: 2.0, inStock: true }, { form: 'tablet', strength: '10mg', unitPrice: 3.5, inStock: true }, { form: 'orally disintegrating tablet', strength: '10mg', unitPrice: 5.0, inStock: true }, { form: 'injection', strength: '10mg vial', unitPrice: 15.0, inStock: true }],
    maxDailyDose: 20, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Olanzapine/Quetiapine', 'Zyprexa/Zyrtec'],
    interactions: [
      { interactsWith: 'Benzodiazepines (IM)', severity: 'major', mechanism: 'Additive CNS and respiratory depression', clinicalEffect: 'Excessive sedation, cardiorespiratory depression', clinicalEffectAr: 'تثبيط مفرط للجهاز العصبي والقلبي التنفسي', management: 'Do not give IM olanzapine with IM benzodiazepine; separate by at least 1 hour', managementAr: 'عدم إعطاء أولانزابين عضلي مع بنزوديازيبين عضلي؛ فصل بساعة على الأقل' },
      { interactsWith: 'Carbamazepine', severity: 'moderate', mechanism: 'CYP1A2 induction increases olanzapine metabolism', clinicalEffect: 'Reduced olanzapine levels', clinicalEffectAr: 'انخفاض مستويات أولانزابين', management: 'May need higher olanzapine dose; monitor clinical response', managementAr: 'قد يلزم زيادة جرعة أولانزابين؛ مراقبة الاستجابة السريرية' },
    ],
    contraindications: ['Hypersensitivity to olanzapine'],
    contraindicationsAr: ['فرط حساسية للأولانزابين'],
    monitoringRequired: ['Metabolic panel (glucose, lipids, weight)', 'Blood pressure', 'Prolactin', 'Hepatic function', 'Extrapyramidal symptoms'],
    storageConditions: 'Store below 25°C. Protect from light and moisture.',
  },
  {
    id: nextId(), genericName: 'Aripiprazole', genericNameAr: 'أريبيبرازول',
    brandNames: ['Abilify'], sfda_registration: 'SFDA-2024-ARI-489',
    atcCode: 'N05AX12', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Atypical Antipsychotics', therapeuticClassAr: 'مضادات الذهان غير النمطية',
    formularyStatus: 'formulary', route: ['oral', 'im'],
    forms: [{ form: 'tablet', strength: '5mg', unitPrice: 2.5, inStock: true }, { form: 'tablet', strength: '10mg', unitPrice: 4.0, inStock: true }, { form: 'tablet', strength: '15mg', unitPrice: 5.5, inStock: true }, { form: 'injection', strength: '9.75mg/1.3ml', unitPrice: 25.0, inStock: true }],
    maxDailyDose: 30, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Aripiprazole/Rabeprazole', 'Abilify/Ambien'],
    interactions: [
      { interactsWith: 'Strong CYP2D6 inhibitors (Fluoxetine, Paroxetine)', severity: 'moderate', mechanism: 'Inhibited CYP2D6 metabolism of aripiprazole', clinicalEffect: 'Increased aripiprazole levels', clinicalEffectAr: 'زيادة مستويات أريبيبرازول', management: 'Reduce aripiprazole dose by 50%', managementAr: 'تقليل جرعة أريبيبرازول بنسبة 50%' },
      { interactsWith: 'Strong CYP3A4 inhibitors (Ketoconazole)', severity: 'moderate', mechanism: 'Inhibited CYP3A4 metabolism', clinicalEffect: 'Increased aripiprazole exposure', clinicalEffectAr: 'زيادة التعرض لأريبيبرازول', management: 'Reduce aripiprazole dose by 50%', managementAr: 'تقليل الجرعة بنسبة 50%' },
    ],
    contraindications: ['Hypersensitivity to aripiprazole'],
    contraindicationsAr: ['فرط حساسية لأريبيبرازول'],
    monitoringRequired: ['Metabolic panel', 'Weight', 'Akathisia/restlessness', 'Suicidality in young adults', 'Blood glucose'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: nextId(), genericName: 'Clozapine', genericNameAr: 'كلوزابين',
    brandNames: ['Clozaril', 'Leponex'], sfda_registration: 'SFDA-2024-CLZ-490',
    atcCode: 'N05AH02', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Atypical Antipsychotics', therapeuticClassAr: 'مضادات الذهان غير النمطية',
    formularyStatus: 'restricted',
    restrictionCriteria: 'Psychiatrist approval only. For treatment-resistant schizophrenia. Requires enrollment in clozapine REMS program with mandatory ANC monitoring.',
    restrictionCriteriaAr: 'موافقة طبيب نفسي فقط. للفصام المقاوم للعلاج. يتطلب التسجيل في برنامج مراقبة كلوزابين مع مراقبة إلزامية لتعداد العدلات المطلق.',
    approverRole: 'psychiatrist', route: ['oral'],
    forms: [{ form: 'tablet', strength: '25mg', unitPrice: 1.5, inStock: true }, { form: 'tablet', strength: '100mg', unitPrice: 3.0, inStock: true }, { form: 'tablet', strength: '200mg', unitPrice: 5.0, inStock: true }],
    maxDailyDose: 900, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'B', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Clozapine/Clonazepam', 'Clozaril/Colazal'],
    blackBoxWarning: 'Severe neutropenia (agranulocytosis): potentially fatal. Requires absolute neutrophil count (ANC) monitoring before, during, and after treatment. Also: myocarditis, cardiomyopathy, seizures, severe orthostatic hypotension.',
    blackBoxWarningAr: 'قلة العدلات الشديدة (ندرة المحببات): قد تكون قاتلة. يتطلب مراقبة تعداد العدلات المطلق قبل وأثناء وبعد العلاج. أيضاً: التهاب عضلة القلب، اعتلال عضلة القلب، النوبات، انخفاض ضغط الدم الانتصابي الشديد.',
    interactions: [
      { interactsWith: 'Fluvoxamine', severity: 'major', mechanism: 'Strong CYP1A2 inhibition increases clozapine levels 5-10 fold', clinicalEffect: 'Severe clozapine toxicity (seizures, sedation, agranulocytosis)', clinicalEffectAr: 'سمية كلوزابين شديدة (نوبات، تخدير، ندرة المحببات)', management: 'Avoid combination or reduce clozapine dose by 2/3 with intensive monitoring', managementAr: 'تجنب الجمع أو تقليل جرعة كلوزابين بالثلثين مع مراقبة مكثفة' },
      { interactsWith: 'Carbamazepine', severity: 'major', mechanism: 'Additive bone marrow suppression plus CYP induction', clinicalEffect: 'Increased agranulocytosis risk and reduced clozapine levels', clinicalEffectAr: 'زيادة خطر ندرة المحببات وانخفاض مستويات كلوزابين', management: 'Contraindicated combination', managementAr: 'الجمع ممنوع' },
    ],
    contraindications: ['ANC <1500/mcL', 'History of clozapine-induced agranulocytosis', 'Uncontrolled epilepsy', 'Paralytic ileus', 'Active myeloproliferative disorder'],
    contraindicationsAr: ['تعداد العدلات المطلق أقل من 1500', 'تاريخ ندرة محببات بسبب كلوزابين', 'صرع غير منضبط', 'شلل الأمعاء', 'اضطراب تكاثر نقوي نشط'],
    monitoringRequired: ['ANC: weekly for first 6 months, biweekly for 6 months, then monthly', 'Metabolic panel', 'ECG (myocarditis)', 'Troponin/CRP if febrile', 'Seizure threshold', 'Fasting glucose/lipids', 'Weight'],
    storageConditions: 'Store below 30°C. Protect from moisture.',
  },
  {
    id: nextId(), genericName: 'Lithium Carbonate', genericNameAr: 'كربونات الليثيوم',
    brandNames: ['Eskalith', 'Lithobid', 'Camcolit'], sfda_registration: 'SFDA-2024-LIT-491',
    atcCode: 'N05AN01', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Mood Stabilizers', therapeuticClassAr: 'مثبتات المزاج',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'capsule', strength: '300mg', unitPrice: 0.5, inStock: true }, { form: 'tablet SR', strength: '400mg', unitPrice: 1.0, inStock: true }, { form: 'syrup', strength: '300mg/5ml', unitPrice: 8.0, inStock: true }],
    maxDailyDose: 2400, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: false,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: true, controlledSubstance: false, lookAlikeSoundAlike: ['Lithium/Lanthanum', 'Lithobid/Levbid'],
    blackBoxWarning: 'Narrow therapeutic index (0.6-1.2 mEq/L). Lithium toxicity can be fatal. Toxicity closely related to serum levels and can occur at doses close to therapeutic levels.',
    blackBoxWarningAr: 'مؤشر علاجي ضيق (0.6-1.2 مك مكافئ/لتر). سمية الليثيوم قد تكون قاتلة. السمية مرتبطة بمستويات المصل وقد تحدث بجرعات قريبة من المستويات العلاجية.',
    interactions: [
      { interactsWith: 'NSAIDs', severity: 'major', mechanism: 'Reduced renal lithium clearance via prostaglandin inhibition', clinicalEffect: 'Lithium toxicity (tremor, confusion, seizures, cardiac arrhythmia)', clinicalEffectAr: 'سمية الليثيوم (رعشة، تشوش، نوبات، اضطراب نظم القلب)', management: 'Avoid NSAIDs if possible; if necessary monitor lithium levels closely and reduce dose', managementAr: 'تجنب مضادات الالتهاب إن أمكن؛ إذا لزم مراقبة مستويات الليثيوم وتقليل الجرعة' },
      { interactsWith: 'ACE Inhibitors/ARBs', severity: 'major', mechanism: 'Reduced renal lithium excretion', clinicalEffect: 'Elevated lithium levels and toxicity', clinicalEffectAr: 'ارتفاع مستويات الليثيوم والسمية', management: 'Monitor lithium levels when starting/stopping; may need 50% dose reduction', managementAr: 'مراقبة مستويات الليثيوم عند البدء/الإيقاف؛ قد يلزم تقليل الجرعة 50%' },
      { interactsWith: 'Thiazide diuretics', severity: 'major', mechanism: 'Increased proximal tubular reabsorption of lithium', clinicalEffect: 'Elevated lithium levels 25-40%', clinicalEffectAr: 'ارتفاع مستويات الليثيوم 25-40%', management: 'Reduce lithium dose by 50% and monitor levels frequently', managementAr: 'تقليل جرعة الليثيوم 50% ومراقبة المستويات بشكل متكرر' },
    ],
    contraindications: ['Severe renal impairment', 'Severe cardiovascular disease', 'Dehydration', 'Sodium depletion', 'Addison disease', 'Brugada syndrome'],
    contraindicationsAr: ['قصور كلوي شديد', 'مرض قلبي وعائي شديد', 'الجفاف', 'نقص الصوديوم', 'مرض أديسون', 'متلازمة بروغادا'],
    monitoringRequired: ['Serum lithium levels (trough, 12h post-dose): weekly until stable then every 3 months', 'Renal function (eGFR, creatinine) every 6 months', 'Thyroid function every 6 months', 'Calcium/PTH annually', 'Weight', 'ECG baseline'],
    storageConditions: 'Store below 25°C. Protect from moisture.',
  },
  {
    id: nextId(), genericName: 'Valproate Sodium (Psychiatric use)', genericNameAr: 'فالبروات الصوديوم (استخدام نفسي)',
    brandNames: ['Depakote', 'Epilim', 'Depakine'], sfda_registration: 'SFDA-2024-VPA-492',
    atcCode: 'N03AG01', atcCategory: 'N03 - Antiepileptics',
    therapeuticClass: 'Mood Stabilizers / Anticonvulsants', therapeuticClassAr: 'مثبتات المزاج / مضادات الاختلاج',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet EC', strength: '250mg', unitPrice: 0.8, inStock: true }, { form: 'tablet EC', strength: '500mg', unitPrice: 1.5, inStock: true }, { form: 'syrup', strength: '250mg/5ml', unitPrice: 10.0, inStock: true }],
    maxDailyDose: 60, maxDailyDoseUnit: 'mg/kg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Depakote/Depakene'],
    blackBoxWarning: 'Hepatotoxicity (may be fatal, highest risk in children under 2). Pancreatitis. Teratogenicity (neural tube defects).',
    blackBoxWarningAr: 'سمية كبدية (قد تكون قاتلة، أعلى خطر في الأطفال أقل من سنتين). التهاب البنكرياس. تشوهات الأجنة (عيوب الأنبوب العصبي).',
    interactions: [
      { interactsWith: 'Lamotrigine', severity: 'major', mechanism: 'Valproate inhibits lamotrigine glucuronidation', clinicalEffect: 'Doubled lamotrigine levels; risk of Stevens-Johnson syndrome', clinicalEffectAr: 'مضاعفة مستويات لاموتريجين؛ خطر متلازمة ستيفنز جونسون', management: 'Reduce lamotrigine dose by 50% when adding valproate', managementAr: 'تقليل جرعة لاموتريجين 50% عند إضافة فالبروات' },
      { interactsWith: 'Carbapenems', severity: 'major', mechanism: 'Rapid reduction of valproate levels by 60-100%', clinicalEffect: 'Loss of seizure/mood control', clinicalEffectAr: 'فقدان السيطرة على النوبات/المزاج', management: 'Avoid combination; use alternative antibiotic', managementAr: 'تجنب الجمع؛ استخدام مضاد حيوي بديل' },
    ],
    contraindications: ['Hepatic disease', 'Urea cycle disorders', 'Pregnancy (for bipolar)', 'Mitochondrial disorders caused by POLG mutations'],
    contraindicationsAr: ['مرض كبدي', 'اضطرابات دورة اليوريا', 'الحمل (للاضطراب ثنائي القطب)', 'اضطرابات الميتوكوندريا بسبب طفرات POLG'],
    monitoringRequired: ['LFTs baseline and frequently during first 6 months', 'Valproate levels (50-100 mcg/mL)', 'CBC with platelets', 'Ammonia if lethargy', 'Weight', 'Pregnancy test in women of childbearing age'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: nextId(), genericName: 'Lamotrigine (Psychiatric use)', genericNameAr: 'لاموتريجين (استخدام نفسي)',
    brandNames: ['Lamictal'], sfda_registration: 'SFDA-2024-LTG-493',
    atcCode: 'N03AX09', atcCategory: 'N03 - Antiepileptics',
    therapeuticClass: 'Mood Stabilizers / Anticonvulsants', therapeuticClassAr: 'مثبتات المزاج / مضادات الاختلاج',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '25mg', unitPrice: 1.0, inStock: true }, { form: 'tablet', strength: '100mg', unitPrice: 2.5, inStock: true }, { form: 'tablet', strength: '200mg', unitPrice: 4.0, inStock: true }, { form: 'chewable tablet', strength: '5mg', unitPrice: 1.5, inStock: true }],
    maxDailyDose: 400, maxDailyDoseUnit: 'mg (200mg if with valproate)', renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: true, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Lamotrigine/Lamivudine', 'Lamictal/Lamisil'],
    blackBoxWarning: 'Serious skin rashes including Stevens-Johnson syndrome and toxic epidermal necrolysis. Risk greatest in first 8 weeks. Higher risk with rapid titration or co-administration with valproate.',
    blackBoxWarningAr: 'طفح جلدي خطير بما في ذلك متلازمة ستيفنز جونسون وانحلال البشرة السمي. الخطر الأكبر في أول 8 أسابيع. خطر أعلى مع التدرج السريع أو مع فالبروات.',
    interactions: [
      { interactsWith: 'Valproate', severity: 'major', mechanism: 'Inhibited glucuronidation doubles lamotrigine half-life', clinicalEffect: 'Increased lamotrigine levels and SJS risk', clinicalEffectAr: 'زيادة مستويات لاموتريجين وخطر متلازمة ستيفنز جونسون', management: 'Use reduced titration schedule; target dose 100-200mg/day (vs 200-400mg without valproate)', managementAr: 'استخدام جدول تدرج مخفض؛ الجرعة المستهدفة 100-200 مغ/يوم' },
      { interactsWith: 'Oral contraceptives', severity: 'moderate', mechanism: 'Ethinylestradiol increases lamotrigine clearance by 50%', clinicalEffect: 'Reduced lamotrigine levels during active pills; rebound toxicity during pill-free week', clinicalEffectAr: 'انخفاض مستويات لاموتريجين أثناء الحبوب النشطة؛ ارتداد سمي أثناء أسبوع التوقف', management: 'May need dose adjustment; consider non-hormonal contraception', managementAr: 'قد يلزم تعديل الجرعة؛ النظر في وسائل منع حمل غير هرمونية' },
    ],
    contraindications: ['Hypersensitivity to lamotrigine'],
    contraindicationsAr: ['فرط حساسية للاموتريجين'],
    monitoringRequired: ['Skin rash (especially first 8 weeks)', 'Mood/suicidality', 'Hepatic function', 'Renal function'],
    storageConditions: 'Store below 25°C. Protect from moisture.',
  },
  {
    id: nextId(), genericName: 'Venlafaxine', genericNameAr: 'فينلافاكسين',
    brandNames: ['Effexor', 'Efexor XR'], sfda_registration: 'SFDA-2024-VEN-494',
    atcCode: 'N06AX16', atcCategory: 'N06 - Psychoanaleptics',
    therapeuticClass: 'SNRIs', therapeuticClassAr: 'مثبطات استرداد السيروتونين والنورإبينفرين',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'capsule XR', strength: '37.5mg', unitPrice: 1.5, inStock: true }, { form: 'capsule XR', strength: '75mg', unitPrice: 2.5, inStock: true }, { form: 'capsule XR', strength: '150mg', unitPrice: 4.0, inStock: true }],
    maxDailyDose: 375, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Venlafaxine/Desvenlafaxine', 'Effexor/Effient'],
    interactions: [
      { interactsWith: 'MAOIs', severity: 'major', mechanism: 'Combined serotonergic and noradrenergic excess', clinicalEffect: 'Serotonin syndrome (potentially fatal)', clinicalEffectAr: 'متلازمة السيروتونين (قد تكون قاتلة)', management: 'Contraindicated; wait 14 days after MAOI before starting, 7 days after stopping venlafaxine before MAOI', managementAr: 'ممنوع الجمع؛ الانتظار 14 يوم بعد MAOI قبل البدء، 7 أيام بعد إيقاف فينلافاكسين قبل MAOI' },
      { interactsWith: 'Tramadol', severity: 'major', mechanism: 'Additive serotonergic effect and lowered seizure threshold', clinicalEffect: 'Serotonin syndrome and seizure risk', clinicalEffectAr: 'خطر متلازمة السيروتونين والنوبات', management: 'Avoid combination when possible', managementAr: 'تجنب الجمع عند الإمكان' },
    ],
    contraindications: ['MAOI use within 14 days', 'Uncontrolled narrow-angle glaucoma'],
    contraindicationsAr: ['استخدام MAOI خلال 14 يوم', 'الجلوكوما ضيقة الزاوية غير المنضبطة'],
    monitoringRequired: ['Blood pressure (dose-dependent hypertension)', 'Suicidality (especially early treatment)', 'Sodium levels', 'Cholesterol', 'Discontinuation syndrome if abruptly stopped'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: nextId(), genericName: 'Duloxetine', genericNameAr: 'دولوكسيتين',
    brandNames: ['Cymbalta'], sfda_registration: 'SFDA-2024-DLX-495',
    atcCode: 'N06AX21', atcCategory: 'N06 - Psychoanaleptics',
    therapeuticClass: 'SNRIs', therapeuticClassAr: 'مثبطات استرداد السيروتونين والنورإبينفرين',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'capsule', strength: '30mg', unitPrice: 3.0, inStock: true }, { form: 'capsule', strength: '60mg', unitPrice: 5.0, inStock: true }],
    maxDailyDose: 120, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Duloxetine/Fluoxetine', 'Cymbalta/Symbyax'],
    interactions: [
      { interactsWith: 'MAOIs', severity: 'major', mechanism: 'Serotonergic excess', clinicalEffect: 'Serotonin syndrome', clinicalEffectAr: 'متلازمة السيروتونين', management: 'Contraindicated; wait 14 days after MAOI, 5 days after stopping duloxetine', managementAr: 'ممنوع؛ الانتظار 14 يوم بعد MAOI، 5 أيام بعد إيقاف دولوكسيتين' },
      { interactsWith: 'CYP1A2 inhibitors (Fluvoxamine)', severity: 'major', mechanism: 'Inhibited duloxetine metabolism', clinicalEffect: 'Markedly increased duloxetine levels', clinicalEffectAr: 'زيادة ملحوظة في مستويات دولوكسيتين', management: 'Avoid combination', managementAr: 'تجنب الجمع' },
    ],
    contraindications: ['MAOI use within 14 days', 'Uncontrolled narrow-angle glaucoma', 'Severe hepatic impairment', 'CrCl <30 mL/min'],
    contraindicationsAr: ['استخدام MAOI خلال 14 يوم', 'الجلوكوما ضيقة الزاوية غير المنضبطة', 'قصور كبدي شديد', 'تصفية الكرياتينين أقل من 30'],
    monitoringRequired: ['Blood pressure', 'Hepatic function', 'Suicidality', 'Sodium levels', 'Bleeding signs'],
    storageConditions: 'Store below 30°C.',
  },
  {
    id: nextId(), genericName: 'Mirtazapine', genericNameAr: 'ميرتازابين',
    brandNames: ['Remeron'], sfda_registration: 'SFDA-2024-MIR-496',
    atcCode: 'N06AX11', atcCategory: 'N06 - Psychoanaleptics',
    therapeuticClass: 'Noradrenergic and Specific Serotonergic Antidepressants (NaSSA)', therapeuticClassAr: 'مضادات الاكتئاب النورأدرينية والسيروتونينية النوعية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '15mg', unitPrice: 1.5, inStock: true }, { form: 'tablet', strength: '30mg', unitPrice: 2.5, inStock: true }, { form: 'orally disintegrating tablet', strength: '15mg', unitPrice: 3.0, inStock: true }],
    maxDailyDose: 45, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Mirtazapine/Mifepristone', 'Remeron/Rozerem'],
    interactions: [
      { interactsWith: 'MAOIs', severity: 'major', mechanism: 'Serotonergic excess', clinicalEffect: 'Serotonin syndrome', clinicalEffectAr: 'متلازمة السيروتونين', management: 'Contraindicated; 14-day washout required', managementAr: 'ممنوع؛ يلزم فترة غسل 14 يوم' },
    ],
    contraindications: ['MAOI use within 14 days', 'Hypersensitivity to mirtazapine'],
    contraindicationsAr: ['استخدام MAOI خلال 14 يوم', 'فرط حساسية للميرتازابين'],
    monitoringRequired: ['Weight and appetite (significant weight gain)', 'Lipid panel', 'Blood glucose', 'Sedation level', 'CBC (rare agranulocytosis)', 'Suicidality'],
    storageConditions: 'Store below 25°C. Protect from moisture.',
  },
  {
    id: nextId(), genericName: 'Bupropion', genericNameAr: 'بوبروبيون',
    brandNames: ['Wellbutrin', 'Zyban'], sfda_registration: 'SFDA-2024-BUP-497',
    atcCode: 'N06AX12', atcCategory: 'N06 - Psychoanaleptics',
    therapeuticClass: 'Norepinephrine-Dopamine Reuptake Inhibitors (NDRI)', therapeuticClassAr: 'مثبطات استرداد النورإبينفرين والدوبامين',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet SR', strength: '150mg', unitPrice: 2.0, inStock: true }, { form: 'tablet XL', strength: '150mg', unitPrice: 3.0, inStock: true }, { form: 'tablet XL', strength: '300mg', unitPrice: 5.0, inStock: true }],
    maxDailyDose: 450, maxDailyDoseUnit: 'mg', renalAdjustment: true, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Bupropion/Buspirone', 'Wellbutrin/Wellcovorin'],
    interactions: [
      { interactsWith: 'MAOIs', severity: 'major', mechanism: 'Increased hypertensive and serotonergic risk', clinicalEffect: 'Hypertensive crisis', clinicalEffectAr: 'أزمة ارتفاع ضغط الدم', management: 'Contraindicated; 14-day washout', managementAr: 'ممنوع؛ فترة غسل 14 يوم' },
      { interactsWith: 'CYP2D6 substrates (Tamoxifen)', severity: 'major', mechanism: 'Strong CYP2D6 inhibition by bupropion', clinicalEffect: 'Reduced tamoxifen activation to endoxifen', clinicalEffectAr: 'تقليل تفعيل تاموكسيفين إلى إندوكسيفين', management: 'Avoid in breast cancer patients on tamoxifen', managementAr: 'تجنب في مريضات سرطان الثدي على تاموكسيفين' },
    ],
    contraindications: ['Seizure disorder', 'Bulimia/anorexia nervosa', 'Abrupt alcohol or benzodiazepine withdrawal', 'MAOI use within 14 days'],
    contraindicationsAr: ['اضطراب الصرع', 'الشره العصبي/فقدان الشهية العصبي', 'الانسحاب المفاجئ من الكحول أو البنزوديازيبين', 'استخدام MAOI خلال 14 يوم'],
    monitoringRequired: ['Seizure risk', 'Blood pressure', 'Weight (may cause weight loss)', 'Suicidality', 'Psychiatric symptoms'],
    storageConditions: 'Store below 25°C. Protect from light and moisture.',
  },
  {
    id: nextId(), genericName: 'Methylphenidate', genericNameAr: 'ميثيلفينيدات',
    brandNames: ['Ritalin', 'Concerta', 'Ritalin LA'], sfda_registration: 'SFDA-2024-MPH-498',
    atcCode: 'N06BA04', atcCategory: 'N06 - Psychoanaleptics',
    therapeuticClass: 'CNS Stimulants', therapeuticClassAr: 'منبهات الجهاز العصبي المركزي',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet IR', strength: '10mg', unitPrice: 1.5, inStock: true }, { form: 'tablet IR', strength: '20mg', unitPrice: 2.5, inStock: true }, { form: 'capsule LA', strength: '20mg', unitPrice: 8.0, inStock: true }, { form: 'tablet ER', strength: '18mg', unitPrice: 10.0, inStock: true }, { form: 'tablet ER', strength: '36mg', unitPrice: 15.0, inStock: true }],
    maxDailyDose: 72, maxDailyDoseUnit: 'mg (adults); 54mg (children)', renalAdjustment: false, hepaticAdjustment: false,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: true, controlSchedule: 'Schedule II',
    lookAlikeSoundAlike: ['Methylphenidate/Methadone', 'Ritalin/Rifadin'],
    blackBoxWarning: 'High potential for abuse and dependence. Assess risk before prescribing. Cardiovascular events including sudden death in patients with pre-existing cardiac abnormalities.',
    blackBoxWarningAr: 'إمكانية عالية للإدمان والاعتماد. تقييم الخطر قبل الوصف. أحداث قلبية وعائية بما في ذلك الموت المفاجئ في مرضى لديهم تشوهات قلبية مسبقة.',
    interactions: [
      { interactsWith: 'MAOIs', severity: 'major', mechanism: 'Potentiated catecholamine release', clinicalEffect: 'Hypertensive crisis', clinicalEffectAr: 'أزمة ارتفاع ضغط الدم', management: 'Contraindicated; 14-day washout from MAOI', managementAr: 'ممنوع؛ فترة غسل 14 يوم من MAOI' },
      { interactsWith: 'Antihypertensives', severity: 'moderate', mechanism: 'Sympathomimetic effect opposes antihypertensive action', clinicalEffect: 'Reduced blood pressure control', clinicalEffectAr: 'تقليل السيطرة على ضغط الدم', management: 'Monitor blood pressure; may need antihypertensive dose adjustment', managementAr: 'مراقبة ضغط الدم؛ قد يلزم تعديل جرعة خافض الضغط' },
    ],
    contraindications: ['Anxiety disorders', 'Glaucoma', 'Motor tics or Tourette syndrome', 'MAOI use within 14 days', 'Severe hypertension', 'Cardiac arrhythmias'],
    contraindicationsAr: ['اضطرابات القلق', 'الجلوكوما', 'تشنجات لاإرادية أو متلازمة توريت', 'استخدام MAOI خلال 14 يوم', 'ارتفاع ضغط دم شديد', 'اضطرابات نظم القلب'],
    monitoringRequired: ['Heart rate and blood pressure', 'Height and weight in children (growth suppression)', 'Appetite/nutrition', 'Sleep quality', 'Behavioral assessment', 'Abuse potential screening'],
    storageConditions: 'Store below 25°C. Controlled substance storage requirements.',
  },
  {
    id: nextId(), genericName: 'Atomoxetine', genericNameAr: 'أتوموكسيتين',
    brandNames: ['Strattera'], sfda_registration: 'SFDA-2024-ATX-499',
    atcCode: 'N06BA09', atcCategory: 'N06 - Psychoanaleptics',
    therapeuticClass: 'Selective Norepinephrine Reuptake Inhibitors', therapeuticClassAr: 'مثبطات استرداد النورإبينفرين الانتقائية',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'capsule', strength: '10mg', unitPrice: 4.0, inStock: true }, { form: 'capsule', strength: '25mg', unitPrice: 6.0, inStock: true }, { form: 'capsule', strength: '40mg', unitPrice: 8.0, inStock: true }, { form: 'capsule', strength: '60mg', unitPrice: 10.0, inStock: true }],
    maxDailyDose: 100, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'C', lactationSafe: false, pediatricApproved: true, geriatricCaution: false,
    highAlertMedication: false, controlledSubstance: false, lookAlikeSoundAlike: ['Atomoxetine/Atorvastatin', 'Strattera/Seroquel'],
    interactions: [
      { interactsWith: 'Strong CYP2D6 inhibitors (Paroxetine, Fluoxetine)', severity: 'moderate', mechanism: 'Inhibited atomoxetine metabolism (CYP2D6 is primary pathway)', clinicalEffect: 'Increased atomoxetine levels 6-8 fold in extensive metabolizers', clinicalEffectAr: 'زيادة مستويات أتوموكسيتين 6-8 أضعاف في المستقلبين السريعين', management: 'Start at lower dose and titrate slowly; monitor for tachycardia and hypertension', managementAr: 'البدء بجرعة أقل والتدرج ببطء؛ مراقبة تسارع القلب وارتفاع الضغط' },
      { interactsWith: 'MAOIs', severity: 'major', mechanism: 'Noradrenergic excess', clinicalEffect: 'Hypertensive crisis', clinicalEffectAr: 'أزمة ارتفاع ضغط الدم', management: 'Contraindicated; 14-day washout', managementAr: 'ممنوع؛ فترة غسل 14 يوم' },
    ],
    contraindications: ['MAOI use within 14 days', 'Narrow-angle glaucoma', 'Pheochromocytoma', 'Severe cardiovascular disorder'],
    contraindicationsAr: ['استخدام MAOI خلال 14 يوم', 'الجلوكوما ضيقة الزاوية', 'ورم القواتم', 'اضطراب قلبي وعائي شديد'],
    monitoringRequired: ['Heart rate and blood pressure', 'Growth in children', 'Hepatic function (rare hepatotoxicity)', 'Suicidality', 'Behavioral changes'],
    storageConditions: 'Store below 25°C.',
  },
  {
    id: nextId(), genericName: 'Diazepam', genericNameAr: 'ديازيبام',
    brandNames: ['Valium'], sfda_registration: 'SFDA-2024-DZP-500',
    atcCode: 'N05BA01', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Benzodiazepines', therapeuticClassAr: 'بنزوديازيبينات',
    formularyStatus: 'formulary', route: ['oral', 'iv', 'rectal'],
    forms: [{ form: 'tablet', strength: '2mg', unitPrice: 0.3, inStock: true }, { form: 'tablet', strength: '5mg', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '10mg', unitPrice: 0.8, inStock: true }, { form: 'injection', strength: '10mg/2ml', unitPrice: 3.0, inStock: true }, { form: 'rectal gel', strength: '10mg', unitPrice: 15.0, inStock: true }],
    maxDailyDose: 40, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: true, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: true, controlSchedule: 'Schedule IV',
    lookAlikeSoundAlike: ['Diazepam/Ditropan/Dilantin'],
    interactions: [
      { interactsWith: 'Opioids', severity: 'major', mechanism: 'Additive CNS and respiratory depression', clinicalEffect: 'Profound sedation, respiratory depression, coma, death', clinicalEffectAr: 'تخدير عميق، تثبيط تنفسي، غيبوبة، وفاة', management: 'Avoid concurrent use; if necessary use lowest doses and shortest duration', managementAr: 'تجنب الاستخدام المتزامن؛ عند الضرورة استخدام أقل الجرعات وأقصر مدة' },
      { interactsWith: 'Alcohol', severity: 'major', mechanism: 'Additive CNS depression via GABA potentiation', clinicalEffect: 'Enhanced sedation and respiratory depression', clinicalEffectAr: 'تعزيز التخدير والتثبيط التنفسي', management: 'Avoid alcohol during therapy', managementAr: 'تجنب الكحول أثناء العلاج' },
    ],
    contraindications: ['Severe respiratory insufficiency', 'Sleep apnea syndrome', 'Severe hepatic insufficiency', 'Myasthenia gravis', 'Acute narrow-angle glaucoma'],
    contraindicationsAr: ['قصور تنفسي شديد', 'متلازمة انقطاع النفس أثناء النوم', 'قصور كبدي شديد', 'الوهن العضلي الوبيل', 'الجلوكوما الحادة ضيقة الزاوية'],
    monitoringRequired: ['Respiratory rate', 'Level of sedation', 'Signs of dependence', 'Duration of use (avoid >4 weeks)', 'Paradoxical reactions in elderly'],
    storageConditions: 'Store below 25°C. Protect from light. Controlled substance storage.',
  },
  {
    id: nextId(), genericName: 'Lorazepam', genericNameAr: 'لورازيبام',
    brandNames: ['Ativan'], sfda_registration: 'SFDA-2024-LRZ-501',
    atcCode: 'N05BA06', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Benzodiazepines', therapeuticClassAr: 'بنزوديازيبينات',
    formularyStatus: 'formulary', route: ['oral', 'iv'],
    forms: [{ form: 'tablet', strength: '0.5mg', unitPrice: 0.3, inStock: true }, { form: 'tablet', strength: '1mg', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '2mg', unitPrice: 0.8, inStock: true }, { form: 'injection', strength: '2mg/ml', unitPrice: 5.0, inStock: true }, { form: 'injection', strength: '4mg/ml', unitPrice: 8.0, inStock: true }],
    maxDailyDose: 10, maxDailyDoseUnit: 'mg', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: true, controlSchedule: 'Schedule IV',
    lookAlikeSoundAlike: ['Lorazepam/Alprazolam/Clonazepam'],
    interactions: [
      { interactsWith: 'Opioids', severity: 'major', mechanism: 'Additive CNS and respiratory depression', clinicalEffect: 'Profound sedation, respiratory failure, death', clinicalEffectAr: 'تخدير عميق، فشل تنفسي، وفاة', management: 'Avoid combination; use lowest effective doses if unavoidable', managementAr: 'تجنب الجمع؛ استخدام أقل الجرعات الفعالة عند الضرورة' },
      { interactsWith: 'Probenecid', severity: 'moderate', mechanism: 'Inhibits lorazepam glucuronidation', clinicalEffect: 'Prolonged lorazepam half-life and enhanced sedation', clinicalEffectAr: 'إطالة عمر النصف وتعزيز التخدير', management: 'Reduce lorazepam dose by 50%', managementAr: 'تقليل جرعة لورازيبام بنسبة 50%' },
    ],
    contraindications: ['Severe respiratory insufficiency', 'Sleep apnea', 'Acute narrow-angle glaucoma', 'Severe hepatic insufficiency'],
    contraindicationsAr: ['قصور تنفسي شديد', 'انقطاع النفس أثناء النوم', 'الجلوكوما الحادة ضيقة الزاوية', 'قصور كبدي شديد'],
    monitoringRequired: ['Respiratory status (especially IV)', 'Sedation level', 'Duration of use', 'Signs of dependence', 'Paradoxical agitation in elderly/children'],
    storageConditions: 'Refrigerate injection 2-8°C. Tablets below 25°C. Controlled substance storage.',
  },
  {
    id: nextId(), genericName: 'Alprazolam', genericNameAr: 'ألبرازولام',
    brandNames: ['Xanax'], sfda_registration: 'SFDA-2024-ALP-502',
    atcCode: 'N05BA12', atcCategory: 'N05 - Psycholeptics',
    therapeuticClass: 'Benzodiazepines', therapeuticClassAr: 'بنزوديازيبينات',
    formularyStatus: 'formulary', route: ['oral'],
    forms: [{ form: 'tablet', strength: '0.25mg', unitPrice: 0.3, inStock: true }, { form: 'tablet', strength: '0.5mg', unitPrice: 0.5, inStock: true }, { form: 'tablet', strength: '1mg', unitPrice: 0.8, inStock: true }, { form: 'tablet', strength: '2mg', unitPrice: 1.5, inStock: true }],
    maxDailyDose: 10, maxDailyDoseUnit: 'mg (anxiety: 4mg; panic: 10mg)', renalAdjustment: false, hepaticAdjustment: true,
    pregnancyCategory: 'D', lactationSafe: false, pediatricApproved: false, geriatricCaution: true,
    highAlertMedication: false, controlledSubstance: true, controlSchedule: 'Schedule IV',
    lookAlikeSoundAlike: ['Alprazolam/Lorazepam/Clonazepam', 'Xanax/Zantac'],
    interactions: [
      { interactsWith: 'Strong CYP3A4 inhibitors (Ketoconazole, Itraconazole)', severity: 'major', mechanism: 'Inhibited alprazolam metabolism', clinicalEffect: 'Markedly increased alprazolam levels and sedation', clinicalEffectAr: 'زيادة ملحوظة في مستويات ألبرازولام والتخدير', management: 'Contraindicated with ketoconazole/itraconazole', managementAr: 'ممنوع مع كيتوكونازول/إيتراكونازول' },
      { interactsWith: 'Opioids', severity: 'major', mechanism: 'Additive CNS depression', clinicalEffect: 'Respiratory depression, coma, death', clinicalEffectAr: 'تثبيط تنفسي، غيبوبة، وفاة', management: 'Avoid combination if possible', managementAr: 'تجنب الجمع إن أمكن' },
    ],
    contraindications: ['Acute narrow-angle glaucoma', 'Co-administration with strong CYP3A4 inhibitors', 'Severe respiratory depression', 'Severe hepatic failure'],
    contraindicationsAr: ['الجلوكوما الحادة ضيقة الزاوية', 'الإعطاء المتزامن مع مثبطات CYP3A4 القوية', 'تثبيط تنفسي شديد', 'فشل كبدي شديد'],
    monitoringRequired: ['Signs of dependence and withdrawal', 'Sedation level', 'Duration of use (shortest possible)', 'Rebound anxiety on discontinuation', 'Fall risk in elderly'],
    storageConditions: 'Store below 25°C. Controlled substance storage requirements.',
  },
];
const MUSCULOSKELETAL: FormularyDrug[] = [];
const HOSPITAL_MISCELLANEOUS: FormularyDrug[] = [];

export { GI_EXTENDED, HEMATOLOGY, PSYCHIATRIC_EXTENDED, MUSCULOSKELETAL, HOSPITAL_MISCELLANEOUS };
